### ISSUE TITLE
[Gradio 4] Uploading a video takes long

### ISSUE THREAD

**Issue by hysts** [gradio-app/gradio#6204] opened 2023-11-01 06:49 UTC
### Describe the bug

(Not sure if this is a bug.)
It was quite fast to upload a video when using `gradio==3.50.2`, but it takes much longer with `gradio==4.0.2`. For example, when I uploaded a 20 second video (1920x1080, 60fps, 9.6MB), it takes like 15 seconds before it became playable when using `gradio==4.0.2`, while it's instantaneous with `gradio==3.50.2`. It's possible to load 5 minute video with `gradio==3.50.2` in a second or two, but it takes forever to load it with `gradio==4.0.2`. (I waited for more than 2 minutes, and gave up.)

Also, if it takes this long to upload/preprocess the input, it would be nice if there was some visual cue that tells you that it's still processing the input.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```py
import gradio as gr

gr.Interface(fn=lambda x: x, inputs="video", outputs="video").launch()
```

### System Info

```shell
gradio==4.0.2
```

### Severity

I can work around it

**Comment by freddyaboulton** [comment] 2023-11-01 13:52
Can you share the video @hysts ?

**Comment by freddyaboulton** [comment] 2023-11-01 18:21
@hysts I can only reproduce the issue when dragging, not via "click" to upload. This is with a 46mb file

# drag
![video_drag](https://github.com/gradio-app/gradio/assets/41651716/bcf0b11d-bd7f-4fe0-bdbe-7dd17c69e409)
# upload
![video_upload](https://github.com/gradio-app/gradio/assets/41651716/39fc135b-8efb-40b1-b18a-9c5ff6ccc58e)

**Comment by hysts** [comment] 2023-11-02 08:23
@freddyaboulton 

(Yes, drag and drop doesn't work for `gr.Video` and `gr.Audio` for now. I had opened an issue here #6202 before I opened this issue, so this is a different issue.)

Hmm, maybe it was partly due to my network speed. Somehow it's faster than yesterday when I tried it again now.
Also, I just noticed that it's fast when I run it locally.

But still, It's quite slow when I run it on Spaces or on my AWS instance.

`gradio==4.0.2`

https://github.com/gradio-app/gradio/assets/25161192/450eb16d-006f-47bd-b961-08c4d6d2e749

`gradio==3.50.2`

https://github.com/gradio-app/gradio/assets/25161192/98f72843-a183-4d57-adab-b40541c68e42

**Comment by hysts** [comment] 2023-11-02 08:26
The video I used in the screen recordings above:

https://github.com/gradio-app/gradio/assets/25161192/09f108c7-c8f8-4995-b025-1d9b231a8e79

(This is a different video than the one I first used.)

**Comment by freddyaboulton** [comment] 2023-11-13 15:37
Thanks for the video @hysts !

So what's happening is that in gradio 3.x, the video was not actually uploaded. It was converted to base64 and sent to the server. Which is why it appeared quickly. We switched to file uploads in 4.x for scalability.

The speed will depend on your network connection but now that we have the upload status progress, users know what's happening. And it's clear that the demo is not ready for inference even though the Predict button is not explicitly blocked.

<img width="1444" alt="image" src="https://github.com/gradio-app/gradio/assets/41651716/4cc623a6-de49-41ee-94e5-807f9d8a0508">

I think we should close this issue and look into separately blocking the event triggers while uploads are happening. What do you think @abidlabs @pngwn @aliabid94 ?

**Comment by abidlabs** [comment] 2023-11-13 16:06
Agreed @freddyaboulton that the new upload status should clarify what's happening and that we can close this. It looks like we already have an issue for the latter: https://github.com/gradio-app/gradio/issues/6219

**Closed** 2023-11-13 16:11 UTC
Labels: bug, Regression
