### ISSUE TITLE
support real-time video output?

### ISSUE THREAD

**Issue by carter54** [gradio-app/gradio#504] opened 2022-01-28 08:19 UTC
**Is your feature request related to a problem? Please describe.**
The input can obtain the video from webcam in real-time, it is possible to output the processed video frame in real-time?

**Comment by abidlabs** [comment] 2022-01-28 17:59
Thanks @carter54, this is on our roadmap!

**Comment by abidlabs** [comment] 2022-04-19 06:33
Duplicate of #220

**Closed by abidlabs** 2022-04-19 06:33 UTC
Labels: enhancement
