### ISSUE TITLE
List index out of range error in Predict API for speaker verification

### ISSUE THREAD

**Issue by heaversm** [gradio-app/gradio#1083] opened 2022-04-25 22:10 UTC
### Describe the bug

I am attempting to implement the speaker verification API via your [code documentation here](https://hf.space/gradioiframe/microsoft/unispeech-speaker-verification/api).

```
fetch('https://hf.space/gradioiframe/microsoft/unispeech-speaker-verification/+/api/predict/', {
                method: 'POST',
                body: JSON.stringify({
                    "data": [
                        { "data": document.getElementById('audioSample').src, "name": "audioSample.wav" },
                        { "data": document.getElementById('audioRecord').src, "name": "audioRecord.wav" }
                    ]
                }), headers: {
                    'Content-Type': 'application/json'
                }
            })
```

using the source from 2 html audio elements. I get a 500 response:

```
{
    "error": "list index out of range"
}
```

I noticed that the demo you have also results in errors:
https://hf.space/gradioiframe/microsoft/unispeech-speaker-verification/+

<img width="516" alt="Screen Shot 2022-04-25 at 4 05 58 PM" src="https://user-images.githubusercontent.com/520541/165182778-035ba0bb-f5fe-4564-b1ae-04863b4bc7d8.png">

### Reproduction

You can reproduce the error by using my hosted demo here:

[https://quiet-semifreddo-e3e65d.netlify.app/](https://quiet-semifreddo-e3e65d.netlify.app/)

View source to see all the source code (no libraries or external dependencies besides the API)

### Screenshot

<img width="516" alt="Screen Shot 2022-04-25 at 4 05 58 PM" src="https://user-images.githubusercontent.com/520541/165183079-97171264-baf8-4ab9-abad-e26bf123bce3.png">

### System Info

```shell
Mac Monterrey, Chrome 100, API version unknown
```

### Severity

blocker

**Comment by abidlabs** [comment] 2022-04-25 22:52
Thanks for creating the issue @heaversm we'll take a look into this

**Comment by abidlabs** [comment] 2022-07-11 08:59
I just tested and I'm not getting that error anymore. Instead, I'm getting:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at (index):116:47
```

I also tested the request from the API page, as well as the Space, and they both seem to be working now. So I think the issue is resolved from the gradio side, you may need to update the request from the JS side. Please let us know if we can go ahead and close this.

**Comment by freddyaboulton** [comment] 2022-08-01 15:18
@heaversm Can you please let us know if the bug is still present?

**Comment by abidlabs** [comment] 2022-08-08 01:35
Going to close the issue for now. @heaversm if the bug is still present, please feel free to reopen the issue with more details on which error you are getting.

**Closed by abidlabs** 2022-08-08 01:35 UTC
Labels: bug, pending clarification

**Comment by heaversm** [comment] 2024-03-18 17:53
Yes - can close. Sorry - need to enable notifications about these issues.
