### ISSUE TITLE
HTML no longer renders in chat output

### ISSUE THREAD

**Issue by pseudotensor** [gradio-app/gradio#4345] opened 2023-05-27 06:37 UTC
### Describe the bug

![image](https://github.com/gradio-app/gradio/assets/2249614/c92f1570-7bd8-4697-9b02-0312a63bc20d)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Just have chatbot push html.  Gets rendered literally always now

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/2249614/4daf579f-9c55-4bb8-b4cc-6259a6173a57)

What it looks like for identical code except 3.31.0:

![image](https://github.com/gradio-app/gradio/assets/2249614/28763fd4-b657-46c9-976a-a74c82ff6091)

### Logs

```shell
NA
```

### System Info

```shell
3.32.0.  No problem for earlier versions.
```

### Severity

blocking upgrade to latest gradio version

**Comment by decent-engineer-decent-datascientist** [comment] 2023-05-27 14:11
https://github.com/gradio-app/gradio/issues/4316 
^ facing the same issue, there's bit more background on why this is happening

**Comment by decent-engineer-decent-datascientist** [comment] 2023-05-27 14:12
@abidlabs @dawoodkhan82 Can we please get a resolution on this?

**Comment by cowanAI** [comment] 2023-05-27 22:00
also the highlight function is not working on dark mode and my users cant read clearly the output :(

**Comment by binary-husky** [comment] 2023-05-28 03:34
> @abidlabs @dawoodkhan82 Can we please get a resolution on this?

you can checkout on this as a temp solution:  https://github.com/binary-husky/gradio-fix/blob/b958d04f21b741af42f0db7c7713c6eca17460f4/js/chatbot/src/ChatBot.svelte

I have
- reversed related chatbot commits in my fork,
- restored the HTML rendering
- fixed a copying button bug

**Comment by binary-husky** [comment] 2023-05-28 03:45
reference issue: https://github.com/gradio-app/gradio/issues/4316
https://github.com/gradio-app/gradio/issues/4264

@decent-engineer-decent-datascientist @cowanAI

**Comment by cowanAI** [comment] 2023-05-28 07:47
> binary-husky

Screenshot 2023-05-28 at 9 45 34 AM

still looks like a mess in dark mode

**Comment by abidlabs** [comment] 2023-05-29 02:43
We'll work on a fix soon! Closing as this is a duplicate of https://github.com/gradio-app/gradio/issues/4316

**Closed by abidlabs** 2023-05-29 02:43 UTC
Labels: bug

**Comment by dawoodkhan82** [comment] 2023-05-30 05:06
@pseudotensor @cowanAI can you test #4360 to see if it fixes your issues. Thanks!
