### ISSUE TITLE
Share button is showing on the top-left corner and under the chatbot label instead of the usual place of top-right corner

### ISSUE THREAD

**Issue by yvrjsharma** [gradio-app/gradio#5478] opened 2023-09-11 11:30 UTC
### Describe the bug

After version 3.41.0, the share button icon has started to appear on the top-left corner but is now barely visible due to overlap with the Chatbot label. This is happening with both Chatbot and ChatInterface.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

- Install latest version of gradio from pip
`
!pip install gradio
`

- Run this demo 
```
import gradio as gr
import random
import time

with gr.Blocks() as demo:
    chatbot = gr.Chatbot(show_share_button=True)
    msg = gr.Textbox(value='hello')
    clear = gr.ClearButton([msg, chatbot])

    def respond(message, chat_history):
        bot_message = random.choice(["How are you?", "I love you", "I'm very hungry"])
        chat_history.append((message, bot_message))
        time.sleep(2)
        return "", chat_history

    msg.submit(respond, [msg, chatbot], [msg, chatbot])

demo.launch()
```

- Uninstall Gradio and install version `gradio==3.42.0` and run the demo again
```
!pip uninstall gradio 
# Run the demo again 
!pip install gradio==3.42.0
```

- Uninstall Gradio and install `gradio==3.41.0`
```
!pip uninstall gradio 

!pip install gradio==3.41.0

import gradio as gr
import random
import time

with gr.Blocks() as demo:
    chatbot = gr.Chatbot(show_share_button=True)
    msg = gr.Textbox(value='hello')
    clear = gr.ClearButton([msg, chatbot])

    def respond(message, chat_history):
        bot_message = random.choice(["How are you?", "I love you", "I'm very hungry"])
        chat_history.append((message, bot_message))
        time.sleep(2)
        return "", chat_history

    msg.submit(respond, [msg, chatbot], [msg, chatbot])

demo.launch()
```

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/48665385/ac486819-651f-40f8-8eba-7d9e7896fc73)

![image](https://github.com/gradio-app/gradio/assets/48665385/ea749459-ecaa-42ca-82d5-ad2ad2fec71b)

### System Info

```shell
Running on Colab:

Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 3.43.2
gradio_client version: 0.5.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 4.2.2
fastapi: 0.103.1
ffmpy: 0.3.1
gradio-client==0.5.0 is not installed.
httpx: 0.24.1
huggingface-hub: 0.16.4
importlib-resources: 6.0.1
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.7.1
numpy: 1.23.5
orjson: 3.9.7
packaging: 23.1
pandas: 1.5.3
pillow: 9.4.0
pydantic: 1.10.12
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
requests: 2.31.0
semantic-version: 2.10.0
typing-extensions: 4.5.0
uvicorn: 0.23.2
websockets: 11.0.3
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.6.0
httpx: 0.24.1
huggingface-hub: 0.16.4
packaging: 23.1
requests: 2.31.0
typing-extensions: 4.5.0
websockets: 11.0.3
```

### Severity

I can work around it

**Comment by dawoodkhan82** [comment] 2023-09-11 15:22
Closing. Duplicate of #5435

**Closed by dawoodkhan82** 2023-09-11 15:22 UTC
Labels: bug
