### ISSUE TITLE
Multiprocessing In Gradio causes second Gradio server to start running

### ISSUE THREAD

**Issue by blairstar** [gradio-app/gradio#7603] opened 2024-03-05 03:54 UTC
### Describe the bug

I have a cpu dense task, and want to use multiprocessing to speedup. When create a new process or call "Manager().Queue()", the program blocks, and prints "Running on local URL:  http://127.0.0.1:7861". In the beginning, the program prints ""Running on local URL:  http://127.0.0.1:7860"。

Program outputs:

Running on local URL:  http://127.0.0.1:7860
To create a public link, set `share=True` in `launch()`.
<IPython.core.display.HTML object>
Running on local URL:  http://127.0.0.1:7861
To create a public link, set `share=True` in `launch()`.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```py
import gradio as gr
from multiprocessing import Pool, Queue, Manager


def greet(name):
    queue = Manager().Queue()
    return "Hello " + name + "!"

with gr.Blocks() as demo:
    name = gr.Textbox(label="Name")
    output = gr.Textbox(label="Output Box")
    greet_btn = gr.Button("Greet")
    greet_btn.click(fn=greet, inputs=name, outputs=output, api_name="greet")
    
demo.launch()
```

### Screenshot

![a](https://github.com/gradio-app/gradio/assets/31396562/d35ed96e-f8e5-4d52-8dfe-c0834e5a4f19)

### System Info

```shell
$ ./gradio.exe environment
Gradio Environment Information:
------------------------------
Operating System: Windows
gradio version: 4.18.0
gradio_client version: 0.10.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.2.0
fastapi: 0.109.2
ffmpy: 0.3.1
gradio-client==0.10.0 is not installed.
httpx: 0.26.0
huggingface-hub: 0.20.3
importlib-resources: 6.1.1
jinja2: 3.1.3
markupsafe: 2.1.5
matplotlib: 3.8.3
numpy: 1.22.4+mkl
orjson: 3.9.13
packaging: 22.0
pandas: 1.5.2
pillow: 9.3.0
pydantic: 2.6.1
pydub: 0.25.1
python-multipart: 0.0.9
pyyaml: 6.0.1
ruff: 0.2.1
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.9.0
uvicorn: 0.27.1
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2024.2.0
httpx: 0.26.0
huggingface-hub: 0.20.3
packaging: 22.0
typing-extensions: 4.9.0
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment] 2024-03-05 21:43
Hi @blairstar I actually can't reproduce this behavior locally:

<img width="782" alt="image" src="https://github.com/gradio-app/gradio/assets/1778297/faa58c11-6192-4bb6-8f4b-f8a1522b0577">


Or on Colab notebook: https://colab.research.google.com/drive/1gsYyweL1NgKpgFPItjZkqsXiVl_RLpv5?usp=sharing

Would you be able to provide us a problematic example in a reproducible environment like Colab?

**Comment by abidlabs** [comment] 2024-03-07 14:58
Closing for now, for lack of repro. Happy to reopen if we have a way to reproduce the issue consistently.

**Closed by abidlabs** 2024-03-07 14:58 UTC
Labels: bug, needs repro

**Comment by carter54** [comment] 2024-07-11 11:09
This happens only on Windows
