### ISSUE TITLE
gr.File corrupts .docx file

### ISSUE THREAD

**Issue by TheSuguser** [gradio-app/gradio#5064] opened 2023-08-02 03:18 UTC
### Describe the bug

I encountered a critical issue with the ``gr.File`` component, where it appears to be corrupting ``.docx`` files upon upload. Subsequently, ``docx2txt``, ``python-docx``, ``langchain.document_loaders.Docx2txtLoader`` modules are all unable to extract text from the uploaded ``.docx`` files, resulting in a ``zipfile.BadZipFile: File is not a zip file error``. This issue renders the component unusable for processing ``.docx`` files.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
from docx2txt import docx2txt
import gradio as gr

def docx2text(file_obj):
    text = docx2txt.process(file_obj.name)
    print(text)
    return text

demo = gr.Interface(docx2text, gr.File(), "textbox")

if __name__ == "__main__":
    demo.launch()
```

### Logs

```shell
Traceback (most recent call last):
  File "C:\Users\Yuan\anaconda3\envs\gpt\lib\site-packages\gradio\routes.py", line 442, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Yuan\anaconda3\envs\gpt\lib\site-packages\gradio\blocks.py", line 1392, in process_api
    result = await self.call_function(
  File "C:\Users\Yuan\anaconda3\envs\gpt\lib\site-packages\gradio\blocks.py", line 1097, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\Yuan\anaconda3\envs\gpt\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Yuan\anaconda3\envs\gpt\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Yuan\anaconda3\envs\gpt\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\Yuan\anaconda3\envs\gpt\lib\site-packages\gradio\utils.py", line 703, in wrapper
    response = f(*args, **kwargs)
  File "d:/Project/PersonalProject/StrucDoc/webui.py", line 5, in docx2text
    text = docx2txt.process(file_obj.name)
  File "C:\Users\Yuan\anaconda3\envs\gpt\lib\site-packages\docx2txt\docx2txt.py", line 76, in process
    zipf = zipfile.ZipFile(docx)
  File "C:\Users\Yuan\anaconda3\envs\gpt\lib\zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "C:\Users\Yuan\anaconda3\envs\gpt\lib\zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

### System Info

```shell
gradio==3.39.0
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment] 2023-08-02 17:33
Taking a look, can you share the .docx file you're trying too?

**Comment by abidlabs** [comment] 2023-08-02 17:37
Hi @TheSuguser I can't reproduce. Your code works fine for me:

<img width="1295" alt="image" src="https://github.com/gradio-app/gradio/assets/1778297/b2e45de3-7d0a-4b86-8520-81d2372aacf5">

using this test file: https://file-examples.com/wp-content/storage/2017/02/file-sample_100kB.docx

Please ensure that your file is not corrupted or share here so that we can repro.

**Comment by TheSuguser** [comment] 2023-08-03 05:53
Hi @abidlabs, thank you for your help. Please check the file below. It is a docx file with Chinese title and content. I can process it via docx2txt directly but fail to extract the text through ``gr.File``.
[上海地铁一号线.docx](https://github.com/gradio-app/gradio/files/12247275/default.docx)

**Comment by abidlabs** [comment] 2023-08-03 15:56
This works for me too: 

<img width="1210" alt="image" src="https://github.com/gradio-app/gradio/assets/1778297/cbf885a5-0f87-437f-b7f5-c756468aeaa9">

Here's a Colab notebook showing that it working: https://colab.research.google.com/drive/1q63jlprNu6AghbhuIeZInQRSOEU8pb8y?usp=sharing

**Comment by TheSuguser** [comment] 2023-08-04 02:34
It works in Colab. But I run it in my own enviroment in Jupyter Notebook, it raised the error. 

![image](https://github.com/gradio-app/gradio/assets/17256461/8ff6ae38-3950-4a46-9ff5-178abd8f1c5e)

**Comment by abidlabs** [comment] 2023-08-04 11:44
Hi @TheSuguser I'm sorry but I can't reproduce this issue at all. Is there anything specific about your local environment that might be causing this issue? If you can think of anything, we might be able to investigate. Otherwise I'll need to close this issue for lack of reproducibility.

**Comment by abidlabs** [comment] 2023-08-07 11:14
Sorry @TheSuguser I'll go ahead and close this for now since we can't reproduce the issue. If you find any more information that might be helpful to reproducing this, we can revisit.

**Closed by abidlabs** 2023-08-07 11:14 UTC
Labels: bug, needs repro

**Comment by EvanTang1998** [comment] 2023-11-23 07:52
similar problem too, I passed a Excel file , but it can't be open, so I try to pass a txt file, but when I open it, it was empty! I'm so confused
