### ISSUE TITLE
Fastapi gradio mount issue

### ISSUE THREAD

**Issue by cemalgndzz** [gradio-app/gradio#5734] opened 2023-09-28 12:37 UTC
### Describe the bug

I am using a fastapi backend. When a request comes to /start endpoint it calls a function from different pyhton file where this function initialize and launches gradio interface, then launched gradio interface is mounted with mount_gradio_app gradio function and fastapi backend redirects to gradio website. However I got the following error when I go to gradio website, there are buttons but their functionalities etc. doesnt work. The error is:

ERROR:Task exception was never retrieved
future: <Task finished name='Task-19' coro=<Queue.start_processing() done, defined at /home/ubuntu/aimployee/installer/installer_files/env/lib/python3.9/site-packages/gradio/queueing.py:121> exception=AttributeError('__aenter__')>
Traceback (most recent call last):
  File "/home/ubuntu/aimployee/installer/installer_files/env/lib/python3.9/site-packages/gradio/queueing.py", line 131, in start_processing
    async with self.delete_lock:
AttributeError: __aenter__

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

-

### System Info

```shell
Gradio 3.45.1
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment] 2023-09-28 15:21
This is a dupe of #5708 so I'm going to close

**Closed by freddyaboulton** 2023-09-28 15:21 UTC
Labels: bug
