### ISSUE TITLE
JS error causes failure to load in Android API <= 29

### ISSUE THREAD

**Issue by greendra8** [gradio-app/gradio#2230] opened 2022-09-11 12:11 UTC
### Describe the bug

`Uncaught SyntaxError: Unexpected token . https://gradio.s3-us-west-2.amazonaws.com/3.3/assets/index.342fe35e.js (1)`

This error is thrown on every recent gradio version I have tested when loading from an android client with API 29 or less. Tried on huggingface spaces site and none loaded. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Try accessing gradio from Android 10 or lower and it will not display.

### Logs

```shell
`Uncaught SyntaxError: Unexpected token . https://gradio.s3-us-west-2.amazonaws.com/3.3/assets/index.342fe35e.js (1)`
```

### System Info

```shell
Android SDK 29
```

### Severity

serious, but I can work around it

**Comment by aliabid94** [comment] 2022-09-13 01:11
Interesting. @abidlabs can you see what's going on?

**Comment by greendra8** [comment] 2022-09-13 01:13
Looking into this further, I think this might not be related to API version but actually android webview version? Have tried phones with API lower than 29 and has worked. Am not able to be 100% sure though.

**Comment by abidlabs** [comment] 2022-09-14 15:32
This is a pretty tough one to reproduce since I don't have that specific hardware. @greendra8 if you are able to give us more direction on how to fix this, I'd be happy to make the necessary changes.

Otherwise, we're probably going to have to close this for lack of reproducibility.

**Comment by abidlabs** [comment] 2022-09-19 20:57
Going to close this for now for the reasons stated above. Please feel free to reopen if you are able to get more details on this that would point to a fix @greendra8

**Closed by abidlabs** 2022-09-19 20:57 UTC
Labels: needs repro
