### ISSUE TITLE
Graph appears without axis

### ISSUE THREAD

**Issue by szm0020** [gradio-app/gradio#3130] opened 2023-02-06 08:43 UTC
### Describe the bug

Hello all,
Gradio app cut of both axis and I can’t figure out how to make this work properly (see attached graph). I found some information here: [Plot Graphs on Gradio Partially Cut off on X- Axis](https://discuss.huggingface.co/t/plot-graphs-on-gradio-partially-cut-off-on-x-axis/13503)

Unfortunately I can’t make this work. Any thoughts on this?

Thanks
![gradio](https://user-images.githubusercontent.com/52922997/216923546-51fd4932-5427-4fbe-a7f9-406a9a640ba9.jpg)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

def greet(regionx, MGx, SRx):
    
    #Load data.
    data=pd.read_csv('.....csv')
    
    set_font=22
    plt.rcParams["figure.figsize"] = [18, 10]
    #plt.rcParams['savefig.edgecolor'] = plt.gcf().patch.get_edgecolor()
    plt.rcParams['font.size'] = set_font
    

    figy_line, ax = plt.subplots()
    ax.plot(data['PD'], data['Yield (bu/ac)'], c="black", linewidth=5)
    plt.xticks(np.arange(70, 210+10, 10), rotation=45)
    ax.fill_between(data["PD"].values, data["bottomy"].values, data["topy"].values, alpha=0.35, color="grey")

    plt.xticks(fontsize=set_font)
    plt.xlabel(xlabel='Planting date',fontsize=set_font)
    plt.ylabel(ylabel='Yield (bu/ac)',fontsize=set_font)

    ax.tick_params(axis='both', which='major', labelsize=set_font)
    plt.suptitle("Red vertical line shows the optimum date", 
                 x=0.5, y=0.98, ha='center', fontsize=set_font)
    plt.title("Grey area shows the 95% confidence limits (uncertainty)", 
              x=0.485, y=1.01, ha='center', fontsize=set_font)

    
    #find min and maximum to set ylimit 
    thresmax1 = (data["topy"].max())+2.5
    thresmin1 = (data["bottomy"].min())*0.999
    ax.set(ylim=(thresmin1, thresmax1));
    
    figy_line=ax.get_figure()
    plt.close();
    
    return figy_line

g=gr.Interface(fn=greet, 
    inputs=[gr.Dropdown(['a','b', 'c'], label="Choose your region"),
            gr.Slider(2, 8, step=1, label="Choose1"),
            gr.Slider(75000, 175000, step=25000, label="Choose2")],
    outputs= gr.Plot(label="forecast"))
g.launch(share=False)

### Logs

```shell
No errors, the output is not shown as it should
```

### System Info

```shell
Gradio version 3.16.2. Windows 10, Mozilla
```

### Severity

serious, but I can work around it

**Comment by freddyaboulton** [comment] 2023-02-06 15:19
Hi @szm0020 !

I think the problem is that you need to change the font color of the axis ticks?

Maybe this will help: https://stackoverflow.com/questions/48958208/how-do-you-change-the-default-font-color-for-all-text-in-matplotlib

Also, `gr.LinePlot` (the native line plot component) will automatically change the font color to match the overall light or dark mode theme of the app so this problem would not be an issue. It does not support the `fill_between` feature of your plot but maybe that's something we can build in a separate ticket if you file it!

**Comment by szm0020** [comment] 2023-02-06 15:55
Thank you for the reply, I changed the font color and it worked.

**Comment by freddyaboulton** [comment] 2023-02-06 16:14
Great to hear @szm0020 !

Will close this issue then. Don't hesitate to reach out in the future.

**Closed by freddyaboulton** 2023-02-06 16:14 UTC
Labels: bug
