### ISSUE TITLE
Custom Components Guide does not seem to lead to a working example

### ISSUE THREAD

**Issue by AlUlkesh** [gradio-app/gradio#6821] opened 2023-12-18 02:25 UTC
### Describe the bug

I tried following the guide at https://www.gradio.app/guides/custom-components-in-five-minutes.

I didn't make any code-changes yet, so I'm expecting to see my new component as a SimpleTextbox.

However when I go to the frontend URL I only see a screen with an infinite "Loading" text. The console shows these errors:

```
Uncaught SyntaxError: Unexpected token '{' (at (index):55:35)

svelte.js:3232 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '$$')
    at init (svelte.js:3232:44)
    at new Blocks (Blocks.svelte:669:31)
    at Array.create_if_block_1 (index.svelte:184:43)
    at Object.p (Index.svelte:394:41)
    at update_slot_base (svelte.js:203:8)
    at Object.p (core.js:231:1)
    at update (svelte.js:2128:30)
    at flush (svelte.js:2088:5)
```

Line 55 at index looks like this:

`		<script>window.gradio_config = {{ config | toorjson }};</script>`

Is this a bug? Am I missing a step?

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Follow the guide until you enter the frontend URL.

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Windows
gradio version: 4.10.0
gradio_client version: 0.7.3

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.2.0
fastapi: 0.105.0
ffmpy: 0.3.1
gradio-client==0.7.3 is not installed.
httpx: 0.24.1
huggingface-hub: 0.19.4
importlib-resources: 6.1.1
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.8.2
numpy: 1.23.5
orjson: 3.9.10
packaging: 23.2
pandas: 2.1.4
pillow: 9.5.0
pydantic: 2.5.2
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.8.0
uvicorn: 0.24.0.post1
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.12.1
httpx: 0.24.1
huggingface-hub: 0.19.4
packaging: 23.2
typing-extensions: 4.8.0
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment] 2023-12-18 21:10
I can't reproduce the problem on my end @AlUlkesh! You're not missing a step though.
Which version of node are you using?

**Comment by AlUlkesh** [comment] 2023-12-18 21:20
@freddyaboulton

These are the versions:
```
node  v21.4.0
npm   10.2.4
```

**Comment by freddyaboulton** [comment] 2023-12-18 21:31
Can you try with node version 18? I'm running v18.17.0

**Comment by AlUlkesh** [comment] 2023-12-18 23:31
I installed and activated node v18.17.0.

Unfortunately the result is the same.

![image](https://github.com/gradio-app/gradio/assets/99896447/379167a8-32a9-4f24-a567-8c45c249aab6)

**Comment by Ethan-yt** [comment] 2023-12-19 06:38
+1

**Comment by freddyaboulton** [comment] 2023-12-19 15:28
Are both of you on windows @Ethan-yt and @AlUlkesh ?

**Comment by Ethan-yt** [comment] 2023-12-19 15:39
> Are both of you on windows @Ethan-yt and @AlUlkesh ?

I am on macOS. Same problem, stuck on loading.
But when I change another macbook everything works fine...

**Comment by AlUlkesh** [comment] 2023-12-19 15:42
I'm on Windows 11.

**Comment by freddyaboulton** [comment] 2023-12-19 15:46
Are both of you on `npm` version 10?

**Comment by AlUlkesh** [comment] 2023-12-19 15:53
Well, I first was on:
```
node  v21.4.0
npm   10.2.4
```

but I since downgraded node due to your suggestion, so now it looks like this:
```
node  v18.17.0
npm   9.6.7
```

**Comment by pangyuteng** [comment] 2023-12-19 19:46
likely encoutering similar issue. I get no tracebacks after running `gradio cc dev` in terminal, accessing `http://127.0.0.1:7862` renders the "Loading..." view, firefox console shows some errors (pasted below) which looks slightly different than screenshots above.

node, npm, and os versions:
```
# node -v && npm -v && cat /etc/lsb-release
v18.17.0
9.6.7
Ubuntu 20.04.6 LTS
```
installed gradio from master ( commit# 16c0e4015ceeca33cf685d5b2cc4e1506579403b )

![image](https://github.com/gradio-app/gradio/assets/5231403/45ff3bbe-0c94-4c65-a421-faab7005b327)

**Comment by freddyaboulton** [comment] 2023-12-19 21:08
@pangyuteng @AlUlkesh @Ethan-yt can you please show me the contents of `window.__GRADIO__CC__` in the browser console?

<img width="338" alt="image" src="https://github.com/gradio-app/gradio/assets/41651716/8064724d-dffb-4adc-823c-39deabafd291">

**Comment by AlUlkesh** [comment] 2023-12-19 21:34
![image](https://github.com/gradio-app/gradio/assets/99896447/c6a78181-5e8a-4a11-b020-204585dca28e)

**Comment by pangyuteng** [comment] 2023-12-19 21:38
lol. i am a javascript noob. i guess mine is a different issue?
![image](https://github.com/gradio-app/gradio/assets/5231403/bc83b570-4cf6-43e2-9f4d-93aa6934529e)

**Comment by freddyaboulton** [comment] 2023-12-19 23:25
Yea they look like separate issues. In @AlUlkesh 's case, we can find the source code of the custom component but we can't load it for some reason. In your case, we couldn't find the source code (that's what `__GRADIO_CC__` being empty means). Still looking into it 😅

**Comment by Ethan-yt** [comment] 2023-12-20 02:37
<img width="1678" alt="image" src="https://github.com/gradio-app/gradio/assets/9592150/850484be-4b0b-4e70-8c4e-12a1704f7a46">

**Comment by kavincsekaran** [comment] 2023-12-20 20:39
+1
Same error message as @AlUlkesh 

node 20.10.0
npm 10.2.5

**Comment by HernanOlave** [comment] 2024-01-29 14:57
Same problem over here, any news on this issue?

I have tested on the Textbox template and the Chatbot template:

![image](https://github.com/gradio-app/gradio/assets/29231702/6f81d943-7978-47f2-bb98-2b812eec417e)

OS: Win 10
npm: 10.2.4
node: 20.11.0

**Comment by freddyaboulton** [comment] 2024-01-29 16:09
Hi @HernanOlave ! Can you please share the contents of `window.__GRADIO__CC_`. You should be able to type that into the console of the demo that's broken.

I believe it's the same windows permission issue. If you can try creating and running the component from the WSL that would be great, I believe it works in that case.

**Comment by HernanOlave** [comment] 2024-01-29 19:31
Update:

Files created by the template were missing some files that I found in the rich text box example:

![image](https://github.com/gradio-app/gradio/assets/29231702/adb57801-1f33-4eb9-97c9-522c854f7380)

I copy pasted them into the textbox template and now works:

![image](https://github.com/gradio-app/gradio/assets/29231702/b83e179f-2ab6-42f7-b199-5dd0e8684caa)

**Comment by freddyaboulton** [comment] 2024-02-02 15:39
> The command's output is undefined
I made a typo, the command in `window.__GRADIO_CC__` (there was an underscore missing at the end)

> Files created by the template were missing some files that I found in the rich text box example
Certainly unexpected.

> Thought It would work without having to build. I have to build and pip install for every change?
No.

What version of gradio are you using? The missing files make it seem like it is an old version but it could be another bug. Could be a good idea to upgrade versions just in case.

**Comment by freddyaboulton** [comment] 2024-03-09 01:35
Hi all, we just released gradio version 4.21.0. If you're still having issues getting dev mode to work can you please upgrade to version `4.21.0` and pass the `--python-path` and `--gradio-path` arguments to `gradio cc dev`.

Something like

```python
gradio cc dev --python-path <path-to-your-python-executable> --gradio-path <path-to-your-gradio-executable
```

I suspect this error comes from the custom component dev command up the wrong version of python installed in your system. We also added some debug output to `gradio cc dev`  that should help us further if that is not the cause of this issue.


PS: if you have a virtual environment, the path of the python executable is `<path-to-virtual-env>/bin/python`

**Comment by AlUlkesh** [comment] 2024-03-09 09:37
Hi @freddyaboulton,

I just upgraded and tried it out. Unfortunately it doesn't seem to help.

```
gradio cc dev --python-path z:\AI\image-browser-gallery\venv\Scripts\python.exe --gradio-path z:\AI\image-browser-gallery\venv\Scripts\gradio.exe
♻ Launching demo\app.py in reload mode

Watching: 'Z:\AI\image-browser-gallery\testtextboxe\demo'
'Z:\AI\image-browser-gallery\testtextboxe\frontend',
'z:\AI\image-browser-gallery\testtextboxe'



Backend Server:  http://127.0.0.1:7861



Frontend Server (Go here): http://localhost:7862/
```

![image](https://github.com/gradio-app/gradio/assets/99896447/6f394a9f-31a2-4d3c-999a-31123896f025)

[localhost-1709976930930.log](https://github.com/gradio-app/gradio/files/14545845/localhost-1709976930930.log)

**Comment by Lealand23231513** [comment] 2024-03-11 12:02
I meet the same problem when developing with windows11, so I develop on linux instead, and this problem no longer arises. I guess there may be something wrong with windows.

**Comment by freddyaboulton** [comment] 2024-03-11 17:05
@AlUlkesh I think we're making progress! Before it seemed like we couldn't find your component. Now we can but Chrome is blocking the filepath. Same issue as #7025 now (which we will fix), so I'm tempted to close this in the next couple of days!

**Comment by AlUlkesh** [comment] 2024-03-11 20:18
@freddyaboulton Sounds good! Looking forward to trying it out, once the fix hits.

**Comment by ysig** [comment] 2024-04-11 22:40
@freddyaboulton I have the same problem as AIUIkesh (code is found but not executed) and I'm working under port forwarding - chrome opens in windows 11 and the server runs in server with linux ubuntu.
npm: 10.5.0
node: v21.7.2

**Comment by freddyaboulton** [comment] 2024-05-09 23:31
@ysig - do you get the same error with gradio 4.29.0?

@ngaudemet please share the steps to reproduce in as much detail as possible (the create command, operating system). Did you access the front-end url, the one that says "(Go here)"?

<img width="643" alt="image" src="https://github.com/gradio-app/gradio/assets/41651716/ebd822c4-d48d-4737-9f4f-e80de3e047cf">

**Comment by jshph** [comment] 2024-05-31 15:53
Hi @freddyaboulton , encountering a similar issue. I run `gradio cc dev` on MacOS, using Gradio 4.32.1 and gradio-client 0.17.0. I used the frontend URL as you suggested

**Comment by freddyaboulton** [comment] 2024-05-31 16:17
Hi @jshph ! Thanks for reporting. Can you please share reproduction steps? Are there any errors reported in the console or the terminal? Can you also please share the contents of `window.__GRADIO_CC__`?

**Comment by jshph** [comment] 2024-05-31 20:49
@freddyaboulton I'm staying pretty close to the boilerplate for a custom component:

1. I created a custom component using the SimpleDropdown template
2. Ran `gradio cc dev` in the component root
3. Replaced the `app.py` code with `gr.Blocks()` code, nesting the custom component within it. A little like:

```python
with gr.Blocks() as demo:
    c = CustomComponent() # as input
    display_json = gr.JSON()
    c.change(lambda x: x, inputs=[c], outputs=[display_json])

demo.launch()
```

I take back `Components are not updating as expected`; I was missing a function call, i.e. `$: value, handle_change()` rather than `$: value, handle_change`, so that was an error with Svelte; components are updating now.

However, I am still seeing the error message in the console; it's just not impacting anything as far as I can tell.

**Comment by bosaeed** [comment] 2024-06-02 21:48
Hi,
I have same problem and following problem and found that as workaround can modify these two lines to fix
```javascript
    const example = exports.example ? `example: () => import("${to_posix(
      join("http://localhost:7861/@fs/"+component.frontend_dir, exports.example)
    )}"),
` : "";
    return `${acc}"${component.component_class_id}": {
			${example}
			component: () => import("${to_posix(
      join("http://localhost:7861/@fs/"+component.frontend_dir, exports.component)
    )}")
			},
`;
  }, "");
``` 
url "http://localhost:7861/@fs/" is added to frontend_dir
the file modified is in path frontend\node_modules\@gradio\preview\dist\index.js

**Comment by bosaeed** [comment] 2024-06-03 07:44
Hi,
I have same problem and following problem I found that as workaround can modify these two lines to fix

``` javascript
    const example = exports.example ? `example: () => import("${to_posix(
      join("http://localhost:7861/@fs/"+component.frontend_dir, exports.example)
    )}"),` : "";
    return `${acc}"${component.component_class_id}": {
			${example}
			component: () => import("${to_posix(
      join("http://localhost:7861/@fs/"+component.frontend_dir, exports.component)
    )}")},`;  }, "");
```

url "http://localhost:7861/@fs/" is added to frontend_dir
the file modified is in path frontend\node_modules@gradio\preview\dist\index.js

**Comment by loganrenaud** [comment] 2024-06-11 11:56
Because I had the same issue with window.__GRADIO_CC__ being undefined, I tried to use the --python-path and --gradio-path; but when my paths start with "C:/" or "/" I receive an error :

Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data, and node are 
supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. 
Received protocol 'c:'

And when my paths start with file:///, I receive the error (during Path(executable_path).exists())

The provided python path (file:///C:/Users/l.renaud/Component_Gradio/myenv/Scripts/python.exe) does not exist or is   
not a file.

So I am a bit confused I don't know if I am doing something wrong or if there is a mistake

**Comment by bosaeed** [comment] 2024-06-11 13:18
> Because I had the same issue with window.**GRADIO_CC** being undefined, I tried to use the --python-path and --gradio-path; but when my paths start with "C:/" or "/" I receive an error :
> 
> Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
> 
> And when my paths start with file:///, I receive the error (during Path(executable_path).exists())
> 
> The provided python path (file:///C:/Users/l.renaud/Component_Gradio/myenv/Scripts/python.exe) does not exist or is not a file.
> 
> So I am a bit confused I don't know if I am doing something wrong or if there is a mistake

to solve as workaround you need to change this line at file index.js in path ..\frontend\node_modules\@gradio\preview\dist\index.js

```
const m = await import(join(component.frontend_dir, "gradio.config.js"));
add "file://" to component.frontend_dir
const m = await import(join("file://"+component.frontend_dir, "gradio.config.js"));
```

**Closed** 2024-06-13 21:26 UTC
Labels: bug, needs repro, custom-components
