### ISSUE TITLE
Dataframe shrinks in height when editing.

### ISSUE THREAD

**Issue by SunXuan90** [gradio-app/gradio#5512] opened 2023-09-13 02:14 UTC
### Describe the bug

When editing dataframe, it keeps shrinking. The code I use is:

```py
gr.Dataframe(
    { "data": [ "aaa", "bbb"], "headers": [ "Model", "Step ID 1"},
    type="array",
    height=200,
    interactive=True,
    max_rows=None,
    max_cols=None,
)
```

When I edit the contents in turn, after editing left side, when I click another grid, it shrinks. This can even be reproduced in offical doc page https://www.gradio.app/docs/dataframe . Just keep editing the table at the begining of the page and it'll shrink.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```
gr.Dataframe(
    { "data": [ "aaa", "bbb"], "headers": [ "Model", "Step ID 1"},
    type="array",
    height=200,
    interactive=True,
    max_rows=None,
    max_cols=None,
)
```

### Screenshot

![屏幕截图 2023-09-13 095828](https://github.com/gradio-app/gradio/assets/27178583/45c8b49a-bbd1-46ae-a407-bb17d8cb68fa)
![屏幕截图 2023-09-13 095845](https://github.com/gradio-app/gradio/assets/27178583/0e3358eb-bd74-4d5c-9802-53ad87c3e13b)
![屏幕截图 2023-09-13 095901](https://github.com/gradio-app/gradio/assets/27178583/a16b4dc4-ce1e-45d8-8522-2b358a9f10ec)
![屏幕截图 2023-09-13 095914](https://github.com/gradio-app/gradio/assets/27178583/42c95d41-ab2c-4425-aac5-3a51ba98ab72)

### System Info

```shell
Win 10
Microsoft Edge 84.0.522.61
python 3.11
gradio 3.43.2
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment] 2023-09-13 02:27
I can reproduce this issue @SunXuan90. Its related to some recent changes we made to the `gr.DataFrame` component -- we'll look into it!

My code to reproduce:

```py
import gradio as gr

with gr.Blocks() as demo:
    gr.Dataframe(
        { "data": [ "aaa", "bbb"], "headers": [ "Model", "Step ID 1"]},
        type="array",
        height=200,
        interactive=True,
        max_rows=None,
        max_cols=None,
    )
    
demo.launch()
```

**Comment by abidlabs** [comment] 2023-09-25 22:23
Looks like this is fixed on `main` now! I tested with this:

```py
import gradio as gr

with gr.Blocks() as demo:
    gr.Dataframe(
        { "data": [ ["aaa"]*2, ["bbb"]*2], "headers": [ "Model", "Step ID 1"]},
        type="array",
        height=200,
        interactive=True,
        max_rows=None,
        max_cols=None,
    )
    
demo.launch()
```

We'll probably do a release to pypi soon, or you can install gradio from main by following the instructions here: https://gradio.app/docs/main

**Closed by abidlabs** 2023-09-25 22:23 UTC
Labels: bug, 💾 Dataframe
