### ISSUE TITLE
[Blocks] Examples component

### ISSUE THREAD

**Issue by aliabd** [gradio-app/gradio#737] opened 2022-02-25 01:13 UTC
Can we get a component for examples in Blocks? 

Would love to add examples to my block like in `Interface`. Maybe it could be a parameter in `button.click`

**Comment by FarukOzderim** [comment] 2022-03-07 07:23
I think this should not be in our priority, this should be in the 2nd next release :)

**Comment by abidlabs** [comment] 2022-03-28 15:41
It looks like this mostly works. However, I'm noticing some issues like with images not being loaded into the input correctly:

![image](https://user-images.githubusercontent.com/1778297/160435702-ac8653c8-9466-481f-b10e-6b5ef9b7aca0.png)

To reproduce, run `demo\image_classifier\run.py`

**Comment by abidlabs** [comment] 2022-03-28 15:41
cc @aliabid94

**Comment by abidlabs** [comment] 2022-04-11 21:47
Closed via #971

**Closed by abidlabs** 2022-04-11 21:47 UTC
Labels: enhancement
