### ISSUE TITLE
For some reason it generates a copy of the file when the image is used as the input parameter

### ISSUE THREAD

**Issue by peeter2** [gradio-app/gradio#9257] opened 2024-09-03 19:07 UTC
### Describe the bug

For some reason it generates a copy of the file when the image is used as the input parameter. If the image component type is already a filepath then there will be two files in the temp folder. One is the original file that I uploaded and the other is a generated file that has the same file name but extension is jpeg instead of jpg, and the image file size is also different.
Why does it generate the additional file? Why can't it use the file that was already uploaded?

### Have you searched existing issues?  🔎

- [x] I have searched and found no existing issues

### Reproduction

```
def function(image):
    return gr.Button(interactive=False)
with gr.Blocks() as demo:
    image = gr.Image(sources="upload", type="filepath")
    btn = gr.Button()
    image.change(fn=function, inputs=image, outputs=[btn])

```

### System Info

```shell
Latest
```

### Severity

I can work around it

**Comment by abidlabs** [comment] 2024-09-10 18:06
Hi @peeter2 can you please provide a minimal code example that we can use to reproduce the issue above? See: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by abidlabs** [comment] 2024-09-10 18:08
Hi @peeter2 the reason a new file is created is because Gradio saves all uploaded files in a temporary directory that it uses to serve files. Only files in this location are accessible to users of your application for security reasons. You can read more here: https://www.gradio.app/guides/sharing-your-app#security-and-file-access

**Comment by peeter2** [comment] 2024-09-10 18:33
the problem is that for some reason it generates two files. Let me try to be more clear:
1) The first file is uploaded to the temp directory when I drag an image to the image component.
2) The second file is generated when I have this line in my code: image.change(fn=function, inputs=image

So why does it generate the second file? Wouldn't it make sense to save resources by not creating a duplicate image file in the temp directory?

**Comment by abidlabs** [comment] 2024-09-10 19:13
Ah I see what you mean, I think yes we can reduce this redundancy

**Comment by abidlabs** [comment] 2024-09-12 03:46
Closed via https://github.com/gradio-app/gradio/pull/9314

**Closed by abidlabs** 2024-09-12 03:46 UTC
Labels: bug
