### ISSUE TITLE
Gallery front-end cannot display a url from web

### ISSUE THREAD

**Issue by kaleidoscopical** [gradio-app/gradio#5127] opened 2023-08-08 12:55 UTC
### Describe the bug

I found the `Gallery` front-end cannot display a url from web. It seems a strange prefix url is added to the front. 

example:
```html
<src="https://zb-dsw-dsw32719-80.pcs-svr.alibaba-inc.com/dsw32719/proxy/7862/file=https://images.unsplash.com/photo-1554151228-14d9def656e4?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=386&q=80">
```

The image I want to reach is from the url `https://images.unsplash.com/photo-1554151228-14d9def656e4?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=386&q=80`. But the prefix added prevents the browser to render the image correctly.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import random
import gradio as gr


with gr.Blocks() as demo:
    gallery = gr.Gallery(value=["https://images.unsplash.com/photo-1554151228-14d9def656e4?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=386&q=80"], preview=True)

demo.launch(root_path='')
```

### System Info

```shell
any
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment] 2023-08-08 14:40
Works for me @kaleidoscopical !

<img width="1794" alt="image" src="https://github.com/gradio-app/gradio/assets/41651716/1d67cf0b-7b00-4e7c-b1de-e98af56657e2">

**Comment by kaleidoscopical** [comment] 2023-08-09 06:37
hi @freddyaboulton ! Thanks for quick reply : )

It also works in my local environment with url `http://127.0.0.1:7860/file=https://images.unsplash.com/photo-1554151228-14d9def656e4?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=386&q=80`, but a prefix is also added, e.g. `http://127.0.0.1:7860/file=`.

My demo environment is a little bit tricky, the prefix becomes `https://zb-dsw-dsw32719-80.pcs-svr.alibaba-inc.com/dsw32719/proxy/7862/file=` which prevents the browser to render the image correctly. It works fine if I manually remove the prefix in the browser console. Could you suggest any action to remove the prefix in my demo environment once for all?

**Comment by luoweb** [comment] 2023-08-12 06:01
> prefix

i have the same problem

**Comment by luoweb** [comment] 2023-08-12 07:12
> > prefix
> 
> i have the same problem

finally i use the _js function return image array solved the problem.

**Comment by freddyaboulton** [comment] 2023-08-14 14:08
Are you using nginx? This may come in handy: https://www.gradio.app/guides/running-gradio-on-your-web-server-with-nginx

**Comment by ivan-mihailov** [comment] 2023-10-02 08:31
I have the same issue on HF Space: Gallery adds `https://{HF SPACE NAME}.hf.space/proxy=https://{HF SPACE NAME}--mgwbh.hf.space/` before the file location URL. When I remove this prefix manually in Chrome Dev Tool and leave src as "file=/tmp/gradio/31eb62425f47ccdf1436dc19af0e6db0db487298/image.png" then the image displays properly. Similarly to @kaleidoscopical the image display works perfectly when tested locally and displays properly.

**Comment by freddyaboulton** [comment] 2023-10-02 14:15
Hi @ivan-mihailov ! That seems like it's caused by your space having more than one replica. That should have been fixed in https://github.com/gradio-app/gradio/pull/5668 which got released in 3.45.2. It's a separate issue from the other comments in this thread.

**Comment by abidlabs** [comment] 2023-10-02 21:49
The original issue should be fixed now on the latest version of `gradio` -- @kaleidoscopical

**Comment by freddyaboulton** [comment] 2023-10-03 17:11
Hi @ivan-mihailov. Thanks for the follow-up. You're right, there is a bug in gradio/HF Spaces that's causing the issue.

Will look into this! 

CC @abidlabs this seems related to #5668 (now the X-Direct-URL gets sent with every request)

**Closed** 2023-10-05 18:17 UTC
Labels: bug, cloud

**Comment by abidlabs** [comment] 2023-10-06 17:20
Can you try with Gradio 3.47.1?

**Comment by ivan-mihailov** [comment] 2023-10-06 18:58
> Can you try with Gradio 3.47.1?

I just did. Same result as to Gradio 3.46.1.  `src="/proxy=https://{HF-SPACE-NAME.hf.space/--replicas/hc4dm/file=/tmp/gradio/2df69fe7039199c1060a36b8508856124a981c2a/image.png"`

**Comment by abidlabs** [comment] 2023-10-06 19:04
Can you link to your Space?

**Comment by ivan-mihailov** [comment] 2023-10-06 21:21
> Can you link to your Space, or provide us with a minimal example we can use to debug?

@abidlabs I could not link you to our Space (proprietary algo/data). So I made a minimal example--and that one worked like a charm with Gradio 3.47.1.

I dug into the Build Logs for our original Space and determined that for some reason, even when I change the Gradio/Gradio-Client versions to 3.47.1/0.6.0, those versions get installed and then a separate pip install command is run that downloads Gradio version 3.45.2 which then uninstalls Gradio version 3.47.1. I spent hours trying to determine if another library in the requirements.txt file is forcing this un-installation but to no avail.

I am attaching the latest Build Log in case you can see something in there that I am missing.
[Build_Log_06_10_23_20_48.txt](https://github.com/gradio-app/gradio/files/12835535/Build_Log_06_10_23_20_48.txt)

**Comment by abidlabs** [comment] 2023-10-07 05:12
Hi @ivan-mihailov, I think I know the issue. To set the version of `gradio` on Hugging Face Spaces, you actually need to set the `sdk_version` in the `README.md` file, not in the requirement.txt. The `sdk_version` takes priority. If you set it to 3.47.1, it should work!

**Comment by ivan-mihailov** [comment] 2023-10-07 08:10
OMG! You are the best, @abidlabs !!!! Thank you so much! I spent so many hours trying to figure this out! I must have re-written the requirements.txt file at least 10 times thinking one of the other libraries was forcing the un-install! Problem has been solved and the Space looks and functions great!
