### ISSUE TITLE
We still don't have full screen image gallery mode right?

### ISSUE THREAD

**Issue by FurkanGozukara** [gradio-app/gradio#8697] opened 2024-07-03 17:41 UTC
I am using gallery as below with latest gradio

                with gr.Column(scale=1):
            
                    gallery = gr.Gallery(label="Generated Images", columns=1, rows=1, height=512, format="png", preview=True, allow_preview=True)

the output still doesn't become full screen when clicked or there isn't any option

it is only like below

can i somehow make it full screen when clicked and user can navigate with arrow keys?

![image](https://github.com/gradio-app/gradio/assets/19240467/6c85f6aa-5f4d-41d4-b3e8-42f6db8255f9)

**Comment by abidlabs** [comment] 2024-07-03 17:47
Hi @FurkanGozukara yes this is still not supported, but its on the roadmap! Closing as this is a duplicate of https://github.com/gradio-app/gradio/issues/6939

**Closed by abidlabs** 2024-07-03 17:47 UTC
Labels: bug

**Comment by FurkanGozukara** [comment] 2024-07-03 17:49
@abidlabs ty for answer
