### ISSUE TITLE
`gr.update` doesn't work for `elem_classes`

### ISSUE THREAD

**Issue by apolinario** [gradio-app/gradio#5524] opened 2023-09-13 15:46 UTC
### Describe the bug

`gr.update` doesn't work for `elem_classes`

```shell
TypeError: Button.update() got an unexpected keyword argument 'elem_classes'
```

Would be great to be able to swap the class of an element, for styling purposes 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```py
def fun():
    gr.update(elem_classes="clicked")

with gr.Blocks() as demo:
    btn = gr.button(elem_classes="unclicked")
    btn.click(fun, outputs=btn)
```

### System Info

```shell
gradio==3.44.0
```

### Severity

I can work around it

**Comment by abidlabs** [comment] 2023-09-13 15:47
Thanks @apolinario, this is duplicate of #4590 so I'll close -- we should get this fixed very soon though. 

cc @aliabid94

**Closed by abidlabs** 2023-09-13 15:47 UTC
Labels: bug
