### ISSUE TITLE
Click event becomes None after upgrading to gradio 4.9.1

### ISSUE THREAD

**Issue by empty-id** [gradio-app/gradio#6800] opened 2023-12-15 02:59 UTC
### Describe the bug

(Pdb) p evt
<gradio.events.SelectData object at 0x1370ab580>
(Pdb) p evt.__dict__
{'target': image, '_data': {'index': [None, None], 'value': None}, 'index': [None, None], 'value': None, 'selected': True}

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

with gr.Blocks() as demo:
    input_img = gr.Image(label="Input", height=500)
    def get_select_coords(state, evt: gr.SelectData):
        img = state['img']
        shape = img.shape
        click = evt.index[1], evt.index[0]
        breakpoint()
    
    input_img.select(get_select_coords, state, [output_txt, input_img])

if __name__ == "__main__":
    demo.launch()
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Darwin
gradio version: 4.9.1
gradio_client version: 0.7.3

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.1.2
fastapi: 0.104.1
ffmpy: 0.3.1
gradio-client==0.7.3 is not installed.
httpx: 0.25.0
huggingface-hub: 0.19.4
importlib-resources: 6.1.1
jinja2: 3.1.2
markupsafe: 2.1.1
matplotlib: 3.7.0
numpy: 1.23.5
orjson: 3.9.10
packaging: 23.1
pandas: 1.5.3
pillow: 9.4.0
pydantic: 2.1.1
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.8.0
uvicorn: 0.24.0.post1
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.9.2
httpx: 0.25.0
huggingface-hub: 0.19.4
packaging: 23.1
typing-extensions: 4.8.0
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment] 2023-12-15 03:09
Thanks @empty-id for the report. Similar to https://github.com/gradio-app/gradio/issues/5945

**Comment by freddyaboulton** [comment] 2023-12-15 16:11
What version was this working correctly in @empty-id ?

**Comment by pngwn** [comment] 2023-12-18 11:59
Duplicate of #5945.

**Closed by pngwn** 2023-12-18 11:59 UTC
Labels: bug, Regression
