### ISSUE TITLE
Output file is put at /tmp file and it doesn't work on cluster environment

### ISSUE THREAD

**Issue by MrNocTV** [gradio-app/gradio#2899] opened 2022-12-28 07:05 UTC
### Describe the bug

I'm using version 3.14, and there is an issue with `/tmp` file.
After `/join` processing , Gradio returns the path to the output file.

<img width="549" alt="Screen Shot 2022-12-28 at 13 58 25" src="https://user-images.githubusercontent.com/11014873/209771615-2f77219a-1023-43cd-b7da-5998f664220e.png">

Then it tries to fetch that file, but unfortunately it failed.
In a cluster environment like multiple pods on K8s, requests are routed to different pod every single times.

In this case, the request was routed to a different pod, and it logs out this error.

```
ValueError: File cannot be fetched: /tmp/output_vsre9e5bfed6ae3cdf251047d5d5ddb1bc5e6d4b1d0.mp4. All files must contained within the Gradio python app working directory
```

I think the only way to fix this problem is to return the output file in websocket message. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Run Gradio 3.14 on kubernetes with at least 2 pods

### Logs

```shell
2022-12-28T05:25:55.012+0000 raw_response = await run_endpoint_function(                                                                                                                              
2022-12-28T05:25:55.013+0000 File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 163, in run_endpoint_function                                                                     
2022-12-28T05:25:55.015+0000 return await run_in_threadpool(dependant.call, **values)                                                                                                                 
2022-12-28T05:25:55.016+0000 File "/usr/local/lib/python3.9/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool                                                                    
2022-12-28T05:25:55.020+0000 return await anyio.to_thread.run_sync(func, *args)                                                                                                                       
2022-12-28T05:25:55.021+0000 File "/usr/local/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync                                                                                   
2022-12-28T05:25:55.023+0000 return await get_asynclib().run_sync_in_worker_thread(                                                                                                                   
2022-12-28T05:25:55.025+0000 File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread                                                        
2022-12-28T05:25:55.027+0000 return await future                                                                                                                                                      
2022-12-28T05:25:55.028+0000 File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run                                                                              
2022-12-28T05:25:55.030+0000 result = context.run(func, *args)                                                                                                                                        
2022-12-28T05:25:55.031+0000 File "/usr/local/lib/python3.9/site-packages/gradio/routes.py", line 272, in file                                                                                        
2022-12-28T05:25:55.033+0000 raise ValueError(                                                                                                                                                        
2022-12-28T05:25:55.034+0000 ValueError: File cannot be fetched: /tmp/output_vsre9e5bfed6ae3cdf251047d5d5ddb1bc5e6d4b1d0.mp4. All files must contained within the Gradio python app working directory
```

### System Info

```shell
- Gradio 3.14
```

### Severity

annoying

**Comment by abidlabs** [comment] 2022-12-29 05:15
Thanks for investigating and creating this issue @MrNocTV. So to confirm the issue, when a user interacts with a Gradio demo and creates an output file using a prediction function, that file is only created on a specific pod. When the demo tries to display the file, the `/file=` request is routed to a different pod, which does not have the file. One option would be return the serialized file to the front end, but I would prefer not to go down that route, as serialization is quite slow esp. for large video files.

Do you have any sort of shared storage between the pods? I don't know K8s that well, but it sounds like K8s supports this:
- https://bluexp.netapp.com/blog/kubernetes-shared-storage-the-basics-and-a-quick-tutorial
- https://itnext.io/temporary-storage-for-kubernetes-pods-f8330ad8db88

It sounds like you might be able to mount a shared volume to the `/tmp/` path. Is that possible?

**Comment by MrNocTV** [comment] 2022-12-29 09:19
I think it's one of the solution, but I'm not sure if it works with Gradio 3.14. I think there is a possibility that pod A creates`/tmp/fileA` and pod B tries to do that again.

**Comment by abidlabs** [comment] 2022-12-29 16:33
Gradio will first check if the temp file already exists, and if it does, it will not create it again

**Comment by MrNocTV** [comment] 2023-01-03 01:54
@abidlabs 
Apologize for my late response, I'll try out your solution and let you know if it works.

**Comment by MrNocTV** [comment] 2023-01-10 05:57
Hi @abidlabs,
Apologize for my late response, even though I have applied a shared PVC, the problem still exists.
```
ValueError: File cannot be fetched: /tmp/output_vsr1261d96dafc23f9d37026cac2c35ee0a050ea4a7.mp4. All files must contained within the Gradio python app working directory, or be a temp file created by the Gradio python app.
```

**Comment by MrNocTV** [comment] 2023-01-10 06:24
Looks like the output file has not been created yet while other pods trying to fetch it.

**Comment by abidlabs** [comment] 2023-01-15 02:45
Thanks for letting us know, hmm. So just to confirm, you created a shared PVC and set its path to /tmp?

**Comment by MrNocTV** [comment] 2023-01-16 02:15
Yes, I created a shared PVC with `mountPath` to `/tmp`.

**Comment by abidlabs** [comment] 2023-01-16 02:17
Hmm that's very strange. How can the file not be created then? This is going to be tricky to debug, but would you be able to manually check to see if ` /tmp/output_vsr1261d96dafc23f9d37026cac2c35ee0a050ea4a7.mp4` has been created?

**Comment by MrNocTV** [comment] 2023-01-16 02:18
The weird thing is the output file has been created, I'm not sure what could be wrong.

**Comment by MrNocTV** [comment] 2023-01-16 07:51
@abidlabs , at the moment, we are applying IP Hash to make requests consistently go to 1 pod.
However this might cause imbalance when the workload increases.

**Comment by MrNocTV** [comment] 2023-01-30 02:18
Hi @abidlabs,

Sorry for bothering you, I just want to ask if this problem is fixable :D

**Comment by abidlabs** [comment] 2023-01-31 22:47
It should definitely be fixable, but it's a difficult problem to reproduce / test given that kubernetes is involved. If you have a simple way we could reproduce this, it would be super helpful in getting this fixed.

**Comment by MrNocTV** [comment] 2023-02-07 03:38
Thank you, I will try setting up a small testing environment using minikube to reproduce this issue locally and give you the details.

**Comment by abidlabs** [comment] 2023-02-07 03:40
Appreciate that!

**Comment by abidlabs** [comment] 2023-02-09 02:35
@MrNocTV just FYI I have some bandwidth tomorrow or Friday to take a look if you are able to set up a reproducible environment. Thanks!

**Comment by abidlabs** [comment] 2023-02-13 18:49
Hi @MrNocTV I'm going to close this issue for now for lack of reproducibility. If you are able to get something up running that we can use to reproduce the issue, feel free to reopen.

**Comment by MrNocTV** [comment] 2023-02-14 04:27
Hi @abidlabs ,

Apologize for my late response,
How can I reopen this issue?
I've been working on fixing some other bugs and I will try to make a reproduction this week.

**Comment by MrNocTV** [comment] 2023-02-14 04:29
I have the source code having the issue, I will try to make a document asap.

**Comment by abidlabs** [comment] 2023-02-14 15:00
You should see a "reopen" button at the bottom of the page -- I'll go ahead and reopen it myself

**Comment by MrNocTV** [comment] 2023-02-16 06:07
The base image that we're using is own private Docker image, I need to build another one and public it so that it won't violate company rules.

**Comment by MrNocTV** [comment] 2023-02-22 09:42
@abidlabs 
I'm trying to create a Deployment and use port-forward to test it, but I got CORS 😢 
It's weird that at first some of the requests are allow to go through, then they all get blocked by CORS.

**Comment by GeneralAwareness** [comment] 2023-02-23 00:48
As a user I am running into this nonsense myself and it is rather annoying, and stupid as well.

 All files must contained within the Gradio python app working directory, or be a temp file created by the Gradio python app.
 
 Comes and goes.
 
 ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 94, in receive
    return self.receive_nowait()
  File "D:\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 89, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 77, in call_next
    message = await recv_stream.receive()
  File "D:\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 114, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\stable-diffusion-webui\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "D:\stable-diffusion-webui\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\fastapi\applications.py", line 271, in __call__
    await super().__call__(scope, receive, send)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\starlette\applications.py", line 125, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "D:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 104, in __call__
    response = await self.dispatch_func(request, call_next)
  File "D:\stable-diffusion-webui\modules\api\api.py", line 96, in log_and_time
    res: Response = await call_next(req)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 80, in call_next
    raise app_exc
  File "D:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 69, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "D:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "D:\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\fastapi\routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\fastapi\routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 286, in file
    raise ValueError(
ValueError: File cannot be fetched: D:/stable-diffusion-webui/extensions/sd-webui-additional-networks/javascript/additional_networks.js. All files must contained within the Gradio python app working directory, or be a temp file created by the Gradio python app.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 94, in receive
    return self.receive_nowait()
  File "D:\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 89, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 77, in call_next
    message = await recv_stream.receive()
  File "D:\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 114, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\stable-diffusion-webui\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "D:\stable-diffusion-webui\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\fastapi\applications.py", line 271, in __call__
    await super().__call__(scope, receive, send)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\starlette\applications.py", line 125, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "D:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 104, in __call__
    response = await self.dispatch_func(request, call_next)
  File "D:\stable-diffusion-webui\modules\api\api.py", line 96, in log_and_time
    res: Response = await call_next(req)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 80, in call_next
    raise app_exc
  File "D:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 69, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "D:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "D:\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\fastapi\routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\fastapi\routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 286, in file
    raise ValueError(
ValueError: File cannot be fetched: D:/stable-diffusion-webui/extensions/sd-webui-additional-networks/javascript/additional_networks.js. All files must contained within the Gradio python app working directory, or be a temp file created by the Gradio python app.

**Comment by abidlabs** [comment] 2023-02-23 02:49
@GeneralAwareness we love feedback, but please being kind and respectful while giving it is also important. We're working very hard on improving the library but please don't forget that we are human on the other side too. I've hidden your comment as it does not reflect our values as a community.

**Comment by abidlabs** [comment] 2023-02-23 02:49
@GeneralAwareness we love feedback, but please being kind and respectful while giving it is also important. We're working very hard on improving the library but please don't forget that we are human on the other side too. I've hidden your comment as it does not reflect our values as a community.

**Comment by GeneralAwareness** [comment] 2023-02-23 03:09
Didn't know this was a touchy feely community.  Broken is as broken was.

Streamit is better but the application I use uses this mess, and it is a mess (there is a reason a lot of authors are switching to streamit if only the one I use would).

Thanks anyway.

**Comment by MrNocTV** [comment] 2023-02-23 03:42
Hi @abidlabs ,

Is it possible to bypass the CORS with Gradio, I've searched several ways but none of them are helpful.

**Comment by abidlabs** [comment] 2023-02-23 03:44
I think we might have the same issue that just opened up here (#3294). Can you elaborate a little more on your setup and the code you're running? Anything that you can do to help us repro would be appreciated

**Comment by MrNocTV** [comment] 2023-02-23 03:57
@abidlabs 
Yes, please take a look.
- Environment: Kubernetes
- Source code: https://github.com/MrNocTV/gradio-tmp-reporduce
- Deployment
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reproduce-tmp
spec:
  selector:
    matchLabels:
      run: reproduce-tmp
  replicas: 1
  template:
    metadata:
      labels:
        run: reproduce-tmp
    spec:
      restartPolicy: Always
      hostNetwork: true
      containers:
      - name: reproduce-tmp
        image: loctvuit/test-gradio:1.0.0
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        args: ["-c", "git config --global http.sslVerify \"false\"; git clone https://github.com/MrNocTV/gradio-tmp-reporduce;cd gradio-tmp-reporduce;pip install -r requirements.txt;python app.py"]
        ports:
        - containerPort: 7860
          protocol: TCP
        resources:
          limits:
            memory: 2000Mi
          requests:
            memory: 1000Mi
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
```

I use port-forwarding to access the Gradio app from my localhost on port 7860.
Some of the file requests in the example (mp4) got 200, but after that all of them got CORS.

**Comment by abidlabs** [comment] 2023-02-27 15:29
@zolero are you also running on Kubernetes?

**Comment by zolero** [comment] 2023-02-27 15:37
I'm running different pods as well yes, although have shared storage mounts. Is there a way how to serve the file from a different path? Do I have to save the file in the working directory of Gradio itself, and if so where? Can't really figure it out reading docs or the code itself.

**Comment by abidlabs** [comment] 2023-02-27 15:48
One thing I'd like to understand is whether the issue is with files not being present on different pods, or whether it's an issue of Gradio preventing access to those files. I'm going to release a version of Gradio that allows accessing to any files, and it would be great @zolero @MrNocTV if you guys can test it out. Stay tuned.

**Comment by zolero** [comment] 2023-02-27 15:50
> One thing I'd like to understand is whether the issue is with files not being present on different pods, or whether it's an issue of Gradio preventing access to those files. I'm going to release a version of Gradio that allows accessing to any files, and it would be great @zolero @MrNocTV if you guys can test it out. Stay tuned.

Sure thing! I'll test it out when it's available.

**Comment by zolero** [comment] 2023-02-27 16:04
@abidlabs I've figured it out for myself, not sure if this helps others as well. I've mounted a shared volume at /root/cache and this directory is set as tempdir. I can share these files now between these pods. I previously had it at mounted at /shared_vol. Seems it has to do something because of it wasn't mounted at /root/... Hope it helps anyone!

```py
##### setup tempdir
tempfile.tempdir = config.CACHE_DIR
```

**Comment by abidlabs** [comment] 2023-02-27 16:11
Nice!! Thanks @zolero for sharing. Did you have to modify your local version of Gradio in order to set `tempfile.tempdir`?

**Comment by zolero** [comment] 2023-02-27 16:21
Nope, it seems to be working now. I'm no python expert yet. Otherwise I could give you a little more information. But right it just uses the latest version of gradio. It can read/write these files now between pods and uploaded files can be passed as filestring and processed between pods, which for me does the job.

About it's security... Got quiet some concerns about this part since you can basically read any file now by just changing the URL path. /file=/root/cache/tmp735ebskw.wav to another file.

Changing it's tempfile.tempdir it changes it not only for gradio, but as well as for other libraries I suppose?

I have a feeling that the file serving / reading / writing logic of gradio needs to have a little work to make it safe against security breaches. This one is because of myself, but some extra options within initialization of gradio and setting tmp directory paths should do the trick.

Thanks for your work @abidlabs.

**Comment by abidlabs** [comment] 2023-02-27 16:23
> About it's security... Got quiet some concerns about this part since you can basically read any file now by just changing the URL path. /file=/root/cache/tmp735ebskw.wav to another file.

Actually that should not be the case. Gradio only allows access to files that it created (or are in the Gradio working directory). You can check this yourself by changing the path to a different file. 

> Changing it's tempfile.tempdir it changes it not only for gradio, but as well as for other libraries I suppose?

Yes, so perhaps this is something that we can let users configure within the Gradio library.

-------

@MrNocTV could you try the solution @zolero provided and let us know if it works for you as well?

**Comment by MrNocTV** [comment] 2023-02-28 07:44
@abidlabs 
Great news, I'll test it out now. :D

**Comment by MrNocTV** [comment] 2023-02-28 07:49
@zolero 

Thank you for your finding. 
I just want to confirm, I only need to mound the shared volume at `/root/cache`, is there anything else I need to configure?

```
##### setup tempdir
tempfile.tempdir = config.CACHE_DIR
```

Where can I make this config?

**Comment by abidlabs** [comment] 2023-02-28 16:54
@MrNocTV I believe it should be at the top of your Python script (anywhere before the Gradio app is created)

**Comment by MrNocTV** [comment] 2023-03-01 02:40
@abidlabs 

That means we have to manually change the user's code, this might not work as we're only allowed to deploy their code.

Is it possible to make it configurable in Gradio via environment variables?

**Comment by MrNocTV** [comment] 2023-03-01 03:35
@abidlabs 

I still have the same error :(

```
2023-03-01T03:34:34.071+0000 [RUN] ValueError: File cannot be fetched: /root/cache/output_vsr1261d96dafc23f9d37026cac2c35ee0a050ea4a7.mp4. All files must  │
│ contained within the Gradio python app working directory, or be a temp file created by the Gradio python app.
```

**Comment by abidlabs** [comment] 2023-03-01 06:31
@MrNocTV thanks for sharing the error. Since the file has been created, it looks like Gradio is blocking access to it for some reason. Can you try one more thing -- in the `launch()` method, can you try specifying this directory to the `file_directories` parameter? This parameter allows the developer to specify additional directories that the Gradio app can serve files from. So you could would look something like this:

```py
...
demo.launch(file_directories="/root/cache")
```

You could be even more permissive and try something like `file_directories="/root"` or `file_directories="/`

**Comment by MrNocTV** [comment] 2023-03-01 06:46
@abidlabs 
I got this error :( 

```
2023-03-01T06:45:17.119+0000 [RUN] TypeError: launch() got an unexpected keyword argument 'file_directories'
```

**Comment by abidlabs** [comment] 2023-03-01 06:48
Looks like you are using an older version of Gradio than 3.18. Can you upgrade to the latest version? (`pip install --upgrade gradio`)

**Comment by MrNocTV** [comment] 2023-03-01 06:52
Let me try, we are using our custom Gradio 3.14, because we want to omit the Google Analytic from the code.

**Comment by abidlabs** [comment] 2023-03-01 07:01
@MrNocTV if you set `analytics_enabled=False` in `launch()`, Google Analytics will be removed automatically

**Comment by MrNocTV** [comment] 2023-03-01 07:07
Yeah, I think we need to change back to using that parameter because this manual-building procedure causing us to fall behind the development process of Gradio.

Is it 100% correct that there will be no code regarding GA rendered in the UI and no GA API calls?

**Comment by abidlabs** [comment] 2023-03-01 07:35
I just checked and from what I see, if you set `analytics_enabled=False`, the Google Analytics javascript is not loaded. To provide a more complete explanation, here is the code needed to run google analytics:

```js
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=TAG_ID"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments)};
  gtag('js', new Date());

  gtag('config', 'TAG_ID');
</script>
```

If `analytics_enabled=False`, this line: `<script async src="https://www.googletagmanager.com/gtag/js?id=TAG_ID"></script>`
is not included, which means that google analytics is not called. The remaining lines are included, but they are just storing data locally, not sending anywhere. Of course, for any kind of sensitive application, I would verify this yourself by monitoring the network requests!

**Comment by MrNocTV** [comment] 2023-03-01 07:42
Hi @abidlabs ,
Thank you for your details explanation, I will talk with my team about the GA code. :D

About the problem, looks like it's working.
I will play with the code a little more to get the correct working code (without redundant configs).

**Comment by abidlabs** [comment] 2023-03-01 07:43
> About the problem, looks like it's working.

Awesome!! Glad to hear. So did you have to add `file_directories="/root/cache"` or did simply upgrading the Gradio version solve the problem?

**Comment by MrNocTV** [comment] 2023-03-01 07:44
I'm figuring that out :D please wait a bit.

**Comment by MrNocTV** [comment] 2023-03-01 07:59
I've removed the `tempfile` and keep ` file_directories="/root/cache"`, that is the only way I could make it works.

**Comment by MrNocTV** [comment] 2023-03-01 08:01
@abidlabs 
It would be so convenient if the `file_directories` can be set as environment variable and could not be override if it is set. 
Same thing goes for the option `analytics_enabled=False`, we remove it manually because it can be override by user's code.

**Comment by abidlabs** [comment] 2023-03-01 08:07
> Same thing goes for the option analytics_enabled=False, we remove it manually because it can be override by user's co

We do allow setting `analytics_enabled` via an environmental variable, but we would always let the user have the final option. Throughout Gradio's codebase, we respect the following priority system: default value < environmental variable < user-provided parameter value. 

We could in theory do something similar for the `file_directories` variable, though I'm inclined against it for now since it could lead to some very insecure settings (if the environmental variable is configured improperly, it could allow users to access any file on the Gradio app's computer). Let's keep it explicit for now, glad to hear that we've finally managed to make it work.

**Closed by abidlabs** 2023-03-01 08:07 UTC
Labels: bug, needs repro

**Comment by MrNocTV** [comment] 2023-03-01 08:31
@abidlabs 

Thank you a lot for your support :D

**Comment by MrNocTV** [comment] 2023-03-02 02:46
Hi @abidlabs ,

I've made a PR here, please check when you have time.

https://github.com/gradio-app/gradio/pull/3355

**Comment by rwb-truelime** [comment] 2024-03-17 09:52
Hi! Running into this issue in Azure Container Instances. How can you set ```file_directories``` in the current version (4.21)? Thanks!

**Comment by varungupta31** [comment] 2024-05-16 16:00
The simplest way turns out to be this

```python
import os
os.environ['GRADIO_TEMP_DIR'] = 'gradio_tmp'
import gradio as gr
```

where `gradio_tmp` is the desired new location of the `tmp`!
