### ISSUE TITLE
Limit on maximum output length

### ISSUE THREAD

**Issue by piecurus** [gradio-app/gradio#523] opened 2022-02-02 14:57 UTC
**Describe the bug**
There is apparently a limitation on the length of the text output, which maximum length appears to be around 4000 characters. Also, there seems to be no possibility to write a text file. Is this bug (or request about to write a text file) going to be fixed in the future?

**To Reproduce**
1. Go to 'https://huggingface.co/spaces/piecurus/speech_to_text'
2. In the function "asr_transcript_long" you can change the output to a bigger number
3. The interface just says there is an error

**Screenshots**

**Device information (please complete the following information):**
 - Running in Huggingface spaces

**Additional context**
 No additional context

**Comment by abidlabs** [comment] 2022-02-02 14:59
Thanks for catching this @piecurus. 

What do you mean "write a text file"? You can return an arbitrary file using the "File" output -- or do you mean something else?

**Comment by piecurus** [comment] 2022-02-02 15:03
From documentation I was not able to catch how to create a file containing text. I was thinking that an alternative to visualise long text could be dumping it in a file.

**Comment by abidlabs** [comment] 2022-02-02 15:43
Yup you can do that by using the `File` output component, and returning the filepath to a file that you've created with the text.

For one example of how to use the `File` output component, you can check out: https://colab.research.google.com/drive/1bGIiLkSsU_hY_I778JS2jTrmvQDXDu1I

**Comment by abidlabs** [comment] 2022-02-07 19:40
I also tested and could not reproduce the maximum output length being 4,000 characters. I tested up to 15k characters and did not see any issue. I'll go ahead and close the issue for now, but if this does not solve your issue, please feel free to reopen and add more details!

**Closed by abidlabs** 2022-02-07 19:40 UTC
Labels: bug
