### ISSUE TITLE
`concurrency_limit` is not respected in event listener if `default_concurrency_limit` is lower

### ISSUE THREAD

**Issue by Cyrilvallez** [gradio-app/gradio#7543] opened 2024-02-26 14:49 UTC
### Describe the bug

From what I understand, individual `concurrency_limit` on event listeners should always take precedence over the global `default_concurrency_limit` (which is set to 1 by default). From the doc: "You can also set the number of requests that can be processed in parallel for each event individually. These take priority over the default_concurrency_limit parameter described previously."

However, in my case, the actual `concurrency_limit` on listeners is not respected if `default_concurrency_limit` is lower. If it is bigger, then it is correctly restrained to the individual `concurrency_limit` on the listener. While I can easily get around the issue by setting `default_concurrency_limit=None` and applying a limit on each event, I still think it should be patched. Indeed, if I set a `concurrency_limit` on my listener, but I do not touch `default_concurrency_limit`, I would still expect the concurrency to be set correctly.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Here are my event listeners for reference:
```python
# Perform chat generation when clicking the button or pressing enter
generate_event1 = gr.on(triggers=[generate_button.click, prompt.submit], fn=chat_generation, inputs=inputs_to_chatbot,
                        outputs=[prompt, conversation, output], concurrency_id='generation', concurrency_limit=5)
# Add automatic callback on success
generate_event1.success(logging_generation, inputs=inputs_to_callback, preprocess=False,
                        queue=False, concurrency_limit=None)

# Continue generation when clicking the button
generate_event2 = continue_button.click(continue_generation, inputs=inputs_to_chatbot_continuation,
                                             outputs=[conversation, output], concurrency_id='generation')
# Add automatic callback on success
generate_event2.success(logging_continuation, inputs=inputs_to_callback, preprocess=False,
                        queue=False, concurrency_limit=None)

# Continue generation when clicking the button
generate_event3 = retry_button.click(retry_chat_generation, inputs=inputs_to_chatbot_retry,
                                          outputs=[conversation, output], concurrency_id='generation')
# Add automatic callback on success
generate_event3.success(logging_retry, inputs=inputs_to_callback, preprocess=False,
                        queue=False, concurrency_limit=None)

# Clear the prompt and output boxes when clicking the button
clear_button.click(clear_chatbot, inputs=[username], outputs=[conversation, output, conv_id],
                   queue=False, concurrency_limit=None)

# Change visibility of generation parameters if we perform greedy search
do_sample.input(lambda value: [gr.update(visible=value) for _ in range(5)], inputs=do_sample,
                outputs=[top_k, top_p, temperature, use_seed, seed], queue=False, concurrency_limit=None)

# Correctly display the model and quantization currently on memory if we refresh the page (instead of default
# value for the elements) and correctly reset the chat output
loading_events = demo.load(loading, outputs=[conversation, output, conv_id, username, max_new_tokens],
                           queue=False, concurrency_limit=None)
```

In this case, running:

```python
demo.queue().launch(server_name='127.0.0.1', server_port=8000,
favicon_path=os.path.join(utils.ROOT_FOLDER, 'favicon.ico'))
``` 

would not work because by default `default_concurrency_limit`  is 1 < 5 (not sure if events with `concurrency_limit=None` are also restrained to 1 also or not because they are not intensive at all and basically run immediately, so hard to test. Moreover, they have `queue=False` so are not even supposed to use the concurrency_limit?).

However, running:

```python
demo.queue(default_concurrency_limit=10).launch(server_name='127.0.0.1', server_port=8000,
favicon_path=os.path.join(utils.ROOT_FOLDER, 'favicon.ico'))
``` 

would correctly restrict the concurrency to 5, which is directly specified on the event group.

### System Info

```shell
Gradio 4.19.2
```

### Severity

I can work around it

**Comment by abidlabs** [comment] 2024-02-28 00:15
Thanks @Cyrilvallez -- @aliabid94 is this a bug or the intended behavior (in which case, docstring needs to be updated)?

**Comment by freddyaboulton** [comment] 2024-03-04 23:58
This feels like a bug. I think `default_concurrency_limit` should apply only when `concurrency_limit` is default and `concurrency_limit` should apply in all other cases.

**Comment by abidlabs** [comment] 2024-10-17 21:49
Hi, apologies for the late follow up. We haven't had a chance to look into this issue, but the Gradio codebase has changed quite significantly since this issue was created, particularly with the release of Gradio 5. Could you let us know if this is still an issue in the latest version of Gradio (`pip install --upgrade gradio`)? Thanks!

**Comment by abidlabs** [comment] 2024-10-23 16:31
Closing the issue for now, but happy to reopen if the issue continues to persist in the latest version of Gradio

**Closed by abidlabs** 2024-10-23 16:31 UTC
Labels: bug, pending clarification
