### ISSUE TITLE
I am unable to run the chatbot for streaming output in the gradio example

### ISSUE THREAD

**Issue by kjhuanhao** [gradio-app/gradio#4972] opened 2023-07-19 09:43 UTC
### Describe the bug

I copied the code for this website and ran it on my pychar. [https://huggingface.co/spaces/gradio/chatbot_streaming/blob/main/run.py](url)

Run without any errors.But when I enter the first message, It cannot function properly and there is an error in the image,
![Snipaste_2023-07-19_17-39-30.png](https://s2.loli.net/2023/07/19/GUmdje8OZXsuYHR.png)

My terminal has no errors.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
import random
import time

with gr.Blocks() as demo:
    chatbot = gr.Chatbot()
    msg = gr.Textbox()
    clear = gr.Button("Clear")


    def user(user_message, history):
        return "", history + [[user_message, None]]


    def bot(history):
        bot_message = random.choice(["How are you?", "I love you", "I'm very hungry"])
        history[-1][1] = ""
        for character in bot_message:
            history[-1][1] += character
            time.sleep(0.05)
            yield history


    msg.submit(user, [msg, chatbot], [msg, chatbot], queue=False).then(
        bot, chatbot, chatbot
    )
    clear.click(lambda: None, None, chatbot, queue=False)

demo.queue()
if __name__ == "__main__":
    demo.launch()
```

### Screenshot

![Snipaste_2023-07-19_17-39-30.png](https://s2.loli.net/2023/07/19/GUmdje8OZXsuYHR.png)

### System Info

```shell
Name: gradio
Version: 3.37.0
Summary: Python library for easily interacting with trained machine learning models
Home-page: 
Author: 
Author-email: Abubakar Abid <team@gradio.app>, Ali Abid <team@gradio.app>, Ali Abdalla <team@gradio.app>, Dawood Khan <team@gradio.app>, Ahsen Khaliq <team@gradio.app>, Pete Allen <team@gradio.app>, Ömer Faruk Özdemir <team@gradio.app>
License: 
Location: E:\Anaconda\envs\gptac_venv\Lib\site-packages
Requires: aiofiles, aiohttp, altair, fastapi, ffmpy, gradio-client, httpx, huggingface-hub, jinja2, markdown-it-py, markupsafe, matplotlib, mdit-py-plugins, numpy, orjson, packaging, pandas, pillow, pydantic, pydub, python-multipart, pyyaml, requests, semantic-version, typing-extensions, uvicorn, websockets
Required-by:
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment] 2023-07-19 20:34
I cannot reproduce the error @kjhuanhao ! Are you running from `pycharm` console?

**Comment by kjhuanhao** [comment] 2023-07-20 09:08
I found something very strange. The same code, both PyCharm and VSCode, had the same issues as before, but when I deployed it in Collab, there were no issues. So I called my friend and tried running locally, but I couldn't stream output either.

**Comment by abidlabs** [comment] 2023-07-28 20:29
Hi @kjhuanhao that's very strange! I can't reproduce this issue either. I think we'll have to close this issue for now since there's nothing actionable we can do. If you can isolate what's different in your local environment versus Google Colab, feel free to comment and we can reopen the issue. Thanks

**Closed by abidlabs** 2023-07-28 20:29 UTC
Labels: bug, needs repro
