### ISSUE TITLE
Gradio is broken on newest Chromium version

### ISSUE THREAD

**Issue by dvruette** [gradio-app/gradio#5339] opened 2023-08-25 12:00 UTC
### Describe the bug

Gradio interfaces fail to load for me ever since updating to the newest Chromium version (116.0.5845.110). The following error is raised and the interface is stuck on "Loading...":

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'insertBefore')
    at k (dom.js:238:9)
    at Object.m (Blocks.svelte:554:63)
    at ke (Component.js:42:23)
    at Object.m (Index.svelte:343:26)
    at Object.p (Index.svelte:296:89)
    at fr (utils.js:168:8)
    at Object.p (Embed.svelte:25:7)
    at cn (scheduler.js:119:30)
    at yr (scheduler.js:79:5)
```

Further info:
- Safari (v16.3) and Firefox (v109.0.1) are not affected
- Sometimes (but not always), the interface loads after reloading the page
- Not all gradio interfaces are affected:
  - working: https://huggingface.co/spaces/HuggingFaceM4/idefics_playground
  - not working (works after reload): https://huggingface.co/spaces/multimodalart/LoraTheExplorer
  - not working (works after reload): https://huggingface.co/spaces/gradio/pictionary
  - not working (works after reload): https://huggingface.co/spaces/fffiloni/Image-to-Story
  - not working (doesn't work after reload on localhost): SD WebUI (https://github.com/AUTOMATIC1111/stable-diffusion-webui)

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

1. Update to Chromium 116.0.5845.110 (tested with Brave, Arc)
2. Open https://huggingface.co/spaces/gradio/pictionary
3. Observe the aforementioned error in the dev console

### System Info

```shell
- macOS 13.2.1
- Chromium 116.0.5845.110
- Whatever Gradio version this runs on: https://huggingface.co/spaces/gradio/pictionary
```

### Severity

Blocking usage of gradio

**Comment by pngwn** [comment] 2023-08-25 15:45
I can't reproduce this with either chrome, brave, or arc using the exact chrome version you mentioned. Also on a Mac. 

Does this also happen in incognito mode? Are there any other details about your system that might be relevant?

**Comment by pngwn** [comment] 2023-08-29 08:34
Closing until we have a reproducible repro.

**Closed** 2023-08-29 08:34 UTC
Labels: bug, needs repro

**Comment by dvruette** [comment] 2023-08-30 10:16
Hi everyone, thanks for looking into this. I took some more time to investigate and it seems that restarting my Mac (incomprehensibly) has fixed the issue. Previously, restarting the Browser didn't help and it even occurred on a freshly installed version on Brave, so I'm not sure what could have changed by restarting but something did.

**Comment by freddyaboulton** [comment] 2023-08-30 14:31
Glad you were able to fix it @dvruette !
