### ISSUE TITLE
Gradio web does not load properly

### ISSUE THREAD

**Issue by jamie0725** [gradio-app/gradio#7836] opened 2024-03-26 01:54 UTC
### Describe the bug

Hi, I attach two screenshots that I take when I run the same code locally and on a GCP container.

Locally everything looks and works fine, but when I deploy it to GCP, the web looks weird and unresponsive.

Do you have any clues on solving this matter, thank you!

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

def get_blocks():
    """
    Get review demo gradio blocks.
    """

    with gr.Blocks(title="xxx", theme="base") as demo:
        gr.Markdown("xxx")
        with gr.Tab("Product Review Analysis"):
            with gr.Row():
                with gr.Column():
                    gr.Markdown(
                        "## Features:\n### Summarize the negative feedback of a product and list the most common"
                        " issues that customers are facing. Then, you can also refer back to the original reviews"
                        " given a summarized common issue."
                    )
                    gr.Markdown(
                        '## How to Use:\n### 1. Separate multiple reviews by -.\n### 2. Run "Analyze" first to analyze'
                        ' the reviews, then run "Lookup" to find the original reviews given a summarized'
                        " tag or issue."
                    )
                with gr.Column():
                    rev_model = gr.Dropdown(
                        label="Model Selection",
                        choices=[KEY_MODEL_GPT35_TURBO, KEY_MODEL_GPT4_TURBO],
                        value=KEY_MODEL_GPT35_TURBO,
                    )
                    gr.Markdown(
                        "*Tips: If your input contains ≤ 100 reviews, opt for GPT-3.5. Otherwise (> 100), use GPT-4.*"
                    )
                temperature = gr.Slider(label="Temperature", minimum=0, maximum=2, step=0.1, value=0)
            with gr.Row():
                review_history = gr.State([])
                value = (
                    "- My earphones came in defective. I can't make calls at all with them, people keep telling "
                    "me I sound too robotic and glitchy\n- Absolutely terrible sound quality can bearly hear at "
                    "max volume I was very disappointed\n- Didn't work. Tried to reset as suggested by on line "
                    "chat. Still didn't' work. I sent them back and now have big credit and don't want to "
                    "purchase another set. Disappointed as my wife loves her set."
                )
                raw_reviews = gr.Textbox(
                    label="Input Reviews",
                    lines=10,
                    placeholder=value,
                    value=value,
                )
                summary = gr.Textbox(label="Analysis Output", lines=10, autoscroll=False)
            rev_button = gr.Button("Step 1. Analyze 🤔️")
            rev_button.click(
                analyze,
                inputs=[raw_reviews, review_history, rev_model, temperature],
                outputs=[summary, review_history],
            )
            with gr.Row():
                review_tags = gr.Textbox(label="Tags Lookup", lines=10, placeholder="Poor sound quality")
                original_reviews = gr.Textbox(label="Matching Reviews", lines=10, autoscroll=False)
            tag_button = gr.Button("Step 2. Lookup 🔍")
            tag_button.click(
                lookup, inputs=[review_tags, review_history, rev_model, temperature], outputs=original_reviews
            )

    return demo


review_io = get_blocks()
```

### Screenshot
On GCP container:
<img width="1686" alt="image" src="https://github.com/gradio-app/gradio/assets/27820994/04973838-7506-43e5-a232-8db02292f684">

Locally:
<img width="1505" alt="image" src="https://github.com/gradio-app/gradio/assets/27820994/1367b848-58e4-440d-9878-063bbf827496">

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 4.21.0
gradio_client version: 0.12.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.2.0
fastapi: 0.110.0
ffmpy: 0.3.2
gradio-client==0.12.0 is not installed.
httpx: 0.27.0
huggingface-hub: 0.21.4
importlib-resources: 6.4.0
jinja2: 3.0.1
markupsafe: 2.1.5
matplotlib: 3.5.0
numpy: 1.26.4
orjson: 3.9.15
packaging: 21.3
pandas: 1.4.3
pillow: 10.2.0
pydantic: 2.6.4
pydub: 0.25.1
python-multipart: 0.0.9
pyyaml: 6.0
ruff: 0.3.4
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.10.0
typing-extensions: 4.10.0
uvicorn: 0.17.6
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2024.3.1
httpx: 0.27.0
huggingface-hub: 0.21.4
packaging: 21.3
typing-extensions: 4.10.0
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by jamie0725** [comment] 2024-03-26 05:34
Update: downgrading gradio version to `4.17.0` solves the problem.
Seems like the problem is related to https://github.com/gradio-app/gradio/issues/7792

**Comment by abidlabs** [comment] 2024-03-26 06:27
Hi @jamie0725 can you try upgrading to the latest version of Gradio? Of that doesn’t fix the issue can you share a screenshot of your console error log?

**Comment by jamie0725** [comment] 2024-03-27 02:41
@abidlabs While uploading to the latest version (4.23.0), I noticed that Gradio does not automatically install its dependencies like gradio-client, httpx, websockets etc, which makes it hard to manage my environment, it hasn't happened before, do you know why? ps. I use poetry to manage my python packages.

**Comment by jamie0725** [comment] 2024-03-27 02:41
@abidlabs While uploading to the latest version (4.23.0), I noticed that Gradio does not automatically install its dependencies like gradio-client, httpx, websockets etc, which makes it hard to manage my environment, it hasn't happened before, do you know why? ps. I use poetry to manage my Python packages.

**Comment by abidlabs** [comment] 2024-03-28 15:44
Hi @jamie0725 I can't think of any reason for that change. Could you try the latest version, `gradio==4.24.0`? Could you also try with `pip` and see if there's a difference in how dependencies are installed?

**Comment by jamie0725** [comment] 2024-03-29 02:02
@abidlabs install with pip indeed works, it might be a problem with poetry.

**Comment by abidlabs** [comment] 2024-03-29 18:06
Certainly might be. Maybe poetry is installing things in its own venv instead of where you'd like, e.g. https://github.com/python-poetry/poetry/issues/6913

I'm going to close this issue since we recommend installing with pip, but if you find that the issue is with gradio, then feel free to share mroe details.

**Closed by abidlabs** 2024-03-29 18:06 UTC
Labels: bug, pending clarification, cloud

**Comment by goldwater668** [comment] 2024-04-15 03:47
How to achieve multiple outputs without displaying the results together？
