### ISSUE TITLE
No exports module issue when importing @gradio/client

### ISSUE THREAD

**Issue by zouspants123321** [gradio-app/gradio#6703] opened 2023-12-07 21:12 UTC
### Describe the bug

When importing gradio/client it will just display no exports 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

const { client } = require("@gradio/client");

### Logs

```shell
node:internal/modules/cjs/loader:573
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in C:\Users\GTSA - Infinity\Desktop\Save\Websites\TextToMerch.com\my-backend\node_modules\@gradio\client\package.json
    at new NodeError (node:internal/errors:405:5)
    at exportsNotFound (node:internal/modules/esm/resolve:359:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:639:13)
    at resolveExports (node:internal/modules/cjs/loader:567:36)
    at Module._findPath (node:internal/modules/cjs/loader:636:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1063:27)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (C:\Users\GTSA - Infinity\Desktop\Save\Websites\TextToMerch.com\my-backend\index.js:11:20) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
```

### System Info

```shell
I am on the latest version "devDependencies": {
    "@gradio/client": "^0.8.2"
  }
```

### Severity

Blocking usage of gradio

**Comment by antonioleo89** [comment] 2023-12-18 14:56
Same

**Comment by arthurwolf** [comment] 2024-01-10 00:51
Same, anyone has a solution to this ??

**Comment by ghadirbeyrouti** [comment] 2024-01-18 18:14
did you solve the errors ?

**Comment by jhleee** [comment] 2024-01-19 06:49
Same

**Comment by freddyaboulton** [comment] 2024-01-19 18:37
Tagging @pngwn !

**Comment by vishesh-baghel** [comment] 2024-03-10 16:18
```
const dynamic = new Function('modulePath', 'return import(modulePath)');
const { client } = await dynamic('@gradio/client');
```
This worked for me also

**Comment by arthurwolf** [comment] 2024-03-10 17:21
> ```
> const dynamic = new Function('modulePath', 'return import(modulePath)');
> const { client } = await dynamic('@gradio/client');
> ```
> 
> This worked for me also

it's great that we have a way forward, but this really should work out of the box ... my node project uses hundreds of modules, and this is the only one with this issue, there really must be some easy way for them to fix this...

**Comment by pngwn** [comment] 2024-04-11 11:54
Duplicate of #4260

**Closed by pngwn** 2024-04-11 11:54 UTC
Labels: bug, gradio_client

**Comment by mohdmoazzam** [comment] 2024-05-24 13:12
same issue i am getting please help please ==>
Error: No "exports" main defined in E:\Work\Code\Resume-Processor\node_modules\@gradio\client\package.json
    at exportsNotFound (node:internal/modules/esm/resolve:304:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:594:13)
    at resolveExports (node:internal/modules/cjs/loader:592:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:669:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1131:27)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (E:\Work\Code\Resume-Processor\node_modules\@cspotcode\source-map-support\source-map-support.js:811:30)    
    at Function.Module._load (node:internal/modules/cjs/loader:986:27)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (E:\Work\Code\Resume-Processor\src\services\processResume.service.ts:1:1) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}

**Comment by sancho1952007** [comment] 2024-09-26 16:53
> > ```
> > const dynamic = new Function('modulePath', 'return import(modulePath)');
> > const { client } = await dynamic('@gradio/client');
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This worked for me also
> 
> it's great that we have a way forward, but this really should work out of the box ... my node project uses hundreds of modules, and this is the only one with this issue, there really must be some easy way for them to fix this...

Thanks a lot man, so saved my project!
