### ISSUE TITLE
Change event trigger slow to respond in Colab

### ISSUE THREAD

**Issue by dawoodkhan82** [gradio-app/gradio#1197] opened 2022-05-09 19:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using the change event trigger for a textbox; when typing quickly, not all of the text is registered in the change event.

### Reproduction

Run the below code example in a colab notebook; and type into the textbox quickly.

```
import gradio as gr


def flip_text(x):
    return x[::-1]

demo = gr.Blocks()

with demo:
    gr.Markdown(
    """
    # Flip Text!
    Start typing below to see the output.
    """)
    inp = gr.Textbox(placeholder="Flip this text")
    out = gr.Textbox()

    inp.change(fn=flip_text, 
                 inputs=inp, 
                 outputs=out)

demo.launch()
```py

### Screenshot

_No response_

### Logs

_No response_

### System Info

```shell
gradio==2.9.b25
```

### Severity

annoyance

**Comment by pngwn** [comment] 2022-05-10 09:20
I think this happens because when a request is pending we reject any new requests. So the first character we type will send a request but until that request has completed, we will not send any more. 

We should actually do the opposite of this. While you can't really cancel a request, we can ignore the responses if there is a fresher request. In order to make sure this doesn't destroy the server, when queuing is enabled we could actually remove old requests of the same function type for the same session ID from the queue.

So.

Request1 : id:001, session_id: 001, fn_id:001 -> awaiting on frontend -> added to queue on backend
Request2: id:002, session_id:001, fn_id: 001 -> awaiting on frontend ( ignore 001 response on FE) -> remove 001 from qeueue on backend, add 002 to queue.

etc

Essentially for a given session_id and function_id, only allow one request to be in the queue. Not sure what else we could do for non_queued functions or apps.

**Comment by FarukOzderim** [comment] 2022-05-11 16:27
related #572

**Comment by abidlabs** [comment] 2022-08-23 23:22
Duplicate of #1954 (closing this one because that has more discussion)

**Closed by abidlabs** 2022-08-23 23:22 UTC
Labels: bug
