### ISSUE TITLE
how to disable sharing on google colab?

### ISSUE THREAD

**Issue by randomgambit** [gradio-app/gradio#414] opened 2021-12-15 16:29 UTC
Hello there! Thanks for this beautiful package!

I am using `gradio` on `google colab` and I am struggling to keep my app private. 

My code is essentially
```gr.Interface(
    predict_function,
    inputs=[gr.inputs.Video()
    outputs=gr.outputs.Video(),
    title='myapp',
    description = description,
).launch(share = False)
```

But running it in `colab` will show that the public link is still available!

```
IMPORTANT: You are using gradio version 2.4.7b9, however version 2.5.1 is available, please upgrade.
--------
Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
Running on public URL: https://XXXXX.gradio.app
```

Am I missing something?
Thanks!

**Comment by abidlabs** [comment] 2021-12-15 16:34
Thanks @randomgambit! Yes, when `gradio` is run in google colab, we automatically set sharing to `True` because otherwise, there is no way to access the localhost server running on the `colab` machine. If you run on a local machine, you can keep your gradio app private.

Is there a different way that you have in mind that would allow your demo on colab to be accessible to you but remain otherwise private? If so, we can implement it

**Comment by randomgambit** [comment] 2021-12-15 16:44
thanks @abidlabs ! I actually have no idea how to do it cant we make the app accessible while I am connected to (and manually running) my colab session but not generating a public link? does that make sense?

**Comment by abidlabs** [comment] 2021-12-15 17:21
We can definitely disable generating a public link, there's no problem with that. The problem is that the gradio application will then only run on a local server (e.g. `localhost:7000`) on the colab notebook, and that local server won't be accessible to you from your machine. Let me know if I'm missing something though.

**Comment by abidlabs** [comment] 2021-12-21 21:03
Closing because there isn't any way (as far as I know) to access the local server on a colab. You need to create an SSH tunnel (either using `gradio` or through another service like `ngrok`).

**Closed by abidlabs** 2021-12-21 21:03 UTC
Labels: enhancement
