### ISSUE TITLE
`gr.State()` doesn't work with `.change()`

### ISSUE THREAD

**Issue by apolinario** [gradio-app/gradio#5703] opened 2023-09-27 07:25 UTC
### Describe the bug

If I do 
```py
my_state = gr.State()
#...
my_state.change(fun, inputs=[prompt], outputs=[result])
```

I get an error
```bash
Traceback (most recent call last):
  File "app.py", line 42, in <module>
    my_state.change(
AttributeError: 'State' object has no attribute 'change'
```

I think it would make sense that I can trigger actions when a state value changes just like any other component value changes. 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### System Info

```shell
`gradio == 3.45.1`
```

### Severity

I can work around it

**Comment by pngwn** [comment] 2023-09-27 07:50
This is basically #5309. Not every component has the ability to dispatch a change event right now.

**Comment by freddyaboulton** [comment] 2023-09-27 15:24
Thanks for filing @apolinario ! Dupe of #2107 so I think we should close this particular one.

**Closed** 2023-09-27 16:07 UTC
Labels: bug
