### ISSUE TITLE
i have an error with fooocus api: ValueError: None

### ISSUE THREAD

**Issue by AlonBensa** [gradio-app/gradio#6911] opened 2023-12-30 12:27 UTC
### Describe the bug

i want to use fooocus api but i get this error how can i solve it please ?

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
from gradio_client import Client

client = Client("http://127.0.0.1:7865/", serialize=False)
result = client.predict(
	"Howdy!",	# str in 'parameter_10' Textbox component
	"Howdy!",	# str in 'Negative Prompt' Textbox component
	["Fooocus V2"],	# List[str] in 'Selected Styles' Checkboxgroup component
	"Speed",	# str in 'Performance' Radio component
	'704×1408 <span style="color: grey;"> ∣ 1:2</span>',	# str in 'Aspect Ratios' Radio component
	1,	# int | float (numeric value between 1 and 32) in 'Image Number' Slider component
	"Howdy!",	# str in 'Seed' Textbox component
	0,	# int | float (numeric value between 0.0 and 30.0) in 'Image Sharpness' Slider component
	1,	# int | float (numeric value between 1.0 and 30.0) in 'Guidance Scale' Slider component
	"juggernautXL_version6Rundiffusion.safetensors",	# str (Option from: ['juggernautXL_version6Rundiffusion.safetensors']) in 'Base Model (SDXL only)' Dropdown component
	"None",	# str (Option from: ['None', 'juggernautXL_version6Rundiffusion.safetensors']) in 'Refiner (SDXL or SD 1.5)' Dropdown component
	0.1,	# int | float (numeric value between 0.1 and 1.0) in 'Refiner Switch At' Slider component
	"None",	# str (Option from: ['None', 'sd_xl_offset_example-lora_1.0.safetensors']) in 'LoRA 1' Dropdown component
	-2,	# int | float (numeric value between -2 and 2) in 'Weight' Slider component
	"None",	# str (Option from: ['None', 'sd_xl_offset_example-lora_1.0.safetensors']) in 'LoRA 2' Dropdown component
	-2,	# int | float (numeric value between -2 and 2) in 'Weight' Slider component
	"None",	# str (Option from: ['None', 'sd_xl_offset_example-lora_1.0.safetensors']) in 'LoRA 3' Dropdown component
	-2,	# int | float (numeric value between -2 and 2) in 'Weight' Slider component
	"None",	# str (Option from: ['None', 'sd_xl_offset_example-lora_1.0.safetensors']) in 'LoRA 4' Dropdown component
	-2,	# int | float (numeric value between -2 and 2) in 'Weight' Slider component
	"None",	# str (Option from: ['None', 'sd_xl_offset_example-lora_1.0.safetensors']) in 'LoRA 5' Dropdown component
	-2,	# int | float (numeric value between -2 and 2) in 'Weight' Slider component
	True,	# bool in 'Input Image' Checkbox component
	"Howdy!",	# str in 'parameter_83' Textbox component
	"Disabled",	# str in 'Upscale or Variation:' Radio component
	"https://raw.githubusercontent.com/gradio-app/gradio/main/test/test_files/bus.png",	# str (filepath or URL to image) in 'Drag above image to here' Image component
	["Left"],	# List[str] in 'Outpaint Direction' Checkboxgroup component
	"https://raw.githubusercontent.com/gradio-app/gradio/main/test/test_files/bus.png",	# str (filepath or URL to image) in 'Drag above image to here' Image component
	"Howdy!",	# str in 'Inpaint Additional Prompt' Textbox component
	"https://raw.githubusercontent.com/gradio-app/gradio/main/test/test_files/bus.png",	# str (filepath or URL to image) in 'Image' Image component
	0,	# int | float (numeric value between 0.0 and 1.0) in 'Stop At' Slider component
	0,	# int | float (numeric value between 0.0 and 2.0) in 'Weight' Slider component
	"ImagePrompt",	# str in 'Type' Radio component
	"https://raw.githubusercontent.com/gradio-app/gradio/main/test/test_files/bus.png",	# str (filepath or URL to image) in 'Image' Image component
	0,	# int | float (numeric value between 0.0 and 1.0) in 'Stop At' Slider component
	0,	# int | float (numeric value between 0.0 and 2.0) in 'Weight' Slider component
	"ImagePrompt",	# str in 'Type' Radio component
	"https://raw.githubusercontent.com/gradio-app/gradio/main/test/test_files/bus.png",	# str (filepath or URL to image) in 'Image' Image component
	0,	# int | float (numeric value between 0.0 and 1.0) in 'Stop At' Slider component
	0,	# int | float (numeric value between 0.0 and 2.0) in 'Weight' Slider component
	"ImagePrompt",	# str in 'Type' Radio component
	"https://raw.githubusercontent.com/gradio-app/gradio/main/test/test_files/bus.png",	# str (filepath or URL to image) in 'Image' Image component
	0,	# int | float (numeric value between 0.0 and 1.0) in 'Stop At' Slider component
	0,	# int | float (numeric value between 0.0 and 2.0) in 'Weight' Slider component
	"ImagePrompt",	# str in 'Type' Radio component
	fn_index=32
)

print(result)
```

### Logs

client side error:
```shell
Loaded as API: http://127.0.0.1:7865/ ✔
Traceback (most recent call last):
  File "e:\Image Generator\pyScript.py", line 4, in <module>
    result = client.predict(
             ^^^^^^^^^^^^^^^
  File "C:\Users\alonb\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio_client\client.py", line 392, in predict
    return self.submit(*args, api_name=api_name, fn_index=fn_index).result()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alonb\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio_client\client.py", line 1573, in result
    return super().result(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alonb\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
    raise self._exception
  File "C:\Users\alonb\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alonb\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio_client\client.py", line 1245, in _inner      
    predictions = _predict(*data)
                  ^^^^^^^^^^^^^^^
  File "C:\Users\alonb\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio_client\client.py", line 1275, in _predict    
    raise ValueError(result["error"])
ValueError: None
```

server side error:
```shell
Traceback (most recent call last):
  File "E:\Image Generator\python_embeded\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\Image Generator\python_embeded\lib\site-packages\gradio\blocks.py", line 1429, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "E:\Image Generator\python_embeded\lib\site-packages\gradio\blocks.py", line 1239, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "E:\Image Generator\Fooocus\modules\gradio_hijack.py", line 278, in preprocess
    im = processing_utils.decode_base64_to_image(x)
  File "E:\Image Generator\python_embeded\lib\site-packages\gradio\processing_utils.py", line 59, in decode_base64_to_image
    img = Image.open(BytesIO(base64.b64decode(image_encoded)))
  File "base64.py", line 87, in b64decode
binascii.Error: Incorrect padding
```

### System Info

```shell
i am using the latest version of gradio_client
```

### Severity

I can work around it

**Comment by abidlabs** [comment] 2024-01-02 19:53
Hi @AlonBensa its not clear to me if this is an issue with fooocus or with gradio. Can you reproduce this issue with a more minimal example? If so, can you share what image(s) you are seeing this error with?

**Comment by abidlabs** [comment] 2024-01-04 18:28
Closing for lack of follow up. We can reopen with a repro

**Closed by abidlabs** 2024-01-04 18:28 UTC
Labels: bug, needs repro, gradio_client

**Comment by a88852asdw** [comment] 2024-01-09 02:35
I also have this error, how to solve this problem?

**Comment by a88852asdw** [comment] 2024-01-09 02:37
Directly run the API in the website like this:

error message:
     raise ValueError(result["error"])
ValueError: None

**Comment by eienmojiki206** [comment] 2024-01-26 05:09
> ### Describe the bug
> i want to use fooocus api but i get this error how can i solve it please ?
> 
> ### Have you searched existing issues? 🔎
> * [x]  I have searched and found no existing issues
> 
> ### Reproduction
> ```python
> from gradio_client import Client
> 
> client = Client("http://127.0.0.1:7865/", serialize=False)
> result = client.predict(
> 	"Howdy!",	# str in 'parameter_10' Textbox component
> 	"Howdy!",	# str in 'Negative Prompt' Textbox component
> 	["Fooocus V2"],	# List[str] in 'Selected Styles' Checkboxgroup component
> 	"Speed",	# str in 'Performance' Radio component
> 	'704×1408 <span style="color: grey;"> ∣ 1:2</span>',	# str in 'Aspect Ratios' Radio component
> 	1,	# int | float (numeric value between 1 and 32) in 'Image Number' Slider component
> 	"Howdy!",	# str in 'Seed' Textbox component
> 	0,	# int | float (numeric value between 0.0 and 30.0) in 'Image Sharpness' Slider component
> 	1,	# int | float (numeric value between 1.0 and 30.0) in 'Guidance Scale' Slider component
> 	"juggernautXL_version6Rundiffusion.safetensors",	# str (Option from: ['juggernautXL_version6Rundiffusion.safetensors']) in 'Base Model (SDXL only)' Dropdown component
> 	"None",	# str (Option from: ['None', 'juggernautXL_version6Rundiffusion.safetensors']) in 'Refiner (SDXL or SD 1.5)' Dropdown component
> 	0.1,	# int | float (numeric value between 0.1 and 1.0) in 'Refiner Switch At' Slider component
> 	"None",	# str (Option from: ['None', 'sd_xl_offset_example-lora_1.0.safetensors']) in 'LoRA 1' Dropdown component
> 	-2,	# int | float (numeric value between -2 and 2) in 'Weight' Slider component
> 	"None",	# str (Option from: ['None', 'sd_xl_offset_example-lora_1.0.safetensors']) in 'LoRA 2' Dropdown component
> 	-2,	# int | float (numeric value between -2 and 2) in 'Weight' Slider component
> 	"None",	# str (Option from: ['None', 'sd_xl_offset_example-lora_1.0.safetensors']) in 'LoRA 3' Dropdown component
> 	-2,	# int | float (numeric value between -2 and 2) in 'Weight' Slider component
> 	"None",	# str (Option from: ['None', 'sd_xl_offset_example-lora_1.0.safetensors']) in 'LoRA 4' Dropdown component
> 	-2,	# int | float (numeric value between -2 and 2) in 'Weight' Slider component
> 	"None",	# str (Option from: ['None', 'sd_xl_offset_example-lora_1.0.safetensors']) in 'LoRA 5' Dropdown component
> 	-2,	# int | float (numeric value between -2 and 2) in 'Weight' Slider component
> 	True,	# bool in 'Input Image' Checkbox component
> 	"Howdy!",	# str in 'parameter_83' Textbox component
> 	"Disabled",	# str in 'Upscale or Variation:' Radio component
> 	"https://raw.githubusercontent.com/gradio-app/gradio/main/test/test_files/bus.png",	# str (filepath or URL to image) in 'Drag above image to here' Image component
> 	["Left"],	# List[str] in 'Outpaint Direction' Checkboxgroup component
> 	"https://raw.githubusercontent.com/gradio-app/gradio/main/test/test_files/bus.png",	# str (filepath or URL to image) in 'Drag above image to here' Image component
> 	"Howdy!",	# str in 'Inpaint Additional Prompt' Textbox component
> 	"https://raw.githubusercontent.com/gradio-app/gradio/main/test/test_files/bus.png",	# str (filepath or URL to image) in 'Image' Image component
> 	0,	# int | float (numeric value between 0.0 and 1.0) in 'Stop At' Slider component
> 	0,	# int | float (numeric value between 0.0 and 2.0) in 'Weight' Slider component
> 	"ImagePrompt",	# str in 'Type' Radio component
> 	"https://raw.githubusercontent.com/gradio-app/gradio/main/test/test_files/bus.png",	# str (filepath or URL to image) in 'Image' Image component
> 	0,	# int | float (numeric value between 0.0 and 1.0) in 'Stop At' Slider component
> 	0,	# int | float (numeric value between 0.0 and 2.0) in 'Weight' Slider component
> 	"ImagePrompt",	# str in 'Type' Radio component
> 	"https://raw.githubusercontent.com/gradio-app/gradio/main/test/test_files/bus.png",	# str (filepath or URL to image) in 'Image' Image component
> 	0,	# int | float (numeric value between 0.0 and 1.0) in 'Stop At' Slider component
> 	0,	# int | float (numeric value between 0.0 and 2.0) in 'Weight' Slider component
> 	"ImagePrompt",	# str in 'Type' Radio component
> 	"https://raw.githubusercontent.com/gradio-app/gradio/main/test/test_files/bus.png",	# str (filepath or URL to image) in 'Image' Image component
> 	0,	# int | float (numeric value between 0.0 and 1.0) in 'Stop At' Slider component
> 	0,	# int | float (numeric value between 0.0 and 2.0) in 'Weight' Slider component
> 	"ImagePrompt",	# str in 'Type' Radio component
> 	fn_index=32
> )
> 
> print(result)
> ```
> 
> ### Screenshot
> _No response_
> 
> ### Logs
> client side error:
> 
> ```shell
> Loaded as API: http://127.0.0.1:7865/ ✔
> Traceback (most recent call last):
>   File "e:\Image Generator\pyScript.py", line 4, in <module>
>     result = client.predict(
>              ^^^^^^^^^^^^^^^
>   File "C:\Users\alonb\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio_client\client.py", line 392, in predict
>     return self.submit(*args, api_name=api_name, fn_index=fn_index).result()
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\alonb\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio_client\client.py", line 1573, in result
>     return super().result(timeout=timeout)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\alonb\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 456, in result
>     return self.__get_result()
>            ^^^^^^^^^^^^^^^^^^^
>     raise self._exception
>   File "C:\Users\alonb\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\alonb\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio_client\client.py", line 1245, in _inner      
>     predictions = _predict(*data)
>                   ^^^^^^^^^^^^^^^
>   File "C:\Users\alonb\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio_client\client.py", line 1275, in _predict    
>     raise ValueError(result["error"])
> ValueError: None
> ```
> 
> server side error:
> 
> ```shell
> Traceback (most recent call last):
>   File "E:\Image Generator\python_embeded\lib\site-packages\gradio\routes.py", line 488, in run_predict
>     output = await app.get_blocks().process_api(
>   File "E:\Image Generator\python_embeded\lib\site-packages\gradio\blocks.py", line 1429, in process_api
>     inputs = self.preprocess_data(fn_index, inputs, state)
>   File "E:\Image Generator\python_embeded\lib\site-packages\gradio\blocks.py", line 1239, in preprocess_data
>     processed_input.append(block.preprocess(inputs[i]))
>   File "E:\Image Generator\Fooocus\modules\gradio_hijack.py", line 278, in preprocess
>     im = processing_utils.decode_base64_to_image(x)
>   File "E:\Image Generator\python_embeded\lib\site-packages\gradio\processing_utils.py", line 59, in decode_base64_to_image
>     img = Image.open(BytesIO(base64.b64decode(image_encoded)))
>   File "base64.py", line 87, in b64decode
> binascii.Error: Incorrect padding
> ```
> 
> ### System Info
> ```shell
> i am using the latest version of gradio_client
> ```
> 
> ### Severity
> I can work around it



> ### Describe the bug
> i want to use fooocus api but i get this error how can i solve it please ?
> 
> ### Have you searched existing issues? 🔎
> * [x]  I have searched and found no existing issues
> 
> ### Reproduction
> ```python
> from gradio_client import Client
> 
> client = Client("http://127.0.0.1:7865/", serialize=False)
> result = client.predict(
> 	"Howdy!",	# str in 'parameter_10' Textbox component
> 	"Howdy!",	# str in 'Negative Prompt' Textbox component
> 	["Fooocus V2"],	# List[str] in 'Selected Styles' Checkboxgroup component
> 	"Speed",	# str in 'Performance' Radio component
> 	'704×1408 <span style="color: grey;"> ∣ 1:2</span>',	# str in 'Aspect Ratios' Radio component
> 	1,	# int | float (numeric value between 1 and 32) in 'Image Number' Slider component
> 	"Howdy!",	# str in 'Seed' Textbox component
> 	0,	# int | float (numeric value between 0.0 and 30.0) in 'Image Sharpness' Slider component
> 	1,	# int | float (numeric value between 1.0 and 30.0) in 'Guidance Scale' Slider component
> 	"juggernautXL_version6Rundiffusion.safetensors",	# str (Option from: ['juggernautXL_version6Rundiffusion.safetensors']) in 'Base Model (SDXL only)' Dropdown component
> 	"None",	# str (Option from: ['None', 'juggernautXL_version6Rundiffusion.safetensors']) in 'Refiner (SDXL or SD 1.5)' Dropdown component
> 	0.1,	# int | float (numeric value between 0.1 and 1.0) in 'Refiner Switch At' Slider component
> 	"None",	# str (Option from: ['None', 'sd_xl_offset_example-lora_1.0.safetensors']) in 'LoRA 1' Dropdown component
> 	-2,	# int | float (numeric value between -2 and 2) in 'Weight' Slider component
> 	"None",	# str (Option from: ['None', 'sd_xl_offset_example-lora_1.0.safetensors']) in 'LoRA 2' Dropdown component
> 	-2,	# int | float (numeric value between -2 and 2) in 'Weight' Slider component
> 	"None",	# str (Option from: ['None', 'sd_xl_offset_example-lora_1.0.safetensors']) in 'LoRA 3' Dropdown component
> 	-2,	# int | float (numeric value between -2 and 2) in 'Weight' Slider component
> 	"None",	# str (Option from: ['None', 'sd_xl_offset_example-lora_1.0.safetensors']) in 'LoRA 4' Dropdown component
> 	-2,	# int | float (numeric value between -2 and 2) in 'Weight' Slider component
> 	"None",	# str (Option from: ['None', 'sd_xl_offset_example-lora_1.0.safetensors']) in 'LoRA 5' Dropdown component
> 	-2,	# int | float (numeric value between -2 and 2) in 'Weight' Slider component
> 	True,	# bool in 'Input Image' Checkbox component
> 	"Howdy!",	# str in 'parameter_83' Textbox component
> 	"Disabled",	# str in 'Upscale or Variation:' Radio component
> 	"https://raw.githubusercontent.com/gradio-app/gradio/main/test/test_files/bus.png",	# str (filepath or URL to image) in 'Drag above image to here' Image component
> 	["Left"],	# List[str] in 'Outpaint Direction' Checkboxgroup component
> 	"https://raw.githubusercontent.com/gradio-app/gradio/main/test/test_files/bus.png",	# str (filepath or URL to image) in 'Drag above image to here' Image component
> 	"Howdy!",	# str in 'Inpaint Additional Prompt' Textbox component
> 	"https://raw.githubusercontent.com/gradio-app/gradio/main/test/test_files/bus.png",	# str (filepath or URL to image) in 'Image' Image component
> 	0,	# int | float (numeric value between 0.0 and 1.0) in 'Stop At' Slider component
> 	0,	# int | float (numeric value between 0.0 and 2.0) in 'Weight' Slider component
> 	"ImagePrompt",	# str in 'Type' Radio component
> 	"https://raw.githubusercontent.com/gradio-app/gradio/main/test/test_files/bus.png",	# str (filepath or URL to image) in 'Image' Image component
> 	0,	# int | float (numeric value between 0.0 and 1.0) in 'Stop At' Slider component
> 	0,	# int | float (numeric value between 0.0 and 2.0) in 'Weight' Slider component
> 	"ImagePrompt",	# str in 'Type' Radio component
> 	"https://raw.githubusercontent.com/gradio-app/gradio/main/test/test_files/bus.png",	# str (filepath or URL to image) in 'Image' Image component
> 	0,	# int | float (numeric value between 0.0 and 1.0) in 'Stop At' Slider component
> 	0,	# int | float (numeric value between 0.0 and 2.0) in 'Weight' Slider component
> 	"ImagePrompt",	# str in 'Type' Radio component
> 	"https://raw.githubusercontent.com/gradio-app/gradio/main/test/test_files/bus.png",	# str (filepath or URL to image) in 'Image' Image component
> 	0,	# int | float (numeric value between 0.0 and 1.0) in 'Stop At' Slider component
> 	0,	# int | float (numeric value between 0.0 and 2.0) in 'Weight' Slider component
> 	"ImagePrompt",	# str in 'Type' Radio component
> 	fn_index=32
> )
> 
> print(result)
> ```
> 
> ### Screenshot
> _No response_
> 
> ### Logs
> client side error:
> 
> ```shell
> Loaded as API: http://127.0.0.1:7865/ ✔
> Traceback (most recent call last):
>   File "e:\Image Generator\pyScript.py", line 4, in <module>
>     result = client.predict(
>              ^^^^^^^^^^^^^^^
>   File "C:\Users\alonb\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio_client\client.py", line 392, in predict
>     return self.submit(*args, api_name=api_name, fn_index=fn_index).result()
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\alonb\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio_client\client.py", line 1573, in result
>     return super().result(timeout=timeout)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\alonb\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 456, in result
>     return self.__get_result()
>            ^^^^^^^^^^^^^^^^^^^
>     raise self._exception
>   File "C:\Users\alonb\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\alonb\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio_client\client.py", line 1245, in _inner      
>     predictions = _predict(*data)
>                   ^^^^^^^^^^^^^^^
>   File "C:\Users\alonb\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio_client\client.py", line 1275, in _predict    
>     raise ValueError(result["error"])
> ValueError: None
> ```
> 
> server side error:
> 
> ```shell
> Traceback (most recent call last):
>   File "E:\Image Generator\python_embeded\lib\site-packages\gradio\routes.py", line 488, in run_predict
>     output = await app.get_blocks().process_api(
>   File "E:\Image Generator\python_embeded\lib\site-packages\gradio\blocks.py", line 1429, in process_api
>     inputs = self.preprocess_data(fn_index, inputs, state)
>   File "E:\Image Generator\python_embeded\lib\site-packages\gradio\blocks.py", line 1239, in preprocess_data
>     processed_input.append(block.preprocess(inputs[i]))
>   File "E:\Image Generator\Fooocus\modules\gradio_hijack.py", line 278, in preprocess
>     im = processing_utils.decode_base64_to_image(x)
>   File "E:\Image Generator\python_embeded\lib\site-packages\gradio\processing_utils.py", line 59, in decode_base64_to_image
>     img = Image.open(BytesIO(base64.b64decode(image_encoded)))
>   File "base64.py", line 87, in b64decode
> binascii.Error: Incorrect padding
> ```
> 
> ### System Info
> ```shell
> i am using the latest version of gradio_client
> ```
> 
> ### Severity
> I can work around it

Try to delete the "serialize" parameter, it works for me

**Comment by Kamakshi8104** [comment] 2024-03-16 16:01
same error

**Comment by Kamakshi8104** [comment] 2024-03-16 16:01
@ abidlabs how to solve this
