### ISSUE TITLE
Unable to get gr.Request in the function with `every`

### ISSUE THREAD

**Issue by Valdanitooooo** [gradio-app/gradio#8582] opened 2024-06-20 03:21 UTC
### Describe the bug

When I tried to get gr.Request in the `then method`, I received an error
```
TypeError: query_for_login_status() missing 1 required positional argument: 'request'
```

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python

# success
def generate_qr_code_image(request: gr.Request):
    if request:
        print("Request headers dictionary:", request.headers)
        print("IP address:", request.client.host)
        print("Query parameters:", dict(request.query_params))
        print("Session hash:", request.session_hash)
    ...
    return im_frame, request.session_hash

# error
def query_for_login_status(session_hash, request: gr.Request):
	print("session_hash:", session_hash)
    if request:
        print("Request headers dictionary:", request.headers)
        print("IP address:", request.client.host)
        print("Query parameters:", dict(request.query_params))
        print("Session hash:", request.session_hash)
    
with gr.Blocks(analytics_enabled=False) as demo:
    session_hash = gr.State()
    with gr.Row(elem_id="login-popup-wrapper"):
        with gr.Group(elem_id="login-popup"):
            qr_code_image = gr.Image(label="Please scan the code to login", elem_id='qr_code', show_label=True, type='pil',
                                     height=400, width=400,
                                     show_download_button=False)
    demo.load(
        generate_qr_code_image,
        inputs=[],
        outputs=[qr_code_image, session_hash],
        show_progress=True
    ).then(
        query_for_login_status,
        inputs=[session_hash],
        outputs=[],
        every=1,
    )

```

### Logs

```shell
TypeError: query_for_login_status() missing 1 required positional argument: 'request'
```

### System Info

```shell
gradio==4.36.1
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment] 2024-06-20 16:50
Hi @Valdanitooooo the issue is actually that that the `gr.Request` attribute currently doesn't work if you define a function with `every`. This issue should be fixed once https://github.com/gradio-app/gradio/pull/8505 is in

**Closed** 2024-06-28 23:53 UTC
Labels: bug
