### ISSUE TITLE
ConnectionResetError: [WinError 10054] when click radio to switch

### ISSUE THREAD

**Issue by Paladin-673** [gradio-app/gradio#8313] opened 2024-05-17 00:50 UTC
### Describe the bug

my code is like this:

def practiceUI():
    def changeCalType(choice):
        if choice == 'type_one':
            return {type_one_row: gr.Row(visible=True),
                    type_two_row: gr.Row(visible=False)}
        if choice == 'type_two':
            return {type_one_row: gr.Row(visible=False),
                    type_two_row: gr.Row(visible=True)}

and when click the radio to change type, and get misktake like this:

Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "asyncio\events.py", line 80, in _run
  File "asyncio\proactor_events.py", line 162, in _call_connection_lost
ConnectionResetError: [WinError 10054]

although this mistake does not effect normal use,but how to clear up this error

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

def practiceUI():
    def changeCalType(choice):
        if choice == 'type_one':
            return {type_one_row: gr.Row(visible=True),
                    type_two_row: gr.Row(visible=False)}
        if choice == 'type_two':
            return {type_one_row: gr.Row(visible=False),
                    type_two_row: gr.Row(visible=True)}

### System Info

```shell
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "asyncio\events.py", line 80, in _run
  File "asyncio\proactor_events.py", line 162, in _call_connection_lost
ConnectionResetError: [WinError 10054]
```

### Severity

I can work around it

**Comment by freddyaboulton** [comment] 2024-05-21 15:14
Hi @Paladin-673 ! Can you please share the full minimal reproducer (properly formatted) so that someone can take a look? We would also need all the system info (browser, gradio version and those of its dependencies). Thank you !

**Comment by Paladin-673** [comment] 2024-05-22 00:54
Thanks for your attention, my brower is google chrome and graido version is 4.16.0

This code in the attachment can report the same error. Please help to slove this problem, 3q.




***@***.***
 
From: Freddy Boulton
Date: 2024-05-21 23:14
To: gradio-app/gradio
CC: Paladin-673; Mention
Subject: Re: [gradio-app/gradio] ConnectionResetError: [WinError 10054] when click radio to switch (Issue #8313)
Hi @Paladin-673 ! Can you please share the full minimal reproducer (properly formatted) so that someone can take a look? We would also need all the system info (browser, gradio version and those of its dependencies). Thank you !

**Comment by Paladin-673** [comment] 2024-05-22 00:56
Thanks for your attention, my brower is google chrome and gradio version is 4.16.0

This code in the attachment can report the same error. Please help to slove this problem, 3q.



***@***.***
 
From: Freddy Boulton
Date: 2024-05-21 23:14
To: gradio-app/gradio
CC: Paladin-673; Mention
Subject: Re: [gradio-app/gradio] ConnectionResetError: [WinError 10054] when click radio to switch (Issue #8313)
Hi @Paladin-673 ! Can you please share the full minimal reproducer (properly formatted) so that someone can take a look? We would also need all the system info (browser, gradio version and those of its dependencies). Thank you !

**Comment by abidlabs** [comment] 2024-10-17 22:23
Hi, apologies for the late follow up. We haven't had a chance to look into this issue yet, but the Gradio codebase has changed quite significantly since this issue was created, particularly with the release of Gradio 5. Could you let us know if this is still an issue in the latest version of Gradio (`pip install --upgrade gradio`)? Thanks!

**Comment by abidlabs** [comment] 2024-10-23 16:36
Closing the issue for now, but happy to reopen if the issue continues to persist in the latest version of Gradio

**Closed by abidlabs** 2024-10-23 16:36 UTC
Labels: bug, pending clarification

**Comment by Paladin-673** [comment] 2024-10-24 00:41
OK, thank you for follow this question.  I will test the latest version of Gradio, if this error happens, I will get help for you.



***@***.***
 
From: Abubakar Abid
Date: 2024-10-18 06:24
To: gradio-app/gradio
CC: Paladin-673; Mention
Subject: Re: [gradio-app/gradio] ConnectionResetError: [WinError 10054] when click radio to switch (Issue #8313)
Hi, apologies for the late follow up. We haven't had a chance to look into this issue yet, but the Gradio codebase has changed quite significantly since this issue was created, particularly with the release of Gradio 5. Could you let us know if this is still an issue in the latest version of Gradio (pip install --upgrade gradio)? Thanks!

**Comment by yang1010x** [comment] 2024-11-08 17:31
把asyncio\windows_events.py里面的

DefaultEventLoopPolicy = WindowsProactorEventLoopPolicy
改成

DefaultEventLoopPolicy = WindowsSelectorEventLoopPolicy
