### ISSUE TITLE
UI can't correctly display on website

### ISSUE THREAD

**Issue by l-gxy-l** [gradio-app/gradio#2766] opened 2022-12-06 03:36 UTC
### Describe the bug

The ui has error like this
![image](https://user-images.githubusercontent.com/91101235/205797256-5d1bd4d8-92ca-4134-aa4c-612890848483.png)
I use edge, and it reports error on compatibility：
         The 'viewport' meta element 'content' attribute value should not contain 'maximum-scale'.
![image](https://user-images.githubusercontent.com/91101235/205797392-578668dc-3c33-4761-9be6-57002167fdfb.png)
the link: [了解这一点很重要的原因及在 webhint.io 上修复的方法](https://webhint.io/docs/user-guide/hints/hint-meta-viewport/?source=devtools)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Python:
3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) 
[MSC v.1932 64 bit (AMD64)] on win32
Microsoft Edge version:
108.0.1462.42   64bit
the running code is:
import gradio as gr

> def greet(name):
>     return "Hello " + name + "!"
> demo = gr.Interface(fn=greet, inputs="text", outputs="text")
> demo.launch()   
![image](https://user-images.githubusercontent.com/91101235/205803058-5c7661b7-e3a9-431f-b018-93349addf951.png)

### Screenshot

![image](https://user-images.githubusercontent.com/91101235/205804465-e70e7473-cb79-4b1f-9a5a-a8c0bb0ec512.png)

### Logs

```shell
The 'viewport' meta element 'content' attribute value should not contain 'maximum-scale'.
```

### System Info

```shell
gradio version:3.12.0
operating system: Microsoft Windows 22H2(19045.2311)
edge: 108.0.1462.42   64bit
```

### Severity

annoying

**Comment by freddyaboulton** [comment] 2023-01-31 22:45
Is this still a problem @l-gxy-l ?

**Comment by freddyaboulton** [comment] 2023-02-03 19:42
Going to close this since we can't reproduce but feel free to reopen if the problem persists!

**Closed by freddyaboulton** 2023-02-03 19:42 UTC
Labels: bug, needs repro
