### ISSUE TITLE
equal_height argument does not work.

### ISSUE THREAD

**Issue by tlqiao** [gradio-app/gradio#5922] opened 2023-10-16 03:17 UTC
### Describe the bug

I want to keep all components in a row same height, I use the gr.Row(equal_height=True) to set it, but it does not work.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

there are two JSON components and one textbox component in the same row, I want to keep them same height. When click the button, will generate some context to fill the JSON components, the length  of the contexts are different, so it cause the height of two JSON components are different. I use gr.Row(equal_height=True), and hope the behavior is if the context of filling the JSON are two long, the height is fixed and can scroll to review the context, but the real behavior is the height of JSON component auto added, it cause the height of two JSON components are different.

Here is some code:

with gr.Blocks() as single_api:
    server_list = get_server_list()
    with gr.Row():
        get_server_button = gr.Button(value="Refresh ServerList")
        get_apiInfo_button = gr.Button(value="Show API Details")
        choose_req_fields_button = gr.Button(value="Choose req fileds")
        choose_res_fields_button = gr.Button(value="Choose res fields")
        language_dropdownlist = gr.Dropdown(
            choices=["Javascript"], label="Choose language")
        test_framework_dropdown = gr.Dropdown(
            choices=["supertest"], label="Choose testFramework")
        generate_api_test_button = gr.Button(value="Generate API Test")
        server_dropdown = gr.Dropdown(
            choices=server_list, label="Server List", interactive=True)
        api_url_list_dropdown = gr.Dropdown(
            choices=[], label="API Url List", interactive=True)
        method_list_dropdown = gr.Dropdown(
            choices=["GET", "POST", "DELETE", "PUT"], label="API Methods")

    def update_server_list():
        list = get_server_list()
        return server_dropdown.update(choices=list)

    def update_api_url_list(server_name):
        list = get_api_url_by_server(server_name)
        return api_url_list_dropdown.update(choices=list)

    server_dropdown.select(update_api_url_list, inputs=server_dropdown,
                           outputs=api_url_list_dropdown)
    get_server_button.click(update_server_list, outputs=server_dropdown)
    **with gr.Row(equal_height=True):**
        with gr.Column(scale=2):
            api_request = gr.Json(label="Api Request")
        with gr.Column(scale=2):
            api_response = gr.Json(label="Api Response")
        with gr.Column(scale=2):
            header_input = gr.TextArea(label="Input user-defined headers")
        get_apiInfo_button.click(get_api_details, inputs=[
                                 server_dropdown, api_url_list_dropdown, method_list_dropdown], outputs=[api_request, api_response])

### Screenshot

<img width="1528" alt="image" src="https://github.com/gradio-app/gradio/assets/16421412/d93c1b56-6555-423f-ad76-f329fd016af3">

### System Info

```shell
Operating System: Darwin
gradio version: 3.44.3
gradio_client version: 0.5.0
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment] 2023-10-16 03:23
Hi @tlqiao would you be able to correctly format the code in your example so that we can run it and reproduce it?

**Comment by tlqiao** [comment] 2023-10-18 08:30
Hi @abidlabs , thanks for your response, here is my new experiment code, left is textbox component and right is code component. Their height are not equal. When you click run the button, the code component will expand automatically base on content length, Is there way to fix the height of code component, if content length is larger, can scroll it to review the contents.

**Produce issue code:**

import gradio as gr

def tranfer_info(string):
    return string + string + string

with gr.Blocks() as demo:
    with gr.Row():
        my_button = gr.Button(value="Run It")
    with gr.Row(equal_height=True):
        with gr.Column():
            input = gr.TextArea()
        with gr.Column():
            output = gr.Code(label="output")
    my_button.click(tranfer_info, inputs=[input], outputs=output)
demo.launch()

**here is screenshot**
<img width="1522" alt="demo" src="https://github.com/gradio-app/gradio/assets/16421412/9d765f72-eb35-4402-817e-c14cf04708bd">

**Comment by freddyaboulton** [comment] 2023-10-18 16:08
This is a duplicate of #3202. Thanks for filing @tlqiao !

**Closed by freddyaboulton** 2023-10-18 16:08 UTC
Labels: bug, pending clarification
