### ISSUE TITLE
BUG:  No rendering of gradio objects within local Docker

### ISSUE THREAD

**Issue by kidcoconut** [gradio-app/gradio#8724] opened 2024-07-08 23:16 UTC
### Describe the bug

I recreated a simple gradio demo, running locally in Docker; 
 ie similar to the first demo listed in https://www.gradio.app/guides/blocks-and-event-listeners;  except I put the input and output textboxes in a gr.Row()

Initial attempt:  requirements.txt gradio version unspecified (defaults to 4.37.2)
- no rendering of any gradio text boxes, or Run button
- Api and Gradio footer links are not visible either

I worked through multiple gradio versions by modifying my requirements.txt and have found:
- works:  <=v4.17.0
- broken: >=4.18.0

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
#--- reproduce where gradio version >=4.18.0
import gradio as gr


def greet(name):
    return "Hello " + name + "!"


with gr.Blocks() as blocks:
    with gr.Row():
        txtInput = gr.Text()
        txtOutput = gr.Text()
    btnRun = gr.Button("Run") 
    btnRun.click(fn=greet, inputs=txtInput, outputs=txtOutput, api_name="greet")
    
#blocks.queue()
blocks.launch(debug=True)

```

### System Info

```shell
latest version of Gradio does not work
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment] 2024-07-09 01:54
Hi @kidcoconut can you follow the steps in this guide and let us know if this works for you: https://www.gradio.app/guides/deploying-gradio-with-docker

We'll need a step-by-step reproduction including the Docker image since it sounds like an issue with the way Gradio is being deployed here.

**Comment by kidcoconut** [comment] 2024-07-09 04:02
works just fine.

Do you have n example for running behind nginx in a Huggingface Docker
space?

**Comment by kidcoconut** [comment] 2024-07-09 04:41
Tried to update my code based on this:
https://www.gradio.app/guides/running-gradio-on-your-web-server-with-nginx

For now, running Docker locally with nginx and gradio.  Same issue as
reported.  No gradio objects are visible.

**Comment by kidcoconut** [comment] 2024-07-09 04:59
Per my original PR;  I reverted my code so that gradio v4.17.0 is specified
on install ... it works.

Gradio in local Docker behind nginx does not work for versions of gradio >
4.17.0

**Comment by kidcoconut** [comment] 2024-07-09 05:16
Update:
So ... no real progress as of yet.  I am still pretty much where I started.
- I have to use a downgraded version of gradio to run a simple page on
local Docker behind nginx

Awaiting further direction.  Thanks for your help so far.

**Comment by kidcoconut** [comment] 2024-07-09 05:46
Update:  Resolved (on local Docker with nginx)

I am now using the most up to date version of gradio.

The issue is that the example nginx.conf file needs to be updated.

>>> this works
    location /gradio-demo/ {  # Change this if you'd like to server your
Gradio app on a different path
        proxy_pass http://127.0.0.1:7860/; # Change this if your Gradio app
will be running on a different port
        #proxy_buffering off;
        proxy_redirect off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        #proxy_set_header Host $host;
        proxy_set_header Host $http_host;
        #proxy_set_header X-Forwarded-Host $host;
        #proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_cache_bypass $http_upgrade;
        proxy_read_timeout 86400;
    }

Note: Gradio behind nginx on Docker in Huggingface only works for root (/)
requests. Other nginx locations such as /gradio/ or /gradio-demo/ does not
work.

Project is here: https://huggingface.co/spaces/kidcoconut/dkr_nginx_fastapi

I would like to have an example of:
- nginx in Docker on huggingface
- 1 nginx location :port1 for gradio; 2 pages
- 1 nginx location :port2 for fastapi; 2 endpoints

Any help appreciated

**Comment by jamie0725** [comment] 2024-07-24 10:20
@abidlabs this problem is related to https://github.com/gradio-app/gradio/issues/7836 and https://github.com/gradio-app/gradio/issues/7792.

**Comment by jamie0725** [comment] 2024-07-24 10:20
@kidcoconut can you check if the screenshot I shared matches your situation?

**Comment by kidcoconut** [comment] 2024-07-24 22:40
Per my comment on July 9th ... this has been resolved

**Comment by kidcoconut** [comment] 2024-07-24 22:41
I'll take a look.  Thanks

**Comment by abidlabs** [comment] 2024-07-24 22:53
I'll go ahead and close this. @jamie0725 if you are still facing this issue in the latest version of gradio, please create a new issue with a complete but minimal repro. thanks!

**Closed by abidlabs** 2024-07-24 22:53 UTC
Labels: bug, needs repro

**Comment by jamie0725** [comment] 2024-07-26 09:30
Hi @abidlabs, I have solved the issue. The solution is rather simple (but takes a long time to identify), providing the correct `root_path` in the `mount_gradio_app` function.

The `/config` path is very useful.
