### ISSUE TITLE
Flagging button not working when clicked

### ISSUE THREAD

**Issue by rockdrigoma** [gradio-app/gradio#914] opened 2022-03-31 19:36 UTC
### Describe the bug

I implemented some flagging_options for my Gradio app at HuggingFace Spaces.
But when I try to flag a result, the feature seems to be broken, it doesn't show any action being held nor a directory being created with the flagging logs inside the app directory.

### Reproduction

```
import gradio as gr
from transformers import AutoModelForSeq2SeqLM
from transformers import AutoTokenizer

model = AutoModelForSeq2SeqLM.from_pretrained('hackathon-pln-es/t5-small-spanish-nahuatl')
tokenizer = AutoTokenizer.from_pretrained('hackathon-pln-es/t5-small-spanish-nahuatl')

def predict(input):
  input_ids = tokenizer('translate Spanish to Nahuatl: ' + input, return_tensors='pt').input_ids
  outputs = model.generate(input_ids)
  outputs = tokenizer.batch_decode(outputs, skip_special_tokens=True)[0]
  return outputs

gr.Interface(
   fn=predict,
   inputs=gr.inputs.Textbox(lines=1, label="Input Text in Spanish"),
   outputs=[
     gr.outputs.Textbox(label="Translated text in Nahuatl"),
     ],
   theme="peach",
   title='🌽 Spanish to Nahuatl Automatic Translation',
   description='This model is a T5 Transformer (t5-small) fine-tuned on 29,007 spanish and nahuatl sentences using 12,890 samples collected from the web and 16,117 samples from the Axolotl dataset. The dataset is normalized using "sep" normalization from py-elotl. For more details visit https://huggingface.co/hackathon-pln-es/t5-small-spanish-nahuatl',
   examples=[
     'hola',
     'conejo',
     'estrella',
     'te quiero mucho',
     'te amo',
     'quiero comer',
     'esto se llama agua',
     'mi abuelo se llama Juan',
     'te amo con todo mi corazón'],
   allow_flagging="manual",
   flagging_options=["right translation", "wrong translation", "error", "other"],
   flagging_dir="logs"
   ).launch(enable_queue=True)
```

## No action nor message when button is clicked
![Captura de Pantalla 2022-03-31 a la(s) 13 32 09](https://user-images.githubusercontent.com/5482256/161134710-df1b5fe3-2934-4cbf-afd3-7bc16c2c72ec.png)

## No flagging logs directory in the app
![Captura de Pantalla 2022-03-31 a la(s) 13 33 15](https://user-images.githubusercontent.com/5482256/161134874-1321f166-5e57-4113-bcbf-21f3c20e2684.png)

### System Info

```shell
2.9.0
```

### Severity

critical

**Comment by dnth** [comment] 2022-04-01 05:54
I have the same issue. It works on my local machine, but not on HF Spaces

**Comment by rockdrigoma** [comment] 2022-04-12 14:22
@osanseviero @abidlabs any idea on this?

**Comment by rockdrigoma** [comment] 2022-04-12 15:19
This is the link to the Space [https://huggingface.co/spaces/hackathon-pln-es/Spanish-Nahuatl-Translation](https://huggingface.co/spaces/hackathon-pln-es/Spanish-Nahuatl-Translation) but it seems that all Spaces have same issue

**Comment by abidlabs** [comment] 2022-04-12 18:19
Thanks @rockdrigoma @dnth @osanseviero 

We're changing how flagging and some other things work at the moment anyways as part of this large PR, so it might get fixed. Otherwise, we'll look into the issue to see what broke. Appreciate it!

**Comment by rockdrigoma** [comment] 2022-04-12 18:21
Great @abidlabs and thanks for your reply, if I can do something in a separate PR to fix only flagging, let me know. Just started to use Gradio so I don't really know where I should start in the code

**Comment by abidlabs** [comment] 2022-04-25 21:47
Hi @rockdrigoma so I looked into this. Flagging _is_ actually working in the case of these Spaces, but the problem is that the flagged data are being saved on the Spaces machine, but are **not being committed and pushed** to your Spaces repo. 

You can confirm this by trying out this Space, which prints the `flagged/` directory, and shows that there is a `log.csv` that has been created: https://huggingface.co/spaces/abidlabs/flagging-tester

**Comment by abidlabs** [comment] 2022-04-25 21:50
The solution here would be use a custom `FlaggingHandler` that pushes the flagging directory after it has been updated. We created a similar one to push flagged data to a Hugging Face Dataset repo, but we could do something similar to push to a Spaces repo, which users might be more familiar with.

**Comment by rockdrigoma** [comment] 2022-04-28 01:14
Thank you @abidlabs, sorry for the noise. This is really helpful. I will try to do what you suggest.

**Comment by abidlabs** [comment] 2022-04-28 08:21
I realized actually that saving and pushing flagged data to the Hugging Face Space is not a good idea since every time a commit is pushed, the Space restarts. 

So to summarize, the best option here is to use a Hugging Face dataset as the storage for flagged data. And to do that, please check out the `HuggingFaceDatasetSaver()` flagging handler, which allows you to do that easily.

Here is an example Space that uses this: https://huggingface.co/spaces/abidlabs/crowd-speech

**Closed by abidlabs** 2022-04-28 08:21 UTC
Labels: enhancement

**Comment by rockdrigoma** [comment] 2022-04-28 13:40
Excellent! Thank you @abidlabs
