### ISSUE TITLE
Gallery Scrolling Bug

### ISSUE THREAD

**Issue by x-CK-x** [gradio-app/gradio#10115] opened 2024-12-04 04:55 UTC
### Describe the bug

`gallery_comp = gr.Gallery(visible=False, elem_id="gallery_id", columns=3, object_fit="contain", height=1356)`
https://github.com/x-CK-x/Dataset-Curation-Tool/blob/main/UI_tabs/gallery_tab.py

I've used this snippet of code for multiple versions of my data curation tool and for months it worked to keep a fixed height for the gallery while still being able to scroll through the images. I was using gradio `3.50.2` for a long time before upgrading to version `5.7.1`.

I've tried several other parameter permutations via the gradio docs for the gallery component, and I am still unable to regain the original functionality as mentioned.

The example image below is of a gallery that contains 33 images with the bug present not showing a scroll bar needed to view the rest of the images.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
`gallery_comp = gr.Gallery(visible=False, elem_id="gallery_id", columns=3, object_fit="contain", height=1356)`
#https://github.com/x-CK-x/Dataset-Curation-Tool/blob/main/UI_tabs/gallery_tab.py for reference
```

### Screenshot

![image](https://github.com/user-attachments/assets/373cc6ca-7133-463e-a726-5561113ce8aa)

### System Info

```shell
Operating System: Linux
gradio version: 5.7.1
gradio_client version: 1.5.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
anyio: 4.6.2.post1
audioop-lts is not installed.
fastapi: 0.115.5
ffmpy: 0.4.0
gradio-client==1.5.0 is not installed.
httpx: 0.28.0
huggingface-hub: 0.26.3
jinja2: 3.1.4
markupsafe: 2.1.5
numpy: 2.1.3
orjson: 3.10.12
packaging: 24.2
pandas: 2.2.3
pillow: 11.0.0
pydantic: 2.10.2
pydub: 0.25.1
python-multipart==0.0.12 is not installed.
pyyaml: 6.0.2
ruff: 0.8.1
safehttpx: 0.1.1
semantic-version: 2.10.0
starlette: 0.41.3
tomlkit==0.12.0 is not installed.
typer: 0.14.0
typing-extensions: 4.12.2
urllib3: 2.2.3
uvicorn: 0.32.1
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2024.10.0
httpx: 0.28.0
huggingface-hub: 0.26.3
packaging: 24.2
typing-extensions: 4.12.2
websockets: 12.0
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment] 2024-12-16 16:51
Thanks @x-CK-x for reporting, as far as I can tell, this is a duplicate of https://github.com/gradio-app/gradio/issues/10044, so I'll go ahead and close

**Closed by abidlabs** 2024-12-16 16:51 UTC
Labels: bug
