### ISSUE TITLE
How to get input image size?

### ISSUE THREAD

**Issue by vijishmadhavan** [gradio-app/gradio#2299] opened 2022-09-20 14:29 UTC
How can we get the input image size or shape?

**Comment by freddyaboulton** [comment] 2022-09-20 14:39
Hi @vijishmadhavan ! Thanks for posting the question. Do you mean the size of the image from within your prediction function?

The `gr.Image` component has a `type` parameter. By default it's set to `numpy` which means your prediction function will get a numpy array as input. You can then do `im.shape` to get the shape of the array.

I'm going to close this out since it's a general question about gradio and not a bug report or feature request. Let's continue the this on a github discussion thread or on the HuggingFace [discord](https://discord.gg/X3wCKYuT)!

**Closed by freddyaboulton** 2022-09-20 14:39 UTC
