### ISSUE TITLE
Drag-and-drop feature for ImageEditor

### ISSUE THREAD

**Issue by hotohoto** [gradio-app/gradio#8395] opened 2024-05-28 13:51 UTC
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
- Using drag-and-drop feature together with image editing was possible in v3.x.x with the `Image` component + brush. But it's not possible anymore in v4.x.x.

**Describe the solution you'd like**  
- The drag-and-drop feature for `ImageEditor` the same as for `Image`

**Additional context**  
- Documentation says `ImageEditor` with the `upload` source, it can handle dropping a file, but actually it can not.
 https://github.com/gradio-app/gradio/blob/a373b0edd36613a9a6a25a1a2893edd6533a7291/gradio/components/image_editor.py#L172

**Comment by abidlabs** [comment] 2024-07-14 16:38
Duplicate of https://github.com/gradio-app/gradio/issues/6503, which we are planning on tackling soon

**Closed by abidlabs** 2024-07-14 16:38 UTC
Labels: enhancement, 🖼️ ImageEditor
