### ISSUE TITLE
Allow persisting upvote/downvote

### ISSUE THREAD

**Issue by cosmosof** [gradio-app/gradio#6755] opened 2023-12-11 22:35 UTC
- [ +] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Users are allowed to vote outputs, I am saving this into the DB, however I can't find a way to display back on each chat items.

**Describe the solution you'd like**  
We should be able to display back vote data when user loads back to the same chat

**Comment by abidlabs** [comment] 2024-01-05 23:43
Hi @cosmosof this is out of scope of the `gr.Chatbot` component. The reason is that we do not save the state of components, only their `value`. There is no way in Gradio to reproduce specific user interactions with a component that does not change its core `value`. I.e. this would be like us trying to display back what parts of a text were highlighted by a user in a `gr.Textbox`. 

Although it is out of scope of `gr.Chatbot`, I think this would be a great case for a custom component!

We've made it possible for Gradio users to create their own custom components -- meaning that you can write some Python and JavaScript (Svelte), and publish it as a Gradio component. You can use it in your own Gradio apps, or share it so that anyone can use it in their Gradio apps. 

Here's an example of a Gradio custom component: https://github.com/PhyscalX/gradio-image-prompter -- it lets you upload images and process points or draw boxes on top of the image.

In your case, you could create a custom component very similar to `gr.Chatbot` that includes likes/dislikes as part of the value. If you'd like to create your own, we've put together a Guide: https://www.gradio.app/guides/five-minute-guide, and we're happy to help.

**Closed by abidlabs** 2024-01-05 23:43 UTC
Labels: enhancement
