### ISSUE TITLE
Custom Component unable to view in dev server 

### ISSUE THREAD

**Issue by alpaolo** [gradio-app/gradio#8669] opened 2024-06-29 21:02 UTC
### Describe the bug

I'm trying to create a custom component starting from the video template. Unfortunately **every template other than Button** (which works) gives me this error. Both on Windows 11 (two different platforms) and WSL2. Latest Gradio Python 3.12 Node 20.
I also tried with Python 3.10 and Node 18, even crossing Node and Python versions.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### System Info
```
------------------------------
Operating System: Windows 11
gradio version: 4.37.1
gradio_client version: 1.0.2

------------------------------------------------
gradio dependencies in your environment:
------------------------- ----------- -----------------------------------------
aiofiles                  23.2.1
altair                    5.3.0
annotated-types           0.7.0
anyio                     4.4.0
attrs                     23.2.0
backports.tarfile         1.2.0
build                     1.2.1
certifi                   2024.6.2
charset-normalizer        3.3.2
click                     8.1.7
colorama                  0.4.6
contourpy                 1.2.1
cycler                    0.12.1
dnspython                 2.6.1
docutils                  0.21.2
email_validator           2.2.0
exceptiongroup            1.2.1
fastapi                   0.111.0
fastapi-cli               0.0.4
ffmpy                     0.3.2
filelock                  3.15.4
fonttools                 4.53.0
fsspec                    2024.6.1
gradio                    4.37.1
gradio_client             1.0.2
gradio_superbutton        0.0.1       G:\GRADIO\CUSTOM_COMPONENTS\superbutton
gradio_superlabel         0.0.1       G:\GRADIO\CUSTOM_COMPONENTS\superlabel
gradio_superpippo         0.0.1       G:\GRADIO\CUSTOM_COMPONENTS\superhtml
h11                       0.14.0
httpcore                  1.0.5
httptools                 0.6.1
httpx                     0.27.0
huggingface-hub           0.23.4
idna                      3.7
importlib_metadata        8.0.0
importlib_resources       6.4.0
jaraco.classes            3.4.0
jaraco.context            5.3.0
jaraco.functools          4.0.1
Jinja2                    3.1.4
jsonschema                4.22.0
jsonschema-specifications 2023.12.1
keyring                   25.2.1
kiwisolver                1.4.5
markdown-it-py            3.0.0
MarkupSafe                2.1.5
matplotlib                3.9.0
mdurl                     0.1.2
more-itertools            10.3.0
nh3                       0.2.17
numpy                     1.26.4
orjson                    3.10.5
packaging                 24.1
pandas                    2.2.2
pillow                    10.3.0
pip                       23.0.1
pkginfo                   1.10.0
pydantic                  2.7.4
pydantic_core             2.18.4
pydub                     0.25.1
Pygments                  2.18.0
pyparsing                 3.1.2
pyproject_hooks           1.1.0
python-dateutil           2.9.0.post0
python-dotenv             1.0.1
python-multipart          0.0.9
pytz                      2024.1
pywin32-ctypes            0.2.2
PyYAML                    6.0.1
readme_renderer           43.0
referencing               0.35.1
requests                  2.32.3
requests-toolbelt         1.0.0
rfc3986                   2.0.0
rich                      13.7.1
rpds-py                   0.18.1
ruff                      0.5.0
semantic-version          2.10.0
setuptools                65.5.0
shellingham               1.5.4
six                       1.16.0
sniffio                   1.3.1
starlette                 0.37.2
tomli                     2.0.1
tomlkit                   0.12.0
toolz                     0.12.1
tqdm                      4.66.4
twine                     5.1.1
typer                     0.12.3
typing_extensions         4.12.2
tzdata                    2024.1
ujson                     5.10.0
urllib3                   2.2.2
uvicorn                   0.30.1
watchfiles                0.22.0
websockets                11.0.3
zipp                      3.19.2
```

### Screenshot

![Screenshot 2024-06-29 225628](https://github.com/gradio-app/gradio/assets/8401155/1e080a92-a04d-4a62-86ec-1955503c10c8)

### Logs

```shell
[2m22:47:28[22m [36m[1m[22m[39m [32m✨ new dependencies optimized: [33m@gradio/statustracker, @gradio/atoms[32m[39m

[2m22:47:28[22m [31m[1m[22m[39m Pre-transform error: Failed to resolve import "virtual:component-loader" from
"frontend/node_modules/@gradio/utils/src/utils.ts?v=b142f2e2". Does the file exist?

[2m22:47:28[22m [31m[1m[22m[39m [31mInternal server error: Failed to resolve import "virtual:component-loader" from
"frontend/node_modules/@gradio/utils/src/utils.ts?v=b142f2e2". Does the file exist?[39m

  Plugin: [35mvite:import-analysis[39m

  File:
[36mD:/DEEPL/GRADIO/CUSTOM_COMPONENT/superhtml/frontend/node_modules/@gradio/utils/src/utils.ts?v=b142f2e2[39m:217:10

[33m  127|      this.client = client;

  128|      if (!virtual_component_loader) {

  129|        import("virtual:component-loader").then((module) => {

     |               ^

  130|          this._load_component = module.load_component;

  131|          virtual_component_loader = module.load_component;[39m

      at TransformPluginContext._formatError
(file:///D:/DEEPL/GRADIO/CUSTOM_COMPONENT/superhtml/frontend/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:49746:41
)

      at TransformPluginContext.error
(file:///D:/DEEPL/GRADIO/CUSTOM_COMPONENT/superhtml/frontend/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:49741:16
)

      at normalizeUrl
(file:///D:/DEEPL/GRADIO/CUSTOM_COMPONENT/superhtml/frontend/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:64326:23
)

      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

      at async
file:///D:/DEEPL/GRADIO/CUSTOM_COMPONENT/superhtml/frontend/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:64458:39

      at async Promise.all (index 0)

      at async TransformPluginContext.transform
(file:///D:/DEEPL/GRADIO/CUSTOM_COMPONENT/superhtml/frontend/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:64385:7)

      at async PluginContainer.transform
(file:///D:/DEEPL/GRADIO/CUSTOM_COMPONENT/superhtml/frontend/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:49587:18
)

      at async loadAndTransform
(file:///D:/DEEPL/GRADIO/CUSTOM_COMPONENT/superhtml/frontend/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:52409:27
)

      at async viteTransformMiddleware
(file:///D:/DEEPL/GRADIO/CUSTOM_COMPONENT/superhtml/frontend/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:62168:24
)

[2m22:56:18[22m [31m[1m[22m[39m [31mInternal server error: Failed to resolve import "virtual:component-loader" from
"frontend/node_modules/@gradio/utils/src/utils.ts?v=b142f2e2". Does the file exist?[39m

  Plugin: [35mvite:import-analysis[39m

  File:
[36mD:/DEEPL/GRADIO/CUSTOM_COMPONENT/superhtml/frontend/node_modules/@gradio/utils/src/utils.ts?v=b142f2e2[39m:217:10

[33m  127|      this.client = client;

  128|      if (!virtual_component_loader) {

  129|        import("virtual:component-loader").then((module) => {

     |               ^

  130|          this._load_component = module.load_component;

  131|          virtual_component_loader = module.load_component;[39m

      at TransformPluginContext._formatError
(file:///D:/DEEPL/GRADIO/CUSTOM_COMPONENT/superhtml/frontend/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:49746:41
)

      at TransformPluginContext.error
(file:///D:/DEEPL/GRADIO/CUSTOM_COMPONENT/superhtml/frontend/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:49741:16
)

      at normalizeUrl
(file:///D:/DEEPL/GRADIO/CUSTOM_COMPONENT/superhtml/frontend/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:64326:23
)

      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

      at async
file:///D:/DEEPL/GRADIO/CUSTOM_COMPONENT/superhtml/frontend/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:64458:39

      at async Promise.all (index 0)

      at async TransformPluginContext.transform
(file:///D:/DEEPL/GRADIO/CUSTOM_COMPONENT/superhtml/frontend/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:64385:7)

      at async PluginContainer.transform
(file:///D:/DEEPL/GRADIO/CUSTOM_COMPONENT/superhtml/frontend/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:49587:18
)

      at async loadAndTransform
(file:///D:/DEEPL/GRADIO/CUSTOM_COMPONENT/superhtml/frontend/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:52409:27
)

      at async viteTransformMiddleware
(file:///D:/DEEPL/GRADIO/CUSTOM_COMPONENT/superhtml/frontend/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:62168:24
)
```

### Severity 
```
Blocking usage of gradio dev
```

**Comment by freddyaboulton** [comment] 2024-07-02 09:26
This seems like a dupe of #8661 so will close this one.

**Closed by freddyaboulton** 2024-07-02 09:26 UTC
Labels: bug, custom-components
