### ISSUE TITLE
Gradio Unable to Load More than 5 iFrames After Package Update to 4.25 Version

### ISSUE THREAD

**Issue by marcoquin** [gradio-app/gradio#8022] opened 2024-04-15 14:06 UTC
### Describe the bug

thanks for the tremendous work on gradio !

After updating the package from version 4.24 to version 4.25, Gradio encounters a problem where it is unable to load more than 5 iFrames. It is loading indefinitely. (the problem is still present in 4.26)

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Here is the main app file:
```python
import gradio as gr
from fastapi import FastAPI, Request
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles

from test import io_1, io_2, io_3, io_4, io_5, io_6
app = FastAPI()

@app.get("/")
async def get_home(request: Request):
    response = FileResponse(f"./folder_front/front.html"    )
    return response

app.mount("/folder_front", StaticFiles(directory="folder_front"), name="folder_front")

io_6_page = gr.mount_gradio_app(app=app, blocks=io_6, path="/6")
io_3_page = gr.mount_gradio_app(
    app=app, blocks=io_3, path="/3"
)
io_1_page = gr.mount_gradio_app(app=app, blocks=io_1, path="/1")
io_5_page = gr.mount_gradio_app(
    app=app, blocks=io_5, path="/5"
)
io_2_page = gr.mount_gradio_app(
    app=app, blocks=io_2, path="/2"
)

io_4_page = gr.mount_gradio_app(
    app=app, blocks=io_4, path="/4"
)
```
the test.py file for the import
```python
import gradio as gr

with gr.Blocks() as io_1:
    title = gr.Markdown("1")
with gr.Blocks() as io_2:
    title = gr.Markdown("2")
with gr.Blocks() as io_3:
    title = gr.Markdown("3")
with gr.Blocks() as io_4:
    title = gr.Markdown("4")
with gr.Blocks() as io_5:
    title = gr.Markdown("5")
with gr.Blocks() as io_6:
    title = gr.Markdown("6")
```
The html front:
```html
<!DOCTYPE html>
<head>
    <meta charset="UTF-8">
</head>
<body class = "light-body">

    <div class="iframe-container">
        <iframe id="1" src="/1/?__theme=light"  style="display:block;" ></iframe>
        <iframe id="2" src="/2/?__theme=light" style="display:block;"></iframe>
        <iframe id="3" src="/3/?__theme=light" style="display:block;"></iframe>
        <iframe id="4" src="/4/?__theme=light" style="display:block;"></iframe>
        <iframe id="5" src="/5/?__theme=light" style="display:block;"></iframe>
        <iframe id="6" src="/6/?__theme=light" style="display:block;"></iframe>
    </div> 

</body>
</html>
```

### Screenshot

Loading indefinitely: 
![image](https://github.com/gradio-app/gradio/assets/166842689/be417064-1349-4413-8630-59abba858c59)

### Logs

```shell
Failed to load resource: the server responded with a status of 404 (Not Found)
:8000/assets/index-a889f790.css:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
:8000/assets/index-a889f790.css:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
:8000/assets/index-a889f790.css:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
index-a80d931b.js:2 Unable to preload CSS for http://127.0.0.1:8000/assets/index-a889f790.css
(anonymous) @ index-a80d931b.js:2
index-a80d931b.js:2 Unable to preload CSS for http://127.0.0.1:8000/assets/index-a889f790.css
(anonymous) @ index-a80d931b.js:2
:8000/assets/index-a889f790.css:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
index-a80d931b.js:2 Unable to preload CSS for http://127.0.0.1:8000/assets/index-a889f790.css
(anonymous) @ index-a80d931b.js:2
index-a80d931b.js:2 Unable to preload CSS for http://127.0.0.1:8000/assets/index-a889f790.css
(anonymous) @ index-a80d931b.js:2
index-a80d931b.js:2 Unable to preload CSS for http://127.0.0.1:8000/assets/index-a889f790.css
(anonymous) @ index-a80d931b.js:2
:8000/assets/index-a889f790.css:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
index-a80d931b.js:2 Unable to preload CSS for http://127.0.0.1:8000/assets/index-a889f790.css
```

### System Info

```shell
Python 3.9

pip freeze: 
aiofiles==23.2.1
altair==5.3.0
annotated-types==0.6.0
anyio==4.3.0
attrs==23.2.0
certifi==2024.2.2
charset-normalizer==3.3.2
click==8.1.7
contourpy==1.2.1
cycler==0.12.1
exceptiongroup==1.2.0
fastapi==0.110.1
ffmpy==0.3.2
filelock==3.13.4
fonttools==4.51.0
fsspec==2024.3.1
gradio==4.25.0
gradio_client==0.15.0
h11==0.14.0
httpcore==1.0.5
httpx==0.27.0
huggingface-hub==0.22.2
idna==3.7
importlib_resources==6.4.0
Jinja2==3.1.3
jsonschema==4.21.1
jsonschema-specifications==2023.12.1
kiwisolver==1.4.5
markdown-it-py==3.0.0
MarkupSafe==2.1.5
matplotlib==3.8.4
mdurl==0.1.2
numpy==1.26.4
orjson==3.10.0
packaging==24.0
pandas==2.2.2
pillow==10.3.0
pydantic==2.7.0
pydantic_core==2.18.1
pydub==0.25.1
Pygments==2.17.2
pyparsing==3.1.2
python-dateutil==2.9.0.post0
python-multipart==0.0.9
pytz==2024.1
PyYAML==6.0.1
referencing==0.34.0
requests==2.31.0
rich==13.7.1
rpds-py==0.18.0
ruff==0.3.7
semantic-version==2.10.0
shellingham==1.5.4
six==1.16.0
sniffio==1.3.1
starlette==0.37.2
tomlkit==0.12.0
toolz==0.12.1
tqdm==4.66.2
typer==0.12.3
typing_extensions==4.11.0
tzdata==2024.1
urllib3==2.2.1
uvicorn==0.29.0
websockets==11.0.3
zipp==3.18.1
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment] 2024-04-16 19:05
Very odd @marcoquin ! I can't repro 
<img width="393" alt="image" src="https://github.com/gradio-app/gradio/assets/41651716/6497f218-5425-426a-87a8-5baa2d6d9704">

We use this set up in our automated deploys for each PR and the demos are able to load so not sure what is happening.

https://huggingface.co/spaces/gradio-pr-deploys/pr-8026-all-demos

**Comment by marcoquin** [comment] 2024-04-17 11:31
That's really strange. I launch my app using uvicorn `uvicorn run:app --reload --log-level info --no-access-log`. I also tried with hypercorn `hypercorn run:app`. Still with python 3.9. I tried with python 3.11 and it doesn't work either. I changed OS from ubuntu to Windows and it doesn't change the bug. 

I repost my system info with hypercorn : 
```aiofiles==23.2.1
altair==5.3.0
annotated-types==0.6.0
anyio==4.3.0
attrs==23.2.0
certifi==2024.2.2
charset-normalizer==3.3.2
click==8.1.7
colorama==0.4.6
contourpy==1.2.1
cycler==0.12.1
exceptiongroup==1.2.0
fastapi==0.110.1
ffmpy==0.3.2
filelock==3.13.4
fonttools==4.51.0
fsspec==2024.3.1
gradio==4.26.0
gradio_client==0.15.1
h11==0.14.0
h2==4.1.0
hpack==4.0.0
httpcore==1.0.5
httpx==0.27.0
huggingface-hub==0.22.2
Hypercorn==0.16.0
hyperframe==6.0.1
idna==3.7
importlib_resources==6.4.0
Jinja2==3.1.3
jsonschema==4.21.1
jsonschema-specifications==2023.12.1
kiwisolver==1.4.5
markdown-it-py==3.0.0
MarkupSafe==2.1.5
matplotlib==3.8.4
mdurl==0.1.2
numpy==1.26.4
orjson==3.10.1
packaging==24.0
pandas==2.2.2
pillow==10.3.0
priority==2.0.0
pydantic==2.7.0
pydantic_core==2.18.1
pydub==0.25.1
Pygments==2.17.2
pyparsing==3.1.2
python-dateutil==2.9.0.post0
python-multipart==0.0.9
pytz==2024.1
PyYAML==6.0.1
referencing==0.34.0
requests==2.31.0
rich==13.7.1
rpds-py==0.18.0
ruff==0.3.7
semantic-version==2.10.0
shellingham==1.5.4
six==1.16.0
sniffio==1.3.1
starlette==0.37.2
taskgroup==0.0.0a4
tomli==2.0.1
tomlkit==0.12.0
toolz==0.12.1
tqdm==4.66.2
typer==0.12.3
typing_extensions==4.11.0
tzdata==2024.1
urllib3==2.2.1
uvicorn==0.29.0
websockets==11.0.3
wsproto==1.2.0
zipp==3.18.1 ```


When I'm trying to reload the application (without changing the file, juste saving `run.py` again, and closing my internet window, I got this logs : 

```WARNING:  StatReload detected changes in 'run.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for connections to close. (CTRL+C to force quit)
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [11992]
Process SpawnProcess-2:
Traceback (most recent call last):
  File "C:\Users\marcoquin\AppData\Local\anaconda3\envs\gradio_bug_311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marcoquin\AppData\Local\anaconda3\envs\gradio_bug_311\Lib\asyncio\base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\marcoquin\AppData\Local\anaconda3\envs\gradio_bug_311\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\marcoquin\AppData\Local\anaconda3\envs\gradio_bug_311\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\marcoquin\AppData\Local\anaconda3\envs\gradio_bug_311\Lib\site-packages\uvicorn\_subprocess.py", line 78, in subprocess_started
    target(sockets=sockets)
  File "C:\Users\marcoquin\AppData\Local\anaconda3\envs\gradio_bug_311\Lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marcoquin\AppData\Local\anaconda3\envs\gradio_bug_311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\marcoquin\AppData\Local\anaconda3\envs\gradio_bug_311\Lib\asyncio\runners.py", line 123, in run
    raise KeyboardInterrupt()
KeyboardInterrupt
INFO:     Started server process [21836]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
```

**Comment by ngaudemet** [comment] 2024-04-21 18:28
Hi @freddyaboulton @marcoquin, I encounter exactly the same issue. 

with gradio 4.24.0, the iframes load perfectly
with gradio 4.25.0 up to 4.27.0, they do not anymore

<img width="1436" alt="image" src="https://github.com/gradio-app/gradio/assets/126974970/64a32a4e-e354-42d5-aa45-0731f4bc3ff3">

you can see the network and console logs of the navigator with a lot of resources that are 'en attente' (= 'pending')
My computer is a MacBook Pro, and the bug appears on Edge, Chrome and Safari. I also tried on an Azure / Linux web app with exactly the same issue.

here is the repro code I used (more packed than the one of @marcoquin, but with the same requirements). 

```import uvicorn
import gradio as gr
from fastapi import FastAPI, Request
from fastapi.responses import HTMLResponse


with gr.Blocks() as io_1:
    title = gr.Markdown("1")
with gr.Blocks() as io_2:
    title = gr.Markdown("2")
with gr.Blocks() as io_3:
    title = gr.Markdown("3")
with gr.Blocks() as io_4:
    title = gr.Markdown("4")
with gr.Blocks() as io_5:
    title = gr.Markdown("5")
with gr.Blocks() as io_6:
    title = gr.Markdown("6")
with gr.Blocks() as io_7:
    title = gr.Markdown("7")
with gr.Blocks() as io_8:
    title = gr.Markdown("8")
with gr.Blocks() as io_9:
    title = gr.Markdown("9")
with gr.Blocks() as io_10:
    title = gr.Markdown("10")

html_front = """<!DOCTYPE html>
<head>
    <meta charset="UTF-8">
</head>
<body class = "light-body">

    <div class="iframe-container">
        <iframe id="1" src="/1/"  style="display:block;" ></iframe>
        <iframe id="2" src="/2/" style="display:block;"></iframe>
        <iframe id="3" src="/3/" style="display:block;"></iframe>
        <iframe id="4" src="/4/" style="display:block;"></iframe>
        <iframe id="5" src="/5/" style="display:block;"></iframe>
        <iframe id="6" src="/6/" style="display:block;"></iframe>
        <iframe id="7" src="/7/" style="display:block;"></iframe>
        <iframe id="8" src="/8/" style="display:block;"></iframe>
        <iframe id="9" src="/9/" style="display:block;"></iframe>
        <iframe id="10" src="/10/" style="display:block;"></iframe>
    </div> 

</body>
</html>"""


app = FastAPI()


@app.get("/")
async def get_home(request: Request):
    response = HTMLResponse(html_front)
    return response


io_1_page = gr.mount_gradio_app(app=app, blocks=io_1, path="/1")
io_2_page = gr.mount_gradio_app(app=app, blocks=io_2, path="/2")
io_3_page = gr.mount_gradio_app(app=app, blocks=io_3, path="/3")
io_4_page = gr.mount_gradio_app(app=app, blocks=io_4, path="/4")
io_5_page = gr.mount_gradio_app(app=app, blocks=io_5, path="/5")
io_6_page = gr.mount_gradio_app(app=app, blocks=io_6, path="/6")
io_7_page = gr.mount_gradio_app(app=app, blocks=io_7, path="/7")
io_8_page = gr.mount_gradio_app(app=app, blocks=io_8, path="/8")
io_9_page = gr.mount_gradio_app(app=app, blocks=io_9, path="/9")
io_10_page = gr.mount_gradio_app(app=app, blocks=io_10, path="/10")

if __name__ == "__main__":
    uvicorn.run(app)
```

Also @freddyaboulton , in my understanding, the setting of https://huggingface.co/spaces/gradio-pr-deploys/pr-8026-all-demos is very different. In the setting you shared, there is one iframe, the html loads one iframe at a time.
As a result, each time you click on a button to switch to another demo, it takes a few second to load. 
The setting of @marcoquin is different because it loads all the iframes at the same time. 
This worked perfectly up to gradio=4.24.0, and it doesn't anymore, which is a blocking issue when you want to combine more than 4 demos and not have to wait seconds to switch from one to another.

As the bug appears when there are more than 4 simultaneous iframes, I believe there might be an efficiency issue with gradio=4.25.0 and following. Maybe @freddyaboulton that your compute has more CPU and memory, which may explain why you couldn't reproduce it. Maybe if you try 20 simultaneous mounted iframes, you could observe it. 

Hope this helps and congrats for gradio!

**Comment by freddyaboulton** [comment] 2024-04-23 14:34
Ok I know the issue. Gradio establishes a persistent connection in order to known when it's safe to clean up state variables. Chrome is limiting the number of such connections to 5/6.

**Comment by ngaudemet** [comment] 2024-04-23 14:42
great, thank you @freddyaboulton.
The problem is not specific to chrome as I also have the issue with Safari and Edge.

**Comment by gnoynait** [comment] 2024-04-28 05:57
I ran into the same issue. I had 5 tabs open in Chrome, and when I tried to open a sixth tab, it would freeze. However, with the 5 tabs still open in Chrome, I could open another 5 tabs in Safari without any issues. So, I suppose this problem won't restrict my app to just 5 users, but rather to as many users as long as they keep fewer than 6 tabs open in the same browser. Does that sound right? @freddyaboulton

**Comment by freddyaboulton** [comment] 2024-04-29 15:05
Yea the issue is that browsers limit the number of concurrent HTTP requests of a given type to a URL to 5 or 6. Gradio connects to a `/heartbeat` url when you open the tab. So if you open 5 tabs at the same time, the 6th one will lock up. But the number of browsers that can connect to the server is not limited to 5.

**Comment by ngaudemet** [comment] 2024-04-30 07:23
Hi @freddyaboulton, I saw that you propose not to connect to the heartbeat if gr.State is unused. But if your apps all use gr.State, you would still get the limitation.
Do you thing it would be possible, if you want to have more than six  iframes with more than six gradio apps running wich are mounted on the same url, to have a specific heartbeat route for each, like mounted_path/heartbeat or name_of_the_app-heartbeat? Would it solve the iframe issue?
Thanks a lot !

**Comment by freddyaboulton** [comment] 2024-05-01 14:30
Hi @ngaudemet ! No that unfortunately would not fix it. Each iframe is already connecting to a different route (`/heartbeat/<unique-hash>`). I'm still thinking about how to display an error message when the 6th+ connection can't be made but that will probably come after that pr is merged.

**Closed** 2024-05-03 17:36 UTC
Labels: bug, pending clarification

**Comment by snakeninny** [comment] 2024-10-13 05:58
I have found the same issue yesterday when I upgraded to 5.0.2; it was alright using 4.20. I have to use `gr.State()`, and sometimes users open more than 5 pages at the same time. Do you have any suggestions of best practice? Thank you! @freddyaboulton

**Comment by freddyaboulton** [comment] 2024-10-14 23:52
Hi @snakeninny - your page can handle more than 5 concurrent users. But one user can't open the page more than 5 times **per browser**. It's a browser limitation that we can't do anything about. But I guess if a user really needs to open a bunch of simultaneous tabs, they can do so across chromium/chrome/firefox etc?

**Comment by snakeninny** [comment] 2024-10-15 00:24
> one user can't open the page more than 5 times **per browser**. It's a browser limitation that we can't do anything about

But why more than 5 pages doable in version 4.20? @freddyaboulton

**Comment by freddyaboulton** [comment] 2024-10-15 00:43
Because we added a persistent connection to check when a user disconnects. This lets us clean up stale `gr.State` variables

**Comment by snakeninny** [comment] 2024-10-15 01:02
I see, will try to find a workaround. Thank you again!
