### ISSUE TITLE
Texbox Empty

### ISSUE THREAD

**Issue by skissy** [gradio-app/gradio#7076] opened 2024-01-19 03:43 UTC
I have searched to see if a similar issue already exists.
How do I disable a text box from submitting when its content is empty? 
Unfortunately, my front-end knowledge sucks. Does this issue need to be modified on the front end?
![image](https://github.com/gradio-app/gradio/assets/48723937/eb62d268-472f-4601-a612-077ef8201b7f)

**Comment by freddyaboulton** [comment] 2024-01-19 16:19
Hi @skissy !

We're currently working on building a dedicated API for this but in the mean time you can raise an error from your function if the text is empty.

```python
def function(text):
    if not text:
        raise gr.Error("Text can't be empty.")
    ....

text.submit(function, ...)
#also raise error on button click
btn.click(function, ...)
```

**Comment by freddyaboulton** [comment] 2024-01-19 16:20
Gonna close as this is a dupe of https://github.com/gradio-app/gradio/issues/2718

**Closed** 2024-01-19 16:21 UTC

**Comment by skissy** [comment] 2024-02-01 08:47
ok, thankyou.

**Comment by skissy** [comment] 2024-02-01 08:49
> Hi @skissy !
> 
> We're currently working on building a dedicated API for this but in the mean time you can raise an error from your function if the text is empty.
> 
> ```python
> def function(text):
>     if not text:
>         raise gr.Error("Text can't be empty.")
>     ....
> 
> text.submit(function, ...)
> #also raise error on button click
> btn.click(function, ...)
> ```

ok,I get it, thank you !
