### ISSUE TITLE
share=False ignored when using 0.0.0.0 as server_name inside Docker

### ISSUE THREAD

**Issue by ividal** [gradio-app/gradio#159] opened 2021-04-21 20:28 UTC
I'm running Gradio inside a Docker container on my own server and followed [this advice](https://github.com/gradio-app/gradio/issues/24#issuecomment-658129710) to use server_name="0.0.0.0" tp make it work.

I do not want an external URL, so I use `launch(..., share=False)`. However, this is ignored and the public URL is still generated.

It seems this is due to [this override](https://github.com/gradio-app/gradio/blob/7828c660e6597413d916588dedd2eb5715405d79/gradio/interface.py#L414), as requests.head will return an Error 502 for 0.0.0.0.

Is there any other way to allow one to use localhost inside a Docker container without a public URL being generated?

Thank you!

**Comment by abidlabs** [comment] 2021-04-21 20:34
Hmm, this shouldn't be happening. Let us look into it.

**Comment by abidlabs** [comment] 2021-04-23 20:35
Hi @ividal I'm not getting this error: see below

![image](https://user-images.githubusercontent.com/1778297/115927003-5e80cf80-a449-11eb-9804-b25950623087.png)

I think it might be that 0.0.0.0 isn't configured correct on your docker container and it may be inaccessible.

**Comment by ividal** [comment] 2021-04-27 18:09
Hi @abidlabs, 

Thanks for looking into it. Not sure about 0.0.0.0 not being configured: other services running inside that container (e.g. a jupyter notebook) are accessible from the outside.

Quick question on your screenshot: were you running that inside a docker container?

Thanks again!

**Comment by abidlabs** [comment] 2021-04-29 18:17
Hi @ividal yes, I was running that inside a docker container on an Ubuntu 18.04 machine. Since we cannot reproduce the issue, I will go ahead and close the issue. 

But I will suggest to you to fork the repo and remove the override and see if it works for you. You can install your forked version of Gradio using this strategy (https://stackoverflow.com/questions/20101834/pip-install-from-git-repo-branch).

**Closed by abidlabs** 2021-04-29 18:17 UTC

**Comment by abidlabs** [comment] 2021-04-29 18:54
Thanks for sharing @ividal!
