### ISSUE TITLE
The window is strange

### ISSUE THREAD

**Issue by 459737087** [gradio-app/gradio#3458] opened 2023-03-14 06:54 UTC
### Describe the bug

when I start gradio ,and it showed in the google , 
![image](https://user-images.githubusercontent.com/54131759/224919083-b098b2a1-e011-4f0e-bf18-179cc3021b86.png)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
import gradio as gr
import os
import torch
import cv2
from basicsr.archs.rrdbnet_arch import RRDBNet

from realesrgan import RealESRGANer
from realesrgan.archs.srvgg_arch import SRVGGNetCompact


def combine(a, b):
    return a + " " + b
 
def mirror(x):
    return x

    
with gr.Blocks() as demo:
    with gr.Row():
        im = gr.Image()
        im_2 = gr.Image()
    
    btn = gr.Button(value="预测图片")
    btn.click(mirror, inputs=[im], outputs=[im_2])

if __name__ == "__main__":
    demo.launch(server_name='127.0.0.1', server_port=8080, show_error=True)
```

### Logs

```shell
When I click it , 
Something went wrong
Unexpected token '<', "<!doctype "... is not valid JSON
```

### System Info

```shell
gradio 3.21.0
ubuntu 20.0
pytorch 1.10
```

### Severity

annoying

**Comment by 459737087** [comment] 2023-03-14 09:38
fine , degrade 3.20.0 , it worked ,But I don't know why

**Comment by abidlabs** [comment] 2023-03-14 16:05
Hi @459737087 I can't reproduce this issue. I ran your code: https://colab.research.google.com/drive/1mYqqtD8zBzkVrRtT26XHcM_4eGEmXz4V#scrollTo=oBL4B5143YKv

And got this:

<img width="840" alt="image" src="https://user-images.githubusercontent.com/1778297/225065905-b2f86aa1-0ce0-453c-acd9-27f9ab7cc855.png">

Could you share a Colab notebook with me with this error?

**Comment by 459737087** [comment] 2023-03-15 03:09
hi @abidlabs  you can upgrade your gradio version to 3.21.0,and this status will appear.

**Comment by abidlabs** [comment] 2023-03-15 03:29
Hi @459737087 this is actually using `gradio==3.21`, I've printed the gradio version in the Colab notebook above

**Comment by 459737087** [comment] 2023-03-15 06:31
I see , the environment is python 3.8.12 , the colab python is 3.9 .
maybe it is the key

**Comment by abidlabs** [comment] 2023-03-15 13:32
Hi @459737087 I don't think that should make a difference. This sounds like somehow the javascripts is not being rendered correctly. I would try clearing your javascript cache, doing a hard refresh, or if need be, uninstalling and reinstalling Gradio to see if that fixes it.

In the meantime, I'll close this issue as we are not able to reproduce. Feel free to reopen if you have any more details.

**Closed by abidlabs** 2023-03-15 13:32 UTC
Labels: needs repro

**Comment by 459737087** [comment] 2023-03-16 04:53
fine

**Comment by jbmaxwell** [comment] 2023-09-27 02:53
Did you manage to resolve this? I'm having the same issue.

**Comment by 459737087** [comment] 2023-09-27 02:59
> Did you manage to resolve this? I'm having the same issue.

degrade your gradio version

**Comment by jbmaxwell** [comment] 2023-09-27 03:32
Sadly, for me that just created a new error about "theme"... can't remember exactly, but I think it just didn't recognize that argument. I'm going to see about not embedding it in an iframe in my context... we'll see
