### ISSUE TITLE
Can't use gradio_client with gr.Blocks (Chatbot component)

### ISSUE THREAD

**Issue by ericbellet** [gradio-app/gradio#5108] opened 2023-08-05 11:07 UTC
### Describe the bug

My goal is to do HTTP requests to my Gradio Server like is mentioned here https://www.gradio.app/guides/getting-started-with-the-python-client, but this last link works with Interfaces but not with Blocks.

I'm trying to call the API to a chatbot I've created with Gradio library. When I check the API documents in gradio-client, it shows that I had to pass a str representing filepath to JSON file in 'parameter_11' Chatbot component
```
from gradio_client import Client

client = Client("https://c88f6cc8edfb2f573b.gradio.live/")
result = client.predict(
                "Howdy!",   # str representing string value in 'parameter_12' Textbox component
                "?????", # str representing filepath to JSON file in 'parameter_11' Chatbot component
                api_name="/chat"
)
print(result)
```

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

What does the JSON file of Gradio Chatbot look like? Can I get an example of using Gradio Chatbot through API? Here is the code to generate the chatbot in Gradio using gr.Blocks() and gr.Chatbot():
```
import gradio as gr
import random
import time

with gr.Blocks() as demo:
    chatbot = gr.Chatbot()
    msg = gr.Textbox()
    clear = gr.Button("Clear")

    def user(user_message, history):
        return "", history + [[user_message, None]]

    def bot(history):
        bot_message = random.choice(["Yes", "No"])
        history[-1][1] = bot_message
        time.sleep(1)
        return history

    msg.submit(user, [msg, chatbot], [msg, chatbot], queue=False, api_name="ask").then(
        bot, chatbot, chatbot
    )
    clear.click(lambda: None, None, chatbot, queue=False, api_name="clear")

if __name__ == "__main__":
    demo.launch(share=True)
```
Here you can test it locally:
```
from gradio_client import Client
import gradio as gr

client = Client("http://localhost:7860")
print(client.view_api())
print(client.predict("Hello", ?????, api_name="/ask"))
```

### System Info

```shell
gradio 3.39.0
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment] 2023-08-06 19:25
Hi @ericbellet ! Thank you for filing this issue. We'll make working with chatbots via API a lot easier soon.

The demo you've chosen is not the best example because the usage `then` makes it a bit more complicated. Hitting the `ask` endpoint doesn't make the bot respond, it just adds the user message to the chatbot. This was done so that the user message shows up instantly in the UI.

I would do the following in this use case:
1. Add an api_name to the `then` event, called `"respond"`
2. Set `serialize=False` in the client so you don't have to deal with files. In general, the chatbot state is a list of tuples of the form `[[user message, bot message], [user message, bot message], ...]`. By default, the client will expect a json file with an object of that structure but it's easier to just use a raw string. This is something we'll fix soon.

So the code would look like this:

```python
import gradio as gr
import random
import time

with gr.Blocks() as demo:
    chatbot = gr.Chatbot()
    msg = gr.Textbox()
    clear = gr.Button("Clear")

    def user(user_message, history):
        return "", history + [[user_message, None]]

    def bot(history):
        bot_message = random.choice(["How are you?", "I love you", "I'm very hungry"])
        time.sleep(2)
        history[-1][1] = bot_message
        return history

    msg.submit(user, [msg, chatbot], [msg, chatbot], queue=False).then(
        bot, chatbot, chatbot, api_name="respond"
    )
    clear.click(lambda: None, None, chatbot, queue=False)
    
if __name__ == "__main__":
    demo.launch()
```

And then the client code would look like this:

```python
import gradio_client as grc
client = grc.Client("http://127.0.0.1:7861", serialize=False)
# Use None as a placeholder for the bot response
client.predict([["Hello", None]], api_name="/respond")
# Result: [['Hello', 'I love you']]
# Replace None with the bot response, and add the next message
client.predict([["Hello", "I love you"], ["I love you too", None]], api_name="/respond")
# Result: ['Hello', 'I love you'], ['I love you too', "I'm very hungry"]]
```

Going to close this out since it's not a bug with gradio but will file another but will work on https://github.com/gradio-app/gradio/issues/4386 to improve this in the future.

**Closed by freddyaboulton** 2023-08-06 19:25 UTC
Labels: bug

**Comment by freddyaboulton** [comment] 2023-08-06 19:30
BTW, the easiest way to use the demo via chatbot is if the demo uses `gr.ChatInterface`. That has a super simple string-in, string-out api signature.
