### ISSUE TITLE
Frozen Gradio Image Update

### ISSUE THREAD

**Issue by smamindl** [gradio-app/gradio#5142] opened 2023-08-09 01:37 UTC
Hi @abidlabs @freddyaboulton 

I have the following code snippet which is taken from your demo examples. The code runs fine locally. However, when we run it in a GCP or OCI server with public IP, it freezes after a couple of seconds and then we need to stop and start again. could you please help me with this? Thanks.

```
import gradio as gr
import numpy as np
import time

# define core fn, which returns a generator {steps} times before returning the image
def fake_diffusion(steps):
    for _ in range(steps):
        time.sleep(0.1)
        image = np.random.random((600, 600, 3))
        yield image
    image = "https://gradio-builds.s3.amazonaws.com/diffusion_image/cute_dog.jpg"
    yield image


demo = gr.Interface(fake_diffusion, inputs=gr.Slider(1, 10000, 5000), outputs="image")

# define queue - required for generators
demo.queue()

demo.launch()
```

**Comment by freddyaboulton** [comment] 2023-08-09 19:58
This looks like a dupe of #5145 ? Will close but anyone can reopen if I'm incorrect

**Closed by freddyaboulton** 2023-08-09 19:58 UTC
Labels: bug, cloud
