### ISSUE TITLE
How does it work on devices that can't connect to the Internet

### ISSUE THREAD

**Issue by szj2ys** [gradio-app/gradio#3910] opened 2023-04-19 10:20 UTC
- [ ] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

**Describe the solution you'd like**  

**Additional context**  

When I first deployed gradio on a server without a network, the following error occurred. 
```
host='api.gradio.app', port=443): Max retries exceeded with url: /gradio-launched-telemetry/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000230FE147400>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')
```
But my server cannot connect to the Internet. How can I solve it

**Comment by freddyaboulton** [comment] 2023-04-20 14:33
What version are you using? Not being able to send telemetry should not cause the demo to run.

You can also block telemetry with `gr.Blocks(analytics_enabled=False)`

**Comment by freddyaboulton** [comment] 2023-04-20 19:17
Going to close as this is a dupe of #1450. Thanks @szj2ys !

**Closed by freddyaboulton** 2023-04-20 19:17 UTC
