### ISSUE TITLE
GPU Input Batching

### ISSUE THREAD

**Issue by FarukOzderim** [gradio-app/gradio#1597] opened 2022-06-17 16:38 UTC
- [X] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
GPUs can process multiple ML inputs at the same time, which can be many times faster instead of running them one by one. (Could not find the correct term for this, please LMK if you know it @osanseviero @abidlabs @cbensimon)

**Describe the solution you'd like**  
Let user explicitly state how many inputs s/he wants to process at the same time, and accumulate requests according to that.
Note that if there are a few requests incoming, we can have a time limit and send the arrived requests even if we don't reach to the parallel_input count. 
Implementation will probably to send `parallel_input_count` many arguments to the related function.

**Additional context**  
Possible related to #572

**Comment by apolinario** [comment] 2022-07-22 18:26
Two questions on this issue: 
1. Is it part of the current queue refactoring effort? https://github.com/gradio-app/gradio/pull/1489 
2. Do this idea also support multiple GPUs? So if a Space has two GPUs assigned to it, the requests could be distributed across GPUs as well as parallelized on the same GPU as it's the original idea of the issue is. So Spaces that have multiple GPUs assigned to them actually benefit from this parallelization. Is it part of this idea? 

If not, I think it should potentially be, however, since GPU allocation is not automatic - there should be a way that the users can programmatically say that for every trigger in the "run" function, a different variable is set (that for example can be `cuda:0` or `cuda:1`)

**Comment by apolinario** [comment] 2022-07-22 19:17
Also, this parallelization (on the same GPU) is already kind of possible if `enable_queue` is `False`. Because each CPU thread can call the GPU independently, two or more threads can effectively run GPU code as long as there's enough VRAM and compute power; which made me create this issue: https://github.com/gradio-app/gradio/issues/1864

**Comment by FarukOzderim** [comment] 2022-07-22 20:59
No, this is not included in the new queue design. It is about processing several number of user-inputs in GPU at the same time. Multiple-GPU sounds like a great idea, but management will be probably hard. Yet you can still create a brainstorming issue around it 😸

**Comment by pcuenca** [comment] 2022-08-08 15:37
I was discussing the same thing with @freddyaboulton today and he pointed me to this issue. This is something we did manually for dalle-mini, and I think it would be useful for viral spaces if it could be generalized. The implementation outlined above (wait for max parallel requests or timeout threshold) sounds good to me!

**Closed** 2022-10-24 23:33 UTC
Labels: enhancement
