### ISSUE TITLE
File.update produces very large text

### ISSUE THREAD

**Issue by duerrsimon** [gradio-app/gradio#1545] opened 2022-06-11 20:52 UTC
### Describe the bug

If I update a gr.File component with a file, the text is extremly large `text-4xl`. Should be smaller. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Setup:
`
all_probs = gr.File(visible=False)`

in my update function: 
```
def update():
    return gr.File.update(value="all_probs_concat.csv", visible=True)
```

### Screenshot

![image](https://user-images.githubusercontent.com/16979577/173204513-1d4a1097-5b94-4cd1-92e4-675102c7b846.png)

### Logs

```shell
No logs
```

### System Info

```shell
gradio >3.0.11
```

### Severity

annoying

**Comment by aliabid94** [comment] 2022-06-13 23:14
Hmm will look into this. Truncating with ellipses might be the best solution here.

**Comment by dawoodkhan82** [comment] 2022-08-01 20:24
@duerrsimon Cannot reproduce this issue. Perhaps it was resolved by another PR. Can you confirm?

**Comment by duerrsimon** [comment] 2022-08-03 22:04
Indeed seems like this was fixed. The offending CSS was `file-name w-3/5 text-4xl p-6 break-all` which I don't find in the main branch anymore.

**Comment by abidlabs** [comment] 2022-08-03 22:10
Awesome, thanks for clarifying!

**Closed by abidlabs** 2022-08-03 22:10 UTC
Labels: bug, good first issue, frontend
