### ISSUE TITLE
gr.Image(label='Image Input', type='pil', tool='sketch', source="upload") doesn't support example input from both image and mask.

### ISSUE THREAD

**Issue by xingqian2018** [gradio-app/gradio#3110] opened 2023-02-01 17:13 UTC
I am trying to create an interface with masked image input and prepare some convenience examples, but it looks like Gradio doesn't support it.
```
import gradio as gr

with gr.Blocks() as demo:
    input_gallary = gr.Image(label='Image Input', type='pil', tool='sketch', source="upload")
    output_gallary = gr.Gallery(label="Image Result").style()

    gr.Examples(
        label='Examples',
        examples=[{'image' : 'image.png', 'mask' : 'mask.png'}],
        fn=lambda x:x,
        inputs=[input_gallary],
        outputs=[output_gallary],
        cache_examples=False, )

demo.launch(share=True)
```

Error message:
```
Exception has occurred: ValueError
Cannot process this value as an Image
```

I also try to hack through `gr.Images` with customized `postprocess()` function, but some other unrelated error shows up.

```
import gradio as gr

class Customized_Image_Block(gr.Image):
    def postprocess(self, y):
        from gradio import processing_utils
        from PIL import Image as _Image
        from pathlib import Path
        import numpy as np
        if y is None:
            return None
        if isinstance(y, np.ndarray):
            return processing_utils.encode_array_to_base64(y)
        elif isinstance(y, dict):
            return processing_utils.encode_url_or_file_to_base64(y['image'])
        elif isinstance(y, _Image.Image):
            return processing_utils.encode_pil_to_base64(y)
        elif isinstance(y, (str, Path)):
            return processing_utils.encode_url_or_file_to_base64(y)
        else:
            raise ValueError("Cannot process this value as an Image")

with gr.Blocks() as demo:
    input_gallary = Customized_Image_Block(label='Image Input', type='pil', tool='sketch', source="upload")
    output_gallary = gr.Gallery(label="Image Result").style()

    gr.Examples(
        label='Examples',
        examples=[{'image' : 'image.png', 'mask' : 'mask.png'}],
        fn=lambda x:x,
        inputs=[input_gallary],
        outputs=[output_gallary],
        cache_examples=False, )

demo.launch(share=True)
```

Error message:

```
Exception has occurred: AttributeError
'Dataset' object has no attribute 'headers'
```

**Comment by pngwn** [comment] 2023-02-18 21:47
This is a duplicate of #2314. This isn't specific to examples, it is just that you can't load a mask for images right now.

**Closed** 2023-11-18 23:42 UTC
Labels: enhancement, 🖼️ image
