### ISSUE TITLE
downloading file from /tmp fails

### ISSUE THREAD

**Issue by hashefa** [gradio-app/gradio#3688] opened 2023-03-29 08:42 UTC
### Describe the bug

I'm trying to download a file that is being saved in a downloadDirectory = tempfile.mkdtemp()
The file exist as far as I understand, but I'm unable to download it, this is the error that raises:

ValueError: File cannot be fetched: /tmp/62800e12341e28a12d06542d8cfa6bcfbb7b1799/1329-subs.srt. All files must contained within the Gradio python app working directory, or be a temp file created by the Gradio python app.

The app is mounted using mount_gradio_app().

Thanks.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Complicated for me to share a working code to reproduce, as it has many dependencies. 

### Logs

```shell
/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "/usr/local/lib/python3.10/site-packages/gradio/routes.py", line 337, in file
    raise ValueError(
ValueError: File cannot be fetched: /tmp/62800e12341e28a12d06542d8cfa6bcfbb7b1799/1329_1329_1wav-subs.srt. All files must contained within the Gradio python app working directory, or be a temp file created by the Gradio python app.
```

### System Info

```shell
gradio-3.23.0
```

### Severity

annoying

**Comment by freddyaboulton** [comment] 2023-03-29 09:45
Hi @hashefa ! Do you have the full code to reproduce?

**Comment by hashefa** [comment] 2023-03-29 09:52
> Hi @hashefa ! Do you have the full code to reproduce?

Hi, thanks for the fast response. 
As I wrote, it's a little bit difficult to share the code, because it has many dependencies. 
What I can tell is that the code was running perfectly when I was running locally using demo.lunch(), but using mount_gradio_app() raises the problem.

**Comment by hashefa** [comment] 2023-03-29 10:12
> Ah sorry I didn’t read that bit about being difficult to share all the code. It will be harder to find the root cause without a repro.
> 
> Just to be sure, if you’re mounting the gradio app at /gradio, for example, you’re sending a get request to /gradio/file=/tmp/…?

right

**Comment by freddyaboulton** [comment] 2023-03-31 19:25
I'm having a hard time reproducing this @hashefa ! Any details would be appreciated

This demo is working fine for me:

```python
from fastapi import FastAPI
import gradio as gr
from zipfile import ZipFile
import tempfile
import pathlib


directory = tempfile.mkdtemp(dir="./")
print(directory)

CUSTOM_PATH = "/gradio"

app = FastAPI()


@app.get("/")
def read_main():
    return {"message": "This is your main app"}

def zip_files(files):
    with ZipFile(pathlib.Path(directory) / "tmp.zip", "w") as zipObj:
        for idx, file in enumerate(files):
            zipObj.write(file.name, file.name.split("/")[-1])
    return pathlib.Path(directory) / "tmp.zip"

demo = gr.Interface(
    zip_files,
    gr.File(file_count="multiple", file_types=["text", ".json", ".csv", "image"]),
    "file",
)


app = gr.mount_gradio_app(app, demo, path=CUSTOM_PATH)
```
![download_file](https://user-images.githubusercontent.com/41651716/229211325-f42d610e-fa28-426a-8cb2-c0ce88813ca2.gif)

**Comment by abidlabs** [comment] 2023-04-04 13:48
Closing for now since we cannot reproduce. @hashefa feel free to reopen once you have a repro that you can share.

**Closed by abidlabs** 2023-04-04 13:48 UTC
Labels: bug, needs repro
