### ISSUE TITLE
Can't add newline when using Highlighted Context

### ISSUE THREAD

**Issue by dyxohjl666** [gradio-app/gradio#1839] opened 2022-07-20 02:42 UTC
The newlines don’t seem to work when I try to split the multiple results. I realized it maybe due to escaping but have no idea how to solve the problem.
What can I do for that?  Or I have to switch to a html output?

**Comment by aliabid94** [comment] 2022-07-20 10:49
Thanks for letting us know about this. Will take a look!

**Comment by aliabid94** [comment] 2022-07-20 11:02
Let me know if this works for you, or if you have any questions!

**Comment by dyxohjl666** [comment] 2022-07-20 15:35
Thanks for your reply! 
It looks quite perfect now when I apply a single Interface component.
But I met the same problem when add the Interface into TabbedInterface. It seems like that the CSS is invalid when in TabbedInterface. I'm confused about that.

**Comment by dyxohjl666** [comment] 2022-07-20 15:37
I generate the Interface like this:
```
import gradio as gr

parse_str = gr.Interface(
    fn=pred_str,
    inputs=gr.Textbox(
        label="String",
        lines=5,
    ),
    outputs=gr.HighlightedText(
        label="The Result of Parsing",
        combine_adjacent=True,
        adjacent_separator=" ",
    )
)

parse_file = gr.Interface(
    fn=pred_file,
    inputs="file",
    outputs=gr.HighlightedText(
        elem_id="htext",
        label="The Result of Parsing",
        combine_adjacent=True,
        adjacent_separator=" ",
    ),
    css="#htext span {white-space: pre-line}",
)
demo = gr.TabbedInterface([parse_str, parse_file], ["Parsing reference string", "Parsing reference for PDF"])

parse_file.launch(share=True)
```

**Comment by aliabid94** [comment] 2022-07-20 22:41
Ahh hmm seems like a bug where custom CSS isn't passed up in a TabbedInterface. @abidlabs can you take a look?

**Comment by freddyaboulton** [comment] 2022-08-01 14:58
This is a dupe of #1683. Going to keep both open so as to not lose all the discussion and add to 3.2 milestone.

**Closed** 2022-08-05 01:47 UTC
Labels: bug

**Comment by HuangChiEn** [comment] 2022-08-05 09:41
> Hi @dyxohjl666, this is now fixed. See #1951 for more information, but the summary is that you will have to pass in a `css` parameter to `TabbedInterface` with your desired css, like this:
> 
> ```python
> import gradio as gr
> 
> def test(text1):
>     return [(text1, "good"), ("\n", None), (text1, "good")]
> 
> demo = gr.Interface(
>     test,
>     "text",
>     gr.HighlightedText(elem_id="htext"),
> )
> 
> def test(text1):
>     return [(text1, "good"), ("\n", None), (text1, "good")]
> 
> demo2 = gr.Interface(
>     test,
>     "text",
>     gr.HighlightedText(elem_id="htext2"),
> )
> 
> gr.TabbedInterface([demo, demo2], css="#htext span {white-space: pre} #htext2 span {white-space: pre}").launch()
> ```
Thanks for your quickly reply.
yes, I think this may be the solution in this case. However, the CSS argument is not supported in gradio==3.1.3 version.

![image](https://user-images.githubusercontent.com/52521165/183049918-f885a807-e1da-43cf-bfa3-e3b3150b7f9d.png)

**Comment by dyxohjl666** [comment] 2022-08-11 04:36
It works well now ! Thanks a lot!

**Comment by emptystack1024** [comment] 2024-06-04 03:18
Hi, my version of gradio is 4.32.0, and when I run your code above, the implementation is still the same as my question #8425, operations on the second tab still feed back into the first tab, and the second tab still doesn't get any output.
![2024-06-04 11-05-19](https://github.com/gradio-app/gradio/assets/104486691/b8f8f368-581b-4f06-ac1b-3e0f374e1f30)

**Comment by emptystack1024** [comment] 2024-06-10 07:27
> 你好，我的 gradio 版本是 4.32.0，当我运行上面的代码时，实现仍然与我的问题#8425相同，第二个选项卡上的操作仍然反馈到第一个选项卡，而第二个选项卡仍然没有得到任何输出。 ![2024-06-04 11-05-19](https://private-user-images.githubusercontent.com/104486691/336293043-b8f8f368-581b-4f06-ac1b-3e0f374e1f30.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMDQ1NDcsIm5iZiI6MTcxODAwNDI0NywicGF0aCI6Ii8xMDQ0ODY2OTEvMzM2MjkzMDQzLWI4ZjhmMzY4LTU4MWItNGYwNi1hYzFiLTNlMGYzNzRlMWYzMC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMFQwNzI0MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YmY3NzgzZTQyNzNjNTA0N2ZkYWFiOGI3OTEwNDE2NzczMjg4MDQzMWE2ODY4Yzg2NjY3MzNkMDJlMDE4ZTk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.q4_W9SURhoAHuEwKQTKmu_F01-zBZ6PEXTtyWlk1t_8) [ ![2024-06-04 11-05-19](https://private-user-images.githubusercontent.com/104486691/336293043-b8f8f368-581b-4f06-ac1b-3e0f374e1f30.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMDQ1NDcsIm5iZiI6MTcxODAwNDI0NywicGF0aCI6Ii8xMDQ0ODY2OTEvMzM2MjkzMDQzLWI4ZjhmMzY4LTU4MWItNGYwNi1hYzFiLTNlMGYzNzRlMWYzMC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMFQwNzI0MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YmY3NzgzZTQyNzNjNTA0N2ZkYWFiOGI3OTEwNDE2NzczMjg4MDQzMWE2ODY4Yzg2NjY3MzNkMDJlMDE4ZTk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.q4_W9SURhoAHuEwKQTKmu_F01-zBZ6PEXTtyWlk1t_8) ](https://private-user-images.githubusercontent.com/104486691/336293043-b8f8f368-581b-4f06-ac1b-3e0f374e1f30.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMDQ1NDcsIm5iZiI6MTcxODAwNDI0NywicGF0aCI6Ii8xMDQ0ODY2OTEvMzM2MjkzMDQzLWI4ZjhmMzY4LTU4MWItNGYwNi1hYzFiLTNlMGYzNzRlMWYzMC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMFQwNzI0MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YmY3NzgzZTQyNzNjNTA0N2ZkYWFiOGI3OTEwNDE2NzczMjg4MDQzMWE2ODY4Yzg2NjY3MzNkMDJlMDE4ZTk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.q4_W9SURhoAHuEwKQTKmu_F01-zBZ6PEXTtyWlk1t_8) [ ](https://private-user-images.githubusercontent.com/104486691/336293043-b8f8f368-581b-4f06-ac1b-3e0f374e1f30.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMDQ1NDcsIm5iZiI6MTcxODAwNDI0NywicGF0aCI6Ii8xMDQ0ODY2OTEvMzM2MjkzMDQzLWI4ZjhmMzY4LTU4MWItNGYwNi1hYzFiLTNlMGYzNzRlMWYzMC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMFQwNzI0MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YmY3NzgzZTQyNzNjNTA0N2ZkYWFiOGI3OTEwNDE2NzczMjg4MDQzMWE2ODY4Yzg2NjY3MzNkMDJlMDE4ZTk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.q4_W9SURhoAHuEwKQTKmu_F01-zBZ6PEXTtyWlk1t_8)

solution：
See also: https://github.com/gradio-app/gradio/issues/8425
Thanks, @ Phillweston 
The version that can be run is  4.31.5 version
