### ISSUE TITLE
When i want to use gr.change(...) in the gr.Tab() , it has a bug 

### ISSUE THREAD

**Issue by xxWeiDG** [gradio-app/gradio#5410] opened 2023-09-05 02:28 UTC
### Describe the bug

When I use radio.change in gr.Tab() it doesn't trigger the method in change()
![截图_20230905101832](https://github.com/gradio-app/gradio/assets/140797957/b79f3c7f-2f2c-4e4b-818f-f83708acc7f2)
![截图_20230905102730](https://github.com/gradio-app/gradio/assets/140797957/458dc639-af72-4f75-8b3f-abf9bd82803b)

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

![截图_20230905101534](https://github.com/gradio-app/gradio/assets/140797957/8a4ff896-1b83-4bd0-9109-e4826968c9a0)
![截图_20230905102730](https://github.com/gradio-app/gradio/assets/140797957/1867704d-6a61-45c3-8fca-3fbd8c9e3659)
![截图_20230905101832](https://github.com/gradio-app/gradio/assets/140797957/53461040-a110-4fcd-ac8d-3d5288768ab9)

### Screenshot

![截图_20230905101534](https://github.com/gradio-app/gradio/assets/140797957/02f47601-772e-4946-aadf-b6173aee435d)

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Windows
gradio version: 3.42.0
gradio_client version: 0.5.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.1.1
fastapi: 0.103.0
ffmpy: 0.3.1
gradio-client==0.5.0 is not installed.
httpx: 0.24.1
huggingface-hub: 0.16.4
importlib-resources: 6.0.1
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.7.2
numpy: 1.25.2
orjson: 3.9.5
packaging: 23.1
pandas: 2.1.0
pillow: 10.0.0
pydantic: 2.3.0
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
requests: 2.31.0
semantic-version: 2.10.0
typing-extensions: 4.7.1
uvicorn: 0.23.2
websockets: 11.0.3
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.6.0
httpx: 0.24.1
huggingface-hub: 0.16.4
packaging: 23.1
requests: 2.31.0
typing-extensions: 4.7.1
websockets: 11.0.3
```

### Severity

I can work around it

**Comment by abidlabs** [comment] 2023-09-05 15:02
Hi @xxWeiDG can you provide a self-contained example with this bug with correctly formatted code? I tried to reproduce but this is working for me on the latest version of `gradio`:

```py
import gradio as gr

with gr.Blocks() as demo:
    with gr.Tab("tab 1"):
        pass
    with gr.Tab("tab 2"):
        r1 = gr.Radio(["a", "b", "c"])
        r2 = gr.Radio(["a", "b", "c"])
        r1.change(lambda x:x, r1, r2)
        
demo.launch()
```

**Comment by xxWeiDG** [comment] 2023-09-07 00:42
> Hi @xxWeiDG can you provide a self-contained example with this bug with correctly formatted code? I tried to reproduce but this is working for me on the latest version of `gradio`:
> 
> ```python
> import gradio as gr
> 
> with gr.Blocks() as demo:
>     with gr.Tab("tab 1"):
>         pass
>     with gr.Tab("tab 2"):
>         r1 = gr.Radio(["a", "b", "c"])
>         r2 = gr.Radio(["a", "b", "c"])
>         r1.change(lambda x:x, r1, r2)
>         
> demo.launch()
> ```

Hi,such as this demo ,it has a bug,hope you can help me

`import gradio as gr
with gr.Blocks() as demo:
    with gr.Tab('Test'):
        radio = gr.Radio([1, 2, 4], label="Set the value of the number")
        number = gr.Number(value=2, interactive=True)
        radio.change(fn=lambda value: gr.update(value=value), inputs=radio, outputs=number)
demo.queue().launch(server_name='0.0.0.0',server_port=12011, share=True,inbrowser=False,debug=True)`

**Comment by abidlabs** [comment] 2023-09-07 18:44
Hi @xxWeiDG your demo works fine for me:

```py
import gradio as gr

with gr.Blocks() as demo:
    with gr.Tab('Test'):
        radio = gr.Radio([1, 2, 4], label="Set the value of the number")
        number = gr.Number(value=2, interactive=True)
        radio.change(fn=lambda value: gr.update(value=value), inputs=radio, outputs=number)

demo.queue().launch()
```

GIF:

![Recording 2023-09-07 at 11 43 20](https://github.com/gradio-app/gradio/assets/1778297/ba81568d-1c71-42e7-a1e3-9fa4f624e80c)

Can you try on a Colab notebook and see if you still observe the same behavior? https://colab.google/

There might be something specific to your environment, but we are unable to reproduce. I'll go ahead and close the issue for now since there's nothing actionable for us. But please feel free to reopen if you can identify what may be different in the environment that you are running the gradio code.

**Closed by abidlabs** 2023-09-07 18:44 UTC
Labels: bug, needs repro
