### ISSUE TITLE
Separate `label` and `value` for all components with `choices`

### ISSUE THREAD

**Issue by apolinario** [gradio-app/gradio#5033] opened 2023-07-28 10:44 UTC
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Sometimes you don't want the options shown to the user on a `gr.Radio()`, `gr.Dropdown()`, `gr.Checkbox()`, etc. to be the same value sent to the functions. 

Not rarely users have to do ugly and long if elses in their processing functions to match the human readable label with the machine readable value in the processing functions.

**Describe the solution you'd like**  
Allow for a choices param to have two values, one for the label and one for the value passed to the function. Maybe as a tuple `(value, label)`? 

It could be optional, so if no tuple is set, the behavior is just like now (label and value are the same) 

Example API:
```py
gr.Radio(
    choices=[("runwayml/stable-diffusion-v1-5", "Stable Diffusion 1"), ("stabilityai/stable-diffusion-2-1", "Stable Diffusion 2"), "other"],
    label="Model"
)
```

**Comment by hysts** [comment] 2023-07-28 10:51
+1
related https://github.com/gradio-app/gradio/issues/3019

**Comment by abidlabs** [comment] 2023-07-28 14:33
Yeah we should add support for this. I'll take a look at this next week. Since this is a duplicate of #3019, I'll close @apolinario

**Closed by abidlabs** 2023-07-28 14:33 UTC
