### ISSUE TITLE
TypeError: Cannot set property WebSocket of #<Object> which has only a getter / Gradio App not working in NextJS

### ISSUE THREAD

**Issue by cantonalex** [gradio-app/gradio#6562] opened 2023-11-23 09:49 UTC
### Describe the bug

unsure why this was closed I still get the same issue on node 20 and nextjs 14 #5583 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

latest nextjs version

### System Info

```shell
node 20 nextjs 14 mac os sonoma
```

### Severity

Blocking usage of gradio

**Comment by cantonalex** [comment] 2023-11-23 09:51
@pngwn

**Comment by pngwn** [comment] 2023-11-23 20:20
No need to ping maintainers. We can see the issue and will get to it as soon as we can.

**Comment by SDLi416** [comment] 2024-01-09 01:58
I finally found a suitable solution. We should not use the gradio client on the server side of Next.js, but instead use it on the client side. Also, by adding the following configuration to next.config.js, I managed to solve the problem:

```
const {webpack} = require("next/dist/compiled/webpack/webpack");
/** @type {import('next').NextConfig} */
const nextConfig = {
    // output: 'export',
    // Optional: Add a trailing slash to all paths `/about` -> `/about/`
    // trailingSlash: true,
    // Optional: Change the output directory `out` -> `dist`
    // distDir: 'dist',
    webpack: (config, {isServer}) => {
        if (!isServer) {
            config.resolve = {
                ...config.resolve,
                fallback: {
                    // fixes proxy-agent dependencies
                    net: false,
                    dns: false,
                    tls: false,
                    assert: false,
                    // fixes next-i18next dependencies
                    path: false,
                    fs: false,
                    // fixes mapbox dependencies
                    events: false,
                    // fixes sentry dependencies
                    process: false
                }
            };
        }
        config.plugins.push(new webpack.NormalModuleReplacementPlugin(/node:/, (resource) => {
            resource.request = resource.request.replace(/^node:/, "");
        }))
        return config
    },
    experimental: {appDir: true}
};
module.exports = nextConfig
```

I hope this comment will help those using Next.js.

**Comment by jakiestfu** [comment] 2024-02-20 21:31
+1 to this issue, this is a huge blocker for me as my software depends on the gradio client to interface with my private spaces. The issue is somehow related to assigning `global.WebSocket = ws.WebSocket` 🤷

**Comment by pngwn** [comment] 2024-04-11 11:53
Duplicate of #5583

**Closed by pngwn** 2024-04-11 11:53 UTC
Labels: bug, gradio_client
