### ISSUE TITLE
Support more data in LinePlots

### ISSUE THREAD

**Issue by JeffersonQin** [gradio-app/gradio#7108] opened 2024-01-22 16:39 UTC
- [x] I have searched to see if a similar issue already exists.

```
Traceback (most recent call last):
  File "/users/server/venv/lib/python3.10/site-packages/gradio/queueing.py", line 489, in call_prediction
    output = await route_utils.call_process_api(
  File "/users/server/venv/lib/python3.10/site-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "/users/server/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1570, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/users/server/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1445, in postprocess_data
    prediction_value = postprocess_update_dict(
  File "/users/server/venv/lib/python3.10/site-packages/gradio/blocks.py", line 426, in postprocess_update_dict
    update_dict["value"] = block.postprocess(value)
  File "/users/server/venv/lib/python3.10/site-packages/gradio/components/line_plot.py", line 321, in postprocess
    return AltairPlotData(type="altair", plot=chart.to_json(), chart="line")
  File "/users/server/venv/lib/python3.10/site-packages/altair/vegalite/v5/api.py", line 1042, in to_json
    spec = self.to_dict(
  File "/users/server/venv/lib/python3.10/site-packages/altair/vegalite/v5/api.py", line 950, in to_dict
    copy.data = _prepare_data(original_data, context)
  File "/users/server/venv/lib/python3.10/site-packages/altair/vegalite/v5/api.py", line 111, in _prepare_data
    data = _pipe(data, data_transformers.get())
  File "/users/server/venv/lib/python3.10/site-packages/toolz/functoolz.py", line 628, in pipe
    data = func(data)
  File "/users/server/venv/lib/python3.10/site-packages/toolz/functoolz.py", line 304, in __call__
    return self._partial(*args, **kwargs)
  File "/users/server/venv/lib/python3.10/site-packages/altair/vegalite/data.py", line 23, in default_data_transformer
    return curried.pipe(data, limit_rows(max_rows=max_rows), to_values)
  File "/users/server/venv/lib/python3.10/site-packages/toolz/functoolz.py", line 628, in pipe
    data = func(data)
  File "/users/server/venv/lib/python3.10/site-packages/toolz/functoolz.py", line 304, in __call__
    return self._partial(*args, **kwargs)
  File "/users/server/venv/lib/python3.10/site-packages/altair/utils/data.py", line 118, in limit_rows
    raise_max_rows_error()
  File "/users/server/venv/lib/python3.10/site-packages/altair/utils/data.py", line 81, in raise_max_rows_error
    raise MaxRowsError(
altair.utils.data.MaxRowsError: The number of rows in your dataset is greater than the maximum allowed (5000).
```

Try enabling the VegaFusion data transformer which raises this limit by pre-evaluating data
transformations in Python.
    >> import altair as alt
    >> alt.data_transformers.enable("vegafusion")

**Additional context**  

When adding the code, we would get

```
ValueError: When the "vegafusion" data transformer is enabled, the 
to_dict() and to_json() chart methods must be called with format="vega".
```

This need support from the gradio side.

**Comment by abidlabs** [comment] 2024-01-22 18:40
Thanks @JeffersonQin. Looks like a duplicate of this issue: https://github.com/gradio-app/gradio/issues/2797 so I'll close.

We're happy to review a PR if you'd like to make one!

**Closed by abidlabs** 2024-01-22 18:40 UTC
Labels: enhancement
