### ISSUE TITLE
Arm (aarch64) CPU cannot generate external link

### ISSUE THREAD

**Issue by pariskang** [gradio-app/gradio#7301] opened 2024-02-04 15:26 UTC
### Describe the bug

I run chatglm.cpp (https://github.com/li-plus/chatglm.cpp) on my Ubuntu based on ARM, but when I use gradio, this bug confused me. I stuuggled to use https://github.com/gradio-app/gradio/pull/6091, but it not work. Can u help me to solve this problem. Previous issue not work (https://github.com/gradio-app/gradio/issues/7288). Thank you !

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
pip uninstall gradio -y
pip install gradio
```

### Screenshot

I have tried to uninstalled and reinstalled from pypi, but cannot generate public link. Due to this problem, I try to reslove it from
https://github.com/gradio-app/gradio/pull/6091.

(zhongjinggpt) root@15-0-0-62:/frp# pip uninstall gradio -y
Found existing installation: gradio 3.50.2
Uninstalling gradio-3.50.2:
Successfully uninstalled gradio-3.50.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
(zhongjinggpt) root@15-0-0-62:/frp# pip install gradio
Collecting gradio
Using cached gradio-4.16.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: aiofiles<24.0,>=22.0 in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from gradio) (23.2.1)
Requirement already satisfied: altair<6.0,>=4.2.0 in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from gradio) (5.2.0)
Requirement already satisfied: fastapi in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from gradio) (0.109.0)
Requirement already satisfied: ffmpy in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from gradio) (0.3.1)
Collecting gradio-client==0.8.1 (from gradio)
Using cached gradio_client-0.8.1-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: httpx in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from gradio) (0.26.0)
Requirement already satisfied: huggingface-hub>=0.19.3 in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from gradio) (0.20.3)
Requirement already satisfied: importlib-resources<7.0,>=1.3 in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from gradio) (6.1.1)
Requirement already satisfied: jinja2<4.0 in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from gradio) (3.1.3)
Requirement already satisfied: markupsafe~=2.0 in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from gradio) (2.1.4)
Requirement already satisfied: matplotlib~=3.0 in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from gradio) (3.8.2)
Requirement already satisfied: numpy~=1.0 in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from gradio) (1.26.3)
Requirement already satisfied: orjson~=3.0 in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from gradio) (3.9.12)
Requirement already satisfied: packaging in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from gradio) (23.2)
Requirement already satisfied: pandas<3.0,>=1.0 in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from gradio) (2.2.0)
Requirement already satisfied: pillow<11.0,>=8.0 in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from gradio) (10.2.0)
Requirement already satisfied: pydantic>=2.0 in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from gradio) (2.6.0)
Requirement already satisfied: pydub in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from gradio) (0.25.1)
Requirement already satisfied: python-multipart in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from gradio) (0.0.6)
Requirement already satisfied: pyyaml<7.0,>=5.0 in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from gradio) (6.0.1)
Requirement already satisfied: ruff>=0.1.7 in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from gradio) (0.1.15)
Requirement already satisfied: semantic-version~=2.0 in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from gradio) (2.10.0)
Requirement already satisfied: tomlkit==0.12.0 in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from gradio) (0.12.0)
Requirement already satisfied: typer<1.0,>=0.9 in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from typer[all]<1.0,>=0.9->gradio) (0.9.0)
Requirement already satisfied: typing-extensions~=4.0 in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from gradio) (4.9.0)
Requirement already satisfied: uvicorn>=0.14.0 in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from gradio) (0.27.0.post1)
Requirement already satisfied: fsspec in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from gradio-client==0.8.1->gradio) (2023.10.0)
Requirement already satisfied: websockets<12.0,>=10.0 in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from gradio-client==0.8.1->gradio) (11.0.3)
Requirement already satisfied: jsonschema>=3.0 in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from altair<6.0,>=4.2.0->gradio) (4.21.1)
Requirement already satisfied: toolz in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from altair<6.0,>=4.2.0->gradio) (0.12.1)
Requirement already satisfied: filelock in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from huggingface-hub>=0.19.3->gradio) (3.13.1)
Requirement already satisfied: requests in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from huggingface-hub>=0.19.3->gradio) (2.31.0)
Requirement already satisfied: tqdm>=4.42.1 in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from huggingface-hub>=0.19.3->gradio) (4.66.1)
Requirement already satisfied: zipp>=3.1.0 in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from importlib-resources<7.0,>=1.3->gradio) (3.17.0)
Requirement already satisfied: contourpy>=1.0.1 in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from matplotlib~=3.0->gradio) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from matplotlib~=3.0->gradio) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from matplotlib~=3.0->gradio) (4.47.2)
Requirement already satisfied: kiwisolver>=1.3.1 in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from matplotlib~=3.0->gradio) (1.4.5)
Requirement already satisfied: pyparsing>=2.3.1 in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from matplotlib~=3.0->gradio) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from matplotlib~=3.0->gradio) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from pandas<3.0,>=1.0->gradio) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.7 in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from pandas<3.0,>=1.0->gradio) (2023.4)
Requirement already satisfied: annotated-types>=0.4.0 in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from pydantic>=2.0->gradio) (0.6.0)
Requirement already satisfied: pydantic-core==2.16.1 in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from pydantic>=2.0->gradio) (2.16.1)
Requirement already satisfied: click<9.0.0,>=7.1.1 in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from typer<1.0,>=0.9->typer[all]<1.0,>=0.9->gradio) (8.1.7)
Requirement already satisfied: colorama<0.5.0,>=0.4.3 in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from typer[all]<1.0,>=0.9->gradio) (0.4.6)
Requirement already satisfied: shellingham<2.0.0,>=1.3.0 in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from typer[all]<1.0,>=0.9->gradio) (1.5.4)
Requirement already satisfied: rich<14.0.0,>=10.11.0 in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from typer[all]<1.0,>=0.9->gradio) (13.7.0)
Requirement already satisfied: h11>=0.8 in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from uvicorn>=0.14.0->gradio) (0.14.0)
Requirement already satisfied: starlette<0.36.0,>=0.35.0 in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from fastapi->gradio) (0.35.1)
Requirement already satisfied: anyio in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from httpx->gradio) (4.2.0)
Requirement already satisfied: certifi in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from httpx->gradio) (2023.11.17)
Requirement already satisfied: httpcore==1.* in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from httpx->gradio) (1.0.2)
Requirement already satisfied: idna in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from httpx->gradio) (3.6)
Requirement already satisfied: sniffio in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from httpx->gradio) (1.3.0)
Requirement already satisfied: attrs>=22.2.0 in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from jsonschema>=3.0->altair<6.0,>=4.2.0->gradio) (23.2.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from jsonschema>=3.0->altair<6.0,>=4.2.0->gradio) (2023.12.1)
Requirement already satisfied: referencing>=0.28.4 in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from jsonschema>=3.0->altair<6.0,>=4.2.0->gradio) (0.33.0)
Requirement already satisfied: rpds-py>=0.7.1 in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from jsonschema>=3.0->altair<6.0,>=4.2.0->gradio) (0.17.1)
Requirement already satisfied: six>=1.5 in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from python-dateutil>=2.7->matplotlib~=3.0->gradio) (1.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from rich<14.0.0,>=10.11.0->typer[all]<1.0,>=0.9->gradio) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from rich<14.0.0,>=10.11.0->typer[all]<1.0,>=0.9->gradio) (2.17.2)
Requirement already satisfied: exceptiongroup>=1.0.2 in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from anyio->httpx->gradio) (1.2.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from requests->huggingface-hub>=0.19.3->gradio) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from requests->huggingface-hub>=0.19.3->gradio) (2.1.0)
Requirement already satisfied: mdurl~=0.1 in /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages (from markdown-it-py>=2.2.0->rich<14.0.0,>=10.11.0->typer[all]<1.0,>=0.9->gradio) (0.1.2)
Using cached gradio-4.16.0-py3-none-any.whl (16.7 MB)
Using cached gradio_client-0.8.1-py3-none-any.whl (305 kB)
Installing collected packages: gradio-client, gradio
Attempting uninstall: gradio-client
Found existing installation: gradio_client 0.7.0b1
Uninstalling gradio_client-0.7.0b1:
Successfully uninstalled gradio_client-0.7.0b1
Successfully installed gradio-4.16.0 gradio-client-0.8.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
(zhongjinggpt) root@15-0-0-62:/frp#
(zhongjinggpt) root@15-0-0-62:/frp#
(zhongjinggpt) root@15-0-0-62:/frp# cd..
cd..: command not found
(zhongjinggpt) root@15-0-0-62:/frp# cd ..
(zhongjinggpt) root@15-0-0-62:# cd chatglm.cpp/examples
(zhongjinggpt) root@15-0-0-62:/chatglm.cpp/examples# python3 web_demo.py -m ../chatglm-ggml.bin
Running on local URL: http://127.0.0.1:7862/

Could not create share link. Missing file: /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages/gradio/frpc_linux_aarch64_v0.2.

Please check your internet connection. This can happen if your antivirus software blocks the download of this file. You can install manually by following these steps:

Download this file: https://cdn-media.huggingface.co/frpc-gradio-0.2/frpc_linux_aarch64
Rename the downloaded file to: frpc_linux_aarch64_v0.2
Move the file to this location: /root/anaconda3/envs/zhongjinggpt/lib/python3.9/site-packages/gradio

### System Info

```shell
(zhongjinggpt) root@15-0-0-62:~/chatglm.cpp# gradio environment
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 3.50.2
gradio_client version: 0.7.0b1

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.2.0
fastapi: 0.109.0
ffmpy: 0.3.1
gradio-client==0.7.0-beta.1 is not installed.
httpx: 0.26.0
huggingface-hub: 0.20.3
importlib-resources: 6.1.1
jinja2: 3.1.3
markupsafe: 2.1.4
matplotlib: 3.8.2
numpy: 1.26.3
orjson: 3.9.12
packaging: 23.2
pandas: 2.2.0
pillow: 10.2.0
pydantic: 2.6.0
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
requests: 2.31.0
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.9.0
uvicorn: 0.27.0.post1
websockets: 11.0.3
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.10.0
httpx: 0.26.0
huggingface-hub: 0.20.3
packaging: 23.2
requests: 2.31.0
typing-extensions: 4.9.0
websockets: 11.0.3
```

### Severity

I can work around it

**Comment by abidlabs** [comment] 2024-03-06 14:56
Dupe of https://github.com/gradio-app/gradio/issues/6053

**Closed by abidlabs** 2024-03-06 14:56 UTC
Labels: bug
