### ISSUE TITLE
Be able to return modified state from ChatInterface

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#8849] opened 2024-07-19 14:50 UTC
- [ ] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
When using LLMs via API, it can be desirable to keep the API requests and response history is a separate data structure (gr.State) from the chatbot state. That is because LLM providers have their own formats that are different from the gradio chatbot. 

**Describe the solution you'd like**  
Be able to return modified state (maybe even other components 👀 ) from the chatinterface function

**Additional context**

**Comment by abidlabs** [comment] 2024-07-19 15:20
Related: #7933

**Comment by abidlabs** [comment] 2024-07-22 20:51
Closing as is a dupe of: #7933

**Closed by abidlabs** 2024-07-22 20:51 UTC
Labels: enhancement, 💬 Chatbot

**Comment by brycepg** [comment] 2025-02-04 16:42
For anyone here from search, here's an example of how to do this:

```python

import gradio as gr

def store_message(user_input: str, history, state):
    return f"You said {user_input['text']} with value {state}", state + 1

with gr.Blocks() as demo:
    state = gr.State(value=0)
    gr.ChatInterface(
        fn=store_message,
        type="messages",
        multimodal=True,
        additional_inputs=[state],
        additional_outputs=[state],
    )

if __name__ == "__main__":
    demo.launch()
```

1. Maintain a state object
2. Feed it to both additional_outputs and additional_inputs
3. Modify your `fn` with a new parameter for the state
4. Return the value of the state every time from your `fn`

(I was testing with multimodal on but it can be turned off)

Hope this helps!
