### ISSUE TITLE
Follow up questions for #4276

### ISSUE THREAD

**Issue by mabodofutk** [gradio-app/gradio#4328] opened 2023-05-24 04:09 UTC
> Hi @mabodofutk !
> 
> The chain of `.then`s only returns the final event in the chain. So the cancel button is only cancelling the second generation not the first.
> 
> If you want the button to cancel both, you'd have to split them up:
> 
> ```python
> submit_event = msg.submit(user, [msg, chatbot], [msg, chatbot], queue=False).then(bot, chatbot, chatbot)
> other_event = submit_event.then(bot, chatbot, chatbot)
> stop.click(None, None, None, cancels=[submit_event, other_event], queue=False)
> ```

@freddyaboulton hello, I have changed the original code accordingly. However, although the "stop" button is functioning, if I submit a new message, the chatbot will start from where it stopped rather than establish a new submit event. Can you further clarify this? Thanks a lot

_Originally posted by @mabodofutk in https://github.com/gradio-app/gradio/issues/4276#issuecomment-1556463224_

**Comment by freddyaboulton** [comment] 2023-05-30 10:35
Hi @mabodofutk !

I can't reproduce that behavior actually. After I stop both messages, a new submit event will trigger a fresh response from the chatbot.

![stop_multiple](https://github.com/gradio-app/gradio/assets/41651716/e02cde83-b245-4636-b6af-8cdf8991dd3a)

**Comment by mabodofutk** [comment] 2023-05-31 05:56
@freddyaboulton pls look at this, when I "stop" and type "hi", it didn't trigger a fresh submit but continuing with the last stopped position
![20230531135352_rec_](https://github.com/gradio-app/gradio/assets/32256767/276ff07a-a77d-4204-9ab8-1a1d4bf0f174)

for reference, this is the full code snippet:
```python
import gradio as gr
import random
import time

with gr.Blocks() as demo:
    chatbot = gr.Chatbot()
    msg = gr.Textbox()
    clear = gr.Button("Clear")
    stop = gr.Button("Stop")

    def user(user_message, history):
        return "", history + [[user_message, None]]

    def bot(history):
        bot_message = random.choice(["How are you?"*10, "I love you"*10, "I'm very hungry"*10])
        history[-1][1] = ""
        for character in bot_message:
            history[-1][1] += character
            # history += [(None, character)]
            time.sleep(0.05)
            yield history

    submit_event = msg.submit(user, [msg, chatbot], [msg, chatbot], queue=False).then(
        bot, chatbot, chatbot)
    submit_2_event = submit_event.then(bot, chatbot, chatbot)
    stop.click(None, None, None, cancels=[submit_event, submit_2_event], queue=False)
    clear.click(lambda: None, None, chatbot, queue=False)

demo.queue()
demo.launch(debug=True)

```

**Comment by freddyaboulton** [comment] 2023-06-05 07:09
Hi @mabodofutk - I still can't reproduce that behavior! What version of gradio are you on? Should work properly on the new version - 3.33.1

**Comment by mabodofutk** [comment] 2023-06-06 09:46
@freddyaboulton I'm using 3.24.1. I tested it with 3.33.1, which indeed has different behavior. And I can reproduce https://github.com/gradio-app/gradio/issues/4328#issuecomment-1568198606, however, I noticed after your first click on the stop button, it stopped and quickly resumed to submit_2_event, is this behavior normal? I thought the expected behavior should be cancelling all subsequent events.

**Comment by freddyaboulton** [comment] 2023-06-06 10:28
Yes that’s expected. The .then will always trigger, even after cancellation.

**Comment by abidlabs** [comment] 2023-06-06 14:49
@mabodofutk you'll need to cancel the events individually

**Comment by abidlabs** [comment] 2023-06-06 14:50
Since the original bug has been resolved, I'll go ahead and close this issue!

**Closed by abidlabs** 2023-06-06 14:50 UTC
Labels: question
