### ISSUE TITLE
"certificate verify failed" error with hosted app

### ISSUE THREAD

**Issue by programehr** [gradio-app/gradio#5325] opened 2023-08-24 14:13 UTC
### Describe the bug

I have a [space](https://huggingface.co/spaces/programehr/GPT4ALL) cloned from [GPT4ALL](https://huggingface.co/spaces/Monster/GPT4ALL).
When trying to communicate with either of them via the API, i get the following error:
```
File "path\to\ssl.py", line 979, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)
```
I tried to set ```ssl_verify=False``` in the app.py on the server, but seemingly this argment is not supported in that version of code.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
from gradio_client import Client

client = Client("Monster/GPT4ALL")
# or client = Client("programehr/GPT4ALL")
# result: Loaded as API: https://programehr-gpt4all.hf.space ✔

client.predict(r"what is 2+2?", fn_index=1)
# result: error
```

### System Info

```shell
gradio_client 0.5.0
Python 3.11.4 
Windows 10
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment] 2023-08-24 19:16
I can't reproduce @programehr !

<img width="429" alt="image" src="https://github.com/gradio-app/gradio/assets/41651716/52ad3577-c1cc-4104-850f-58f067cbf948">

**Comment by abidlabs** [comment] 2023-08-30 14:48
Closing for lack of repro.

**Closed by abidlabs** 2023-08-30 14:48 UTC
Labels: bug, needs repro
