### ISSUE TITLE
Can I automatically add line numbers when inputting using gr.DataFrame

### ISSUE THREAD

**Issue by Annnnnnnnnnnnn** [gradio-app/gradio#4423] opened 2023-06-05 09:29 UTC
- [ ] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

**Describe the solution you'd like**  

**Additional context**

**Comment by pngwn** [comment] 2023-06-06 02:50
I think this is a feature request to add a 'number' column to rows.

**Comment by abidlabs** [comment] 2023-08-01 14:31
Duplicate of #5054 -- I'll close this one as that one is a little clearer imo

**Closed by abidlabs** 2023-08-01 14:31 UTC
Labels: enhancement
