### ISSUE TITLE
Uploading a video causes a problem when app is deployed using mount_gradio_app

### ISSUE THREAD

**Issue by dstieglitz** [gradio-app/gradio#3612] opened 2023-03-24 22:46 UTC
### Describe the bug

This may or may not be related to #3610, but the background is the same:

```We've been trying to run Gradio behind a local proxy. This works for one instance, but when you try to run multiple instances behind a proxy using path-based routing, you need to use mount_gradio_app to deploy your apps at different paths (you can't rewrite proxied URLs to / as the browser will request css resources at / and your server is serving them from whatever path you configured in your app.```

Below is an interface that just takes a video as input and returns it as output. Running this using mount_gradio_app through uvicorn or hypercorn causes an error (hypercorn error shown below).

Possibly related to websocket uploads? 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
import gradio as gr
from fastapi import FastAPI

def run_stuff(input):
    return input

#
# Gradio code
#
demo = gr.Blocks().queue()
with demo:
    with gr.Row():
        gr.Markdown("# Bug test")
    with gr.Row():
        input = gr.Video()
        with gr.Column(scale=1, min_width=600):
            go = gr.Button("Go")
    with gr.Row():
        video_output = gr.PlayableVideo()
    with gr.Row():
        go.click(fn=run_stuff, inputs=[input], outputs=[video_output],
                 queue=True, show_progress=True, status_tracker=None)

app = FastAPI()

@app.get("/")
def read_main():
    return {"message": "This is your main app"}

gradio_app = gr.mount_gradio_app(app, demo, path='/mypath') 
```

### Logs

```shell
[2023-03-24 15:39:25 -0700] [231647] [INFO] Running on http://127.0.0.1:8000 (CTRL + C to quit)
Task exception was never retrieved
future: <Task finished name='Task-26' coro=<worker_serve.<locals>._server_callback() done, defined at /home/dstieglitz/miniconda3/envs/transcribe/lib/python3.8/site-packages/hypercorn/asyncio/run.py:94> exception=LocalProtocolError('Event CloseConnection(code=<CloseReason.ABNORMAL_CLOSURE: 1006>, reason=None) cannot be sent in state ConnectionState.LOCAL_CLOSING.')>
Traceback (most recent call last):
  File "/home/dstieglitz/miniconda3/envs/transcribe/lib/python3.8/site-packages/hypercorn/asyncio/task_group.py", line 23, in _handle
    await app(scope, receive, send, sync_spawn, call_soon)
  File "/home/dstieglitz/miniconda3/envs/transcribe/lib/python3.8/site-packages/hypercorn/app_wrappers.py", line 33, in __call__
    await self.app(scope, receive, send)
  File "/home/dstieglitz/miniconda3/envs/transcribe/lib/python3.8/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/home/dstieglitz/miniconda3/envs/transcribe/lib/python3.8/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/dstieglitz/miniconda3/envs/transcribe/lib/python3.8/site-packages/starlette/middleware/errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "/home/dstieglitz/miniconda3/envs/transcribe/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/dstieglitz/miniconda3/envs/transcribe/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/dstieglitz/miniconda3/envs/transcribe/lib/python3.8/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/dstieglitz/miniconda3/envs/transcribe/lib/python3.8/site-packages/starlette/routing.py", line 443, in handle
    await self.app(scope, receive, send)
  File "/home/dstieglitz/miniconda3/envs/transcribe/lib/python3.8/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/home/dstieglitz/miniconda3/envs/transcribe/lib/python3.8/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/dstieglitz/miniconda3/envs/transcribe/lib/python3.8/site-packages/starlette/middleware/errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "/home/dstieglitz/miniconda3/envs/transcribe/lib/python3.8/site-packages/starlette/middleware/cors.py", line 76, in __call__
    await self.app(scope, receive, send)
  File "/home/dstieglitz/miniconda3/envs/transcribe/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/dstieglitz/miniconda3/envs/transcribe/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/dstieglitz/miniconda3/envs/transcribe/lib/python3.8/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/dstieglitz/miniconda3/envs/transcribe/lib/python3.8/site-packages/starlette/routing.py", line 341, in handle
    await self.app(scope, receive, send)
  File "/home/dstieglitz/miniconda3/envs/transcribe/lib/python3.8/site-packages/starlette/routing.py", line 82, in app
    await func(session)
  File "/home/dstieglitz/miniconda3/envs/transcribe/lib/python3.8/site-packages/fastapi/routing.py", line 289, in app
    await dependant.call(**values)
  File "/home/dstieglitz/miniconda3/envs/transcribe/lib/python3.8/site-packages/gradio/routes.py", line 534, in join_queue
    await asyncio.sleep(1)
  File "/home/dstieglitz/miniconda3/envs/transcribe/lib/python3.8/asyncio/tasks.py", line 648, in sleep
    return await future
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dstieglitz/miniconda3/envs/transcribe/lib/python3.8/site-packages/hypercorn/asyncio/run.py", line 96, in _server_callback
    await TCPServer(app, loop, config, context, reader, writer)
  File "/home/dstieglitz/miniconda3/envs/transcribe/lib/python3.8/site-packages/hypercorn/asyncio/tcp_server.py", line 70, in run
    await self._read_data()
  File "/home/dstieglitz/miniconda3/envs/transcribe/lib/python3.8/site-packages/hypercorn/asyncio/task_group.py", line 82, in __aexit__
    await task
  File "/home/dstieglitz/miniconda3/envs/transcribe/lib/python3.8/site-packages/hypercorn/asyncio/task_group.py", line 78, in __aexit__
    await task
  File "/home/dstieglitz/miniconda3/envs/transcribe/lib/python3.8/site-packages/hypercorn/asyncio/task_group.py", line 29, in _handle
    await send(None)
  File "/home/dstieglitz/miniconda3/envs/transcribe/lib/python3.8/site-packages/hypercorn/protocol/ws_stream.py", line 260, in app_send
    await self._send_wsproto_event(CloseConnection(code=CloseReason.ABNORMAL_CLOSURE))
  File "/home/dstieglitz/miniconda3/envs/transcribe/lib/python3.8/site-packages/hypercorn/protocol/ws_stream.py", line 336, in _send_wsproto_event
    data = self.connection.send(event)
  File "/home/dstieglitz/miniconda3/envs/transcribe/lib/python3.8/site-packages/wsproto/connection.py", line 107, in send
    raise LocalProtocolError(
wsproto.utilities.LocalProtocolError: Event CloseConnection(code=<CloseReason.ABNORMAL_CLOSURE: 1006>, reason=None) cannot be sent in state ConnectionState.LOCAL_CLOSING.
```
```


### System Info

```shell
gradio 3.23.0
gradio_client 0.0.4
python 3.8
Ubuntu 20.04
hypercorn 0.14.3
```

### Severity

annoying

**Comment by dstieglitz** [comment] 2023-03-25 00:03
After resolving #3610, and removing queuing from the app, this problem goes away.

**Comment by dstieglitz** [comment] 2023-03-27 23:46
I think there's some confusion. I don't think the fix in #3640 will actually fix this issue as you still won't be able to use queuing() and mount_gradio_app() at the same time. My comment above was simply to confirm that queuing is part of the problem.

**Comment by abidlabs** [comment] 2023-03-27 23:53
@dstieglitz ah you're right, sorry about that confusion. I've removed this issue from #3640. But I just ran your above code with uvicorn, and can't reproduce the problem.

Saving the above file to "test.py" and running:

`uvicorn test:gradio_app --port 7888` 

works perfectly fine. Are you running the code similarly?

**Comment by dstieglitz** [comment] 2023-03-27 23:56
Just confirming you actually tried to upload a video by setting the file in the video component and clicking "Go" (and didn't just launch the app)?

**Comment by abidlabs** [comment] 2023-03-28 00:51
Yup, screenshot here: 
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/1778297/228098555-7c6e6bdf-61da-40f2-aee2-7936b9596304.png">

I haven't checked hypercorn, but you said that you're experiencing the same issue with uvicorn, right?

**Comment by freddyaboulton** [comment] 2023-03-29 21:41
That would make sense - in gradio, we manually set the max websocket size to 1gb ( https://github.com/gradio-app/gradio/blob/main/gradio/networking.py#L152 )

**Comment by abidlabs** [comment] 2023-03-31 13:22
@dstieglitz can you try making the change to the line above, installing gradio locally, and seeing if that changes anything for you?

**Comment by freddyaboulton** [comment] 2023-04-03 17:05
@dstieglitz Sorry for the delay. Can you share the code and video you're uploading? It seems like there was an error running your processing function (`"output": {"error"...0)"}, "success": false}`) and it will be hard to dig in further without more information.

**Comment by abidlabs** [comment] 2023-04-06 23:46
Hi @dstieglitz were you able to figure this out?

**Comment by dstieglitz** [comment] 2023-04-07 05:54
@abidlabs I’m out of the office this week. I’ll post an update when I’m back.

**Comment by abidlabs** [comment] 2023-04-17 18:09
Let's go ahead and close this issue for now, @freddyaboulton? @dstieglitz feel free to reopen with more details / repro if you are still running into any issues.

**Closed by abidlabs** 2023-04-17 18:09 UTC
Labels: needs repro, pending clarification

**Comment by gerisg** [comment] 2023-06-23 04:18
> @abidlabs I’m out of the office this week. I’ll post an update when I’m back.

Hi @dstieglitz were you able to figure this out? Thanks!

**Comment by dstieglitz** [comment] 2023-06-23 16:19
We had to move on, whatever is in this ticket is the latest info from us
