### ISSUE TITLE
Event bubbling issues in Accordion (4.25.0)

### ISSUE THREAD

**Issue by sbarman-mi9** [gradio-app/gradio#7920] opened 2024-04-03 00:31 UTC
### Describe the bug

As can be seen in the attached video, firing 'click' events from children of a Accordion component, changes the state of Accordion. This issue didn't exist in 4.21.0 but when I upgraded today to 4.25, it showed up. 

**Expected Outcome**: If a accordion is in 'open' state, clicking a button inside of it, should not alter it's state to 'close'.

@abidlabs @aliabid94

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

with gr.Blocks() as demo:
    with gr.Accordion("Settings", open=False, elem_id='p_accordion'):
        gr.HTML("<div></div>")
        gr.HTML("<div></div>")
        btn = gr.Button("Button")

    btn.click(None, None, None, js="""() => {console.log("Button clicked");}""")

demo.queue().launch(server_name="0.0.0.0", server_port=7000)

```

### Screenshot

https://github.com/gradio-app/gradio/assets/14152255/f4f90730-2117-47ad-868a-97fd70ba8f89

### System Info

```shell
gradio==4.25.0
python==3.10.12
```

### Severity

I can work around it

**Comment by pngwn** [comment] 2024-04-03 00:36
This is a duplicate of #7786.

**Closed by pngwn** 2024-04-03 00:36 UTC
Labels: bug
