### ISSUE TITLE
High CPU utilization

### ISSUE THREAD

**Issue by geshihuazhong** [gradio-app/gradio#107] opened 2021-01-26 11:03 UTC
It takes up 100% of the CPU for a long time

**Comment by abidlabs** [comment] 2021-02-10 21:35
Hi @geshihuazhong can you share what script you're running so that I can better reproduce your issue?

**Comment by abidlabs** [comment] 2021-02-11 17:57
I'm going to close this issue because I can't reproduce it with the current information. Feel free to open it with additional details?

**Closed by abidlabs** 2021-02-11 17:57 UTC
