### ISSUE TITLE
Add the ability to switch between waveform display and the standard audio player.

### ISSUE THREAD

**Issue by Bebra777228** [gradio-app/gradio#8779] opened 2024-07-14 16:43 UTC
Problem with the waveform display: the update is too slow. It would be nice if you could get an additional parameter that would return the display of the standard audio player instead of the waveform. (The audio player under the waveform is not what you need).

**Comment by abidlabs** [comment] 2024-07-14 16:46
Thanks @Bebra777228, we are working on this, but duplicate of: https://github.com/gradio-app/gradio/issues/6801

**Closed by abidlabs** 2024-07-14 16:46 UTC
