### ISSUE TITLE
gradio 3.45 breaks dropdown component when multiselect is enabled

### ISSUE THREAD

**Issue by vladmandic** [gradio-app/gradio#5850] opened 2023-10-09 18:25 UTC
### Describe the bug

as title says, when multiselect is enabled in `gr.Dropdown`, result is client-side js error (no errors on python side).

it seems that issue is introduced via #5384 
and svelte Multiselect component has its arguments shifted to the left by one
(so it receives type as label and choices become null)

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

N/A

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/57876960/864dbd71-cef9-4319-a9b1-4b551129a7b3)

### Logs

```shell
attached screenshot shows chrome session with log point set (you can see where in the code)
and resulting log shows two ok dropdowns (which are not multiselect) and third which shows behavior i've described above.
```

and actual error is:
![image](https://github.com/gradio-app/gradio/assets/57876960/6a692e87-c3e1-484e-bdb8-9a8ef5ac485e)

### System Info

```shell
gradio==3.47.1
```

### Severity

Blocking usage of gradio

**Comment by aliabid94** [comment] 2023-10-09 21:53
Yikes. Fixing now

**Comment by aliabid94** [comment] 2023-10-09 22:00
Is this a gradio==3.45 or a gradio==3.47 issue? in the title you've put 3.45 but in the version you've set 3.47. I've reproduced in 3.45 but not 3.47.

**Comment by vladmandic** [comment] 2023-10-10 10:50
3.44.4 ok
3.45.0 not ok
3.46.0 not ok
3.47.0 not ok
3.47.1 not ok

**Comment by aliabid94** [comment] 2023-10-10 16:28
Can you provide a reproducible code snippet? The following works for me on 3.47.1

```
import gradio as gr


def sentence_builder(activity_list):
    return f"""We {" and ".join(activity_list)}"""


demo = gr.Interface(
    sentence_builder,
    [
        gr.Dropdown(
            ["ran", "swam", "ate", "slept"],
            multiselect=True,
        ),
    ],
    "text",
)

if __name__ == "__main__":
    demo.launch()
```

**Comment by vladmandic** [comment] 2023-10-10 16:54
this is example of a typical code through entire app and it works fine in all gradio versions below 3.45.0:

```python
import gradio as gr

class FormComponent:
    def get_expected_parent(self):
        return gr.components.Form

class DropdownMulti(FormComponent, gr.Dropdown):
    def __init__(self, **kwargs):
        super().__init__(multiselect=True, **kwargs)

    def get_block_name(self):
        return "dropdown"

gr.Dropdown.get_expected_parent = FormComponent.get_expected_parent

print('gradio version:', gr.__version__)
with gr.Blocks(analytics_enabled=False) as demo:
    gr.Dropdown(label='test1', value='first', choices=['first', 'second', 'third'], type='value', multiselect=False, interactive=True) # works
    gr.Dropdown(label='test2', value='first', choices=['first', 'second', 'third'], type='value', multiselect=True, interactive=True) # works
    gr.Dropdown(label='test3', value=['first', 'second'], choices=['first', 'second', 'third'], type='value', multiselect=True, interactive=True) # works
    DropdownMulti(label='test4', value=['first', 'second'], choices=['first', 'second', 'third'], type='value', interactive=True) # doesnt work
    demo.launch()
```

**Comment by aliabid94** [comment] 2023-10-10 18:08
What is the purpose of DropdownMulti? It seems like that class is hacking around gradio internal APIs that are not externally supported. Any reason `gr.Dropdown(multiselect=True)` is not sufficient?

**Comment by vladmandic** [comment] 2023-10-10 19:00
the reason why those classes were introduced was so component could have a single **kwargs in a constructor and that can be lambda (e.g. `choices` can be result of a function, not statically determined) - and not all options can be touched outside of the constructor (e.g. `multiselect` is only valid during init, but not during update)

could it have been done differently in the past? sure.
but now we have massive app ecosystem with hundreds of extensions using this.

for example, another thing that 3.45 breaks is 

```python
class ToolButton(FormComponent, gr.Button):
    """Small button with single emoji as text, fits inside gradio forms"""

    def __init__(self, *args, **kwargs):
        classes = kwargs.pop("elem_classes", [])
        super().__init__(*args, elem_classes=["tool", *classes], **kwargs)

    def get_block_name(self):
        return "button"
```

can it all be rewritten? sure. if all of the extension authors can even be found to update their extensions.
impact? a1111 webui, sdnext, etc.
size of user base? daily unique clones >60k combined.

**Comment by aliabid94** [comment] 2023-10-11 19:20
ok lemme see what can be done here. Hopefully the custom component support coming in 4.0 will discourage this type of component creation.

**Comment by aliabid94** [comment] 2023-10-11 19:44
@vladmandic can you confirm the above PR fixes all issues? Install with `pip install https://gradio-builds.s3.amazonaws.com/62a6031b727a2cf5e7f68555aa2e65143613fef7/gradio-3.47.1-py3-none-any.whl`

**Comment by vladmandic** [comment] 2023-10-11 19:51
tried, step forward, but still issues:
- `ToolButton` appears ok, but its disabled (cannot be clicked on)
- `DropdownMulti` throws an error:

```log
  File "/home/vlado/dev/sdnext/modules/ui_components.py", line 62, in __init__
    super().__init__(multiselect=True, **kwargs)
TypeError: gradio.components.dropdown.Dropdown.__init__() got multiple values for keyword argument 'multiselect'
```

i've confimed, `multiselect` is not in kwargs in this constructor, so there is no reason why it should complain.

**Comment by aliabid94** [comment] 2023-10-11 19:55
what should I run to reproduce this?

**Comment by vladmandic** [comment] 2023-10-11 19:59
install:
```
git clone https://github.com/vladmandic/automatic
python launch.py
```

first start will install all dependencies and may take a while (especially torch).
when its done, just stop it.

```
pip install -U gradio
python launch.py --experimental
```
(experimental flag tells sdnext not to complain about unexpected package versions)

**Comment by aliabid94** [comment] 2023-10-12 19:12
It works fine on my machine? Can you provide a smaller reproducible piece of code

**Comment by aliabid94** [comment] 2023-10-20 18:06
following up @vladmandic

**Comment by abidlabs** [comment] 2023-11-02 07:29
Closing for lack of follow-up.

**Closed by abidlabs** 2023-11-02 07:29 UTC
Labels: bug, needs repro
