### ISSUE TITLE
Informative progress bars & more

### ISSUE THREAD

**Issue by merveenoyan** [gradio-app/gradio#2796] opened 2022-12-12 09:07 UTC
Hello 👋🏼
I didn't know how to search for this so I don't know if similar issue exists but I have a feature request.

In [Dreambooth Training Space](https://huggingface.co/spaces/multimodalart/dreambooth-training) we have a progress section and I know that gradio has progress bars. It would be nice to give user an option to have what's going on in the box written on the box itself when progress takes place (not something like label). This is a little cryptic because people don't know what's happening (maybe training has started now that users have uploaded and named their concepts? they probably won't know!)

<img width="1118" alt="Ekran Resmi 2022-12-12 12 05 24" src="https://user-images.githubusercontent.com/53175384/207005174-ee9a9c93-92c7-44c3-82e0-60685147f8ce.png">

**Comment by freddyaboulton** [comment] 2022-12-12 14:00
Hi @merveenoyan ! I think this is a duplicate of the discussion happening in issues #2683, #340 and PR #2750

**Closed as completed** 2022-12-12 14:01 UTC
