### ISSUE TITLE
Module "gradio" has no attribute "Blocks"

### ISSUE THREAD

**Issue by ElleLeonne** [gradio-app/gradio#4297] opened 2023-05-21 14:54 UTC
### Describe the bug

Trying to run the latest version of gradio, and code that I had used previously no longer works.

I'm instantiating my gradio loop like so:

with gr.Blocks(theme=gr.themes.Default(text_size="lg")) as demo:

Which used to work. Following advice on other threads, I've reinstalled both my gradio and my gradio_client to no avail.
Also restarted my computer, which has fixed odd issues before.

Curious if there were any major updates playing with the gradio object or something.

What is a bit odd is that vs code seems to see the Blocks object just fine from the source code.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
with gr.Blocks(theme=gr.themes.Default(text_size="lg")) as demo:
    with gr.Row():
        with gr.Column():
            context_box = gr.components.Textbox(lines=2, value=cfg.context, interactive=True, label="Context")
            history_box = gr.components.Textbox(lines=5, value=cfg.history, interactive=True, label="History")
            reply_box = gr.components.Textbox(lines=2, value=cfg.reply, interactive=True, label="Reply")
        
        with gr.Column():
            progress_box = gr.components.Textbox(lines=1, interactive=False, value=f"Remaining Sequences: {cfg.remaining}", show_label=False)
            less_recent_box = gr.components.Textbox(lines=5, placeholder=cfg.least_recent, label="Less recent")
            more_recent_box = gr.components.Textbox(lines=5, placeholder=cfg.least_recent, label="Less recent")

    with gr.Row():
        export_btn = gr.Button("Export & Quit")
        export_btn.click(fn=export_quit)

        reject_btn = gr.Button("Reject")
        reject_btn.click(fn=reject, outputs = [context_box, history_box, reply_box, progress_box, less_recent_box, more_recent_box])
        
        continue_btn = gr.Button("Save & Continue")
        continue_btn.click(fn=save_continue, inputs=[context_box, history_box, reply_box], outputs = [history_box, reply_box, progress_box, less_recent_box, more_recent_box])
        
        next_btn = gr.Button("Save & Next")
        next_btn.click(fn=save_next, inputs=[context_box, history_box, reply_box], outputs = [context_box, history_box, reply_box, progress_box, less_recent_box, more_recent_box])
```

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/87243032/0a98e806-b3bf-42d4-8ac0-660cc6cee775)

### Logs

```shell
Traceback (most recent call last):
  File "/home/xxx/Desktop/xxx (copy)/data_clean_ui.py", line 111, in <module>
    with gr.Blocks(theme=gr.themes.Default(text_size="lg")) as demo:
AttributeError: module 'gradio' has no attribute 'Blocks'
```

### System Info

```shell
Ubuntu 22.04
gradio                     3.32.0
gradio_client              0.2.5
```

### Severity

annoying

**Comment by abidlabs** [comment] 2023-05-22 02:56
Hi @ElleLeonne this issue usually happens when `gradio` is not successfully installed in your local system. Can you try uninstalling and re-installing it? 

You can see it work fine on Colab: 
https://colab.research.google.com/drive/1ETcUIkKiVHXHXPVHo3GsqsCxjNgRDAk2?usp=sharing

**Comment by akx** [comment] 2023-05-22 09:04
You probably have another module named `gradio.py` e.g. next to your `data_clean_ui.py`. You can verify that with a quick REPL session:

```
$ python
>>> import gradio
>>> gradio
<module 'gradio' from '.../python3.10/site-packages/gradio/__init__.py'>
```
You'll probably get a vastly different `from '...`.

**Comment by abidlabs** [comment] 2023-05-23 20:50
Thanks @akx, yes that's a possibility as well. I'll go ahead and close this issue since it's almost certainly not a bug in the `gradio` library. @ElleLeonne let us know if you are able to figure this out

**Closed by abidlabs** 2023-05-23 20:50 UTC
Labels: bug, needs repro
