### ISSUE TITLE
timeout error

### ISSUE THREAD

**Issue by tsw123678** [gradio-app/gradio#7673] opened 2024-03-12 05:27 UTC
### Describe the bug

I've recently been studying Gradio, but I've encountered an unresolved error. I've tried extending the timeout for HTTPX according to the referenced issues, but it still hasn't been resolved. I've set the proxy port to 33210 in the code. Would this have any impact? 

The error message is as follows:
Traceback (most recent call last):
  File "E:\conda\envs\trm\lib\site-packages\httpx\_transports\default.py", line 69, in map_httpcore_exceptions
    yield
  File "E:\conda\envs\trm\lib\site-packages\httpx\_transports\default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
  File "E:\conda\envs\trm\lib\site-packages\httpcore\_sync\connection_pool.py", line 216, in handle_request
    raise exc from None
  File "E:\conda\envs\trm\lib\site-packages\httpcore\_sync\connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "E:\conda\envs\trm\lib\site-packages\httpcore\_sync\http_proxy.py", line 207, in handle_request
    return self._connection.handle_request(proxy_request)
  File "E:\conda\envs\trm\lib\site-packages\httpcore\_sync\connection.py", line 101, in handle_request
    return self._connection.handle_request(request)
  File "E:\conda\envs\trm\lib\site-packages\httpcore\_sync\http11.py", line 143, in handle_request
    raise exc
  File "E:\conda\envs\trm\lib\site-packages\httpcore\_sync\http11.py", line 113, in handle_request
    ) = self._receive_response_headers(**kwargs)
  File "E:\conda\envs\trm\lib\site-packages\httpcore\_sync\http11.py", line 186, in _receive_response_headers
    event = self._receive_event(timeout=timeout)
  File "E:\conda\envs\trm\lib\site-packages\httpcore\_sync\http11.py", line 224, in _receive_event
    data = self._network_stream.read(
  File "E:\conda\envs\trm\lib\site-packages\httpcore\_backends\sync.py", line 126, in read
    return self._sock.recv(max_bytes)
  File "E:\conda\envs\trm\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "E:\conda\envs\trm\lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ReadTimeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\deeplearning\langchain_agent\learn_gradio\1.py", line 50, in <module>
    demo.launch(share=True)
  File "E:\conda\envs\trm\lib\site-packages\gradio\blocks.py", line 2080, in launch
    and not networking.url_ok(self.local_url)
  File "E:\conda\envs\trm\lib\site-packages\gradio\networking.py", line 252, in url_ok
    r = httpx.head(url, timeout=3, verify=False)
  File "E:\conda\envs\trm\lib\site-packages\httpx\_api.py", line 278, in head
    return request(
  File "E:\conda\envs\trm\lib\site-packages\httpx\_api.py", line 106, in request
    return client.request(
  File "E:\conda\envs\trm\lib\site-packages\httpx\_client.py", line 827, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "E:\conda\envs\trm\lib\site-packages\httpx\_client.py", line 914, in send
    response = self._send_handling_auth(
  File "E:\conda\envs\trm\lib\site-packages\httpx\_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
  File "E:\conda\envs\trm\lib\site-packages\httpx\_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
  File "E:\conda\envs\trm\lib\site-packages\httpx\_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
  File "E:\conda\envs\trm\lib\site-packages\httpx\_transports\default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
  File "E:\conda\envs\trm\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "E:\conda\envs\trm\lib\site-packages\httpx\_transports\default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout: timed out

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import os
os.environ['HF_API_KEY'] = 'xxx'
os.environ['http_proxy'] = 'http://127.0.0.1:33210'
os.environ['https_proxy'] = 'http://127.0.0.1:33210'

hf_api_key=os.getenv('HF_API_KEY')

import requests, json

def get_completion(inputs, parameters=None, ENDPOINT_URL="https://api-inference.huggingface.co/models/Salesforce/blip-image-captioning-base"): 
    headers = {
      "Authorization": f"Bearer {hf_api_key}",
      "Content-Type": "application/json"
    }
    data = { "inputs": inputs }
    if parameters is not None:
        data.update({"parameters": parameters})
    response = requests.request("POST",
                                ENDPOINT_URL,
                                headers=headers,
                                data=json.dumps(data))
    return json.loads(response.content.decode("utf-8"))

import gradio as gr
import io
import base64

def image_to_base64_str(pil_image):
    byte_arr = io.BytesIO()
    pil_image.save(byte_arr, format='PNG')
    byte_arr = byte_arr.getvalue()
    return str(base64.b64encode(byte_arr).decode('utf-8'))

def captioner(image):
    base64_image = image_to_base64_str(image)
    result = get_completion(base64_image)
    return result[0]['generated_text']

gr.close_all()

demo = gr.Interface(
    fn=captioner,
    inputs=[gr.Image(label="Upload image", type="pil")],
    outputs=[gr.Textbox(label="Caption")],
    title="Image Captioning with BLIP",
    description="Caption any image using the BLIP model",
    allow_flagging="never",
)

demo.launch(share=True)

```

### System Info

```shell
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ E:\conda\envs\trm\lib\runpy.py:194 in _run_module_as_main                                        │
│                                                                                                  │
│   191 │   main_globals = sys.modules["__main__"].__dict__                                        │
│   192 │   if alter_argv:                                                                         │
│   193 │   │   sys.argv[0] = mod_spec.origin                                                      │
│ ❱ 194 │   return _run_code(code, main_globals, None,                                             │
│   195 │   │   │   │   │    "__main__", mod_spec)                                                 │
│   196                                                                                            │
│   197 def run_module(mod_name, init_globals=None,                                                │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │   alter_argv = 0                                                                             │ │
│ │         code = <code object <module> at 0x0000014ED15FB2F0, file                             │ │
│ │                "E:\conda\envs\trm\Scripts\gradio.exe\__main__.py", line 2>                   │ │
│ │ main_globals = {                                                                             │ │
│ │                │   '__name__': '__main__',                                                   │ │
│ │                │   '__doc__': None,                                                          │ │
│ │                │   '__package__': '',                                                        │ │
│ │                │   '__loader__': <zipimporter object                                         │ │
│ │                "E:\conda\envs\trm\Scripts\gradio.exe\">,                                     │ │
│ │                │   '__spec__': ModuleSpec(name='__main__', loader=<zipimporter object        │ │
│ │                "E:\conda\envs\trm\Scripts\gradio.exe\">,                                     │ │
│ │                origin='E:\\conda\\envs\\trm\\Scripts\\gradio.exe\\__main__.py'),             │ │
│ │                │   '__annotations__': {},                                                    │ │
│ │                │   '__builtins__': <module 'builtins' (built-in)>,                           │ │
│ │                │   '__file__': 'E:\\conda\\envs\\trm\\Scripts\\gradio.exe\\__main__.py',     │ │
│ │                │   '__cached__':                                                             │ │
│ │                'E:\\conda\\envs\\trm\\Scripts\\gradio.exe\\__pycache__\\__main__.cpython-38… │ │
│ │                │   're': <module 're' from 'E:\\conda\\envs\\trm\\lib\\re.py'>,              │ │
│ │                │   ... +2                                                                    │ │
│ │                }                                                                             │ │
│ │     mod_name = '__main__'                                                                    │ │
│ │     mod_spec = ModuleSpec(name='__main__', loader=<zipimporter object                        │ │
│ │                "E:\conda\envs\trm\Scripts\gradio.exe\">,                                     │ │
│ │                origin='E:\\conda\\envs\\trm\\Scripts\\gradio.exe\\__main__.py')              │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ E:\conda\envs\trm\lib\runpy.py:87 in _run_code                                                   │
│                                                                                                  │
│    84 │   │   │   │   │      __loader__ = loader,                                                │
│    85 │   │   │   │   │      __package__ = pkg_name,                                             │
│    86 │   │   │   │   │      __spec__ = mod_spec)                                                │
│ ❱  87 │   exec(code, run_globals)                                                                │
│    88 │   return run_globals                                                                     │
│    89                                                                                            │
│    90 def _run_module_code(code, init_globals=None,                                              │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │       cached = 'E:\\conda\\envs\\trm\\Scripts\\gradio.exe\\__pycache__\\__main__.cpython-38… │ │
│ │         code = <code object <module> at 0x0000014ED15FB2F0, file                             │ │
│ │                "E:\conda\envs\trm\Scripts\gradio.exe\__main__.py", line 2>                   │ │
│ │        fname = 'E:\\conda\\envs\\trm\\Scripts\\gradio.exe\\__main__.py'                      │ │
│ │ init_globals = None                                                                          │ │
│ │       loader = <zipimporter object "E:\conda\envs\trm\Scripts\gradio.exe\">                  │ │
│ │     mod_name = '__main__'                                                                    │ │
│ │     mod_spec = ModuleSpec(name='__main__', loader=<zipimporter object                        │ │
│ │                "E:\conda\envs\trm\Scripts\gradio.exe\">,                                     │ │
│ │                origin='E:\\conda\\envs\\trm\\Scripts\\gradio.exe\\__main__.py')              │ │
│ │     pkg_name = ''                                                                            │ │
│ │  run_globals = {                                                                             │ │
│ │                │   '__name__': '__main__',                                                   │ │
│ │                │   '__doc__': None,                                                          │ │
│ │                │   '__package__': '',                                                        │ │
│ │                │   '__loader__': <zipimporter object                                         │ │
│ │                "E:\conda\envs\trm\Scripts\gradio.exe\">,                                     │ │
│ │                │   '__spec__': ModuleSpec(name='__main__', loader=<zipimporter object        │ │
│ │                "E:\conda\envs\trm\Scripts\gradio.exe\">,                                     │ │
│ │                origin='E:\\conda\\envs\\trm\\Scripts\\gradio.exe\\__main__.py'),             │ │
│ │                │   '__annotations__': {},                                                    │ │
│ │                │   '__builtins__': <module 'builtins' (built-in)>,                           │ │
│ │                │   '__file__': 'E:\\conda\\envs\\trm\\Scripts\\gradio.exe\\__main__.py',     │ │
│ │                │   '__cached__':                                                             │ │
│ │                'E:\\conda\\envs\\trm\\Scripts\\gradio.exe\\__pycache__\\__main__.cpython-38… │ │
│ │                │   're': <module 're' from 'E:\\conda\\envs\\trm\\lib\\re.py'>,              │ │
│ │                │   ... +2                                                                    │ │
│ │                }                                                                             │ │
│ │  script_name = None                                                                          │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ in <module>:7                                                                                    │
│                                                                                                  │
│ E:\conda\envs\trm\lib\site-packages\gradio\cli\cli.py:27 in cli                                  │
│                                                                                                  │
│   24 │   if len(args) == 0:                                                                      │
│   25 │   │   raise ValueError("No file specified.")                                              │
│   26 │   if args[0] in {"deploy", "environment", "deploy-discord"}:                              │
│ ❱ 27 │   │   app()                                                                               │
│   28 │   elif args[0] in {"cc", "component"}:                                                    │
│   29 │   │   sys.argv = sys.argv[1:]                                                             │
│   30 │   │   custom_component()                                                                  │
│                                                                                                  │
│                                                                                                  │
│ E:\conda\envs\trm\lib\site-packages\typer\main.py:553 in                                         │
│ get_params_convertors_ctx_param_name_from_function                                               │
│                                                                                                  │
│ E:\conda\envs\trm\lib\site-packages\typer\main.py:850 in get_click_param                         │
│                                                                                                  │
│ E:\conda\envs\trm\lib\site-packages\typer\main.py:779 in get_click_type
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment] 2024-03-12 17:24
HI @tsw123678 ? What version of python, gradio, httpx are you running?

**Comment by tsw123678** [comment] 2024-03-13 01:20
> 你好@tsw123678？您正在运行什么版本的 python、gradio、httpx？

@freddyaboulton thanks for your interest about my problem，my version is here：
Python 3.8.18
gradio  4.19.2
httpx    0.27.0

If I don't set up a proxy, I can't connect to the Hugging Face inference API for model usage. I've looked at some posts about Nginx, but I just want to run Gradio on my local web. How should I solve this problem?

**Comment by abidlabs** [comment] 2024-03-13 18:08
What happens if you don't set share=True?

**Comment by tsw123678** [comment] 2024-03-14 02:38
> 如果不设置 share=True 会发生什么？

I change the code to "demo.launch(share=False)",but the same error message as before still appears.

**Comment by tsw123678** [comment] 2024-03-14 02:40
> What happens if you don't set share=True?

I also try to change the code to "demo.launch()" ,the same error

**Comment by tsw123678** [comment] 2024-03-14 13:06
I have solve the problem by changing the version of gradio from gradio 4.19.2 to 3.50.2.

**Comment by abidlabs** [comment] 2024-03-14 14:30
Ok I'll close this issue, as its a duplicate of: https://github.com/gradio-app/gradio/issues/5143. I think we'll need a way to expose a way to increase the timeout

**Closed by abidlabs** 2024-03-14 14:30 UTC
Labels: bug, pending clarification

**Comment by datalee** [comment] 2024-07-31 04:59
mark
