### ISSUE TITLE
Improve Chatbot type in client

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#4386] opened 2023-06-01 05:48 UTC
### Describe the bug

If you connect to a chatbot app via client, the `view_api` method will say that the expected data is a filepath to a JSON file but that's not very helpful. 

It would be better if we specified that this is a list of lists where each sublist follows the [user-msg, bot-msg] pattern.

We should also consider letting users pass in a list of lists directly by default as opposed to having to read/write json files. Maybe this latter point is a 4.0 thing.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```python
import gradio as gr
import random
import time

with gr.Blocks() as demo:
    with gr.Row():
        with gr.Column(scale=1, min_width=600):
                chatbot = gr.Chatbot()
                msg = gr.Textbox()
                clear = gr.Button("Clear")


    def user(user_message, history):
        return "", history + [[user_message, None]]

    def bot(history):
        bot_message = random.choice(["Yes", "No"])
        history[-1][1] = bot_message
        time.sleep(1)
        return history

    msg.submit(user, [msg, chatbot], [msg, chatbot], queue=False).then(
        bot, chatbot, chatbot, api_name="predict"
    )
    clear.click(lambda: None, None, chatbot, queue=False)

demo.launch(debug=True)
```

<img width="589" alt="image" src="https://github.com/gradio-app/gradio/assets/41651716/47bd4c99-9369-44eb-9abe-4713153bf6bf">

### Logs

```shell
-
```

### System Info

```shell
3.31.0
```

### Severity

annoying

**Comment by pngwn** [comment] 2023-06-01 05:58
This is true for almost all of the 'JSON' components.

**Comment by abidlabs** [comment] 2023-06-01 08:46
Dupe of #4129?

**Comment by pngwn** [comment] 2023-06-01 14:09
Kinda, #4129 issue seems to be about files (which is specific to the python client) but this is more the fact that we don't really list the full schema for most components anywhere. We discussed this a short while ago when discussing the clients.

This also relates to the idea of splitting out the 'type' or 'schema' information from the serializers. The JSON serializer is appropriate for these components, it just isn't very useful for the `info` endpoint.

**Comment by freddyaboulton** [comment] 2023-08-06 19:29
I think we'll have a holistic solution to this in 4.0 but we should look at a possible fix for chatbots since I've seen confusion about this.

**Closed** 2023-11-03 15:59 UTC
Labels: enhancement
