### ISSUE TITLE
How can I manually change the value of a control?

### ISSUE THREAD

**Issue by DoiiarX** [gradio-app/gradio#8342] opened 2024-05-21 09:17 UTC
I have a scenario where I need to monitor changes in a folder. When the folder changes, I will call a function to refresh the file list and then reload it.

I apologize for asking this question. But the resources I currently see all require users to manually trigger.

**Comment by freddyaboulton** [comment] 2024-05-21 15:30
Sounds like a duplicate of https://github.com/gradio-app/gradio/issues/7788

**Comment by DoiiarX** [comment] 2024-05-23 11:13
> Sounds like a duplicate of #7788

My code is here. I never use FileExplorer.

https://github.com/gradio-app/gradio/pull/8357/files/ff11bc69558159e084ac1080fad014c7113d30ba

**Comment by abidlabs** [comment] 2024-05-23 20:09
Hi @DoiiarX I think you may have pasted the wrong link -- I don't see code for a Gradio app. Can you please provide a minimal code example that we can use to reproduce the issue?

**Comment by abidlabs** [comment] 2024-05-27 05:03
I'll go ahead and close for now, but we can reopen with more details.

**Closed by abidlabs** 2024-05-27 05:03 UTC
Labels: pending clarification
