### ISSUE TITLE
Gradio doesn't work on older IOS versions

### ISSUE THREAD

**Issue by thedirptastic** [gradio-app/gradio#2689] opened 2022-11-21 20:45 UTC
### Describe the bug

Whenever I try to use a website using Gradio, my phone (IOS 12.5) shows a blank webpage. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Grab an old IOS device (I think before IOS 14.8)
Visit a site using Gradio

### Screenshot

![51C074D5-9D60-4369-877B-1799A7019CFE](https://user-images.githubusercontent.com/80712226/203154423-b11668a1-4409-4fe8-8398-39924895405e.png)

### Logs

```shell
As I am not hosting, I do not have logs. I would assume that there are no errors in console, as I have tried this with multiple sites.
```

### System Info

```shell
3.10.1 (Latest), IOS 12.5.5, Safari (Also tried on chrome)
```

### Severity

blocking all usage of gradio

**Comment by abidlabs** [comment] 2022-11-23 04:55
Hi @thedirptastic thanks for bringing this to our attention. I do not think we have the resources to investigate performance on iOS 12 or older versions. If you are able to investigate this and let us know the underlying issue, we can look into a fix, but otherwise, I'm inclined to close this issue.

**Comment by thedirptastic** [comment] 2022-11-23 18:19
I suspect it is a css issue, and there are no errors in console. I do understand that IOS 12 is old but I have been told the bug persists until IOS 14.5. If you can’t look into this, I understand, but I hope this is enough info to look into this problem.

**Comment by abidlabs** [comment] 2023-01-13 14:21
Sorry @thedirptastic, but we can't reproduce this issue. Besides #2646, we have not found any gradio-related issues on iOS devices, so I'll go ahead and close this.

**Closed by abidlabs** 2023-01-13 14:21 UTC
Labels: bug
