### ISSUE TITLE
UserWarning: The `style` method is deprecated

### ISSUE THREAD

**Issue by Valdanitooooo** [gradio-app/gradio#4874] opened 2023-07-11 08:06 UTC
When I use gradio version 3.35.2, I get this warning:
```
UserWarning: The `style` method is deprecated. Please set these arguments in the constructor instead
```

Then how should I set the height style of my chatbot to be 100% ? 

```
chatbot = gr.Chatbot(elem_id="chat_chatbot", label="Chat").style(height="100%")
```

I have seen #4374 , and the construction method of Chatbot, only see a height argument of type int.

**Comment by abidlabs** [comment] 2023-07-12 03:56
Duplicate of https://github.com/gradio-app/gradio/issues/4001, we don't currently have a way to do full height elements in gradio

**Closed by abidlabs** 2023-07-12 03:56 UTC
