### ISSUE TITLE
Have pointers on how to pass token to use via API

### ISSUE THREAD

**Issue by merveenoyan** [gradio-app/gradio#3250] opened 2023-02-20 23:45 UTC
I absolutely love _use via API_ feature of gradio Spaces, it would be nice to put a pointer on where the token should go in the request. I figured it out after second try but not everyone might be able to figure it out.

**Comment by abidlabs** [comment] 2023-02-21 10:41
Thanks @merveenoyan! Definitely agree that this an important problem and I'll take it on this week. I believe that it is a duplicate of this issue here, though: #2569 so let me close this. (Feel free to reopen if I'm mistaken)

**Closed by abidlabs** 2023-02-21 10:41 UTC
