### ISSUE TITLE
I cannot use CUDA in Gradio.

### ISSUE THREAD

**Issue by Arkye20** [gradio-app/gradio#8036] opened 2024-04-16 08:46 UTC
### Describe the bug

I have a python venv that has pytorch installed and a ML function that uses cuda functions. I can run the function with cuda perfectly and torch.cuda.is_available() returns True. But as I integrate the function to a Gradio web code I cant use cuda anymore. I tested the output of torch.cuda.is_available() it returns False in Gradio code. How can I fix this?
Is Gradio has a built-in python venv or other problem that I dont know?

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
with gr.Blocks() as demo:
    input_img = gr.Image()
    output_img = gr.Image()
    detect_btn = br.Button()
    detect_btn.click(fn=my_function, inputs=input_img, outputs=output_img)

def my_function(input_img):
    print(torch.cuda.is_available()) # This code returns False
    # This is the function that I have and I can run perfectly outside this file
    # It uses cuda but I can run it here
    output_img = object_detection(input_img) 
    return output_img

demo.launch()
```

### System Info

```shell
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.2.0
fastapi: 0.108.0
ffmpy: 0.3.2
gradio-client==0.14.0 is not installed.
httpx: 0.27.0
huggingface-hub: 0.22.1
importlib-resources: 6.4.0
jinja2: 3.1.3
markupsafe: 2.1.3
matplotlib: 3.8.0
numpy: 1.24.3
orjson: 3.10.0
packaging: 23.1
pandas: 2.2.1
pillow: 10.2.0
pydantic: 2.5.3
pydub: 0.25.1
python-multipart: 0.0.9
pyyaml: 6.0.1
ruff: 0.3.4
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.9.0
uvicorn: 0.29.0
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.10.0
httpx: 0.27.0
huggingface-hub: 0.22.1
packaging: 23.1
typing-extensions: 4.9.0
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment] 2024-04-18 19:09
Hi @Arkye20. I can't reproduce this issue. I ran your code on a Colab notebook with GPU enabled, and it correctly printed that: https://colab.research.google.com/drive/1PPPu7sJHD0W9VvRuv7uDCOQL3DSeUwu_?usp=sharing

**Comment by abidlabs** [comment] 2024-04-21 06:54
Closing for lack of follow up. We can reopen if needed once we have a repro

**Closed by abidlabs** 2024-04-21 06:54 UTC
Labels: bug, needs repro
