### ISSUE TITLE
Public URL not working

### ISSUE THREAD

**Issue by Adeel-Intizar** [gradio-app/gradio#1348] opened 2022-05-20 10:53 UTC
Hi, 
![image](https://user-images.githubusercontent.com/56041154/169513108-a53650f8-70fa-4614-9d31-97499c9aae30.png)
I created a gradio Interface with public url, local url is working 
![image](https://user-images.githubusercontent.com/56041154/169513206-b4c152ec-3300-4172-af3f-1010915659ec.png)
fine, but public url is not working

**Comment by abidlabs** [comment] 2022-05-21 20:39
I can't reproduce this on my end @Adeel-Intizar. Are you using the latest version of `gradio` and is still an issue?

**Comment by Adeel-Intizar** [comment] 2022-05-22 09:06
I am using latest version

**Comment by Adeel-Intizar** [comment] 2022-05-23 06:58
![image](https://user-images.githubusercontent.com/56041154/169761534-0096cdd4-67cd-4cb4-9a40-0a902d9b3f2c.png)

**Comment by abidlabs** [comment] 2022-05-23 20:43
Can you please provide more details: what OS / browser are you using? Are you sure the device that you are running Gradio on has internet connection?

**Comment by Adeel-Intizar** [comment] 2022-05-24 05:34
OS: Windows 10 Pro 21H1
Browsers: Chrome, Opera
Device has internet connection

**Comment by abidlabs** [comment] 2022-07-11 09:20
Seems like the same issue as here: https://github.com/gradio-app/gradio/issues/1193. I've tried to reproduce this on my end, but cannot.

Can you please test on a colab notebook and see if you are experiencing the same issue? If colab works for you, can you let us know more about what might be different in your network, so that we can fix the underlying issue?

**Comment by freddyaboulton** [comment] 2022-08-01 15:33
@Adeel-Intizar Can you please let us know if the problem persists while running on google colab?

**Comment by abidlabs** [comment] 2022-08-08 01:36
Going to close the issue for now. @Adeel-Intizar if the bug is still present, please feel free to reopen the issue with more details.

**Closed by abidlabs** 2022-08-08 01:36 UTC
Labels: bug, pending clarification
