### ISSUE TITLE
DataFrame component resets heading when empty

### ISSUE THREAD

**Issue by vladmandic** [gradio-app/gradio#4845] opened 2023-07-09 12:43 UTC
### Describe the bug

when using `gradio.DataFrame` component, it will show correct headers if there is any data in the component.
but when component has no data, it resets headers to just numbers

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

create `DataFrame` with some data and custom headers. it will show correct headers.
now set data to empty and update - headers reset to showing just numbers.

### Screenshot

correct one:
![image](https://github.com/gradio-app/gradio/assets/57876960/4213db4e-a4d1-4567-aca8-dff2cdaa65d4)

incorrect one:
![image](https://github.com/gradio-app/gradio/assets/57876960/557aeeb3-2339-47de-86b8-87b7dbb6bb7e)

### System Info

```shell
gradio 3.32.0 on ubuntu 22.04 with client being windows 11 and edge 114
```

### Severity

I can work around it

**Comment by abidlabs** [comment] 2023-07-31 14:25
@vladmandic this is actually the intended behavior. The reason is that the headers are a property of the data, not of the `gr.DataFrame` object. So if you want to keep the headers while making the data, you should pass in the headers as part of the dictionary from your function. To give a concrete example, this is how you can preserve headers while clearing the data:

```py
import gradio as gr
import pandas as pd

df = pd.DataFrame({"nums": [1, 2, 3], "sums": [1, 2, 3]})

def clear():
    return {"headers": ["nums", "sums"], "data":[[]]}

with gr.Blocks() as demo:
    d = gr.DataFrame(df)
    b = gr.Button()
    b.click(clear, None, d)

demo.launch()
```

I'll close this issue for now.

Note for @aliabid94: this behavior *will* change if we do a a single config-per-session because in that case headers would become a property of the `gr.DataFrame` object instead of the data. (But probably something most users want)

**Closed by abidlabs** 2023-07-31 14:25 UTC
Labels: bug

**Comment by vladmandic** [comment] 2023-08-01 18:43
@abidlabs unfortunately, i can't seem to get it working as you describe - upon creation `gr.DataFrame` has no column labels if number of rows is 0.

actualy code:
```python
model_headers = ['name', 'type', 'filename', 'hash', 'added', 'size', 'metadata']
model_data = []
model_table = gr.DataFrame(
    data = model_data,
    headers = model_headers,
    label = 'Model data',
    show_label = True,
    interactive = False,
    wrap = True,
    overflow_row_behaviour = 'paginate',
    max_rows = 50,
)
```

**Comment by vladmandic** [comment] 2023-08-02 06:23
that is one of the variants i've tried, it doesn't work.
perhaps its fixed in newer versions of gradio, but i'm blocked from upgrading from version 3.32.0 due to other issues present in newer versions.

**Comment by abidlabs** [comment] 2023-08-02 15:57
Hi @vladmandic we can't go back and patch older versions so let's instead fix the issues you're facing in the newer versions. Can you point to those issues or create new issues and we'll take a look?
