### ISSUE TITLE
Some Block-based gradio apps cannot be used with `gr.load`

### ISSUE THREAD

**Issue by juanluisrto** [gradio-app/gradio#7480] opened 2024-02-19 19:05 UTC
### Describe the bug

Im trying to load a space with `gr.load`. The gradio app loads but whenever I try to input anything I get an IndexError which looks pretty  nasty.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python3
import gradio as gr
demo = gr.load("spaces/troper/assistant")
demo.launch()
```

### Logs

```shell
File "/Users/juanluis/miniconda3/envs/doc/lib/python3.10/site-packages/gradio_client/client.py", line 1141, in _gather_files
    if self.input_component_types[i].value_is_file:
IndexError: list index out of range
```

### System Info

```shell
This is gradio==4.19.1
MacBook Pro M1
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment] 2024-03-14 20:21
Hi @juanluisrto I have a PR (https://github.com/gradio-app/gradio/pull/7706) that fixes this issue partially. You can try it out by installing `gradio` from this branch with this command:

You'll be able to load the demo, but running the demo still gives me errors. I'm having a hard time pinning down what the issue is. It might actually be fixed if you upgrade the version of `gradio` in the "troper/assistant' space to `4.21`. I would do it myself, but that Space has several secrets that need to be supplied for it to work properly.

Alternatively, and this would be quite helpful, is if you can create a simplified test Space that doesn't `gr.load` for you, in which case we can test that locally and use it as a repro to solve this issue.

Thanks!

**Comment by abidlabs** [comment] 2024-03-15 14:51
For example, I built a simplified version of your Space (without any external dependencies) here: https://huggingface.co/spaces/abidlabs/gr_load_test

And it loads correctly using `gradio` from the `main` branch:

```py
import gradio as gr

gr.load("abidlabs/gr_load_test", src="spaces").launch()
```

You can try installing gradio from the main branch in your own Space and see if it fixes the issue. If not, it would be great if you can share a simplified repro like this for us to investigate. Thanks! I'll close this issue for now but can reopen if needed.

**Closed by abidlabs** 2024-03-15 14:51 UTC
Labels: bug, needs repro
