### ISSUE TITLE
[REGRESSION again] Accordion close behavior back in gradio 4.22.0

### ISSUE THREAD

**Issue by pseudotensor** [gradio-app/gradio#7786] opened 2024-03-21 20:12 UTC
Accordion either pops open and while streaming cannot be closed, or other way it closes and cannot be opened, depending upon where the elements are.

Reproduction
pops-open no matter what repro is below. If you need a repro of case where it pops-close no matter, let me know.

```python
import time

import gradio as gr

with gr.Blocks() as demo:
    with gr.Column():
        with gr.Accordion():
            image = gr.Image()
        with gr.Tabs():
            with gr.Tab("Chat"):
                chatbot = gr.Chatbot()
                msg = gr.Textbox()
                clear = gr.Button("Clear")
            with gr.Tab("Other"):
                msg2 = gr.Textbox()

    def user(user_message, history):
        return "", history + [[user_message, None]]

    def bot(history):
        history[-1][1] = ''
        for msg in range(0, 10000):
            history[-1][1] += str(msg)
            if msg % 100 == 0:
                history[-1][1] += '\n'
            time.sleep(0.01)
            yield history

    msg.submit(user, [msg, chatbot], [msg, chatbot], queue=False).then(
        fn=bot, inputs=chatbot, outputs=chatbot, api_name='bot',
    )
    clear.click(lambda: None, None, chatbot, api_name='clear')

demo.queue()
demo.launch()
```

**Comment by abidlabs** [comment] 2024-03-21 20:15
Agggh that really sucks I thought we had a test for this. cc @hannahblair @pngwn if you have bandwidth could you take a look?

**Comment by pseudotensor** [comment] 2024-03-21 20:36
I confirmed by going back and forth from 4.20.1 vs. 4.22.0.  I didn't try between, so unsure if really 4.22.0 when hit.  I can bisect.

**Comment by pseudotensor** [comment] 2024-03-21 20:43
4.21.0 is also ok.  So only 4.22.0 is bad.

**Comment by pngwn** [comment] 2024-03-21 21:50
Hmm, this is weird. We also _do_ have a test for this.

**Comment by pngwn** [comment] 2024-03-21 21:50
Clearly not a very reliable one, will take a look.

**Comment by pseudotensor** [comment] 2024-03-29 16:07
Any progress here?

With https://github.com/gradio-app/gradio/issues/7882 I am stuck on 4.21.0 as all other new releases are DOA.

**Comment by pseudotensor** [comment] 2024-03-29 16:07
Any progress here?

With https://github.com/gradio-app/gradio/issues/7882 I am stuck on 4.21.0 as all other new releases are DOA.

**Comment by pseudotensor** [comment] 2024-03-29 17:52
Note that the exact same repro that failed in original issue still fails here.  Can this be fixed please?

Thanks!

```
import time

import gradio as gr

with gr.Blocks() as demo:
    with gr.Column():
        with gr.Accordion():
            image = gr.Image()
        with gr.Tabs():
            with gr.Tab("Chat"):
                chatbot = gr.Chatbot()
                msg = gr.Textbox()
                clear = gr.Button("Clear")
            with gr.Tab("Other"):
                msg2 = gr.Textbox()

    def user(user_message, history):
        return "", history + [[user_message, None]]

    def bot(history):
        history[-1][1] = ''
        for msg in range(0, 10000):
            history[-1][1] += str(msg)
            if msg % 100 == 0:
                history[-1][1] += '\n'
            time.sleep(0.01)
            yield history

    msg.submit(user, [msg, chatbot], [msg, chatbot], queue=False).then(
        fn=bot, inputs=chatbot, outputs=chatbot, api_name='bot',
    )
    clear.click(lambda: None, None, chatbot, api_name='clear')

demo.queue()
demo.launch()
```

**Comment by pngwn** [comment] 2024-04-01 19:24
Yep, it will be fixed when get round to it. No need to keep replying. We are aware of the issue and repeatedly 'bumping' issues will not change anything.

**Comment by pseudotensor** [comment] 2024-04-01 20:04
That's a slightly disappointing response @pngwn .  I posted the repro because I wasn't aware that it was obvious that there was a repro.

Sorry for participating.

**Comment by pngwn** [comment] 2024-04-02 00:53
https://github.com/gradio-app/gradio/issues/7786#issuecomment-2027429138 was posted prior to the repro. That is an obvious 'bump' with no additional information.

**Comment by pseudotensor** [comment] 2024-04-02 00:56
I see, I will no longer contribute.  Thanks for your negativity.

**Comment by abidlabs** [comment] 2024-04-02 01:20
Hi @pseudotensor, I think this is an overreaction to @pngwn's request to stop bumping this and other issues. We are a relatively small team and constant notifications on issues are distracting. It also pollutes issue threads and makes it harder for us to read through and quickly get to important information such as the repro for each issue. That being said, we do sincerely appreciate your contributions and your willingness to work with us. I would personally appreciate if you could reopen the issues that are still present in `gradio` so that we can continue to work through them

**Comment by aliabid94** [comment] 2024-04-02 23:09
I'm not able to reproduce this.

**Comment by abidlabs** [comment] 2024-04-03 06:55
@aliabid94 I was able to reproduce it (I'm unable to close the accordion while the text is streaming):


https://github.com/gradio-app/gradio/assets/1778297/3afdd46a-fb31-4a45-8d6b-3189e87d3af6

**Comment by 1100111GTH** [comment] 2024-04-07 16:26
https://github.com/gradio-app/gradio/assets/154310050/3046ab1e-53f2-4c3c-89b9-9611423eb933

same problem

**Comment by 1100111GTH** [comment] 2024-04-07 16:29
click then close is not what i trying to do, but it's just happend.

**Comment by pngwn** [comment] 2024-04-08 12:21
This happens with the built files but doesn't happen in dev mode, not sure why but possibly a race condition. Investigating. Not sure why the test passes will also check that.

**Closed** 2024-04-08 17:12 UTC
Labels: bug, Priority, Regression
