### ISSUE TITLE
Make gr.Tab visibility configurable

### ISSUE THREAD

**Issue by snowarea1994** [gradio-app/gradio#4898] opened 2023-07-12 15:57 UTC
### Describe the bug

![image](https://github.com/gradio-app/gradio/assets/18032043/9b371922-63af-4a86-9298-2d9939ccbc82)
![image](https://github.com/gradio-app/gradio/assets/18032043/5c616e68-dff1-4281-86b9-57c62047b9f2)

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

import gradio as gr

def greet(tabs):
    return tabs.append("tab")

def add_tab(k):
    k = int(k)
    return [gr.update(visible=True)] * k + [gr.update(visible=False)] * (max_tabs - k)

max_tabs = 10

with gr.Blocks() as demo:
    with gr.Row():
        btn_import = gr.Button("导入数据")
        btn_analysis = gr.Button("解析数据")
        btn_export = gr.Button("导出结果")
    s = gr.Slider(1, 10, value=10, step=1, label="How many textboxes to show:")
    tabs = []
    with gr.Tab(label="隐藏", visible=False) as tab:
        gr.Dataframe(row_count=(2, "dynamic"), col_count=(4, "dynamic"), label="Input Data", interactive=True)
    for i in range(max_tabs):
        with gr.Tab(label="tab" + str(i), visible=False) as tab:
            gr.Dataframe(row_count=(2, "dynamic"), col_count=(4, "dynamic"), label="Input Data", interactive=True,
                         visible=False)
        tabs.append(tab)

    # s.change(fn=add_tab, inputs=s, outputs=tabs)
demo.launch()

### System Info

```shell
Version: 3.28.3
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment] 2023-07-13 18:18
Hi @snowarea1994 - `gr.Tab` cannot be made visible right now. It's not a part of the api - look at the `Tab` here: https://www.gradio.app/docs/block-layouts

I think this enhancement can be made though.

**Comment by abidlabs** [comment] 2023-07-13 18:32
Duplicate of #2592, please follow that issue @snowarea1994

**Closed by abidlabs** 2023-07-13 18:32 UTC
Labels: enhancement
