### ISSUE TITLE
Error loading resources when in http

### ISSUE THREAD

**Issue by BardiaKh** [gradio-app/gradio#2699] opened 2022-11-22 16:50 UTC
### Describe the bug

When running gradio demo locally without SSL (over HTTP) sodium.js fails to instantiate WebAssembly in Chrome. It seems that this is the case in HTTP and to fix that you have to pass in a CSP meta tag ([source](https://github.com/jedisct1/libsodium.js/issues/196#issuecomment-489232730)).

I did try to change the `/templates/frontend/index.html' to include the mentioned tag but it seems the HTML is being rendered from somewhere else as I don't see the tag being used in the final web app.

Can you please tell me where are the tags come from and how one tag can be added as a quick fix?

This causes the UI to be messed up, for example there would be two down arrows for dropdowns or the slider position is off.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

This is a demo I put together:

http://35.194.44.16:1900/

You will see the error if you open the dev console in chrome. Also, the UI elements are not rendered correctly.

This happens with any local demo in HTTP.

### Screenshot

![image](https://user-images.githubusercontent.com/13269112/203371081-39e0d358-be61-487d-a882-8112318b1817.png)

![image](https://user-images.githubusercontent.com/13269112/203372928-2753036b-0261-471e-957a-fbd1118999b1.png)

### Logs

```shell
JS Console:

Uncaught (in promise) RuntimeError: Aborted(CompileError: WebAssembly.instantiate(): ). Build with -s ASSERTIONS=1 for more info.
    at x (sodium.js:1:304371)
    at sodium.js:1:447655
```

### System Info

```shell
Gr version: 3.9.1
OS: Ubuntu
Browser: Chrome / Edge [Safari is fine]
```

### Severity

blocking all usage of gradio

**Comment by abidlabs** [comment] 2022-11-27 06:04
Hi @BardiaKh started looking into this but everything looks fine to me:

<img width="1126" alt="image" src="https://user-images.githubusercontent.com/1778297/204121633-95d434bf-4825-415a-964c-08d81dde0dab.png">

Were you able to fix the issue or is it still broken on your end?

**Comment by abidlabs** [comment] 2022-12-10 05:12
Will close this issue as it looks like it was solved or the reproducer doesn't work. Please feel free to reopen if this is still a problem @BardiaKh with a fresh repro

**Closed by abidlabs** 2022-12-10 05:12 UTC
Labels: bug
