### ISSUE TITLE
New port for every cell

### ISSUE THREAD

**Issue by shaileshj2803** [gradio-app/gradio#401] opened 2021-12-11 22:24 UTC
I am using jupyter notebook with gradio running on a docker image. I have setup port forwarding to port 7777 and i have launched gradio server using 0.0.0.0 and port 7777. For first run everything is fine. If i use gradio in other cell or or or re-run the same cell it everytime starts the server on new port for eg 7778, 7779 etc. Can you please help? The share is set to false.

**Comment by abidlabs** [comment] 2021-12-11 23:14
Yes this is the expected behavior because the first interface continues running on port 7777, which means the subsequent interface must find a new open port. If you’d like to reuse the port, then close the interface by calling the ‘close()’ function of the  ‘Interface’ object

**Comment by abidlabs** [comment] 2021-12-13 16:26
Closing, but feel free to open if this does not resolve your issue. Thanks!

**Closed by abidlabs** 2021-12-13 16:26 UTC
Labels: question
