### ISSUE TITLE
huggingface examples bug

### ISSUE THREAD

**Issue by Zengyf-CVer** [gradio-app/gradio#1484] opened 2022-06-08 00:00 UTC
### Describe the bug

When I click on Examples, all components don't work:
My project link: https://huggingface.co/spaces/Zengyf-CVer/Gradio_YOLOv5_Det_v4

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

![ksnip_20220608-075913](https://user-images.githubusercontent.com/41098760/172503164-48ac3534-0770-44f4-9c67-2c7fa76efddf.png)

### Logs

```shell
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/gradio/routes.py", line 255, in run_predict
    output = await app.blocks.process_api(
  File "/home/user/.local/lib/python3.8/site-packages/gradio/blocks.py", line 538, in process_api
    predictions, duration = await self.call_function(fn_index, processed_input)
  File "/home/user/.local/lib/python3.8/site-packages/gradio/blocks.py", line 452, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/user/.local/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/user/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/user/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/user/.local/lib/python3.8/site-packages/gradio/interface.py", line 599, in load_example
    processed_examples += load_from_cache(self, example_id)
  File "/home/user/.local/lib/python3.8/site-packages/gradio/process_examples.py", line 62, in load_from_cache
    component.restore_flagged(
  File "/home/user/.local/lib/python3.8/site-packages/gradio/components.py", line 3001, in restore_flagged
    return json.loads(data)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

### System Info

```shell
gradio 3.0.13
huggingface spaces
```

### Severity

annoying

**Comment by abidlabs** [comment] 2022-06-08 04:15
Thanks @Zengyf-CVer it looks like this might be related to a recent change with cached examples. @dawoodkhan82 can you please take a look?

**Comment by abidlabs** [comment] 2022-06-08 04:32
@Zengyf-CVer was this Space previously working in `gradio==3.0.12`?

**Comment by Zengyf-CVer** [comment] 2022-06-08 04:51
@abidlabs  Doesn't work, it's always been that way.

**Comment by Zengyf-CVer** [comment] 2022-06-17 23:21
@abidlabs  I upgraded gadio to 3.0.18, but the problem is still not solved.

**Comment by Zengyf-CVer** [comment] 2022-08-23 23:28
@abidlabs I upgraded gradio to 3.1.8b0, but it still fails.
![ksnip_20220824-072705](https://user-images.githubusercontent.com/41098760/186283501-13a79c8c-7024-4121-9ee1-a5c9c44e44f1.png)

**Comment by abidlabs** [comment] 2022-08-23 23:35
It looks like one of the outputs might be `None`, which is causing the example caching to fail, perhaps? Given the complexity of your Space, it's going to be very hard to figure out what exactly is the issue.

If you can please come back with a minimal example of this error, we can take another look it.

**Comment by Zengyf-CVer** [comment] 2022-08-23 23:55
@abidlabs 
I made an example of single image input and output, and it works fine. I'm guessing this error is caused by some input or some combination of inputs in my program. I need some time to build a minimal example.

**Comment by abidlabs** [comment] 2022-08-24 20:50
No problem, take your time. Let me close the issue for now so that we can focus on issues that we are able to reproduce, but if you are able to find a minimal example, please feel free to reopen the issue. Thanks!

**Closed by abidlabs** 2022-08-24 20:50 UTC
Labels: bug, needs repro
