### ISSUE TITLE
[Bug]:No module named 'gradio.floating'

### ISSUE THREAD

**Issue by Daydream0929** [gradio-app/gradio#6498] opened 2023-11-20 13:30 UTC
### Describe the bug

Python3.11 gradio
ModuleNotFoundError: No module named 'gradio.floating'
but Python3.9 No Error
I don't know why

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

import gradio.floating

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/61659904/e60b0bdf-ab95-427d-b5b3-2c8508bc602e)

### System Info

```shell
gradio 3.32.6 
python 3.9
MacOS
```

### Severity

I can work around it

**Comment by abidlabs** [comment] 2023-11-20 16:12
Hi @Daydream0929 I can't reproduce this error. Can you try uninstalling gradio and installing a recent version of gradio, such as `4.4.1`?

**Comment by abidlabs** [comment] 2023-11-21 20:03
Closing as this module does not actually exist

**Closed by abidlabs** 2023-11-21 20:03 UTC
Labels: bug, pending clarification
