### ISSUE TITLE
When I used gradio in win11 system, had a "httpx.ReadTimeout: timed out" problem

### ISSUE THREAD

**Issue by xuehua312741499** [gradio-app/gradio#7644] opened 2024-03-08 08:09 UTC
### Describe the bug

My code:
# coding:utf-8
import os
import gradio as gr
os.environ['GRADIO_ANALYTICS_ENABLED'] = "False"
def greet(name):
    return "Hello " + name + "!"
if __name__ == '__main__':
    demo = gr.Interface(fn=greet,
                        inputs=[gr.Textbox(label='Text to summarize', lines=6)],
                        outputs=[gr.Textbox(label="Result", lines=6)],
                        title="Text summarization with distilbart-cnn",
                        description="Summarize any text using the `shleifer/distilbart-cnn-12-6` model under the hood!"
                        )
    demo.launch(share=False, ssl_verify=False)
=error===========================================
https://api.gradio.app/gradio-messaging/en
Running on local URL:  http://127.0.0.1:7860
http://127.0.0.1:7860/startup-events
Traceback (most recent call last):
  File "D:\SDK\anaconda3\envs\python3\lib\site-packages\httpx\_transports\default.py", line 69, in map_httpcore_exceptions
    yield
  File "D:\SDK\anaconda3\envs\python3\lib\site-packages\httpx\_transports\default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
  File "D:\SDK\anaconda3\envs\python3\lib\site-packages\httpcore\_sync\connection_pool.py", line 216, in handle_request
    raise exc from None
  File "D:\SDK\anaconda3\envs\python3\lib\site-packages\httpcore\_sync\connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "D:\SDK\anaconda3\envs\python3\lib\site-packages\httpcore\_sync\http_proxy.py", line 207, in handle_request
    return self._connection.handle_request(proxy_request)
  File "D:\SDK\anaconda3\envs\python3\lib\site-packages\httpcore\_sync\connection.py", line 101, in handle_request
    return self._connection.handle_request(request)
  File "D:\SDK\anaconda3\envs\python3\lib\site-packages\httpcore\_sync\http11.py", line 143, in handle_request
    raise exc
  File "D:\SDK\anaconda3\envs\python3\lib\site-packages\httpcore\_sync\http11.py", line 113, in handle_request
    ) = self._receive_response_headers(**kwargs)
  File "D:\SDK\anaconda3\envs\python3\lib\site-packages\httpcore\_sync\http11.py", line 186, in _receive_response_headers
    event = self._receive_event(timeout=timeout)
  File "D:\SDK\anaconda3\envs\python3\lib\site-packages\httpcore\_sync\http11.py", line 224, in _receive_event
    data = self._network_stream.read(
  File "D:\SDK\anaconda3\envs\python3\lib\site-packages\httpcore\_backends\sync.py", line 126, in read
    return self._sock.recv(max_bytes)
  File "D:\SDK\anaconda3\envs\python3\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\SDK\anaconda3\envs\python3\lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ReadTimeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Workplace\SecGPT-main\SecGPT-main\secgpt-mini\sec_start.py", line 20, in <module>
    demo.launch(share=False, ssl_verify=False)
  File "D:\SDK\anaconda3\envs\python3\lib\site-packages\gradio\blocks.py", line 2087, in launch
    httpx.get(f"{self.local_url}startup-events", verify=ssl_verify)
  File "D:\SDK\anaconda3\envs\python3\lib\site-packages\httpx\_api.py", line 198, in get
    return request(
  File "D:\SDK\anaconda3\envs\python3\lib\site-packages\httpx\_api.py", line 106, in request
    return client.request(
  File "D:\SDK\anaconda3\envs\python3\lib\site-packages\httpx\_client.py", line 827, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "D:\SDK\anaconda3\envs\python3\lib\site-packages\httpx\_client.py", line 914, in send
    response = self._send_handling_auth(
  File "D:\SDK\anaconda3\envs\python3\lib\site-packages\httpx\_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
  File "D:\SDK\anaconda3\envs\python3\lib\site-packages\httpx\_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
  File "D:\SDK\anaconda3\envs\python3\lib\site-packages\httpx\_client.py", line 1016, in _send_single_request
    response = transport.handle_request(request)
  File "D:\SDK\anaconda3\envs\python3\lib\site-packages\httpx\_transports\default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
  File "D:\SDK\anaconda3\envs\python3\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\SDK\anaconda3\envs\python3\lib\site-packages\httpx\_transports\default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
**httpx.ReadTimeout: timed out**

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

# coding:utf-8
import os

import gradio as gr

os.environ['GRADIO_ANALYTICS_ENABLED'] = "False"

def greet(name):
    return "Hello " + name + "!"

if __name__ == '__main__':
    demo = gr.Interface(fn=greet,
                        inputs=[gr.Textbox(label='Text to summarize', lines=6)],
                        outputs=[gr.Textbox(label="Result", lines=6)],
                        title="Text summarization with distilbart-cnn",
                        description="Summarize any text using the `shleifer/distilbart-cnn-12-6` model under the hood!"
                        )
    demo.launch(share=False, ssl_verify=False)

### Logs

```shell
https://api.gradio.app/gradio-messaging/en
Running on local URL:  http://127.0.0.1:7860
http://127.0.0.1:7860/startup-events
Traceback (most recent call last):
  File "D:\SDK\anaconda3\envs\python3\lib\site-packages\httpx\_transports\default.py", line 69, in map_httpcore_exceptions
    yield
  File "D:\SDK\anaconda3\envs\python3\lib\site-packages\httpx\_transports\default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
  File "D:\SDK\anaconda3\envs\python3\lib\site-packages\httpcore\_sync\connection_pool.py", line 216, in handle_request
    raise exc from None
  File "D:\SDK\anaconda3\envs\python3\lib\site-packages\httpcore\_sync\connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "D:\SDK\anaconda3\envs\python3\lib\site-packages\httpcore\_sync\http_proxy.py", line 207, in handle_request
    return self._connection.handle_request(proxy_request)
  File "D:\SDK\anaconda3\envs\python3\lib\site-packages\httpcore\_sync\connection.py", line 101, in handle_request
    return self._connection.handle_request(request)
  File "D:\SDK\anaconda3\envs\python3\lib\site-packages\httpcore\_sync\http11.py", line 143, in handle_request
    raise exc
  File "D:\SDK\anaconda3\envs\python3\lib\site-packages\httpcore\_sync\http11.py", line 113, in handle_request
    ) = self._receive_response_headers(**kwargs)
  File "D:\SDK\anaconda3\envs\python3\lib\site-packages\httpcore\_sync\http11.py", line 186, in _receive_response_headers
    event = self._receive_event(timeout=timeout)
  File "D:\SDK\anaconda3\envs\python3\lib\site-packages\httpcore\_sync\http11.py", line 224, in _receive_event
    data = self._network_stream.read(
  File "D:\SDK\anaconda3\envs\python3\lib\site-packages\httpcore\_backends\sync.py", line 126, in read
    return self._sock.recv(max_bytes)
  File "D:\SDK\anaconda3\envs\python3\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\SDK\anaconda3\envs\python3\lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ReadTimeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Workplace\SecGPT-main\SecGPT-main\secgpt-mini\sec_start.py", line 20, in <module>
    demo.launch(share=False, ssl_verify=False)
  File "D:\SDK\anaconda3\envs\python3\lib\site-packages\gradio\blocks.py", line 2087, in launch
    httpx.get(f"{self.local_url}startup-events", verify=ssl_verify)
  File "D:\SDK\anaconda3\envs\python3\lib\site-packages\httpx\_api.py", line 198, in get
    return request(
  File "D:\SDK\anaconda3\envs\python3\lib\site-packages\httpx\_api.py", line 106, in request
    return client.request(
  File "D:\SDK\anaconda3\envs\python3\lib\site-packages\httpx\_client.py", line 827, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "D:\SDK\anaconda3\envs\python3\lib\site-packages\httpx\_client.py", line 914, in send
    response = self._send_handling_auth(
  File "D:\SDK\anaconda3\envs\python3\lib\site-packages\httpx\_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
  File "D:\SDK\anaconda3\envs\python3\lib\site-packages\httpx\_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
  File "D:\SDK\anaconda3\envs\python3\lib\site-packages\httpx\_client.py", line 1016, in _send_single_request
    response = transport.handle_request(request)
  File "D:\SDK\anaconda3\envs\python3\lib\site-packages\httpx\_transports\default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
  File "D:\SDK\anaconda3\envs\python3\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\SDK\anaconda3\envs\python3\lib\site-packages\httpx\_transports\default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
**httpx.ReadTimeout: timed out**
```

### System Info

```shell
------------------------------
Operating System: Windows
gradio version: 4.20.1
gradio_client version: 0.11.0

gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.2.0
fastapi: 0.110.0
ffmpy: 0.3.2
gradio-client==0.11.0 is not installed.
httpx: 0.27.0
huggingface-hub: 0.20.3
importlib-resources: 6.1.1
jinja2: 3.1.2
markupsafe: 2.1.1
matplotlib: 3.8.0
numpy: 1.26.0
orjson: 3.9.15
packaging: 23.1
pandas: 2.2.1
pillow: 10.0.1
pydantic: 2.6.3
pydub: 0.25.1
python-multipart: 0.0.9
pyyaml: 6.0.1
ruff: 0.3.1
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.9.0
uvicorn: 0.27.1
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.
```

### Severity

I can work around it

**Comment by abidlabs** [comment] 2024-03-08 15:40
Duplicate of https://github.com/gradio-app/gradio/issues/5143, we'll take a look at this!

**Closed by abidlabs** 2024-03-08 15:40 UTC
Labels: bug
