### ISSUE TITLE
Kaggle runtime crashes 

### ISSUE THREAD

**Issue by erfanzar** [gradio-app/gradio#6210] opened 2023-11-01 11:29 UTC
### Describe the bug

kaggle runtime always crashes no matter which runtime type you are using (TPU, CPU, GPU) 
after I run
```python
block.launch(share=True)
```

for example, try this code on Kaggle 

```python
import gradio as gr

with gr.Blocks() as demo:
    with gr.Row():
        with gr.Column():
            Drug = gr.Radio(["Yes","No"])
            Family = gr.Radio(["Yes","No"])
demo.launch()
```

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

with gr.Blocks() as demo:
    with gr.Row():
        with gr.Column():
            Drug = gr.Radio(["Yes","No"])
            Family = gr.Radio(["Yes","No"])
demo.launch()
```

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/59269023/6bbc4bbf-c379-4325-9940-408d753bd7dc)

### Logs

```shell
Keyboard interruption in main thread... closing server.
Killing tunnel 127.0.0.1:7860 <>
```

### System Info

```shell
Kaggle TPU,CPU,GPU
```

### Severity

Blocking usage of gradio

**Comment by erfanzar** [comment] 2023-11-06 10:52
help ?

**Comment by StonkGuy** [comment] 2023-11-09 03:59
I also encountered the same issue while using Gradio on Kaggle. I found a pretty neat workaround: disabling share=true and using a tunneling solution. Personally, only ngrok worked for me. To use this workaround, you'll have to install ngrok with pip (!pip install ngrok) and run it in the same cell with your code. Here's my Kaggle notebook, you can check it out and apply these fixes. https://www.kaggle.com/code/blyatcyka/roop-unleashed-patched

**Comment by abidlabs** [comment] 2024-10-17 21:22
Duplicate of https://github.com/gradio-app/gradio/issues/6132

**Closed by abidlabs** 2024-10-17 21:22 UTC
Labels: bug
