### ISSUE TITLE
Labels below images in gallery

### ISSUE THREAD

**Issue by hwasiti** [gradio-app/gradio#2174] opened 2022-09-03 22:06 UTC
In ML it is common to show details about each of the images such as probabilities. It would be great if there is a way to show labels below each image (filename, probs,...etc.).

**Comment by abidlabs** [comment] 2022-09-05 21:28
Hi @hwasiti thanks for opening the issue! I think this is a duplicate of #2091, correct? I'll close the issue for now, but please feel free to reopen and add more details if this issue is different.

**Closed by abidlabs** 2022-09-05 21:28 UTC
