### ISSUE TITLE
Merge microphone and upload audio components

### ISSUE THREAD

**Issue by osanseviero** [gradio-app/gradio#1593] opened 2022-06-17 13:10 UTC
If you go to https://huggingface.co/spaces/keras-io/english-speaker-accent-recognition-using-transfer-learning, you can either record from microphone or upload an audio file. Would it make more sense to have a single component? As a user, it's confusing to see two different components for the same thing

**Comment by aliabid94** [comment] 2022-06-17 17:14
This makes a lot of sense, the kwarg `source` for Image, Video, and Audio should be able to be set as `source= "all"`, which allows the user to set the soucrce

**Comment by abidlabs** [comment] 2023-02-02 13:21
Here's a code snippet that shows how to achieve this in Blocks: https://huggingface.co/spaces/abidlabs/mic_or_file/blob/main/app.py

**Comment by abidlabs** [comment] 2023-02-06 21:37
Closing as it's a duplicate of https://github.com/gradio-app/gradio/issues/3099 and #3099 has more discussion

**Closed by abidlabs** 2023-02-06 21:37 UTC
Labels: enhancement
