### ISSUE TITLE
Error in gr.ChatInterface() When Pressing Example Questions in grodio-lite.examples

### ISSUE THREAD

**Issue by shirou1217** [gradio-app/gradio#9491] opened 2024-10-01 13:05 UTC
### Describe the bug

In **gr.ChatInterface()** within the **grodio-lite.examples**, I encountered an issue where pressing the example questions causes an error. Previously, the examples were displayed below the chatbot window, and when a user clicked on an example, the content would be pasted into the textbox for editing before submission. However, this week, the behavior changed. Now, when a user clicks on an example, the question is automatically sent to the model, which leads to an error. Interestingly, typing a question manually in the textbox and submitting it does not trigger the same error.

This issue is only present when using gradio-lite in an **HTML browser**. When deploying the same Gradio interface on Hugging Face Spaces, the error does not occur. 
Could there have been a recent modification to the gr.ChatInterface() function that is causing this issue?

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```
<!doctype html>
<html>
  <head>
      <script src="https://cdn.jsdelivr.net/pyodide/v0.27.0a2/full/pyodide.js"></script>  
      <script type="module" crossorigin src="https://cdn.jsdelivr.net/npm/@gradio/lite/dist/lite.js"></script>
	  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@gradio/lite/dist/lite.css" />
  </head>
  <body>
    <gradio-lite theme="light">
        import gradio as gr

        def yes_man(message, history):
            if message.endswith("?"):
                return "Yes"
            else:
                return "Ask me anything!"
        
        gr.ChatInterface(
            yes_man,
            textbox=gr.Textbox(placeholder="Ask me a yes or no question", container=False, scale=7),
            title="Yes Man",
            description="Ask Yes Man any question",
            theme="soft",
            examples=["Hello", "Am I cool?", "Are tomatoes vegetables?"],
            cache_examples=True,            
        ).launch()
    
    </gradio-lite>
  </body>
</html>

```

### Screenshot

<img width="884" alt="image" src="https://github.com/user-attachments/assets/c965611c-3894-4924-9e80-87659f9c193e">

### Logs

```shell
GET file:////static/fonts/ui-monospace/ui-monospace-Regular.woff2 net::ERR_FILE_NOT_FOUND
```

### System Info

```shell
https://cdn.jsdelivr.net/npm/@gradio/lite/dist/lite.js
https://cdn.jsdelivr.net/npm/@gradio/lite/dist/lite.css
```

### Severity

Blocking usage of gradio

**Comment by whitphx** [comment] 2024-11-19 17:30
Thank you for reporting this bug.

With the latest release (5.6.0), the same error does no longer occur.

However this example still doesn't work because `cache_example` is not supported in Lite by nature.
The problem is currently a warning message about it is not shown. #10000 will fixes it, so plz let close this issue with it.

**Closed** 2024-11-20 13:56 UTC
Labels: bug
