### ISSUE TITLE
When I set the default_concurrency_limit parameter higher than 1, the response was confusing when testing concurrency.

### ISSUE THREAD

**Issue by shuaiFLYINTHESKY** [gradio-app/gradio#6866] opened 2023-12-21 18:16 UTC
### Describe the bug

When I set the default_concurrency_limit parameter higher than 1, the response was confusing when testing concurrency.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr


gr.Interface(
        fn=evaluate_llm,
        inputs=[
            gr.components.Textbox(lines=3, label="Instruction", placeholder="Anything you want to ask WizardCoder ?"),
            gr.components.Slider(minimum=0, maximum=1, value=0, label="Temperature"),
            gr.components.Slider(minimum=1, maximum=2048, step=1, value=1024, label="Max tokens")
        ],
        outputs=[gr.components.Textbox(lines=30, label="Output")],
        # queue=True,  
        # batch=True,
        # max_batch_size=4,
        # concurrency_limit=16,
    ).queue(
        max_size=16,  
        default_concurrency_limit=16,  
    ).launch(
        share=True, 
        server_name='0.0.0.0', 
        server_port=port, 
        max_threads=128
   )
```
### Screenshot

![MG111](https://github.com/gradio-app/gradio/assets/98887892/34c2e92d-9458-4c61-b16e-c9a4a0ee2c6c)

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 4.11.0
gradio_client version: 0.7.3

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.1.0
altair: 4.2.2
fastapi: 0.104.1
ffmpy: 0.3.0
gradio-client==0.7.3 is not installed.
httpx: 0.23.3
huggingface-hub: 0.19.4
importlib-resources: 5.12.0
jinja2: 3.1.2
markupsafe: 2.1.2
matplotlib: 3.6.2
numpy: 1.22.4
orjson: 3.8.11
packaging: 23.2
pandas: 1.4.3
pillow: 10.1.0
pydantic: 2.5.2
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.8.0
uvicorn: 0.24.0.post1
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.12.1
httpx: 0.23.3
huggingface-hub: 0.19.4
packaging: 23.2
typing-extensions: 4.8.0
websockets: 11.0.3
```

### Severity

I can work around it

**Comment by shuaiFLYINTHESKY** [comment] 2023-12-21 18:21
I don't know how to set these parameters, doing concurrent tests will generate correct code instead of generating messy code.
Please give me some comments, thank you very much!

**Comment by abidlabs** [comment] 2023-12-21 19:13
Hi @shuaiFLYINTHESKY it sounds like what might be happening is that the user history is not being saved correctly, and it is being shared across sessions. Its a little hard to know for sure without seeing the code for `evaluate_llm`. A few options:

1. Could you share the full code for your app?
2. Or (preferably) provide a minimal code example that we can use to reproduce the issue above? See: https://stackoverflow.com/help/minimal-reproducible-example

Otherwise, I might also suggest the `gr.ChatInterface` class which is designed to handle chatbots and should take care of handling user history correctly. See https://www.gradio.app/guides/creating-a-chatbot-fast

**Comment by shuaiFLYINTHESKY** [comment] 2023-12-22 03:08
> Hi @shuaiFLYINTHESKY it sounds like what might be happening is that the user history is not being saved correctly, and it is being shared across sessions. Its a little hard to know for sure without seeing the code for `evaluate_llm`. A few options:
> 
> 1. Could you share the full code for your app?
> 2. Or (preferably) provide a minimal code example that we can use to reproduce the issue above? See: https://stackoverflow.com/help/minimal-reproducible-example
> 
> Otherwise, I might also suggest the `gr.ChatInterface` class which is designed to handle chatbots and should take care of handling user history correctly. See https://www.gradio.app/guides/creating-a-chatbot-fast


Thanks for your reply. Well, I looked at the gr.ChatInterface class and it might not be what I want. I guess my project is completion and not chat, I don't need to deal with user history, but can handle concurrency properly while completing. But from the screenshots I uploaded, the code generated while testing for concurrency issues is messy.


I deployed wizardcoder locally to generate the code. The inference code is as follows
```
from vllm import LLM, SamplingParams


llm = LLM(model=base_model, tensor_parallel_size=n_gpus)

def evaluate_llm(
        instruction,
        temperature=1,
        max_new_tokens=2048,
    ):
        problem_prompt = (
            "Below is an instruction that describes a task. "
            "Write a response that appropriately completes the request.\n\n"
            "### Instruction:\n{instruction}\n\n### Response:"
        )
        prompt = problem_prompt.format(instruction=instruction)

        problem_instruction = [prompt]
        # stop_tokens = ['</s>']  # Training use this
        stop_tokens = ['<|endogtext|>']  # Inference use this
        sampling_params = SamplingParams(temperature=temperature, top_p=1, max_tokens=max_new_tokens, stop=stop_tokens)
        completions = llm.generate(problem_instruction, sampling_params)
        for output in completions:
            prompt = output.prompt
            print('==========================question=============================')
            print(prompt)
            generated_text = output.outputs[0].text
            print('===========================answer==============================')
            print(generated_text)
            print('=========================answer end============================')
            return generated_text
```

I didn't do concurrency issues in the evaluate_llm() function. I thought Gradio gave it to me, but maybe I didn't use it correctly. I hope you can help me out. I would appreciate it very much.

**Comment by abidlabs** [comment] 2024-01-23 21:23
Hi @shuaiFLYINTHESKY,

I can't reproduce this issue using a minimal code example:

```py
import gradio as gr
import time

def evaluate_llm(x, *args):
    time.sleep(10)
    return x

gr.Interface(
        fn=evaluate_llm,
        inputs=[
            gr.components.Textbox(lines=3, label="Instruction", placeholder="Anything you want to ask WizardCoder ?"),
            gr.components.Slider(minimum=0, maximum=1, value=0, label="Temperature"),
            gr.components.Slider(minimum=1, maximum=2048, step=1, value=1024, label="Max tokens")
        ],
        outputs=[gr.components.Textbox(lines=30, label="Output")],
    ).queue(
        max_size=16,  
        default_concurrency_limit=16,  
    ).launch()
```

The requests are processed concurrently and I get the expected results:

<img width="1355" alt="image" src="https://github.com/gradio-app/gradio/assets/1778297/90f31610-1233-4fb6-acb0-c243bd883db3">

Can you see if you are able to repro the issue without any external dependencies such as vllm? It will help us figure out if the issue with gradio or the external dependencies.

**Comment by abidlabs** [comment] 2024-01-25 01:06
Closing for now, can reopen if we get a suitable repro.

**Closed by abidlabs** 2024-01-25 01:06 UTC
Labels: needs repro
