### ISSUE TITLE
Initial gr.State value is shared accross users, even on page refresh

### ISSUE THREAD

**Issue by jerpint** [gradio-app/gradio#4558] opened 2023-06-17 16:43 UTC
### Describe the bug

In the documentation, it is written for gradio state:

> Special hidden component that stores session state across runs of the demo by the same user. The value of the State variable is cleared when the user refreshes the page.
[link](https://gradio.app/docs/#state-header)

However, I have noticed that this is NOT the case. It seems that the first assigned value to gr.State is in fact shared by ALL users, and NOT reset when a page is refreshed.

This is very problematic, when for example assigning a UUID to each user. In practice, this UUID ends up being shared by all users.

My hypothesis is that the `gr.State` value is being cached somewhere. I cannot confirm this.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Here is a link to a live space with the issue: 

https://huggingface.co/spaces/jerpint/uuid-test

## Issue

I have made 2 textboxes, they are only clickable (no inputs).

1) In the first box, the random number is generated as a `gr.State` when the user accesses the page. You will see that even when refreshing the page, the same random number appears. This is true even in a new incognito window.

2) in the second box, a new random number is appended to the state. The first number is always the same and shared accross sessions. The following numbers are unique, and state is not shared.

I don't know what the exact issue is, but it seems that the first value of `gr.State` is being cached somewhere. This is very problematic when you expect `gr.State` to be a single value assigned at the start of the session that doesn't change.

## Code

I am providing the code (very simple) to reproduce the issue, to make it apparent:

```
import gradio as gr
import uuid
import random

def return_number(number):
    return number

def update_state(state):
    state.append(random.random())
    return state

with gr.Blocks() as demo:

    user_state = gr.State(random.random())
    textbox = gr.Textbox(placeholder="Only the first random state...", label="user state (random number)", value=None)
    button = gr.Button()
    button.click(fn=return_number, inputs=user_state, outputs=textbox)

    user_state_2 = gr.State([str(random.random())])
    textbox_2 = gr.Textbox(placeholder="List of numbers...", label="user state (random number + appended extra numbers)", value=None)
    button_2 = gr.Button()
    button_2.click(fn=update_state, inputs=user_state_2, outputs=textbox_2)
demo.launch()
```

### Screenshot

As long as the space is not reset, you will see the same number. Remember that this number is supposed to represent a random user state set at page load up. Here I show the same number on two separate windows, one of them incognito:

<img width="1385" alt="image" src="https://github.com/gradio-app/gradio/assets/18450628/80c1bdd5-5dbb-4c7c-a598-b71105931f7c">
<img width="1304" alt="image" src="https://github.com/gradio-app/gradio/assets/18450628/fdb85e54-f766-45db-92bc-08d0836c082e">

### Logs

```shell
No log to show
```

### System Info

```shell
tested on MacOS with both

gradio==3.19.1
gradio==3.35.2

Seems to be a cross-platform issue since it also is happening on the space...
```

### Severity

serious, but I can work around it

**Comment by abidlabs** [comment] 2023-06-17 21:04
Hi @jerpint thanks for creating this issue. This is actually expected behavior, not a bug. The reason for this is the command  `random.random()` is only executed when the script is first run. The resulting value, **which does not change anymore since the script has already run**, is stored as the initial state of `gr.State()` for _all_ users/sessions. 

If you would like to provide a different seed to each user, you have two options:

(1) Do not set any initial value to `gr.State()` using `random.random()` but only run `random.random()` within a function that is triggered by the user. Since these functions are run separately for each user, you will end up with a different random number for each user. You can run a function on page load by using the the `.load()` event listener assigned to your Blocks object (in this case `demo`).

(2) We provide a convenient shorthand for (1), which is -- if you provide a `Callable` (i.e. a function, not a fixed value) as the initial value of a component, it is re-run every time the page loads. In this case, that would mean replacing `random.random()` with `random.random`. Here's the updated code, which works as expected:

```py
import gradio as gr
import uuid
import random

def return_number(number):
    return number

def update_state(state):
    state.append(random.random())
    return state

with gr.Blocks() as demo:

    user_state = gr.State(random.random)
    textbox = gr.Textbox(placeholder="Only the first random state...", label="user state (random number)", value=None)
    button = gr.Button()
    button.click(fn=return_number, inputs=user_state, outputs=textbox)
    
demo.launch()
```

**Closed** 2023-06-17 21:04 UTC
Labels: bug

**Comment by jerpint** [comment] 2023-06-17 22:56
Thanks for the quick response. While not what I expected, it makes much more sense now that you explain it. I will keep that in mind for future deployments 🙏
