### ISSUE TITLE
How to cancel double-check of the change() function of a ImageEditor?

### ISSUE THREAD

**Issue by 4thfever** [gradio-app/gradio#6966] opened 2024-01-08 10:49 UTC
Hi,

At first I would like to say thanks for your incredible word which is very convenient for me, a ML developer who knows little about front end.

I am recently facing a problem: I wanna make a image-in image-out system, which gives the feedback once the user make one paint. 

However, right now, the Paint mode requires a double-check to call the change() function, which makes the change() func less usable.
![image](https://github.com/gradio-app/gradio/assets/19970391/3dc9f6bc-f1af-4de9-95d1-df2e56b99b7f)

I didn't find a good way to remove that. I tried to change the trigger mode but nothing happened.

Should I rewrite the svelte code of gradio or do some hack things in js attribute?
Thanks for your advice in advance.

**Comment by pngwn** [comment] 2024-01-08 15:58
Do you mean that you need to click the button twice in order for changes to take effect or that you don't want to click it at all?

**Comment by 4thfever** [comment] 2024-01-09 03:03
> Do you mean that you need to click the button twice in order for changes to take effect or that you don't want to click it at all?

Hi, I don't want to click it at all.

**Comment by abidlabs** [comment] 2024-01-22 18:41
Let me close this as a duplicate of https://github.com/gradio-app/gradio/issues/7098 as that issue has more details and a repro

**Closed by abidlabs** 2024-01-22 18:41 UTC
Labels: enhancement
