### ISSUE TITLE
Gradio recording video from webcam error

### ISSUE THREAD

**Issue by aliabid94** [gradio-app/gradio#2366] opened 2022-09-29 04:04 UTC
Try running demo/webcam/run.py. Throws some path error related to trying to flip the video, which is enabled by default (should it be?).

**Comment by pngwn** [comment] 2022-09-30 09:42
I'll take a look at this, flipping should be enabled by default (to match online meeting behaviour that users are familar with--meet, zoom, etc.) but I don't know if we really thought much about webcam input to video (most of that work has been around image).

**Comment by pngwn** [comment] 2022-10-11 11:49
@aliabid94 I can't reproduce this with `demo/webcam`, are you still seeing this behaviour and if so do you have more detailed reproduction instructions? 

I do get a warning `File ended prematurely at pos. ...` but the file is processed successfully and the app works as expected.

**Comment by abidlabs** [comment] 2022-10-15 03:03
@aliabid94 I can't reproduce either: 

<img width="771" alt="image" src="https://user-images.githubusercontent.com/1778297/195966106-b0944003-69c3-4423-8fb7-11154cbc29de.png">


Do you have `ffmpeg` installed? Which version?

**Comment by abidlabs** [comment] 2022-11-14 16:11
Going to close this @aliabid94, feel free to reopen if you have more details.

**Closed by abidlabs** 2022-11-14 16:11 UTC
Labels: bug, pending clarification
