### ISSUE TITLE
If the example is cached, it should jump within the queue

### ISSUE THREAD

**Issue by osanseviero** [gradio-app/gradio#1858] opened 2022-07-22 13:22 UTC
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
If I go to https://huggingface.co/spaces/THUDM/CogVideo, and I click any of the examples, it puts me in the queue. I would have expected that since the example is cached it would be extremely fast, and there's no need to put at the queue.

**Comment by abidlabs** [comment] 2022-07-22 15:42
I thought this was already the case, did I break something @aliabid94?

**Comment by freddyaboulton** [comment] 2022-07-22 15:46
I think the problem is that the space does not use the `gr.Examples` component but instead uses `gr.Dataset` + click.

See code [here](https://huggingface.co/spaces/THUDM/CogVideo/blob/main/app.py#L77). Setting `examples.click(..., queue=False)` should fix the issue.

**Comment by osanseviero** [comment] 2022-07-22 16:00
Thanks! This makes sense! One additional question, the current approach would not cache the examples then right? Just if using `gr.Examples`?

**Comment by freddyaboulton** [comment] 2022-07-22 16:06
Yes exactly, using `gr.Dataset` + `click` would not cache the examples unless that logic was explicitly built-in to the function registered with the click event.

**Comment by freddyaboulton** [comment] 2022-07-25 17:31
Going to close as the issue was fixed in the space by using `gr.Examples`. Thanks all!

**Closed by freddyaboulton** 2022-07-25 17:31 UTC
Labels: bug
