### ISSUE TITLE
paired HTML tags in Chatbot/ChatInterface output break WebUI down

### ISSUE THREAD

**Issue by Keldos-Li** [gradio-app/gradio#7651] opened 2024-03-09 17:37 UTC
### Describe the bug

Similar existing issue report is #7198, #7587. but I think this is a different problem. In the Gradio v3 version, for instance, version 3.43.2 that we are currently using, enabling markdown rendering for chatbot and disabling sanitize_html still allows HTML to be present in the bot message. However, after updating to Gradio v4.2, HTML in the bot message causes the webUI to crash.

For example, in https://huggingface.co/spaces/gradio/chatinterface_streaming_echo, inputting `<b>bold text</b>` or `<u>underline</u>` or any other HTML in the user message displays correctly but causes the webUI to become unresponsive during the streaming output in the bot message.

**But if the output is not streamed but directly displayed, the webpage functions normally.**

Note that HTML output is essential for our needs, and theoretically, disabling sanitize_html is intended to allow developers to manually intervene in the chatbot's output. We require this HTML functionality.

Moreover,  **_the original Gradio v3.43.2 does not exhibit this error_**, and **_if the output is not streamed but directly displayed, the webpage functions normally_**. Therefore, I believe the issue lies in the rendering process of the output.

Additionally, I observed that after the webpage crashes, the console indicates `Unhandled Promise Rejection: NotFoundError: The object can not be found here.` from svelte.js. I am uncertain whether this is caused by a new version of Svelte.

Please fix this, I can't use the new version of grario at all now just because of this problem.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction
1. type `bold text: <b>bold</b>` in textbox
2. press submit button

```python
import time
import gradio as gr

def slow_echo(message, history):
    for i in range(len(message)):
        time.sleep(0.05)
        yield "You typed: " + message[: I+1]

demo = gr.ChatInterface(slow_echo).queue()

if __name__ == "__main__":
    demo.launch()

```

### Screenshot

<img width="1280" alt="image" src="https://github.com/gradio-app/gradio/assets/23137268/10bb9d24-4cdb-4f1a-a515-1d57ea764186">

https://github.com/gradio-app/gradio/assets/23137268/8f100041-691e-494c-a132-948844a584fb

### System Info

```shell
gradio 4.20.1
```

### Severity

Blocking usage of gradio

**Comment by GaiZhenbiao** [comment] 2024-03-09 18:00
Here's the code to reproduce this issue.

```
import time
import json
import random
import gradio as gr

def chat(chatbot):
    with open("chatbots.json") as f:
        chatbots = json.load(f)
    for i in chatbots:
        time.sleep(random.random()/30)
        chatbot = i
        yield chatbot


with gr.Blocks() as demo:
    chatbot = gr.Chatbot(sanitize_html=False, render_markdown=True)
    submit = gr.Button("Submit")

    submit.click(chat, [chatbot], [chatbot])

demo.launch()
```

[chatbots.json](https://github.com/gradio-app/gradio/files/14547285/chatbots.json)

**Comment by 1390806607** [comment] 2024-03-10 15:35
Hello, I want to jump from the first to the third, but the redirection cannot pass, could you please help me find out the reason?
The code is as follows：
"""
后端框架： fastapi
数据库：mysql
前端页面展示： gradio

注册

登录+验证

未登录不能访问聊天页

聊天页

充值页

个人主页

"""

import os
from fastapi import FastAPI, Depends, Request
from starlette.config import Config
from starlette.responses import RedirectResponse
from starlette.middleware.sessions import SessionMiddleware
import uvicorn
import gradio as gr
from contextlib import asynccontextmanager
from dotenv import dotenv_values,find_dotenv
from db import DB
import hashlib



app = FastAPI()
SECRET_KEY = None
app.add_middleware(SessionMiddleware, secret_key=SECRET_KEY)



with gr.Blocks() as third:
    gr.Button("third")
app = gr.mount_gradio_app(app, third, path="/3")

@app.route('/2')
def sec():
    return RedirectResponse('/3')


with gr.Blocks() as first:
    first_button = gr.Button("first")
    first_button.click(fn=sec)
app = gr.mount_gradio_app(app, first, path="/")





if __name__ == '__main__':
    uvicorn.run(app)

**Comment by 1390806607** [comment] 2024-03-10 15:36
@Keldos-Li

**Comment by abidlabs** [comment] 2024-03-11 18:40
I can repro the issue from the parent comment. @dawoodkhan82 can you look into this?

**Comment by dawoodkhan82** [comment] 2024-03-20 04:06
@Keldos-Li I can't repro this with the new release/main. I think this was fixed by https://github.com/gradio-app/gradio/pull/7623. @Keldos-Li can you confirm this is fixed?

**Closed** 2024-03-20 04:07 UTC
Labels: bug, 💬 Chatbot

**Comment by Keldos-Li** [comment] 2024-03-20 14:47
Yeah! It seems that the problem has been solved. Thank you so much!
