### ISSUE TITLE
Failed to connect to ec2.gradio.app:22

### ISSUE THREAD

**Issue by xishanhan** [gradio-app/gradio#1193] opened 2022-05-09 12:33 UTC
When I used 'interface.launch(share=True)' to build link, I met:

Running on local URL:  http://127.0.0.1:7860/
*** Failed to connect to ec2.gradio.app:22: 

But this happened sometimes, and sometimes the public link would be successfully built. 
I wanna know why.

**Comment by xishanhan** [comment] 2022-05-09 19:18
I also encountered another problem that the public link was successfully built, but when I the link clicked into the public link, it showed that 'No interface is running right now'.
I don't know why this happens.

**Comment by xishanhan** [comment] 2022-05-09 19:19
I also encountered another problem that the public link was successfully built, but when I clicked into the public link, it showed that 'No interface is running right now'.
I don't know why this happens.

**Comment by xishanhan** [comment] 2022-05-09 20:07
I didn't use Huggingface spaces.

**Comment by 5joon2** [comment] 2022-05-11 15:08
> When I used 'interface.launch(share=True)' to build link, I met:
> 
> Running on local URL: http://127.0.0.1:7860/ *** Failed to connect to ec2.gradio.app:22:
> 
> But this happened sometimes, and sometimes the public link would be successfully built. I wanna know why.

How could you open public link?

**Comment by 5joon2** [comment] 2022-05-12 00:53
> > > When I used 'interface.launch(share=True)' to build link, I met:
> > > Running on local URL: http://127.0.0.1:7860/ *** Failed to connect to ec2.gradio.app:22:
> > > But this happened sometimes, and sometimes the public link would be successfully built. I wanna know why.
> > 
> > 
> > How could you open public link?
> 
> I copied the link to google chrome and opened it.

How did you solve `*** Failed to connect to ec2.gradio.app:22:` log?
was it related to port forwarding?

**Comment by xishanhan** [comment] 2022-05-12 01:07
I don't know exactly what you mean, I didn't solve this problem. But sometimes the public link can be built successfully, and sometimes it can't.
When the public link cannot be built successfully, the linux terminal shows only these two sentences：
`
Running on local URL: http://127.0.0.1:7860/
*** Failed to connect to ec2.gradio.app:22:
`

**Comment by 5joon2** [comment] 2022-05-12 01:26
> I don't know exactly what you mean, I didn't solve this problem. But sometimes the public link can be built successfully, and sometimes it can't.
> When the public link cannot be built successfully, the linux terminal shows only these two sentences：
> `Running on local URL: http://127.0.0.1:7860/ *** Failed to connect to ec2.gradio.app:22:`

I got it. I asked that question because my console always show that log (fail to build public link). Thanks anyway!

**Comment by abidlabs** [comment] 2022-07-11 09:05
Hi @xishanhan and @5joon2, I tried pretty extensively to reproduce this and I have not been able to. Could this be a problem with your network connection? 

One way to test this would be try on a [colab notebook](https://colab.research.google.com/) and see if you still experience this an issue?

**Comment by abidlabs** [comment] 2022-07-11 09:07
Going to close this for now, but please feel free to reopen with more details on what platform / browser you are running (and make sure you are using the latest version of Gradio) if you still experience this issue.

**Closed by abidlabs** 2022-07-11 09:07 UTC

**Comment by xishanhan** [comment] 2022-07-11 09:23
Yeah, I guess so. The network connection is always unstable, so sometimes the public link can be built, sometimes cannot. Anyway, thanks for your reply!

**Comment by chamk21** [comment] 2022-10-21 03:55
I came across this error when running a gradio application and I had demo.launch(share=True, show_error=True). For some reason, it kept saying "*** Failed to connect to ec2.gradio.app:22: [Errno None] Unable to connect to port 22 on 35.160.54.199". Therefore I just changed it to demo.launch() and it works fine.

**Comment by chamk21** [comment] 2022-10-21 03:56
I came across this error when running a gradio application and I had demo.launch(share=True, show_error=True). For some reason, it kept saying "*** Failed to connect to ec2.gradio.app:22: [Errno None] Unable to connect to port 22". Therefore I just changed it to demo.launch() and it works fine.

**Comment by Litchilitchy** [comment] 2022-11-15 08:22
> I came across this error when running a gradio application and I had demo.launch(share=True, show_error=True). For some reason, it kept saying "*** Failed to connect to ec2.gradio.app:22: [Errno None] Unable to connect to port 22". Therefore I just changed it to demo.launch() and it works fine.

`demo.launch()` is to start it locally, however, the connection speed is obviously faster than setting `share=True` and it seems after setting `share=True` and `server_name="0.0.0.0"` the network stability requirement becomes very critical.

Don't know if I am the only one who experiences this. But anyway, I think it's not very reasonable to require such critical connection in a Web UI like this.

**Comment by lanxiuying** [comment] 2022-11-17 06:04
I wonder if your network were in China , which hard to fetch gradio、github and so on.

**Comment by Hubert2102** [comment] 2023-12-14 09:29
pip install gradio==3.31.0
