### ISSUE TITLE
Requests HTTPS Post results in error

### ISSUE THREAD

**Issue by sridiyer** [gradio-app/gradio#7602] opened 2024-03-05 03:34 UTC
### Describe the bug

Stand alone (not HF spaces) gradio app, calling GPT-4 vision. The python code works fine when executed from command line. With gradio frontend, the HTTPS call appears to time out (400 return code).

SystemExit: Failed to make the request. Error: 400 Client Error: Bad Request for url:

Traceback (most recent call last):
  File "/Users/sridhariyer/spdev/azcop_v1/azai/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 412, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sridhariyer/spdev/azcop_v1/azai/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sridhariyer/spdev/azcop_v1/azai/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/sridhariyer/spdev/azcop_v1/azai/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/sridhariyer/spdev/azcop_v1/azai/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/Users/sridhariyer/spdev/azcop_v1/azai/lib/python3.11/site-packages/starlette/middleware/base.py", line 192, in __call__
    await response(scope, wrapped_receive, send)
  File "/Users/sridhariyer/spdev/azcop_v1/azai/lib/python3.11/site-packages/starlette/responses.py", line 264, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "/Users/sridhariyer/spdev/azcop_v1/azai/lib/python3.11/site-packages/starlette/responses.py", line 260, in wrap
    await func()
  File "/Users/sridhariyer/spdev/azcop_v1/azai/lib/python3.11/site-packages/starlette/responses.py", line 237, in listen_for_disconnect
    message = await receive()
              ^^^^^^^^^^^^^^^
  File "/Users/sridhariyer/spdev/azcop_v1/azai/lib/python3.11/site-packages/starlette/middleware/base.py", line 52, in wrapped_receive
    msg = await self.receive()
          ^^^^^^^^^^^^^^^^^^^^
  File "/Users/sridhariyer/spdev/azcop_v1/azai/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 542, in receive
    await self.message_event.wait()
  File "/Users/sridhariyer/miniconda3/lib/python3.11/asyncio/locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

```

AZ_OPENAI_35KEY = os.getenv("AZ_OAI_35MOD_KEY")
AZ_OPENAI_4VISION_KEY = os.getenv("AZ_OAI_4VISION_PRI_KEY")

def parse_chat_input(history,text,img_t, img_r):
    # need to return a list of lists 
    resp1 = test_vlm_compare (text, img_t, img_r)
    #print (' output type ', type(resp1))
    return [(None, resp1)]
    

def image_to_base64(image_path):
    with open(image_path, 'rb') as img:
        encoded_string = base64.b64encode(img.read())
    return encoded_string.decode('utf-8')

def query_message(history,txt,img):
    
    if not img:
        history += [(txt,None)]
        return history
    base64 = image_to_base64(img)
    data_url = f"data:image/jpeg;base64,{base64}"
    history += [(f"{txt} ![]({data_url})", None)]

with gr.Blocks() as app:
    with gr.Tab("VLM"):
        with gr.Row():
            image_box_ref = gr.Image(type="filepath", label="Reference Image")
            image_box_test = gr.Image(type="filepath", label="Test Image")
   
            chatbot = gr.Chatbot(
                scale = 2,
                height=500
            )
        text_box = gr.Textbox(
            placeholder="Enter text and press enter, or upload an image",
            container=False,
        )

        btn = gr.Button("Submit")
        clicked = btn.click(query_message,
                        [chatbot,text_box,image_box_test],
                        chatbot
                        ).then(parse_chat_input,
                                [chatbot,text_box,image_box_test, image_box_ref],
                                chatbot
                                )

app.queue()
#app.launch(debug=True)
app.launch(server_name="0.0.0.0", server_port=8080)

### System Info

```shell
Operating System: Darwin
gradio version: 4.19.2
gradio_client version: 0.10.1

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.2.0
fastapi: 0.110.0
ffmpy: 0.3.2
gradio-client==0.10.1 is not installed.
httpx: 0.27.0
huggingface-hub: 0.21.3
importlib-resources: 6.1.2
jinja2: 3.1.3
markupsafe: 2.1.5
matplotlib: 3.8.3
numpy: 1.26.4
orjson: 3.9.15
packaging: 23.2
pandas: 2.2.1
pillow: 10.2.0
pydantic: 2.6.3
pydub: 0.25.1
python-multipart: 0.0.9
pyyaml: 6.0.1
ruff: 0.3.0
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.10.0
uvicorn: 0.27.1
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2024.2.0
httpx: 0.27.0
huggingface-hub: 0.21.3
packaging: 23.2
typing-extensions: 4.10.0
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by sridiyer** [comment] 2024-03-05 03:36
The same front-end works for a faster openAI call. (when the call is complicated with images, appear to time-out). I have tested the code with the HTTPS POST call (requests library). the code works fine. thank you very much.

**Comment by abidlabs** [comment] 2024-10-17 21:56
Closing as the issue is not clear but it appears to be resolved

**Closed by abidlabs** 2024-10-17 21:56 UTC
Labels: bug
