### ISSUE TITLE
Make the accordion open by default if its the last message in the chatbot history

### ISSUE THREAD

**Issue by davidberenstein1957** [gradio-app/gradio#9081] opened 2024-08-11 13:38 UTC
### Describe the bug

The docs show different bahavior https://www.gradio.app/docs/gradio/chatbot#behavior

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

https://github.com/davidberenstein1957/data-viber/blob/main/README.md
```python
from data_viber import AnnotatorInterFace

prompts = [
    [
        {
            "role": "user",
            "content": "Tell me something about Anthony Bourdain."
        },
        {
            "role": "assistant",
            "content": "Anthony Michael Bourdain was an American celebrity chef, author, and travel documentarian."
        }
    ]
]

interface = AnnotatorInterFace.for_chat_classification_per_message(
    prompts=prompts,
    labels=["toxic", "non-toxic"],
    fn=None, # a callable e.g. (function or transformers pipelines) that returns [{"label": str, "score": float}]
    dataset_name=None # "<my_hf_org>/<my_dataset>" if you want to log to the hub
)
interface.launch()
```

### Screenshot

<img width="1345" alt="image" src="https://github.com/user-attachments/assets/c151e809-4d83-403e-8672-9f3078661ced">

### System Info

```shell
MacOS 
Chromium
gradio                        4.22.0
```

### Severity

I can work around it

**Comment by abidlabs** [comment] 2024-08-12 02:43
Hi @davidberenstein1957 sorry I didn't understand, can you elaborate what the issue is? In your screenshot, it looks like the accordion is expanded, no?

**Comment by davidberenstein1957** [comment] 2024-08-12 04:32
Hi @aliabid94, It is collapsed by default and according to the docs it should not be an accordion at all. I think having the accordion collapsed by default makes it a bit useless for chat interactionsbut I guess it inherits the behavior from the agent tool information accordion? Would it be possible to add an additional flag to the Metadata to control this? "expanded=True" or something?

**Comment by abidlabs** [comment] 2024-08-13 21:08
Slight tangent: but one thing that I think we should do is make the accordion open by default if its the last message in the chatbot history. That creates a nice effect that while a message is streaming, you can see the tool use, but once its finished, it doesn't take up unnecessary space. Not sure whether that would be sufficient for you @davidberenstein1957a?

**Comment by davidberenstein1957** [comment] 2024-08-14 06:34
Hi,I agree that that makes sense but sadly it would not halo with my usecase. I can work around it for now if there is not other way.Thank you for the help. On 13 Aug 2024, at 23:08, Abubakar Abid ***@***.***> wrote:﻿
Slight tangent: but one thing that I think we should do is make the accordion open by default if its the last message in the chatbot history. That creates a nice effect that while a message is streaming, you can see the tool use, but once its finished, it doesn't take up unnecessary space. Not sure whether that would be sufficient for you @davidberenstein1957?

**Comment by abidlabs** [comment] 2024-09-26 05:08
Closed via https://github.com/gradio-app/gradio/pull/9359

**Closed by abidlabs** 2024-09-26 05:08 UTC
Labels: enhancement, 💬 Chatbot
