### ISSUE TITLE
Slider input works wrong in release 2.0.0

### ISSUE THREAD

**Issue by PVLTMK** [gradio-app/gradio#197] opened 2021-05-27 10:14 UTC
In release 2.0.0 i can drag slider input only on integer number of points even if specified 'step' = 0.1 [according these docs](https://www.gradio.app/docs#i_slider)

You can reproduce this bug using the following code:

```python
import gradio as gr


def foo():
    return 'result'


iface = gr.Interface(
    fn=foo,
    inputs=[gr.inputs.Slider(minimum=1.0,   maximum=10.0,  step=0.1,   default=5.0,   label="Slider:")],
    outputs=['text'])
iface.launch()
```

After starting, make sure that you can't select a fractional slider value

Requirements:
gradio==2.0.0

**Comment by nikhil-shah505** [comment] 2021-05-28 20:19
You can also change the data type from float to integer

**Comment by abidlabs** [comment] 2021-05-29 20:15
Thanks guys! We are looking into this issue right now, and should have a fix soon.. For now, you may want to install an older version of Gradio (e.g. `pip install gradio==1.7.6`)

**Comment by aliabid94** [comment] 2021-05-30 00:20
Fixed now in 2.0.1! Thanks for pointing this out @PVLTMK

**Closed by aliabid94** 2021-05-30 00:20 UTC

**Comment by gogurtenjoyer** [comment] 2023-05-05 23:00
It seems this issue has returned; I'm using
```
❯ pip list | grep gradio
gradio                   3.28.3
gradio_client            0.1.4
```

**Comment by abidlabs** [comment] 2023-05-05 23:02
Hi @gogurtenjoyer I can't reproduce. Can you share the code that you're using?

**Comment by gogurtenjoyer** [comment] 2023-05-06 02:29
Yep, here's the code:
```py
import gradio as gr
from transformers import pipeline

generator = pipeline(model="cactusfriend/nightmare-invokeai-prompts",
                    tokenizer="cactusfriend/nightmare-invokeai-prompts",
                    task="text-generation")



def makePrompts(prompt: str, temp: float, p: float, k: int):
    temp = float(temp)
    outputs = generator(prompt, max_new_tokens=200,
                        temperature=temp, do_sample=True,
                        top_p=p, top_k=k, num_return_sequences=5)
    items = set([i['generated_text'] for i in outputs])
    return "\n --- \n".join(items)


iface = gr.Interface(fn=makePrompts,
                     inputs=[gr.Textbox(lines=1, label="Prompt", info="the start of the prompts", placeholder="a photograph of"),
                             gr.Slider(0.5, 2.9, value=1.8, step=0.1, label="Temperature", info="higher = crazier"),
                             gr.Slider(0.02, 0.98, value=0.9, step=0.01, label="Top P"),
                             gr.Slider(10, 80, value=40, step=1, label="Top K")],
                     outputs=gr.Textbox(lines=10, label="Five prompts"),
                     title="Nightmare InvokeAI Prompts",
                     allow_flagging="never")
iface.launch()
```

In this case, the problem happens with the `Temperature` slider - if one sets it to, for example, `2.0` via the slider UI element, it'll actually show as `2` in the interface, and as the `generator()` func expects a float, it throws an error. Hopefully I'm just doing something wrong, and if so I do apologize for wasting your time!

**Comment by gogurtenjoyer** [comment] 2023-05-07 02:57
(forgot to mention that `temp = float(temp)` is my workaround right now; would have to remove that to see the issue)
