### ISSUE TITLE
Support object detection pipelines via Load

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#3734] opened 2023-04-03 02:12 UTC
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Right now, object detection models cannot be loaded via `load`

**Describe the solution you'd like**  
Support object detection models hosted on the HF inference API.

**Additional context**  

This is the stacktrace you get when trying to run the following code:

```python
import gradio as gr
gr.Interface.load("models/facebook/detr-resnet-50").launch()
```

```
cmrfd 2023-04-03T02:06:48.944Z     blocks: gradio.Blocks = factory_methods[src](name, api_key, alias, **kwargs)
cmrfd 2023-04-03T02:06:48.944Z   File "/home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages/gradio/external.py", line 311, in from_model
cmrfd 2023-04-03T02:06:48.944Z     raise ValueError("Unsupported pipeline type: {}".format(p))
cmrfd 2023-04-03T02:06:48.944Z ValueError: Unsupported pipeline type: object-detection
```

**Comment by abidlabs** [comment] 2023-04-03 10:15
Looks like duplicate of #2085?

**Closed** 2023-04-03 15:52 UTC
