### ISSUE TITLE
CORS policy problem

### ISSUE THREAD

**Issue by WisleyWang** [gradio-app/gradio#3942] opened 2023-04-23 06:26 UTC
### Describe the bug

hi~  this problem occurs when I visit the page from another machine on the LAN after I have Lunch service locally.

```
Access to font at 'hottps://fonts.gstatic.com/sourcesanspro/v21/6xK3dSBYKcSV-LCoeQqfx1RYOo3qOK71.woff2' fron origin 'https://10.30.21.151:7013' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource
```
my example just like:
···
import gradio as gr

def greet(name):
    return "Hello " + name + "!"

demo = gr.Interface(fn=greet, inputs="text", outputs="text")
    
if __name__ == "__main__":
    demo.launch()   
···

I want to allow CORS, like FLASK or FASTAPI can to set it  allow_origins = ["*"] , but in gradio I never see any metods

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

https://github.com/gradio-app/gradio

### Logs

```shell
*
```

### System Info

```shell
3.27.0
```

### Severity

blocking all usage of gradio

**Comment by abidlabs** [comment] 2023-04-23 23:01
Hi @WisleyWang can you mount the Gradio app within a larger fastapi application and enable CORS on that fastapi application?

Here's how to do that: https://gradio.app/sharing-your-app/#mounting-within-another-fastapi-app

**Comment by abidlabs** [comment] 2023-04-28 21:52
Closing for lack of followup

**Closed by abidlabs** 2023-04-28 21:52 UTC
Labels: bug, pending clarification

**Comment by Banbury** [comment] 2023-05-07 12:30
I'm running into the same problem. And no I can't wrap the Gradio app with FastApi, since it isn't my project. I just want to use it.
And as the upstream project, I think it's your responsibility to send the proper headers.

**Comment by abidlabs** [comment] 2023-05-07 12:48
Hi @Banbury this issue didn't have enough info for us to be able to reproduce and address the issue. Can you please create a new issue with step-by-step instructions to reproduce the problem? Thanks

**Comment by emersonium** [comment] 2024-06-04 05:48
Hi same issue here, it is a simple problem to describe:

 "Access-Control-Allow-Origin" is part of the HTTP protocol, how do we configure this in gradio ? 


(fastapi has this, so since gradio itself launches fast api, there should be a method to allow setting of this and all HTTP headers.)

thanks!

**Comment by ignaceHelsen** [comment] 2025-03-19 14:15
Experiencing the exact same problem.
