### ISSUE TITLE
gradio 3.28.0 - TypeError: issubclass() arg 1 must be a class

### ISSUE THREAD

**Issue by narugo1992** [gradio-app/gradio#4015] opened 2023-04-29 07:38 UTC
### Describe the bug

When I created the Hugging Face space using `gradio` version `3.28.0`, I encountered the following exception (the exact code is available here: https://huggingface.co/spaces/deepghs/anime_object_detection/commit/90b436448adff9eeb00d9067aff593c32defce34):

```python
Traceback (most recent call last):
  File "app.py", line 25, in <module>
    gr_face_submit.click(
  File "/home/user/.local/lib/python3.8/site-packages/gradio/events.py", line 132, in __call__
    dep, dep_index = self.trigger.set_event_trigger(
  File "/home/user/.local/lib/python3.8/site-packages/gradio/blocks.py", line 217, in set_event_trigger
    check_function_inputs_match(fn, inputs, inputs_as_dict)
  File "/home/user/.local/lib/python3.8/site-packages/gradio/utils.py", line 869, in check_function_inputs_match
    if not is_special_typed_parameter(name):
  File "/home/user/.local/lib/python3.8/site-packages/gradio/utils.py", line 858, in is_special_typed_parameter
    is_event_data = issubclass(parameter_types.get(name, int), EventData)
TypeError: issubclass() arg 1 must be a class
```

However, everything is okay when I downgrade the version to `3.18.0`.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

This issue also occurs on my local machine and should be easily reproducible.

### Logs

```shell
See above.
```

### System Info

```shell
The issue can be reproduced on my local machine running gradio `3.28.0` on Linux (most likely Ubuntu).
```

### Severity

serious, but I can work around it

**Comment by freddyaboulton** [comment] 2023-05-01 15:19
Looks like a dupe of #3514 - will close!

**Closed by freddyaboulton** 2023-05-01 15:19 UTC
Labels: bug
