### ISSUE TITLE
Running Gradio using Nginx HTTPS in a Web Server

### ISSUE THREAD

**Issue by MarkIvanDev** [gradio-app/gradio#6341] opened 2023-11-08 13:23 UTC
### Describe the bug

We already have a guide for serving gradio apps on a web serving using nginx here: https://www.gradio.app/guides/running-gradio-on-your-web-server-with-nginx. But converting this to use https leads to problems. The gradio app (in my case, chat) does not stop getting of the queueing stage and when I inspect the developer tools, it seems that when making a post to the /queue/data path, it results in an Internal Server Error.

I am using this nginx configuration to enable https:

```
server {
    server_name <SERVER_NAME>;

    location / {
        proxy_pass              http://localhost:7860;
        proxy_http_version      1.1;
        proxy_redirect          off;
        proxy_set_header        Upgrade $http_upgrade;
        proxy_set_header        Connection "upgrade";
        proxy_set_header        Host $host;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/<domain>/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/<domain>/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

server {
    if ($host = <DOMAIN>) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    server_name <DOMAIN>;
    listen      80;
    return 404; # managed by Certbot
}
```

And I am using this nginx configuration for http. The gradio app works perfectly when using this, but I can only use an https so I need to convert this into https if possible:

```
server {
    server_name <SERVER_NAME>;
    listen 80;

    location / {
        proxy_pass              http://localhost:7860;
        proxy_http_version      1.1;
        proxy_redirect          off;
        proxy_set_header        Upgrade $http_upgrade;
        proxy_set_header        Connection "upgrade";
        proxy_set_header        Host $host;
    }
}
```

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Use the nginx configuration as above and restart the nginx service and use the https version of the gradio app site.

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 4.1.1
gradio_client version: 0.7.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.1.2
fastapi: 0.104.1
ffmpy: 0.3.1
gradio-client==0.7.0 
httpx: 0.25.1
huggingface-hub: 0.17.3
importlib-resources: 6.1.0
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.8.1
numpy: 1.26.1
orjson: 3.9.10
packaging: 23.2
pandas: 2.1.2
pillow: 10.1.0
pydantic: 2.4.2
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
requests: 2.31.0
semantic-version: 2.10.0
tomlkit==0.12.0
typer: 0.9.0
typing-extensions: 4.8.0
uvicorn: 0.24.0.post1
websockets: 11.0.3
authlib; 
itsdangerous; 


gradio_client dependencies in your environment:

fsspec: 2023.10.0
httpx: 0.25.1
huggingface-hub: 0.17.3
packaging: 23.2
requests: 2.31.0
typing-extensions: 4.8.0
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by Lyzin** [comment] 2023-11-08 14:08
I'm having the same problem, and I'm also using nginx to proxy the gradio service,
gradio    == 4.1.2
gradio_client   ==  0.7.0

**Comment by Lyzin** [comment] 2023-11-08 15:44
> I'm having the same problem, and I'm also using nginx to proxy the gradio service, gradio == 4.1.2 gradio_client == 0.7.0

This is how I solved it, gradio downgraded to version 3.50.2, still using nginx, but need to add the following to the nginx routing block again, then you can access the gradio service normally using the domain name.

```bash 
proxy_http_version 1.1; 
proxy_set_header Upgrade $http_upgrade; 
proxy_set_header Connection "upgrade";
```

**Comment by MarkIvanDev** [comment] 2023-11-09 00:46
@Lyzin I already have those lines in my nginx config though. When you said that you can access the gradio service normally again, do you mean that it works when accessing the domain using HTTPS? Thank you

Will try downgrading gradio and check again.

**Comment by MarkIvanDev** [comment] 2023-11-09 00:58
I can verify that downgrading to gradio v3.50.2 works. Which means this is a bug in the recent releases of gradio.

**Comment by MarkIvanDev** [comment] 2023-11-09 01:05
When embedding the gradio-app, I am still getting errors:

```
index.js:1017  Mixed Content: The page at <domain> was loaded over HTTPS, but requested an insecure resource 'http://<domain>/config'. This request has been blocked; the content must be served over HTTPS.
```

It seems that even though the gradio app is served using HTTPS, other endpoints are still using HTTP. How can I force all endpoints to use HTTPS?

**Comment by Lyzin** [comment] 2023-11-09 02:40
> I can verify that downgrading to gradio v3.50.2 works. Which means this is a bug in the recent releases of gradio.

gradio4.0+ version whether there is a problem I can not be sure, my interactive page project with gradio4.0+ and nginx, using http access, did not try https access, /queue/data error: internal error, and your report the same error, and then I thought of graido downgrade to 3.50+! Then I thought of downgrading graido to 3.50+, configured nginx, https and http can be accessed normally. I think if your project uses the new features of gradio4.0, then you may need the gradio team to help look at it, otherwise you can use gradio3.50+ version to fulfill the page functionality.

**Comment by yuripeyamashita** [comment] 2023-11-09 12:40
Same error.

**Comment by BrunoBosshard** [comment] 2023-11-20 03:10
Same error. This issue seems to be a duplicate of https://github.com/gradio-app/gradio/issues/6274

**Comment by BrunoBosshard** [comment] 2023-11-20 05:53
The solution might have been discussed here: https://github.com/gradio-app/gradio/issues/6366 . Quote from @AntoDono:

After hours of debug, it turns out I was just missing `proxy_buffering off;` in `location /` 😭😭😭

Thanks, @AntoDono !

**Closed** 2023-12-19 16:44 UTC
Labels: bug, cloud
