### ISSUE TITLE
Image Editor tool overlays input image

### ISSUE THREAD

**Issue by huseynlilkin** [gradio-app/gradio#244] opened 2021-07-14 00:01 UTC
When I try to edit an input image (for example, crop), the tool panel overlays the input image. Please check the example image below.

<img src="https://user-images.githubusercontent.com/10523514/125539943-f6a4dddd-ad77-4197-b5c0-9132a4e4ffb5.png" alt="drawing" width="640"/>

I'm using gradio at localhost and with Chrome browser.

**Comment by AK391** [comment] 2021-08-18 18:11
@huseynlilkin I was able to reproduce this with gradio , will notify @aliabid94 could try using a older version of gradio which does not have this issue for example version 2.0.5
<img width="1018" alt="Screen Shot 2021-08-18 at 2 07 48 PM" src="https://user-images.githubusercontent.com/81195143/129949890-b435e06b-1630-4e80-ac71-48c3a3d16199.png">

**Comment by abidlabs** [comment] 2021-11-03 18:51
It looks like this is fixed now, as of `gradio>2.4.0`. If not, please let us know and reopen this issue!

**Closed by abidlabs** 2021-11-03 18:51 UTC
