### ISSUE TITLE
highlightedtext color map changing when the componenet is interactive

### ISSUE THREAD

**Issue by moussaKam** [gradio-app/gradio#6742] opened 2023-12-11 09:59 UTC
### Describe the bug

If I put interactive to true and I change the label of some tokens in the text, the color map will not be the same as the `color_map`  dictionary passed as argument to the component.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
from difflib import Differ

import gradio as gr


def diff_texts(text1, text2):
    d = Differ()
    x = [
        (token[2:], token[0] if token[0] != " " else None)
        for token in d.compare(text1, text2)
    ]
    return x


demo = gr.Interface(
    diff_texts,
    [
        gr.Textbox(
            label="Text 1",
            info="Initial text",
            lines=3,
            value="The quick brown fox jumped over the lazy dogs.",
        ),
        gr.Textbox(
            label="Text 2",
            info="Text to compare",
            lines=3,
            value="The fast brown fox jumps over lazy dogs.",
        ),
    ],
    gr.HighlightedText(
        label="Diff",
        combine_adjacent=True,
        show_legend=True,
        interactive=True,
        color_map={"+": "red", "-": "green"}),
    theme=gr.themes.Base()
)
if __name__ == "__main__":
    demo.launch()
```

### Screenshot

screenshot before the interaction:
![image](https://github.com/gradio-app/gradio/assets/28675016/d99ff1f3-4f12-456d-9a79-46d5b1c0d4a7)

screenshot after the interaction:
![image](https://github.com/gradio-app/gradio/assets/28675016/dddc4879-fdd4-43a8-be80-cbf07f37fe1d)

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 4.8.0
gradio_client version: 0.7.1

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.1.0
altair: 4.2.2
fastapi: 0.104.1
ffmpy: 0.3.0
gradio-client==0.7.1 is not installed.
httpx: 0.24.0
huggingface-hub: 0.18.0
importlib-resources: 5.12.0
jinja2: 3.1.2
markupsafe: 2.1.2
matplotlib: 3.7.1
numpy: 1.24.2
orjson: 3.8.10
packaging: 23.1
pandas: 2.0.0
pillow: 9.5.0
pydantic: 2.5.2
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0
requests: 2.28.2
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.8.0
uvicorn: 0.21.1
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.10.0
httpx: 0.24.0
huggingface-hub: 0.18.0
packaging: 23.1
requests: 2.28.2
typing-extensions: 4.8.0
websockets: 11.0.1
```

### Severity

Possible workaround: 
update `color_map` with the initial dictionary for each interaction.

**Comment by shubhamofbce** [comment] 2024-02-03 17:48
I tried reproducing this issue, whenever you assign a label to a text, gradio assigns it a random color and if that random color is from your `color_map` then the order breaks and creates an issue.
So to fix this when we are picking random colors we have to avoid the colors used in color_map.

**Comment by abidlabs** [comment] 2024-10-17 21:30
Hi, apologies for the late follow up. We haven't had a chance to look into this issue, but the Gradio codebase has changed quite significantly since this issue was created, particularly with the release of Gradio 5. Could you let us know if this is still an issue in the latest version of Gradio (`pip install --upgrade gradio`)? Thanks!

**Comment by abidlabs** [comment] 2024-10-23 16:28
Closing the issue for now, but can reopen if the issue continues to persist in the latest version of Gradio

**Closed by abidlabs** 2024-10-23 16:28 UTC
Labels: bug, svelte, pending clarification
