### ISSUE TITLE
can not hid the tab

### ISSUE THREAD

**Issue by stevenweish** [gradio-app/gradio#5899] opened 2023-10-13 06:11 UTC
I can not hid or disable the checkTabB or checkTabB ,the code as follows:

```
with gr.Blocks() as demo:
    with gr.Tabs(elem_id="tabs") as tabs:
        with gr.TabItem("updataA") as checkTabA:
            name_boxA = gr.Textbox(label="NameA")
        with gr.TabItem("updataB") as checkTabB:
            name_boxB = gr.Textbox(label="NameB")
        with gr.TabItem("updataC") as checkTabC:
            name_boxC = gr.Textbox(label="NameC")


    def init_value(req: gr.Request):
        return {
            checkTabB: gr.update(interactive=False),
            checkTabC: gr.update(visible=False)
        }
    demo.load(init_value, inputs=[], outputs=[checkTabB, checkTabC])

    demo.launch()
```

**Comment by abidlabs** [comment] 2023-10-16 00:51
Closing as this is a duplicate of https://github.com/gradio-app/gradio/issues/2592

**Closed by abidlabs** 2023-10-16 00:51 UTC
