### ISSUE TITLE
Support setting sample rate and channels for mic capture

### ISSUE THREAD

**Issue by virajkarandikar** [gradio-app/gradio#5848] opened 2023-10-09 14:26 UTC
- [x]  I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
I am building a app for real time streaming ASR use case. App is hosted on a webserver. Streaming mic data to app happens at 48khz, 2 channel. This seems to adding latency. Can this format be changed to 16khz, 1 channel?

**Describe the solution you'd like**  
Support setting audio format of the mic audio stream - sample rate, channel, sample width 

**Additional context**

**Comment by Archit-Kohli** [comment] 2023-10-18 07:58
Hey @virajkarandikar are you still working on this issue? I might have some idea how to do this, and would like to work on it

**Comment by virajkarandikar** [comment] 2023-10-19 08:21
I am not working on fixing this issue

**Comment by mikejgray** [comment] 2023-11-09 03:29
https://github.com/gradio-app/gradio/blob/37dd335e5f04a8e689dd7f23ae24ad1934ea08d8/gradio/processing_utils.py#L330

It appears that the `AudioSegment.from_file()` method does accept kwargs for sample_width, frame_rate, and channels (https://github.com/jiaaro/pydub/blob/996cec42e9621701edb83354232b2c0ca0121560/pydub/audio_segment.py#L179), but it isn't exposed in `gradio.processing_utils.audio_from_file()`.  Should be a pretty straightforward passthrough.

Will do some testing on a local fork and possibly PR, if no one beats me to it. 🙂

**Comment by virajkarandikar** [comment] 2023-11-23 12:35
Hi @mikejgray did you get time to submit PR for this?

**Comment by virajkarandikar** [comment] 2023-11-24 07:35
@mikejgray the code you mentioned above is for reading audio from file. My request was to allow setting sample rate for the mic capture.

**Comment by qianhuiliu** [comment] 2023-11-26 09:27
> Hey @virajkarandikar are you still working on this issue? I might have some idea how to do this, and would like to work on it

Hello, I have the same question. Can you share the ideas of how to figure it out with me? Thx!

**Comment by qianhuiliu** [comment] 2023-11-26 09:28
@Archit-Kohli
Hello, I have the same question. Can you share the ideas of how to figure it out with me? Thx!

**Comment by Archit-Kohli** [comment] 2023-11-26 09:36
> @Archit-Kohli
> Hello, I have the same question. Can you share the ideas of how to figure it out with me? Thx!

I too thought the same as @mikejgray but it seems @virajkarandikar wants this in the mic input, @virajkarandikar can you send the link to the files where mic input is being preprocessed, I looked (not hard enough though) but couldn't find them

**Comment by virajkarandikar** [comment] 2023-11-28 06:49
Code here https://github.com/gradio-app/gradio/blob/main/js/audio/recorder/AudioRecorder.svelte handles microphone recording. It uses https://github.com/katspaugh/wavesurfer.js/blob/main/src/plugins/record.ts for recording.

**Comment by virajkarandikar** [comment] 2024-01-25 19:20
any update here?

**Comment by freddyaboulton** [comment] 2024-10-24 22:09
Thanks everyone for the discussion! I will close this for two reasons:

1. I think it's a duplicate of #5024 
2. The core gradio settings are pretty good for streaming demos. If you really want to do realtime audio you can use the webrtc component which does support setting track_constraints natively. https://github.com/freddyaboulton/gradio-webrtc

**Closed by freddyaboulton** 2024-10-24 22:09 UTC
Labels: enhancement, 🎵 Audio
