### ISSUE TITLE
ImageEditor doesn't trigger change event at all!

### ISSUE THREAD

**Issue by empty-id** [gradio-app/gradio#6563] opened 2023-11-23 10:41 UTC
### Describe the bug

```python
import gradio as gr

cnt = 0

def test():
    cnt += 1
    return f'triggered!{cnt}'


with gr.Blocks() as demo:
    sketch_pad = gr.ImageEditor(type="pil")
    output_text = gr.Textbox(label='Output Text')
    sketch_pad.change(test, outputs=[output_text])
    
demo.launch()
```

Whatever I edit the uploaded image, the change event doesn't trigger!

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

cnt = 0

def test():
    cnt += 1
    return f'triggered!{cnt}'


with gr.Blocks() as demo:
    sketch_pad = gr.ImageEditor(type="pil")
    output_text = gr.Textbox(label='Output Text')
    sketch_pad.change(test, outputs=[output_text])
    
demo.launch()
```

### Screenshot

<img width="1023" alt="image" src="https://github.com/gradio-app/gradio/assets/56990007/117de643-38c2-4da0-80d5-757b53841007">

### System Info

```shell
gradio==4.7.0
```

### Severity

Blocking usage of gradio

**Comment by empty-id** [comment] 2023-11-23 10:47
All right... I have to click the top-right `save` button to trigger change... Is there any automatical way?

**Comment by sean-styleai** [comment] 2024-02-17 13:49
gr.ImageMask.upload() also not working in the latest version (4.19.1) !
gr.Image.upload() works fine.
Source code looks similar like inheritance Componet. What cause this problem?

```
with gr.Blocks() as demo_ip_adapter_inpaint:
    with gr.Row():
        with gr.Column():
            gr.Markdown(value="""## Reference Image  
                            Min 512x512px""")
            gr.Image
            ref_img = gr.ImageEditor(label="Reference Image", sources=["upload"], type="pil")
            crop_button = gr.Button(value="Crop")
            crop_ref_img = gr.Image(label="Cropped Reference Image")

            ref_img.upload(fn=warning_img_size, inputs=[ref_img])
```

**Comment by pngwn** [comment] 2024-02-20 16:01
Duplicate of #7098 and #6757.

**Closed by pngwn** 2024-02-20 16:01 UTC
Labels: bug, Priority, 🖼️ ImageEditor
