### ISSUE TITLE
Dataframe doesn't display in Tab on Firefox

### ISSUE THREAD

**Issue by piotrszleg** [gradio-app/gradio#7077] opened 2024-01-19 08:10 UTC
### Describe the bug

On Firefox browser dataframe rows are displayed only in the first Gradio tab, on the other tabs dataframes are empty.

The same thing happens with closed Accordions so the issue might come from the Dataframe element not being visible at the start.

On Edge everything works correctly.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
import pandas as pd

df = pd.DataFrame(
    {
        "col1": [1, 2, 3, 4],
        "col2": [5, 6, 7, 8],
        "col3": [9, 10, 11, 12]
    }
)

with gr.Blocks() as demo:
    with gr.Tab("Tab 1"):
        gr.DataFrame(df, label="Statistics")
    with gr.Tab("Tab 2"):
        gr.DataFrame(df, label="Statistics")
    with gr.Tab("Tab 3"):
        gr.DataFrame(df, label="Statistics")

demo.launch()
```

### Screenshot

<img width="570" alt="Screenshot 2024-01-19 085116" src="https://github.com/gradio-app/gradio/assets/16499460/29a36c8d-c7b6-4bb7-b53f-7d5dc25c2037">
<img width="555" alt="Screenshot 2024-01-19 085127" src="https://github.com/gradio-app/gradio/assets/16499460/c3211b06-8695-4e63-a471-d198ea10aded">
<img width="557" alt="Screenshot 2024-01-19 085137" src="https://github.com/gradio-app/gradio/assets/16499460/d97c7986-42f5-4a2b-9e26-9a6715dbcb77">

### Logs

```shell
- browser dev console is empty
- nothing related to this issue appears in the Python script output
```

### System Info

```shell
- Firefox version 121.0.1 (64 bits)
- all extensions are disabled and I tested incognito mode
- I tested both latest version on pip and main branch of this repo
```

### Severity

Blocking usage of gradio

**Comment by shubhamofbce** [comment] 2024-02-03 10:53
@piotrszleg I tried to reproduce this on my mac firefox and i was unsuccessful as it looks good in both firefox and safari.
Can you confirm if you are on the latest gradio version?
If this issue persists for you in the latest version then can you please let us know your OS so that we can investigate further.
![image](https://github.com/gradio-app/gradio/assets/45156638/e086e4f8-c1e6-41c9-9ef3-bfe694219290)

**Comment by piotrszleg** [comment] 2024-02-29 13:16
With latest Firefox update the issue stopped persisting so I'm closing the issue for now.

**Comment by shubhamofbce** [comment] 2024-02-29 16:01
Thanks @piotrszleg for the confirmation.

**Comment by abidlabs** [comment] 2024-10-17 21:33
Hi, apologies for the late follow up. We haven't had a chance to look into this issue, but the Gradio codebase has changed quite significantly since this issue was created, particularly with the release of Gradio 5. Could you let us know if this is still an issue in the latest version of Gradio (`pip install --upgrade gradio`)? Thanks!

**Comment by abidlabs** [comment] 2024-10-23 16:29
Closing the issue for now, but happy to reopen if the issue continues to persist in the latest version of Gradio

**Closed by abidlabs** 2024-10-23 16:29 UTC
Labels: bug, pending clarification, 💾 Dataframe
