### ISSUE TITLE
Chat Interface - Adding additional params or inputs for use in function

### ISSUE THREAD

**Issue by w8jie** [gradio-app/gradio#9084] opened 2024-08-12 04:51 UTC
- [X] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
My goal for the chatbot is to classify reports given by users and ask questions based on a set of question list specific to the classification type. Essentially there are two parts to the LLM chatbot and two different api calls (send_classify and send_qna)

My problem comes when I am unable to store the question list to continue asking questions after returning the first user response.

**Describe the solution you'd like**  
I would like to either store the question_list or resolve this using global/session states. However I have not been able to make it work with the docs provided.

**My codes**
Initial problem:
```
def generate_answer(message:dict, history:list) -> str:
    '''
    Function to run backend api when user submits a query

    Args:
    - message (dict): input query from user
    - history (list): list of past conversation

    Returns:
    - new_message (str): output generated answer
    '''
    
    user_report = message['text']
    
    classification = send_classify(user_report)
    print("CLASSIFICATION:", classification)
    
    question_list = fetch_questions(classification)
    print("QN_LIST:", question_list)
    
    while question_list:
        # pick up top question
        question = question_list[0]
        
        is_skipped = send_qna(question, user_report)
        
        if not is_skipped:
            # asks user for input
            return question
        
        else:
            print("Qn was skipped:", question)
        # remove qn from the original list
        question_list.pop(0)
    

demo = gr.ChatInterface(fn=generate_answer,
                        title="LLM Chatbot", multimodal=True, retry_btn=None, undo_btn=None, clear_btn=None)
demo.launch()
```

Trying to return question_list as additonal params:
```
def generate_answer(message:dict, history:list, question_list:list) -> str:
    '''
    Function to run backend api when user submits a query

    Args:
    - message (dict): input query from user
    - history (list): list of past conversation

    Returns:
    - new_message (str): output generated answer
    '''
    
    user_report = message['text']
    
    try:
        print(question_list)
        
    except:
        print("no qn list yet")
        classification = send_classify(user_report)
        print("CLASSIFICATION:", classification)
        
        question_list = fetch_questions(classification)
        print("QN_LIST:", question_list)
    
    if question_list != []:
        
        # pick up top question
        question = question_list[0]
        
        is_skipped = send_qna(question, user_report)
        
        if not is_skipped:
            # asks user for input
            return question
        
        else:
            print("Qn was skipped:", question)
        # remove qn from the original list
        question_list.pop(0)
    

demo = gr.ChatInterface(fn=generate_answer, 
                        additonal_inputs=[question_list],
                        title="LLM Chatbot", multimodal=True, retry_btn=None, undo_btn=None, clear_btn=None)
demo.launch()
```

**Comment by freddyaboulton** [comment] 2024-08-12 15:24
I think this is a duplicate of #7933 as it would be solved by being able to return a modified state component from ChatInterface. Will close but thanks for filing @w8jie !

**Closed by freddyaboulton** 2024-08-12 15:24 UTC
