### ISSUE TITLE
🐛[component/gr.ImageEditor]: `ImageEditor.upload`  listener not triggered when uploading image

### ISSUE THREAD

**Issue by rchuzh99** [gradio-app/gradio#7413] opened 2024-02-14 07:20 UTC
### Describe the bug

The callback was no triggered when I was uploaded an image.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr


def placeholder_function():
    return "Hiiiiii"


################################# MAIN #########################################

with gr.Blocks() as demo:
    with gr.Row():
        with gr.Column(scale=2):

            token_map = gr.JSON(label="Supported Tokens", visible=True)

        with gr.Column(scale=3):
            image_editor = gr.ImageEditor(
                label="Sketchpad", sources="upload", value=None, show_share_button=False, transforms=[]
            )
            placeholder = gr.Textbox(label="Placeholder")
    image_editor.upload(fn=placeholder_function, outputs=placeholder)

if __name__ == "__main__":
    demo.launch(server_port=7860)


```

### Screenshot

-

### Logs

```shell
-
```

### System Info

```shell
Gradio Environment Information:
------------------------------ 
Operating System: Windows
gradio version: 4.18.0
gradio_client version: 0.10.0

------------------------------------------------
gradio dependencies in your environment:        

aiofiles: 23.2.1
altair: 5.2.0   
fastapi: 0.109.2
ffmpy: 0.3.2
gradio-client==0.10.0 is not installed.
httpx: 0.26.0
huggingface-hub: 0.20.3   
importlib-resources: 6.1.1
jinja2: 3.1.3
markupsafe: 2.1.5
matplotlib: 3.8.2
numpy: 1.26.4
orjson: 3.9.13
packaging: 23.2
pandas: 2.2.0
pillow: 10.2.0
pydantic: 2.6.1
pydub: 0.25.1
python-multipart: 0.0.9
pyyaml: 6.0.1
ruff: 0.2.1
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.9.0
uvicorn: 0.27.1
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2024.2.0
httpx: 0.26.0
huggingface-hub: 0.20.3
packaging: 23.2
typing-extensions: 4.9.0
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment] 2024-02-14 14:33
Thanks @rchuzh99! We'll get this fixed, but I'll close this for now as this is a duplicate of https://github.com/gradio-app/gradio/issues/6757

cc @pngwn

**Closed by abidlabs** 2024-02-14 14:33 UTC
Labels: bug

**Comment by rchuzh99** [comment] 2024-02-14 21:00
Thanks @abidlabs 🙏🏻
