### ISSUE TITLE
Large files cause Gradio Interface to crash without any indication of internal error 

### ISSUE THREAD

**Issue by thermelin** [gradio-app/gradio#2322] opened 2022-09-22 09:18 UTC
### Describe the bug

When getting Gradio internal error, the app seems to continue to "run" without executing anything or returning. 

It would be great to be able to stop the run in case there is such an error and present an error message to the user (rather than having it look like it's still running forever). It seems like the exception is not populating beyond the scope of Gradio. Adding 'show_error=True' did not help.

Side note, when an error occurs in invoked code I can catch it and return a message to the users without any issues.

Thanks!

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I used uploading a big file to generate an error.
1. Create an interactive file component
2. Create a button that sends the uploaded file to some dummy function
3. Launch the app
4. Upload a big file (> 500MB)
5. Click the button

### Screenshot

![image](https://user-images.githubusercontent.com/108273730/191707347-093c73ba-47d7-4444-8f5c-8850e40183aa.png)

### Logs

```shell
no logs.
```

### System Info

```shell
'3.0.11', Windows, Edge
```

### Severity

serious, but I can work around it

**Comment by freddyaboulton** [comment] 2022-09-26 15:07
Hi @thermelin ! If you upgrade to the latest gradio version and use `show_error` does the problem persist? We recently added a new `gr.Error` component that will show errors from the backend on the front-end.

**Comment by pngwn** [comment] 2022-09-27 14:50
@freddyaboulton 
> It seems like the exception is not populating beyond the scope of Gradio. Adding 'show_error=True' did not help.

I have notice this myself a few times but I haven't looked into it too closely. We need to think more holistically about error handling across the application imo.

**Comment by abidlabs** [comment] 2022-12-23 16:51
Hi @thermelin it sounds like this is a duplicate of #2421, correct? Can we go ahead and close this issue while we look into a fix for large file?

**Comment by thermelin** [comment] 2022-12-25 08:19
Hi,
Actually, from reading the top of #2421, it seems that it is closer to a different issue (more critical) that I've opened and was closed (due to duplication with #2421, which is #2297). 
Also, it seems that there is a difference between the issues. The new one discusses a several seconds freeze, while I experienced an indefinite freeze.

**Comment by abidlabs** [comment] 2023-02-07 19:15
Hi @thermelin I looked into this issue and I'm pretty sure it's the same underlying problem as #2421. For files that are about 200 MB - 500 MB, the interface freezes for a few seconds. For files larger than that, the interfaces crashes indefinitely.

**Closed by abidlabs** 2023-02-07 19:15 UTC
Labels: bug

**Comment by pangyuteng** [comment] 2023-12-03 18:54
For what it's worth, I was testing out gradio, tried uploading a 60MB .nii.gz file.
got the same traceback with `gradio==4.7.1`, but was able to upload after downgrading verion to `gradio==3.41.0`!

```

import gradio as gr

def test(x):
    return x.name
    
with gr.Blocks() as demo:
    inp = gr.File(label="Input")
    vis_out=gr.File(label="output")
    with gr.Row():
        btn = gr.Button("Run")
    btn.click(fn=test, inputs=[inp], outputs=[vis_out])

demo.queue().launch(debug=True,show_api=True,share=False) # server_name='0.0.0.0' # for within docker

```
