### ISSUE TITLE
Why is gr.dataframe not found in official documentation?

### ISSUE THREAD

**Issue by tt0203** [gradio-app/gradio#1774] opened 2022-07-13 02:35 UTC
Is the component description missing from the official documentation?
https://gradio.app/docs/
Also, is there a component that supports arrays directly?
Also, I used HuggingFece to build an API interface for uploading Excel files on gr.File. How to submit the body part?

I build the app address is: https://huggingface.co/spaces/changxin/pq

Also you can look at: https://hf.space/embed/changxin/pq/+

API address is: https://hf.space/embed/changxin/pq/+/api/df

Input Payload

{

"data": [

(List[Dict[name: str, data: str]]), // represents str, data: str]]): List of JSON objects with filename as 'name' property and base64 data as 'data' property of 'Select the Excel File' File that you want to read component

]

}
How do I build the body part of this post api?

**Comment by freddyaboulton** [comment] 2022-07-13 02:51
@tt0203 Going to close as this is a duplicate of #1773! Let's continue the discussion there.

**Closed by freddyaboulton** 2022-07-13 02:51 UTC
