### ISSUE TITLE
Inputs component with  _js don’t match fn parameter

### ISSUE THREAD

**Issue by luoweb** [gradio-app/gradio#5385] opened 2023-08-31 00:26 UTC
- [ ] I have searched to see if a similar issue already exists.

I need js just modified partial input value with js, like chatbot component, I just change the pormpt input, and cannot pass state and chabot to js

**Comment by abidlabs** [comment] 2023-08-31 00:27
Hi @luoweb there isn't a lot of information in this issue, but I believe this is a duplicate of https://github.com/gradio-app/gradio/issues/3525. I'll close this -- please feel free to follow that issue or respond here if I'm mistaken.

**Closed** 2023-08-31 00:28 UTC
