### ISSUE TITLE
A way of displaying progress

### ISSUE THREAD

**Issue by NotNANtoN** [gradio-app/gradio#1973] opened 2022-08-08 14:28 UTC
- [x] I have searched to see if a similar issue already exists.
For some reason, this is not possible. I tried using the StatusReport block, but it does not do anything as far as I can see.

**Is your feature request related to a problem? Please describe.**  
The processing of my app takes a considerable amount of time (up to 5 hours). It would be great to show intermediate outputs and status reports to the user - also because it would be easier to identify where the process goes wrong if it crashes.

**Describe the solution you'd like**  
 It would be so convenient, if the .update function of a TextBlock or a Gallery allows updating the actual content that is shown. I tried modifying the .value field but that does not do anything. Furthermore, it would be great if the progress bar of the actual interface would not just be a timer but instead allows the developer to insert time estimations and progress updates.

**Comment by freddyaboulton** [comment] 2022-08-08 14:31
Thanks for filing! 

This sounds like a duplicate of https://github.com/gradio-app/gradio/issues/776 . Do you agree? If so, let's close this and add your comment to the thread of #776

**Comment by NotNANtoN** [comment] 2022-08-08 16:24
Hi, 

yes, to some degree. Although I would love to have this not only for images but also for text boxes

**Comment by freddyaboulton** [comment] 2022-08-08 16:33
Noted! Let's close this but I added your feedback to #776

**Closed by freddyaboulton** 2022-08-08 16:33 UTC
