### ISSUE TITLE
input=microphone  can not get the content 

### ISSUE THREAD

**Issue by jkluo** [gradio-app/gradio#3387] opened 2023-03-06 14:30 UTC
### Describe the bug

**my code** 

`
import gradio as gr

def application(text):
    return text

with gr.Blocks() as app:
    with gr.Row():
            inp = gr.Audio(source="microphone")
            out = gr.Microphone()
    btn = gr.Button("Go")
    btn.click(fn=application, inputs=inp, outputs=out)
app.launch(server_port=9999,server_name="0.0.0.0")

`

**errors:**

Traceback (most recent call last):
  File "/Users/alvin/Library/Python/3.8/lib/python/site-packages/gradio/routes.py", line 384, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/alvin/Library/Python/3.8/lib/python/site-packages/gradio/blocks.py", line 1030, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "/Users/alvin/Library/Python/3.8/lib/python/site-packages/gradio/blocks.py", line 922, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "/Users/alvin/Library/Python/3.8/lib/python/site-packages/gradio/components.py", line 2087, in preprocess
    sample_rate, data = processing_utils.audio_from_file(
  File "/Users/alvin/Library/Python/3.8/lib/python/site-packages/gradio/processing_utils.py", line 200, in audio_from_file
    audio = AudioSegment.from_file(filename)
  File "/Users/alvin/Library/Python/3.8/lib/python/site-packages/pydub/audio_segment.py", line 728, in from_file
    info = mediainfo_json(orig_file, read_ahead_limit=read_ahead_limit)
  File "/Users/alvin/Library/Python/3.8/lib/python/site-packages/pydub/utils.py", line 279, in mediainfo_json
    info = json.loads(output)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

empty

### Screenshot

empty

### Logs

```shell
empty
```

### System Info

```shell
gradio version is 3.20

``` 

### Severity

blocking all usage of gradio

**Comment by abidlabs** [comment] 2023-03-06 15:25
Hi @jkluo I cannot reproduce the issue locally, nor on Colab: https://colab.research.google.com/drive/1YAz3sPjEil_CWuihkItIMezQPMiqtitJ?usp=sharing

Can you try seeing if you can reproduce this error on Colab and share the resulting code with us?

**Comment by jkluo** [comment] 2023-03-06 15:33
> Hi @jkluo I cannot reproduce the issue locally, nor on Colab: https://colab.research.google.com/drive/1YAz3sPjEil_CWuihkItIMezQPMiqtitJ?usp=sharing
> 
> Can you try seeing if you can reproduce this error on Colab and share the resulting code with us?


I don't know how it is caused. It may be my local environmental problem.
When I submitted the recording, the above error occurred.
I try to pip3 uninstall gradio &&  pip3 install gradio , But it hasn't been solved.
Are there any other dependent packages here？

**Comment by jkluo** [comment] 2023-03-06 15:35
> Colab
The code runing in Colab is ok

**Comment by jkluo** [comment] 2023-03-06 15:43
@abidlabs Thank you so much.

**Comment by abidlabs** [comment] 2023-03-06 16:08
Ok sounds good, so it looks like we can close this?

**Closed** 2023-03-06 16:08 UTC
Labels: needs repro
