### ISSUE TITLE
TABLE DISPLAY IN GRADIO OUTPUT

### ISSUE THREAD

**Issue by sathyapriyaa13** [gradio-app/gradio#6806] opened 2023-12-15 14:41 UTC
### Describe the bug

----GRADIO couldn't display o/p in tabular format--------even if upgraded to the latest version - please help

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

```

### Screenshot

![Screenshot (1454)](https://github.com/gradio-app/gradio/assets/147392056/9d15c33e-2e2b-41af-bb88-153af04eff2c)

### System Info

```shell
latest version is being used
```

### Severity

I can work around it

**Comment by freddyaboulton** [comment] 2023-12-15 15:48
Closing as duplicate of #6805 !

**Closed by freddyaboulton** 2023-12-15 15:48 UTC
Labels: bug
