### ISSUE TITLE
why Textbox can send the value is empty or "", Shouldn't it be checked before submitting?

### ISSUE THREAD

**Issue by Tiffany0622** [gradio-app/gradio#7675] opened 2024-03-12 10:43 UTC
### Describe the bug

why Textbox can send the value is empty or "", Shouldn't it be checked before submitting?
How to solve the problem when the user clicks the submit button without inputting a value, and the pending dialog box appears
Maybe you don't think this is a bug, but it shouldn't happen , and it will confuse users.

![image](https://github.com/gradio-app/gradio/assets/58634084/85f3a619-89db-44dd-96c1-166bdd7a7bed)

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

with gr.Blocks(css=css,theme=gr.themes.Default(font=[gr.themes.GoogleFont("Inconsolata"), "Arial", "sans-serif"])) as demo:
    gr.HTML(html_content)
    chatbot = gr.Chatbot(show_label=False, show_copy_button=True, likeable=True, elem_classes="chatbot_container")

   with gr.Row(elem_classes="message_form"):
        with gr.Column(elem_classes=["chat_input"]):
            msg = gr.Textbox(show_label=False, elem_id="inputTextBox", placeholder="......")
        with gr.Column(elem_classes=["submit_button"]):
            submit_button = gr.Button(elem_id="submitButton",value="↑")


    def user(user_message, history):
        if len(user_message) == 0 and (history is None or len(history) == 0):
            return "",  []      
        if not user_message.strip(): 
            return "", history
        if history is None:
            history = []
        return "", history + [[user_message, None]]

    def bot(history):
        if history is None or len(history) == 0:
            history = []
            return "", history + []
        
        question = history[-1][0]

        if question != "":
            history[-1][1] = ""
            answer(question=question)
            while True:
                try:
                    next_token = q.get(True, timeout=1)
                    if next_token is job_done:
                        break
                    history[-1][1] += next_token
                    yield history
                except Empty:
                    continue
        else:
            return history



    msg.submit(user, [msg, chatbot], [msg, chatbot], queue=False).then(bot, chatbot, chatbot)



```

### System Info

```shell
gradio==4.20.0
```

### Severity

I can work around it

**Comment by freddyaboulton** [comment] 2024-03-12 17:11
Hi @Tiffany0622 - this is a duplicate of #2718 . If you don't want to allow empty messages you can modify your function to check the length of the message and raise an error

```python
if not len(user_message):
    raise gr.Error("Chat messages cannot be empty")
```

**Closed by freddyaboulton** 2024-03-12 17:11 UTC
Labels: bug
