### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'python'

### ISSUE THREAD

**Issue by RichardKentos** [gradio-app/gradio#5833] opened 2023-10-06 19:41 UTC
### Describe the bug

Today I tried to create my first gradio app. I followed the quickstart, but then when I ran gradio app.py in terminal I have received this error. When I run python app.py, everything's fine, it's just the auto reload that is not working. What could I do?

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

1. create file app.py
2. place this code inside

`import gradio as gr`

```
with gr.Blocks() as demo:
    gr.Markdown("# Greetings from Gradio!")
    inp = gr.Textbox(placeholder="What is your name?")
    out = gr.Textbox()
```

    inp.change(fn=lambda x: f"Welcome, {x}!",
               inputs=inp,
               outputs=out)

```
if __name__ == "__main__":
    demo.launch()`
```
3. run gradio app.py in terminal

### Screenshot

<img width="1061" alt="image" src="https://github.com/gradio-app/gradio/assets/77812166/e1377baf-3b9c-4634-8ccc-c6f6b3835e17">

### System Info

```shell
Operating System: Darwin
gradio version: 3.47.1
gradio_client version: 0.6.0
```

### Severity

I can work around it

**Comment by freddyaboulton** [comment] 2023-10-06 19:44
I know what the problem is @RichardKentos ! Thanks for filing. I think this related to #5464

**Comment by RichardKentos** [comment] 2023-10-06 20:24
> I know what the problem is @RichardKentos ! Thanks for filing. I think this related to #5464

So I have added shell=True, but now I got:

`python: command not found`

Could it be something with the fact that I have 2 different Python interepreters? Gradio is installed on 3.11

<img width="601" alt="image" src="https://github.com/gradio-app/gradio/assets/77812166/65a95850-4b58-472c-9c03-94bd63d616bb">

**Comment by freddyaboulton** [comment] 2023-10-06 20:33
Yea I think we need to do `shutil.which("python")` to find the python executable for the current environment you're in.

**Comment by RichardKentos** [comment] 2023-10-06 20:45
Good news, I have added this:
<img width="652" alt="image" src="https://github.com/gradio-app/gradio/assets/77812166/c4adef0e-3bd7-4f3f-97a6-b3d2d9f64e00">
and it resolved the issue. I recently created alias for python=python3, but obviously it caused some error. Do you know why?

Also, I wanted to ask if this changing the Gradio's code is safe, and if this error could also occur when I deploy it elsewhere.

Thank you very much for the very quick responses and help  👌🏻

**Comment by henryruhs** [comment] 2023-10-08 13:01
There is this:

```
import sys

print(sys.executable)
```

**Comment by freddyaboulton** [comment] 2023-10-12 19:59
Closed in v4 branch!

**Closed by freddyaboulton** 2023-10-12 19:59 UTC
Labels: bug
