### ISSUE TITLE
ChatInterface raise ValueError

### ISSUE THREAD

**Issue by pesiwang** [gradio-app/gradio#7201] opened 2024-01-29 01:55 UTC
### Describe the bug

when I submit empty message, ChatInterface raise ValueError: Invalid message for Chatbot component: {'code': 1, 'msg': "runtime error{'error_code': 336003, 'error_msg': 'message content can not be empty', 'id': 'as-g7hxmhegi5'}"}

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

app = FastAPI()
io = gr.ChatInterface(agent_framework_run)
app = gr.mount_gradio_app(app, io, path=CUSTOM_PATH)
```

### Logs

```shell
runtime error: {'error_code': 336003, 'error_msg': 'message content can not be empty', 'id': 'as-g7hxmhegi5'}
Traceback (most recent call last):
  File "D:\demo_code\python_samples\fastapi_sample\myenv\Lib\site-packages\gradio\queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\demo_code\python_samples\fastapi_sample\myenv\Lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\demo_code\python_samples\fastapi_sample\myenv\Lib\site-packages\gradio\blocks.py", line 1570, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\demo_code\python_samples\fastapi_sample\myenv\Lib\site-packages\gradio\blocks.py", line 1455, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\demo_code\python_samples\fastapi_sample\myenv\Lib\site-packages\gradio\components\chatbot.py", line 214, in postprocess
    self._postprocess_chat_messages(message_pair[1]),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\demo_code\python_samples\fastapi_sample\myenv\Lib\site-packages\gradio\components\chatbot.py", line 193, in _postprocess_chat_messages
    raise ValueError(f"Invalid message for Chatbot component: {chat_message}")
ValueError: Invalid message for Chatbot component: {'code': 1, 'msg': "runtime error{'error_code': 336003, 'error_msg': 'message content can not be empty', 'id': 'as-g7hxmhegi5'}"}
```

### System Info

```shell
mac, window and linux work the same
```

### Severity

Blocking usage of gradio

**Comment by fatelei** [comment] 2024-01-29 06:22
maybe this is not a bug, client should handle empty message

**Comment by abidlabs** [comment] 2024-01-29 12:47
Hi @pesiwang can you please provide a minimal code example that we can use to reproduce the issue above? See: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by abidlabs** [comment] 2024-01-30 19:24
Closing for lack of followup but happy to reopen once we have a repro

**Closed by abidlabs** 2024-01-30 19:24 UTC
Labels: needs repro
