### ISSUE TITLE
gradio_client with remote HF private instance

### ISSUE THREAD

**Issue by tomerkulla** [gradio-app/gradio#8564] opened 2024-06-16 14:09 UTC
### Describe the bug

Hello I trying to request my private HF space gradio via python gardio_client and I'm getting error that my MultimodalTextbox is str while it's defently dict

this is the init on the HF space side:
```
demo = gr.ChatInterface(fn=bot_streaming, title="Heello",  description="Hello",
  | stop_btn="Stop Generation", multimodal=True)

```

this is how I call it on python script side:
```
gradioClient = Client("...", hf_token="....")

result2 = gradioClient.predict(
		{"text":"sample text","files":[file("examples/image2.jpg")]},
		api_name="/chat"
)

```

the error I get on the script side:
```
line 1228, in _predict
    raise AppError(
gradio_client.exceptions.AppError: The upstream Gradio app has raised an exception: MultimodalTextbox expects a dictionary with optional keys 'text' and 'files'. Received str
```

on the HF logs side I get something similar:
```
ValueError: MultimodalTextbox expects a dictionary with optional keys 'text' and 'files'. Received str
{'text': 'sample text', 'files': [{'path': '/tmp/gradio/92bcb021af1315abcd6ab08f98c8da2b340fed5e/image2.jpg', 'url': '/file=/tmp/gradio/92bcb021af1315abcd6ab08f98c8da2b340fed5e/image2.jpg', 'size': None, 'orig_name': 'image2.jpg', 'mime_type': None, 'is_stream': False, 'meta': {'_type': 'gradio.FileData'}}]}
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
```

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

mentioned above

### System Info

```shell
on script side:
gradio==4.36.1
gradio_client==1.0.1

on HF space side: (not sure if I can upgrade the version there?)
gradio==4.22.0
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment] 2024-06-19 18:50
Hi @tomerkulla I'm not able to reproduce this when I test on `main`:

```py
import gradio as gr

_, url, _ = gr.ChatInterface(lambda x,y: x).launch(inline=False, show_error=True)

from gradio_client import Client, file

gradioClient = Client(url)

result2 = gradioClient.predict(
		{"text":"sample text","files":[file("cheetah.jpg")]},
		api_name="/chat"
)
```

* Can you try upgrading the `gradio` version in the HF Space? You can indeed do it by going to the README.md and updating the `sdk_version` to `4.36.1`
* If you still continue to face this issue, does this also happen if the Space is public

**Comment by abidlabs** [comment] 2024-06-20 15:48
I'm going to close this for now, but can reopen if still an issue.

**Closed by abidlabs** 2024-06-20 15:48 UTC
Labels: bug, needs repro, pending clarification

**Comment by keeeal** [comment] 2024-07-01 06:22
@tomerkulla Did you manage to resolve this issue? I am getting the same error message - but when connecting to a locally running ChatInterface rather than a huggingface space.
