### ISSUE TITLE
tmp directory is being cleaned

### ISSUE THREAD

**Issue by msis** [gradio-app/gradio#4620] opened 2023-06-21 21:38 UTC
### Describe the bug

The temporary directory is never cleared:
```sh
$ du -hd0 /tmp/gradio/
24G     /tmp/gradio/
```

This leads to filling up all the disk space available until none is available.

`gradio` then will fail:
```
Traceback (most recent call last):                                                                                                                                                  
  File "/home/msis/.local/lib/python3.10/site-packages/gradio/routes.py", line 437, in run_predict                                                                                  
    output = await app.get_blocks().process_api(                                                                                                                                    
  File "/home/msis/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1350, in process_api                                                                                 
    inputs = self.preprocess_data(fn_index, inputs, state)                                                                                                                          
  File "/home/msis/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1200, in preprocess_data                                                                             
    processed_input.append(block.preprocess(inputs[i]))                                                                                                                             
  File "/home/msis/.local/lib/python3.10/site-packages/gradio/components/audio.py", line 191, in preprocess                                                                         
    temp_file_path = self.base64_to_temp_file_if_needed(file_data, file_name)                                                                                                       
  File "/home/msis/.local/lib/python3.10/site-packages/gradio/components/base.py", line 302, in base64_to_temp_file_if_needed                                                       
    fb.write(data)                                                                                                                                                                  
OSError: [Errno 28] No space left on device
```

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

The following example will store the audio files in `/tmp/gradio/` but never clean after itself:
```py
import os

import gradio as gr
from pydub.utils import mediainfo

def get_duration_ms(audio_file):
    duration = mediainfo(audio_file)["duration"]  # a string in seconds
    duration_ms = int(float(duration) * 1000)
    print(f"{audio_file}: {duration_ms} ms")
    return duration_ms


with gr.Blocks() as demo:
    with gr.Row():
        audio_file = gr.Audio(source="upload", type="filepath", label="File")

    b2 = gr.Button("Get Duration")

    with gr.Row():
        duration = gr.TextArea(label="Duration")

    b2.click(
        get_duration_ms,
        inputs=[audio_file],
        outputs=[duration],
        api_name="get_duration_ms",
    )

demo.queue(concurrency_count=30)
demo.launch(server_name="0.0.0.0")
```

### System Info

```shell
- `gradio`: '3.35.2'
- `gradio_client`: '0.2.7'
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment] 2023-06-21 21:42
Hi @msis ! This is a duplicate of https://github.com/gradio-app/gradio/issues/3950 so I will close.

In general, we don't know when a user is "done" with a file so we don't know when we can delete it.

**Closed by freddyaboulton** 2023-06-21 21:42 UTC
Labels: bug

**Comment by msis** [comment] 2023-06-21 21:49
I looked and that issue didn't come up...
I will take the conversation there then.

**Comment by freddyaboulton** [comment] 2023-06-21 21:59
No worries - thanks!!
