### ISSUE TITLE
Can't get value

### ISSUE THREAD

**Issue by Gerschel** [gradio-app/gradio#2837] opened 2022-12-16 02:26 UTC
### Describe the bug

Can't get updated value of component from calling components.value member.  
I know how to use inputs to pass the values. But in an environment where my script is loaded in, and others as well, and they hand me the component, but my script was setup before others, my event handlers have no knowledge of those components. So i must be able to access the values directly.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```python
import gradio as gr                                                   
                                                                      
                                                                      
with gr.Blocks(analytics_enabled=False) as demo:                      
    t = gr.Slider()                                                   
    t.change(fn=lambda x: print(f"t-value = {x}"), inputs=t)          
                                                                      
    b = gr.Button()                                                   
    b.click(fn = lambda: print(f"Direct access to t.value = {t.value}"))
                                                                      
if __name__ == "__main__":                                            
    demo.launch()       
```

### Screenshot

![image](https://user-images.githubusercontent.com/9631031/208007338-a4c0272b-d1c4-4713-ba8d-f2222bf66083.png)

### Logs

```shell
No errors
```

### System Info

```shell
Windows 10
gradio 3.9
```

### Severity

annoying

**Comment by freddyaboulton** [comment] 2022-12-16 14:35
Hi @Gerschel ! The state of the component is stored in the front-end and not in the component instance itself. This is by design. We may store some front-end state in the backend in the future but the api for that is not settled.

What are you trying to accomplish?

**Comment by abidlabs** [comment] 2022-12-16 15:15
You can also pass in the current value of the by supplying the component as the argument to the `inputs` parameter of an event listener. Like this:

```py
import gradio as gr                                                   
                                                                      
                                                                      
with gr.Blocks(analytics_enabled=False) as demo:                      
    t = gr.Slider()                                                   
    t.change(fn=lambda x: print(f"t-value = {x}"), inputs=t)          
                                                                      
    b = gr.Button()                                                   
    b.click(fn = lambda x: print(f"Direct access to t.value = {x}"), inputs=t)
                                                                      
if __name__ == "__main__":                                            
    demo.launch()       
```

**Comment by Gerschel** [comment] 2022-12-17 18:11
It's very specific.  I have mostly resolved it, I had to flip my code around and get more sleep.
It's still worth mentioning, so you have information on how users implement gradio. My next fix would have to be working with the other project to implement some method() that executes after all other scripts have there components loaded, then load my .change() .clicks() and .submits()

There's a Script class that goes in to user created files, as either custom scripts or extensions, and there are other built-in extensions, that this class loads.  

During loading of these scripts, we can signal to the class that we are interested in getting components from other scripts.  
Depending on the sort order, some of these components don't exist yet by the time my ui is created, but eventually I do get to see them all.  


I don't like mentioning other projects if I don't know if it's acceptable, but I think I need to for clarity, the task of my script would make more sense.  
I'm building a custom extension for automatic1111 stable-diffusion-webui, https://github.com/AUTOMATIC1111/stable-diffusion-webui which uses gradio  
My extension https://github.com/Gerschel/sd_web_ui_preset_utils serves to act like a preset manager.  
There are no presets for the app otherwise.

In my script, I create a dictionary to hold the components, while the component doesn't exist yet, I put `None` in it's place.
Because my script is loaded in more than one tab, and components could be different between tabs, `None` is used in the list comprehension as a filter so it creates the correct amount of inputs.  

```python
self.save_button.click(
    fn = self.save_config(path=self.settings_file),
    inputs = [self.save_as] + [self.component_map[comp_name] for comp_name in list(x for x in self.available_components if self.component_map[x] is not None)],
    outputs = [self.save_as, self.preset_dropdown]
)
```  
In this code section, available_components (yes it needs renamed to suit what it does now, because I extended it to work for custom scripts instead of default components), is a list of component labels, to say capture these ones only when all are handed to me.  
component_map is a dictionary that holds these labels as the keys, and the reference to the actual component in the values field of the dictionary.  

So it builds a list of components that match the desired ones from the list if the component exists in the map (if not None).  

If another script gets loaded after mine, this value remains as None for a short time.
It's hard to remember the exact problem, but it went someting like this. 
I had put the `None` filter in the list comprehension in the wrong place. The list comprehension consisted of a single comprehension instead of a nested comprehension.  

Old way:
```python
inputs = [self.save_as] + [self.component_map[comp_name] for comp_name in self.available_components if self.component_map[comp_name] is not None],
```

I can't really describe how this was the issue, it looks right, but I think the list comprehenison was locking in the width of inputs during run-time, but in the new code, it rebuilds the list inner list, so the width of inputs gets updated.  

The old way seemed like it made sense, but it resulted in handing off 19 components, when there were 20, so in the function, I would receive 19, but I could see 20 if I called the map directly.

So I was attempting to reach in to my mapping and extract the updated values.

An idea I almost played around with, if an event handler has a way of getting the updated values, I could grab the event handler from memory and force it to trigger, another idea was to grab the .change() or .click() methods, go in to their __dict__ and modify their inputs and outputs directly, but I assume that during load time, it builds javascript, and this javascript wouldn't be updated to include them.  

Finally, for a comlete fix, I could climb the parent tree in the __dict__, then traverse the children, much earlier, instead of waiting for the hand-off.

**Comment by abidlabs** [comment] 2022-12-18 18:45
Thanks for providing the complete explanation @Gerschel. It will hopefully help other folks who have a similar question. Closing this issue

**Closed by abidlabs** 2022-12-18 18:45 UTC
Labels: question

**Comment by Gerschel** [comment] 2022-12-20 08:34
I just want to really thank you for your help. You said it to me before, you mentioned stored in front end and stored in back end.  

I put a lot of thought into this, what do I need to do to synchronize the backend to what is in the front-end, and how do I manipulate the dom from the back-end. It really helped a lot. I just wasn't quite grasping the details. Hours and hours pouring over both codebases, drilling in and out of files. 

Your words were right on key, there was no simpler way to explain it. It totally clicks now. I can manipulate values, choices, everything all from instructions on the back-end, because your tool is so in-depth, it builds all the front-end that I need. Blows my mind. 

Thank you.
