### ISSUE TITLE
cannot import name 'RootModel' from 'pydantic' 

### ISSUE THREAD

**Issue by MohamedAliRashad** [gradio-app/gradio#6492] opened 2023-11-19 11:35 UTC
### Describe the bug

cannot import name 'RootModel' from 'pydantic' 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

import gradio

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 4.4.1
gradio_client version: 0.7.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.1.1
fastapi: 0.103.1
ffmpy: 0.3.1
gradio-client==0.7.0 is not installed.
httpx: 0.25.0
huggingface-hub: 0.16.4
importlib-resources: 6.0.1
jinja2: 3.1.2
markupsafe: 2.1.2
matplotlib: 3.7.3
numpy: 1.23.5
orjson: 3.9.7
packaging: 23.1
pandas: 2.1.0
pillow: 10.1.0
pydantic: 2.5.1
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
requests: 2.23.0
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.7.1
uvicorn: 0.23.2
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.4.0
httpx: 0.25.0
huggingface-hub: 0.16.4
packaging: 23.1
requests: 2.23.0
typing-extensions: 4.7.1
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment] 2023-11-20 16:58
Are you able to reproduce this in a clean environment like Google Colab notebook? We've seen reports of this issue but I'm not able to reproduce?

**Comment by freddyaboulton** [comment] 2023-11-20 17:54
Hi @MohamedAliRashad ! Do you have multiple versions of pydantic installed in the same environment, like with conda? I would make sure only one version is installed (preferrably via pip)!

**Comment by MohamedAliRashad** [comment] 2023-11-21 12:09
@abidlabs 
It works in a clean environment like colab but it doesn't work on my conda environment.

**Comment by freddyaboulton** [comment] 2023-11-21 17:06
Can you try in a new conda environment? Since we can't repro in a fresh environment, I will close this!

**Closed by freddyaboulton** 2023-11-21 17:06 UTC
Labels: bug, pending clarification

**Comment by MohamedAliRashad** [comment] 2023-11-21 22:05
@freddyaboulton 
I tried to remove `gradio` and `gradio_client` and reintsall them and everything worked.
