### ISSUE TITLE
`Remove All` button on `gr.Dropdown` should be hideable/configurable

### ISSUE THREAD

**Issue by space-nuko** [gradio-app/gradio#3526] opened 2023-03-20 01:23 UTC
### Describe the bug

Dropdowns with a single element might not want to support removal of the single element. There should be a property on `gr.Dropdown` that configures if the button is hidden or not.

Also, the user might want to configure the `Remove All` behavior. Say there's a `None` element in the dropdown they'd want to switch to if the button is clicked, it should be able to be passed as a property, and the button should be hidden if that item is selected

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Create `gr.Dropdown()` with `multiselect=false`
2. Populate dropdown with items
3. `Remove All` button appears

### Logs

```shell
N/A
```

### System Info

```shell
3.22.1, Windows, Chromium
```

### Severity

annoying

**Comment by space-nuko** [comment] 2023-03-20 04:02
Actually this is a duplicate of #3435

**Comment by pngwn** [comment] 2023-03-28 22:57
Dupe of #3435 as mentioned. Closing.

**Closed by pngwn** 2023-03-28 22:57 UTC
Labels: enhancement
