### ISSUE TITLE
How to define function for regression problems

### ISSUE THREAD

**Issue by pit9921** [gradio-app/gradio#161] opened 2021-04-26 17:49 UTC
I can't to define the the function for a regression model.
The goal is to display the predicted value in the app.
Could you please modify the last row in the code below. The Output "Durchmesser" is continuous.

  
```
def predict(model, ESD, NDZ, NDH, WTemp): 
   df = pd.DataFrame.from_dict({'ESD': [ESD], 'NDZ': [NDZ], 
                                 'NDH': [NDH], 'WTemp': [WTemp]})
    
    model_index = list(compare_model_results['Model']).index(model)
    model = best[model_index]
    pred = predict_model(model, df)
    return {'Durchmesser': pred['Label'][0].astype('float64')}
```

**Comment by abidlabs** [comment] 2021-04-26 17:59
Can you try converting it to a `float` instead of a `numpy` `float`? So change the last line to be:
```return {'Durchmesser': float(pred['Label'][0].astype('float64'))}```

**Comment by pit9921** [comment] 2021-04-26 18:30
Thank you for the answer. But there is no improvement.
What should i check?

![grafik](https://user-images.githubusercontent.com/77811022/116132474-e545de80-a6cd-11eb-9168-50e54edd5f86.png)

![grafik](https://user-images.githubusercontent.com/77811022/116132754-3229b500-a6ce-11eb-90da-124eced030e7.png)

**Comment by abidlabs** [comment] 2021-04-26 18:50
@pit9921 would you be able to share a colab notebook with the complete code so that we can try running it? It sounds like the problem is with the line `pred = predict_model(model, df)`, not with the gradio interface

**Comment by abidlabs** [comment] 2021-04-29 18:53
Based on the colab notebook that you shared from me, the problem is that you are not passing in any values for the features ESZ', 'MTemp', 'UTemp', 'LF', and 'KUZ'. If you pass in these features, your function should work. Closing as this is not a gradio-related error.

**Closed by abidlabs** 2021-04-29 18:53 UTC
