### ISSUE TITLE
Request for Adding Multi-page Support in Gradio

### ISSUE THREAD

**Issue by YuminosukeSato** [gradio-app/gradio#5164] opened 2023-08-10 03:26 UTC
- [ ] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
I often find the need to create interfaces with multiple pages using Gradio. Currently, Gradio supports single-page interfaces, but there are cases where having the ability to switch between different pages within the interface would greatly enhance the user experience.

**Describe the solution you'd like**  
I would like to request the addition of a feature that allows users to create multi-page interfaces using Gradio. This feature would enable us to define multiple pages within a single Gradio application and provide a way to navigate between them. Each page could contain its own set of input and output components, making it easier to organize and present complex interactions to the users.

**Additional context**  
In some applications, it becomes necessary to divide the user interaction flow into different sections or steps. For instance, in a survey application, there might be separate pages for user registration, survey questions, and submission confirmation. The ability to create such multi-page interfaces using Gradio would enhance its versatility and applicability for a wider range of use cases.

**Comment by pngwn** [comment] 2023-08-10 07:57
This is a duplicate of #2654. Feel free to take a look at that issue and add any additional information there.

**Closed by pngwn** 2023-08-10 07:57 UTC
