### ISSUE TITLE
can chatbot or textbox add “like button” to each text just like "show copy box"

### ISSUE THREAD

**Issue by Shelliemayinforest** [gradio-app/gradio#5389] opened 2023-08-31 07:41 UTC
hi:
I'd like to use this "like button" to tell the app to cache the user prefer answer in the backgroud.
the action after user click the "like button" means he is  satisfied with the answer, and I need to cache the query and response both in to a cache store, can you please tell me how to do it ? or is there any existing interface to do it .
thanks.

![image](https://github.com/gradio-app/gradio/assets/95324821/469ac72e-8b4a-4263-a680-621522b0c3e0)

**Comment by abidlabs** [comment] 2023-08-31 14:14
Thanks @Shelliemayinforest. This is a duplicate of #5250 so I'll go ahead and close.

**Closed by abidlabs** 2023-08-31 14:14 UTC
