### ISSUE TITLE
A component to render Youtube/Vimeo videos

### ISSUE THREAD

**Issue by sunilkumardash9** [gradio-app/gradio#4339] opened 2023-05-25 18:30 UTC
### Describe the bug

It seems gr.Video()  is not able to render youtube videos. 

It works perfectly with URLs like [https://f.vimeocdn.com/_videos/home/desktop-masthead-720p-2.mp4](https://f.vimeocdn.com/_videos/home/desktop-masthead-720p-2.mp4)

But cannot render videos like [https://vimeo.com/829951809](https://vimeo.com/829951809) or [https://www.youtube.com/watch?v=MHlNcKr9g50&list=RDMHlNcKr9g50&start_radio=1
](https://www.youtube.com/watch?v=MHlNcKr9g50&list=RDMHlNcKr9g50&start_radio=1)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
import gradio as gr

with gr.Blocks() as demo:
    video = gr.Video(interactive=True)
    url = gr.Textbox()

    url.submit(lambda x:x, inputs=url, outputs=video)

demo.launch()
```

### Logs

```shell
Logs are Normal
```

### System Info

```shell
gradio==3.31.0
```

### Severity

annoying

**Comment by abidlabs** [comment] 2023-05-25 23:23
Hi @sunilkumardash9 this is by design as the video component only supports direct filepaths. We process videos in certain ways that would require downloading YouTube videos and there isn't a reliable way to do that from YouTube and Vimeo.

That being said, we _are_ working on letting community members build their own components and I could imagine interest in building a community component specifically designed to handle YouTube/Vimeo components so I'll rename the issue as such.

**Comment by abidlabs** [comment] 2023-11-07 00:06
Hey! We've now made it possible for Gradio users to create their own custom components -- meaning that you can write some Python and JavaScript (Svelte), and publish it as a Gradio component. You can use it in your own Gradio apps, or share it so that anyone can use it in their Gradio apps. Here are some examples of custom Gradio components:

* A "Rich Textbox" that [allows you to write bold/italics/colored text](https://huggingface.co/spaces/abidlabs/gradio_rich_textbox)
* A "Folium Map Viewer" component that [allows you to use interactive maps](https://huggingface.co/spaces/freddyaboulton/gradio_folium)

You can see the source code for those components by clicking the "Files" icon and then clicking "src". The complete source code for the backend and frontend is visible. **In particular, its very fast if you want to build off an existing component**. We've put together a Guide: https://www.gradio.app/guides/five-minute-guide, and we're happy to help. Hopefully this will help address this issue.

**Comment by abidlabs** [comment] 2023-12-05 16:34
I'll go ahead and close this issue since we are not planning to include this in the core Gradio library. But happy to help if you are interested in making this a custom Gradio component (feel free to ask questions in this issue).

**Closed by abidlabs** 2023-12-05 16:34 UTC
Labels: new component
