### ISSUE TITLE
Image input with *.png not working

### ISSUE THREAD

**Issue by TangWen920812** [gradio-app/gradio#4005] opened 2023-04-28 10:26 UTC
### Describe the bug

When I use the image input with .png, there is a error: Unexpected token '<', " <!DOCTYPE "... is not valid JSON
But it was fine when I using .jpg input.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

def sepia(input_img):
    sepia_filter = np.array([
        [0.393, 0.769, 0.189], 
        [0.349, 0.686, 0.168], 
        [0.272, 0.534, 0.131]
    ])
    sepia_img = input_img.dot(sepia_filter.T)
    sepia_img /= sepia_img.max()
    return sepia_img

demo = gr.Interface(sepia, gr.Image(shape=(200, 200)), "image")
demo.launch()

It happened in the example in quickstart. 

### Logs

```shell
'Unexpected token '<', " <!DOCTYPE "... is not valid JSON'
```

### System Info

```shell
gradio version == 3.27.0
ubuntu == 18.04
python == 3.8.10
```

### Severity

annoying

**Comment by abidlabs** [comment] 2023-04-28 19:56
Hi @TangWen920812 I can't reproduce this issue. Can you try setting up a demo on a reproducible environment such as a Colab notebook and linking that here? Also please check and make sure the .png file you are using is valid.

**Comment by abidlabs** [comment] 2023-05-01 17:08
Closing for lack of followup. @TangWen920812 feel free to reopen with a reproducible example.

**Closed by abidlabs** 2023-05-01 17:08 UTC
Labels: needs repro

**Comment by sabir-sayyed** [comment] 2023-07-06 14:46
hey , i am facing a similar issue , heres  a public url https://251bed48f6a7bb769d.gradio.live/ 
and this is the note book **https://www.kaggle.com/sabirsayyed/merc-bmw**

**Comment by ndvbd** [comment] 2024-01-15 08:41
https://github.com/gradio-app/gradio/issues/3185
change
demo.launch(share=True)
to
demo.queue().launch(share=True)
Enabling the queue is required for inference times > 60 seconds: https://gradio.app/key-features/#queuing
