### ISSUE TITLE
Support S3 pre-signed URL as value for video component

### ISSUE THREAD

**Issue by Sreerag-ibtl** [gradio-app/gradio#3940] opened 2023-04-22 12:28 UTC
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
I am trying to make a video stored in an s3 bucket displayed. I am returning pre-signed URL to the video file in s3. For some reason, gradio complains file not found. The exact traceback is as follows:
```
Traceback (most recent call last):                              ]    
  File "/usr/local/lib/python3.9/site-packages/gradio/routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.9/site-packages/gradio/blocks.py", line 1111, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/usr/local/lib/python3.9/site-packages/gradio/blocks.py", line 1045, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/usr/local/lib/python3.9/site-packages/gradio/components.py", line 2145, in postprocess
    y = processing_utils.convert_video_to_playable_mp4(y)
  File "/usr/local/lib/python3.9/site-packages/gradio/processing_utils.py", line 523, in convert_video_to_play
able_mp4
    shutil.copy2(video_path, tmp_file.name)
  File "/usr/local/lib/python3.9/shutil.py", line 444, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/lib/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'https://pre-signed-url'
```
**Describe the solution you'd like**  
I would like to have the video displayed without throwing exceptions when given a valid URL to an object in s3.

**Additional context**  
I am assuming the URL is not in a format that satisfies the internal URL validator since it complains about the file not found error.

**Comment by abidlabs** [comment] 2023-04-23 23:06
Hi @Sreerag-ibtl can you share:
* Minimal code to reproduce the problem? 
* An example of what a presigned URL looks like?

**Comment by abidlabs** [comment] 2023-04-28 21:49
Closing for lack of follow up

**Closed by abidlabs** 2023-04-28 21:49 UTC
Labels: needs repro
