### ISSUE TITLE
Web UI not correctly rendered when path comes with prefix while custom CSS is used

### ISSUE THREAD

**Issue by BorisPolonsky** [gradio-app/gradio#3798] opened 2023-04-10 11:30 UTC
### Describe the bug

Path for `theme.css` is not correctly handled when path to app comes with prefix, which leads to failed UI rendering attempt in browser.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Path for `theme.css`` is not correctly handled when path to app comes with prefix
```
#! -*- coding: utf-8 -*-

import gradio as gr
import random
import time
import os
import logging
import re


def convert_history2massages(history):
    messages = [
        {"role": "system", "content": "You are a helpful assistant."},
    ]
    for h in history:
        query, response = h
        if query:
            messages.append({"role": "user", "content": query})
        if response:
            messages.append({"role": "assistant", "content": response})
    return messages


def clean_text(text):
    res = re.sub(r'\n{2,}', '\n\n', text)
    return res

def get_chat_bot_interface():
    with gr.Blocks() as bot_interface:
        def chat(input_, history):
            history = history or []
            logging.info(f'input text: {input}')
            response, history = model.chat(tokenizer, input_, history=history)
            return '', history, history

        chatbot = gr.Chatbot(label='ChatGLM Assistant AI Demo')#\
            #.style(height=500, color_map={"AI": 'blue', 'You': 'green'})
        message = gr.Textbox(label='Say hello')
        state = gr.State()
        submit = gr.Button("submit")
        clear = gr.Button("Clear")
        message.submit(chat, inputs=[message, state], outputs=[message, chatbot, state])
        submit.click(chat, inputs=[message, state], outputs=[message, chatbot, state])

        def clear_function(input_, history):
            return '', [], []
        clear.click(clear_function, [message, state], [message, chatbot, state], queue=False)

        return bot_interface


if __name__ == "__main__":
    bot_interface = get_chat_bot_interface()
    bot_interface.launch(server_port=5000, debug=True)
    logging.info("Started")
```
- Deploy the example app as shown above on a cloud where the path for the service is automatically generated, say `/inference/s-20230410163708-b5ps2/rest/`
- Browse http://domain./inference/s-20230410163708-b5ps2/rest/

Header for `theme.css`, where HTTP 404 was popped
```
Request URL: http://10.128.15.51:30086/theme.css
Request Method: GET
Status Code: 404 Not Found
Remote Address: 10.128.15.51:30086
Referrer Policy: strict-origin-when-cross-origin
Connection: keep-alive
Content-Length: 548
Content-Type: text/html
Date: Mon, 10 Apr 2023 11:14:56 GMT
Accept: text/css,*/*;q=0.1
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9,zh-TW;q=0.8,zh;q=0.7
Connection: keep-alive
Cookie: _ga=GA1.1.89040943.1678252526; _gid=GA1.1.2093549719.1681121835
Host: 10.128.15.51:30086
Referer: http://10.128.15.51:30086/inference/s-20230410163708-b5ps2/rest/
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
```
Header for other resource (with path correctly handled), for example `Blocks.15437627.css`
```
Request URL: http://10.128.15.51:30086/inference/s-20230410163708-b5ps2/rest/assets/Blocks.15437627.css
Request Method: GET
Status Code: 200 OK
Remote Address: 10.128.15.51:30086
Referrer Policy: strict-origin-when-cross-origin
Connection: keep-alive
Content-Length: 8781
Content-Type: text/css; charset=utf-8
Date: Mon, 10 Apr 2023 11:14:56 GMT
etag: fe8e61371e20b3b6598c3a67860e7ee9
last-modified: Thu, 06 Apr 2023 09:41:45 GMT
Accept: text/css,*/*;q=0.1
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9,zh-TW;q=0.8,zh;q=0.7
Connection: keep-alive
Cookie: _ga=GA1.1.89040943.1678252526; _gid=GA1.1.2093549719.1681121835
Host: 10.128.15.51:30086
Referer: http://10.128.15.51:30086/inference/s-20230410163708-b5ps2/rest/
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
```

### Logs

```shell
root@dbc1a4a7d1eb:/app# python3 app.py
Running on local URL:  http://0.0.0.0:5000

To create a public link, set `share=True` in `launch()`.
```

### System Info

```shell
Gradio version: 3.24.1
```

### Severity

annoying

**Comment by abidlabs** [comment] 2023-04-10 12:33
Hi @BorisPolonsky thanks, I believe this is a duplicate of #3472. We are looking into this right now. Please chime into that issue, or feel free to reopen this issue if you think this isn't a duplicate.

**Closed by abidlabs** 2023-04-10 12:33 UTC
Labels: bug

**Comment by apc-may** [comment] 2024-12-11 06:07
Hello
Is the issue fixed in the latest version?
