### ISSUE TITLE
mount_gradio_app doesn't work when on a subpath

### ISSUE THREAD

**Issue by anentropic** [gradio-app/gradio#4291] opened 2023-05-19 22:02 UTC
### Describe the bug

I am mounting my gradio app inside a fastapi app on a subpath, like:

```python
gr.mount_gradio_app(app, blocks, path="/game")
```

But it fails.  The page loads, the interface displays, but the `load` event is never called and subsequent interaction fails. If I look in the logs I see:

```
INFO:     127.0.0.1:62434 - "GET /info HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:62434 - "GET /theme.css HTTP/1.1" 200 OK
```

So it seems like the `api_info` route defined in the Gradio app has failed to adopt the prefix it was mounted under

It's  weird because mounting should automatically prefix the urls of the sub app

I see the same thing with the example code from here: https://gradio.app/sharing-your-app/#mounting-within-another-fastapi-app ... it appears to work at first because the interface loads up, but it's not interactive and if you check the logs there is a request to `/info` which 404s

Issue won't be caught by the mount test here, as it only checks that the page loads:
https://github.com/gradio-app/gradio/blob/834afdd303c5942e58d612e0a8c02b3854c11a7c/test/test_routes.py#L341

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```python
from fastapi import FastAPI
import gradio as gr

CUSTOM_PATH = "/gradio"

app = FastAPI()


@app.get("/")
def read_main():
    return {"message": "This is your main app"}


io = gr.Interface(lambda x: "Hello, " + x + "!", "textbox", "textbox")
app = gr.mount_gradio_app(app, io, path=CUSTOM_PATH)
```

### Logs

```shell
poetry run uvicorn repro.app:app
INFO:     Started server process [82073]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     127.0.0.1:49849 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:49849 - "GET /info HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:49849 - "GET /theme.css HTTP/1.1" 200 OK
```

### System Info

```shell
gradio==3.31.0

Python 3.11.1
macOS
```

### Severity

blocking all usage of gradio

**Comment by abidlabs** [comment] 2023-05-19 22:08
@anentropic thanks for raising this issue, I think this must be something that broke recently. Can you see if it works if you use a slightly older version of gradio, such as `3.29.0`?

**Comment by anentropic** [comment] 2023-05-19 22:11
@abidlabs  indeed... 3.29.0 works fine 👍

**Comment by abidlabs** [comment] 2023-05-19 22:17
Ok we'll get this fixed soon! cc @pngwn

**Comment by pngwn** [comment] 2023-05-19 23:31
This is a duplicate of #4257 and was fixed in #4271 which was merged recently. 

It will be released shortly.

**Closed** 2023-05-19 23:31 UTC
Labels: bug

**Comment by giuliohome** [comment] 2023-05-20 08:08
@pngwn: - applied @anentropic's workaround (i.e. a `path` in `mount_gradio_app` of a `app = FastAPI()` plus the downgrade to 3.29... [reading now](https://github.com/gradio-app/gradio/issues/4257#issuecomment-1552352721) that 3.30 could have worked either), however let me now when the fix is released, thanks. 

btw... I've seen it's a [one-liner](https://github.com/gradio-app/gradio/pull/4271/files) in vitejs client: I guess it's called under the hood of `gr.Blocks()` where I was experiencing the issue with the `root_path` in the new [Blocks launch](https://gradio.app/docs/#blocks-launch-header)

**Comment by anentropic** [comment] 2023-05-22 17:33
I can confirm this seems fine in `3.32.0` now

**Comment by giuliohome** [comment] 2023-05-23 08:22
Does it work `with gr.Blocks() as demo:` or is it **another issue** to open?
```python
demo.launch(root_path=os.getenv('GR_ROOT'), debug=True, server_name="0.0.0.0", server_port=8000, show_api=False) 
```
and let say
```sh
ENV GR_ROOT="/chat"
```
**Am I missing** something or what? Getting `{"detail":"Not Found"}` from `http://localhost:8000/chat/`
Going to rollback again my code changes to the previous version 🤷‍♂️ in absence of feedback and also considering that this issue has been closed..
Thank you again for the above said workaround

**Comment by anentropic** [comment] 2023-05-23 10:13
As far as I understand it, `root_path` is something different - I don't think it can be used that way

`root_path` is for when a proxy server routing rule adds a path prefix to the url before it reaches your Starlette/FastAPI application

I doubt there is any way to serve on a subpath when using `demo.launch` alone, I would assume you have to mount it on the subpath within a FastAPI app and then run the FastAPI app (I'm using just Starlette and it works too)

**Comment by giuliohome** [comment] 2023-05-23 10:20
The doc says

> The root path (or "mount point") of the application, if it's not served from the root ("/") of the domain. For example, if the application is served at "https://example.com/myapp", the `root_path` should be set to "/myapp"

and it is a param of demo.launch

Is it a doc issue or again me not reading the docs correctly?

**Comment by giuliohome** [comment] 2023-05-23 11:24
Furthermore I see another problem with 3.32 that was not present in 3.29 ad 3.30

the chat messages contents are not rendered as html by as text! (I doubt this is a feature by design but I would guess it is a bug, am I correct?)

Just only for this I must rollback to 3.30 o 3.29.

**Comment by xingqiwu55555** [comment] 2023-07-06 09:11
3.35.2 still can't work.

**Comment by jianbohuang** [comment] 2023-07-10 17:24
> 
gradio-3.36.1  works

**Comment by EricoZhao** [comment] 2025-05-29 02:58
Tested it. gradio<=5.18 works fine, but when gradio>=5.19 it doesn't mount properly.
