### ISSUE TITLE
Issue with Gradio and SSL

### ISSUE THREAD

**Issue by bharadwaj509** [gradio-app/gradio#3846] opened 2023-04-13 19:06 UTC
### Describe the bug

Hello,

I have a issue with the ssl.  I got my cert and key files using openssl in remote ubuntu machine. I have to use the microphone and the http is not sufficient as I understand and that is the reason I am going for https. I got my self-signed certificate. And as I run it, the following is the error. 

I also followed the [#563](https://github.com/gradio-app/gradio/issues/563) and [#2551](https://github.com/gradio-app/gradio/issues/2551) to change the **blocks.py** but neither change did not work for me.

I see that you are working on some change on the latest gradio, please let me know if that CR is already publsihed.

Also, I have only 443 available as an open port at my company. Will the certificates work on that port?

If not, kindly help me on this.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

'
demo.launch(server_port=443,server_name="0.0.0.0", ssl_keyfile="key.pem", ssl_certfile="cert.pem")-
'

### Logs

```shell
`requests.exceptions.SSLError: HTTPSConnectionPool(host='localhost', port=443): Max retries exceeded with url: /startup-events (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:997)')))
`
```

### System Info

```shell
Gradio 3.10, Ubuntu machine accessing remotely.
```

### Severity

annoying

**Comment by bharadwaj509** [comment] 2023-04-13 19:08
Hey @abidlabs and @Escovilla , Could you please help me on this one when you get time?

**Comment by abidlabs** [comment] 2023-05-06 13:36
Should be fixed now via #3873!

**Closed by abidlabs** 2023-05-06 13:36 UTC
Labels: bug

**Comment by Nancis1130** [comment] 2023-07-10 03:06
Have you solved this issue?

**Comment by shanky100** [comment] 2023-07-27 11:51
demo.launch(share=False, server_name="0.0.0.0",server_port=7000,ssl_verify=False, ssl_certfile="cert.pem", ssl_keyfile="key.pem")

I am using this command, and my version are
gradio 3.39.0
gradio_client 0.3.0

I have used openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -sha256 -days 365 -nodes
to generate the files.

But I get this error again and again
requests.exceptions.SSLError: HTTPSConnectionPool(host='localhost', port=7000): Max retries exceeded with url: /startup-events (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)')))

Any help or solutions would be helpful.
