### ISSUE TITLE
`gr.ImageEditor` not showing icons

### ISSUE THREAD

**Issue by matabear-wyx** [gradio-app/gradio#9810] opened 2024-10-23 02:32 UTC
### Describe the bug

in gradio 5.0.2, the gr.ImageEditor block is not working as expected, after uploading an image, all the buttons below the block will disappear.
In 5.0.2:
![image](https://github.com/user-attachments/assets/9aca4cfc-b814-4e1b-a17d-fe50d0ecd978)
In 4.42.0:
![image](https://github.com/user-attachments/assets/869d6515-8c3e-4a0a-9d44-d6ef60ceba66)

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

input_image = gr.ImageEditor(label='Image', type='pil', sources=["upload", "webcam"], image_mode='RGB', layers=False, brush=gr.Brush(colors=["#FFFFFF"], color_mode="fixed"))
```

### System Info

```shell
gradio 5.0.2
```

### Severity

I can work around it

**Comment by matabear-wyx** [comment] 2024-10-23 02:38
And the issue remains the same in gradio 5.3.0

**Comment by flashingtt** [comment] 2024-10-23 09:33
The size of ImageEditor can not fix the input image size. I try to set the height of ImageEditor to 900, then I can see the editor buttons. Now I use ```return gr.update(height=, width=) to fix the input image size``` .It is so inconvenient, I wish the size of ImageEditor could be dynamic automatically.

**Comment by abidlabs** [comment] 2024-10-23 17:12
Actually just realized this is a duplicate of https://github.com/gradio-app/gradio/issues/9694

**Closed by abidlabs** 2024-10-23 17:12 UTC
Labels: bug, Priority, Regression, 🖼️ ImageEditor

**Comment by yaosheng216** [comment] 2024-10-25 02:56
@abidlabs I met this problem too in Gradio 5.3.0, wish can repair this problem.

**Comment by BangDoon** [comment] 2024-12-04 02:40
the issue still remains the same in gradio 5.7.1
