### ISSUE TITLE
The Colab link might need to be updated

### ISSUE THREAD

**Issue by xianbaoqian** [gradio-app/gradio#3034] opened 2023-01-20 14:34 UTC
### Describe the bug

https://gradio.app/developing-faster-with-reload-mode/

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Open https://gradio.app/developing-faster-with-reload-mode/ and click on [Here's a colab notebook](https://colab.research.google.com/drive/1jUlX1w7JqckRHVE-nbDyMPyZ7fYD8488?authuser=1#scrollTo=zxHYjbCTTz_5)

### Screenshot

<img width="691" alt="image" src="https://user-images.githubusercontent.com/38108242/213724112-513812a2-b44a-4009-8c8e-3e676bd9c6e0.png">

### Logs

```shell
Unable to see the content
```

### System Info

```shell
Chrome
```

### Severity

annoying

**Comment by abidlabs** [comment] 2023-01-20 16:36
Hi @xianbaoqian I just checked and colab links works for me both when I'm logged in as well as when I open it in incognito mode.  Can you double check your network, maybe there's some issues that are preventing you from accessing Colab notebooks?

**Comment by abidlabs** [comment] 2023-01-21 02:17
Confirmed on another device/browser as well, so will go ahead and close this -- please let me know if you find out any more to explain why it might not open for you.

**Closed by abidlabs** 2023-01-21 02:17 UTC
Labels: bug, needs repro
