### ISSUE TITLE
Gradio share with the gradio.live website has stopped working

### ISSUE THREAD

**Issue by cadaeix** [gradio-app/gradio#3067] opened 2023-01-27 04:09 UTC
### Describe the bug

Setting a launch with `share=True` issues a public link, and then errors out with (example) `ReadTimeout: HTTPSConnectionPool(host='XXXXXXXXXXX.gradio.live', port=443): Read timed out. (read timeout=3)`

Other users in the Huggingface discord are reporting 504 error timeouts on the gradio.live website

This makes Gradio unusable on Colab notebooks, example at https://colab.research.google.com/drive/1CxumIMuWqst7LOb9r9iYiXOtIBavBYqm

Local still works for me with share=False

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

import gradio as gr

with gr.Blocks() as main:
    t = gr.Textbox()

main.launch(share=True)

### Screenshot

From a Colab Notebook

![image](https://user-images.githubusercontent.com/26790650/215005937-4e6f8434-5c8f-48aa-ad16-2e805b32a7a0.png)

### Logs

```shell
---------------------------------------------------------------------------
TimeoutError                              Traceback (most recent call last)
File env\lib\site-packages\urllib3\connectionpool.py:449, in HTTPConnectionPool._make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
    445         except BaseException as e:
    446             # Remove the TypeError from the exception chain in
    447             # Python 3 (including for exceptions like SystemExit).
    448             # Otherwise it looks like a bug in the code.
--> 449             six.raise_from(e, None)
    450 except (SocketTimeout, BaseSSLError, SocketError) as e:

File <string>:3, in raise_from(value, from_value)

File env\lib\site-packages\urllib3\connectionpool.py:444, in HTTPConnectionPool._make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
    443 try:
--> 444     httplib_response = conn.getresponse()
    445 except BaseException as e:
    446     # Remove the TypeError from the exception chain in
    447     # Python 3 (including for exceptions like SystemExit).
    448     # Otherwise it looks like a bug in the code.

File C:\Program Files\Python310\lib\http\client.py:1374, in HTTPConnection.getresponse(self)
   1373 try:
-> 1374     response.begin()
   1375 except ConnectionError:

File C:\Program Files\Python310\lib\http\client.py:318, in HTTPResponse.begin(self)
    317 while True:
--> 318     version, status, reason = self._read_status()
    319     if status != CONTINUE:

File C:\Program Files\Python310\lib\http\client.py:279, in HTTPResponse._read_status(self)
    278 def _read_status(self):
--> 279     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
    280     if len(line) > _MAXLINE:

File C:\Program Files\Python310\lib\socket.py:705, in SocketIO.readinto(self, b)
    704 try:
--> 705     return self._sock.recv_into(b)
    706 except timeout:

File C:\Program Files\Python310\lib\ssl.py:1274, in SSLSocket.recv_into(self, buffer, nbytes, flags)
   1271         raise ValueError(
   1272           "non-zero flags not allowed in calls to recv_into() on %s" %
   1273           self.__class__)
-> 1274     return self.read(nbytes, buffer)
   1275 else:

File C:\Program Files\Python310\lib\ssl.py:1130, in SSLSocket.read(self, len, buffer)
   1129 if buffer is not None:
-> 1130     return self._sslobj.read(len, buffer)
   1131 else:

TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

ReadTimeoutError                          Traceback (most recent call last)
File env\lib\site-packages\requests\adapters.py:489, in HTTPAdapter.send(self, request, stream, timeout, verify, cert, proxies)
    488 if not chunked:
--> 489     resp = conn.urlopen(
    490         method=request.method,
    491         url=url,
    492         body=request.body,
    493         headers=request.headers,
    494         redirect=False,
    495         assert_same_host=False,
    496         preload_content=False,
    497         decode_content=False,
    498         retries=self.max_retries,
    499         timeout=timeout,
    500     )
    502 # Send the request.
    503 else:

File env\lib\site-packages\urllib3\connectionpool.py:787, in HTTPConnectionPool.urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    785     e = ProtocolError("Connection aborted.", e)
--> 787 retries = retries.increment(
    788     method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
    789 )
    790 retries.sleep()

File env\lib\site-packages\urllib3\util\retry.py:550, in Retry.increment(self, method, url, response, error, _pool, _stacktrace)
    549 if read is False or not self._is_method_retryable(method):
--> 550     raise six.reraise(type(error), error, _stacktrace)
    551 elif read is not None:

File env\lib\site-packages\urllib3\packages\six.py:770, in reraise(tp, value, tb)
    769         raise value.with_traceback(tb)
--> 770     raise value
    771 finally:

File env\lib\site-packages\urllib3\connectionpool.py:703, in HTTPConnectionPool.urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    702 # Make the request on the httplib connection object.
--> 703 httplib_response = self._make_request(
    704     conn,
    705     method,
    706     url,
    707     timeout=timeout_obj,
    708     body=body,
    709     headers=headers,
    710     chunked=chunked,
    711 )
    713 # If we're going to release the connection in ``finally:``, then
    714 # the response doesn't need to know about the connection. Otherwise
    715 # it will also try to release it and we'll have a double-release
    716 # mess.

File env\lib\site-packages\urllib3\connectionpool.py:451, in HTTPConnectionPool._make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
    450 except (SocketTimeout, BaseSSLError, SocketError) as e:
--> 451     self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
    452     raise

File env\lib\site-packages\urllib3\connectionpool.py:340, in HTTPConnectionPool._raise_timeout(self, err, url, timeout_value)
    339 if isinstance(err, SocketTimeout):
--> 340     raise ReadTimeoutError(
    341         self, url, "Read timed out. (read timeout=%s)" % timeout_value
    342     )
    344 # See the above comment about EAGAIN in Python 3. In Python 2 we have
    345 # to specifically catch it and throw the timeout error

ReadTimeoutError: HTTPSConnectionPool(host='a13a2ade-d842-4c8a.gradio.live', port=443): Read timed out. (read timeout=3)

During handling of the above exception, another exception occurred:

ReadTimeout                               Traceback (most recent call last)
Cell In[1], line 6
      3 with gr.Blocks() as main:
      4     t = gr.Textbox()
----> 6 main.launch(share=True)

File env\lib\site-packages\gradio\blocks.py:1480, in Blocks.launch(self, inline, inbrowser, share, debug, enable_queue, max_threads, auth, auth_message, prevent_thread_lock, show_error, server_name, server_port, show_tips, height, width, encrypt, favicon_path, ssl_keyfile, ssl_certfile, ssl_keyfile_password, quiet, show_api, _frontend)
   1477 from IPython.display import HTML, Javascript, display  # type: ignore
   1479 if self.share and self.share_url:
-> 1480     while not networking.url_ok(self.share_url):
   1481         time.sleep(0.25)
   1482     display(
   1483         HTML(
   1484             f'<div><iframe src="{self.share_url}" width="{self.width}" height="{self.height}" allow="autoplay; camera; microphone; clipboard-read; clipboard-write;" frameborder="0" allowfullscreen></iframe></div>'       
   1485         )
   1486     )

File env\lib\site-packages\gradio\networking.py:179, in url_ok(url)
    177 with warnings.catch_warnings():
    178     warnings.filterwarnings("ignore")
--> 179     r = requests.head(url, timeout=3, verify=False)
    180 if r.status_code in (200, 401, 302):  # 401 or 302 if auth is set
    181     return True

File env\lib\site-packages\requests\api.py:100, in head(url, **kwargs)
     89 r"""Sends a HEAD request.
     90
     91 :param url: URL for the new :class:`Request` object.
   (...)
     96 :rtype: requests.Response
     97 """
     99 kwargs.setdefault("allow_redirects", False)
--> 100 return request("head", url, **kwargs)

File env\lib\site-packages\requests\api.py:59, in request(method, url, **kwargs)
     55 # By using the 'with' statement we are sure the session is closed, thus we
     56 # avoid leaving sockets open which can trigger a ResourceWarning in some
     57 # cases, and look like a memory leak in others.
     58 with sessions.Session() as session:
---> 59     return session.request(method=method, url=url, **kwargs)

File env\lib\site-packages\requests\sessions.py:587, in Session.request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    582 send_kwargs = {
    583     "timeout": timeout,
    584     "allow_redirects": allow_redirects,
    585 }
    586 send_kwargs.update(settings)
--> 587 resp = self.send(prep, **send_kwargs)
    589 return resp

File env\lib\site-packages\requests\sessions.py:701, in Session.send(self, request, **kwargs)
    698 start = preferred_clock()
    700 # Send the request
--> 701 r = adapter.send(request, **kwargs)
    703 # Total elapsed time of the request (approximately)
    704 elapsed = preferred_clock() - start

File env\lib\site-packages\requests\adapters.py:578, in HTTPAdapter.send(self, request, stream, timeout, verify, cert, proxies)
    576     raise SSLError(e, request=request)
    577 elif isinstance(e, ReadTimeoutError):
--> 578     raise ReadTimeout(e, request=request)
    579 elif isinstance(e, _InvalidHeader):
    580     raise InvalidHeader(e, request=request)

ReadTimeout: HTTPSConnectionPool(host='a13a2ade-d842-4c8a.gradio.live', port=443): Read timed out. (read timeout=3)
```

### System Info

```shell
Local: Windows 10, 3.16.2, Firefox

Colab: Linux, 3.16.2, Firefox
```

### Severity

blocking all usage of gradio

**Comment by FunkEngine2023** [comment] 2023-01-27 04:16
Can confirm this issue.  Receiving 504s on gradio.live links, as well as even the favicon.ico.

Would like to add that initially, while the "load" is in progress (before the 504 is recieved.) I get a security warning.  Once the 504 appears however the cert is valid and matches fingerprints from open tabs in expired sessions.
![image](https://user-images.githubusercontent.com/123712145/215008159-dd7dafc1-46a9-46ec-ba6b-c2bbb2a48dde.png)

(There is a 504 timeout behind the cert details here, once it "loads" (fails to load with 504 timeout error)

![image](https://user-images.githubusercontent.com/123712145/215008239-9e08883a-50c3-4400-abb2-ede110dc9f33.png)


Not sure if this has ANYTHING to do with the issue, but it is behavior I had not previously noticed (insecure content warnings.) during use of gradio.live via a colab notebook.

--FunkEngine

**Comment by LuoShaoyin** [comment] 2023-01-27 04:41
Do this occurs. I've found the links unreachable this morning, about 11:30 CST. My firewall is disabled. Downgrading the gradio package won't work.

**Comment by GrennKren** [comment] 2023-01-27 04:43
> Do this occurs. I've found the links unreachable this morning, about 11:30 CST. My firewall is disabled. Downgrading the gradio package won't work.

It work's for me though, downgrading to 3.9

**Comment by abidlabs** [comment] 2023-01-27 05:06
Should be fixed now, thanks for reporting. It looks like the share servers were down due to a traffic spike that we're investigating the cause of.

**Comment by abidlabs** [comment] 2023-01-27 05:07
@cadaeix out of curiosity why do you say that "this makes Gradio unusable on Colab notebooks"? Did running with `share=False` not work for you in Colab?

**Comment by cadaeix** [comment] 2023-01-27 05:14
@abidlabs thank you! Also weird - in the past, when I used to use Automatic1111's webui in [this Colab notebook](https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb#scrollTo=CFWtw-6EPrKi), I could never get the local version working and always had to use the share option, so I assumed that Colab notebooks had to have `share=True` - but it does appear that setting` share=False` in a test notebook does work. I don't use that notebook anymore, but I may do more testing with the notebooks I do use and if it continues to be a problem, I'll make another issue, thanks!

**Comment by abidlabs** [comment] 2023-01-27 05:15
Good to know @cadaeix, please do create an issue and we'll look into it!

**Closed by abidlabs** 2023-01-27 05:15 UTC
Labels: bug
