### ISSUE TITLE
graido File component fails to filter text files

### ISSUE THREAD

**Issue by Solomin0** [gradio-app/gradio#7785] opened 2024-03-21 18:04 UTC
### Describe the bug

The "text" file type does not properly filter the file dialogue pop-up. Allowing users to select any type of file. 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

with gr.Blocks() as demo:
    a = gr.File(label = "pdf only", file_types= [".pdf"])
    b = gr.File(label = "all text", file_types= ["text"])
    c = gr.File(label = "all images", file_types= ["image"])

demo.launch()
```

### Screenshot

component a
![image](https://github.com/gradio-app/gradio/assets/37559666/a6c37b4f-9e96-4f03-9e70-fa32c9fed880)

component b
![image](https://github.com/gradio-app/gradio/assets/37559666/22b5f19a-3cd5-4265-b28b-0555d244a98c)

component c
![image](https://github.com/gradio-app/gradio/assets/37559666/12cf3431-d37f-4938-bef3-d64addbe1949)

### System Info

```shell
Operating System: Windows
gradio version: 4.20.1
gradio_client version: 0.11.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.2.0
fastapi: 0.109.2
ffmpy: 0.3.2
gradio-client==0.11.0 is not installed.
httpx: 0.26.0
huggingface-hub: 0.20.3
importlib-resources: 6.1.1
jinja2: 3.1.3
markupsafe: 2.1.5
matplotlib: 3.8.3
numpy: 1.26.4
orjson: 3.9.14
packaging: 23.2
pandas: 2.2.0
pillow: 10.2.0
pydantic: 2.6.1
pydub: 0.25.1
python-multipart: 0.0.9
pyyaml: 6.0.1
ruff: 0.3.0
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.9.0
uvicorn: 0.27.1
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2024.2.0
httpx: 0.26.0
huggingface-hub: 0.20.3
packaging: 23.2
typing-extensions: 4.9.0
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment] 2024-03-21 19:04
cc @dawoodkhan82

**Comment by tabishqidwai98** [comment] 2024-04-27 11:34
is the bug still open? @abidlabs @Solomin0

**Comment by freddyaboulton** [comment] 2024-04-29 15:26
I believe so. Please feel free to open a PR for this fix and we will review promptly!

**Comment by tabishqidwai98** [comment] 2024-05-02 00:57
I'm not able to reproduce the bug. I would like to work on #8192 . I have reproduced that one. @abidlabs @Solomin0 @freddyaboulton

**Comment by abidlabs** [comment] 2024-05-02 01:22
I cannot reproduce this either, it looks like this must have been fixed -- specifying "text" does indeed filter down to the "text/plain" mime type. Closing!

**Closed by abidlabs** 2024-05-02 01:22 UTC
Labels: bug
