### ISSUE TITLE
Chatbot css height of inner chat pane does not work. 

### ISSUE THREAD

**Issue by ffahmed** [gradio-app/gradio#3356] opened 2023-03-02 06:50 UTC
Hi there, 

I tried to apply height in Chatbot like following. Although I was able to change the height, but the inner pane (where the text and image comes in) still has default height and appears with scroller. How do I make the inner pane bigger. Check the image attached. I want to make the inner pane bigger so I can view the image and the text together. How do I do it.

Current code
with gr.Blocks(css="#chatbot {height:600px}") as demo:
    chatbot = gr.Chatbot(elem_id="chatbot")

Resulting Chatbot:
![image](https://user-images.githubusercontent.com/16159711/222352403-eb1702f4-d821-4260-bea2-2b9a82689465.png)

**Comment by abidlabs** [comment] 2023-03-02 10:45
Looks like a duplicate of #3357 and also by the way, for general questions like this (that are not feature requests or bug reports), please ask in [GitHub Discussions](https://github.com/gradio-app/gradio/discussions) or [our Discord](http://discord.gg/feTf9x3ZSB). (I'll close this issue)

**Closed by abidlabs** 2023-03-02 10:45 UTC
