### ISSUE TITLE
Remove loading indicator when using gr.Image streaming mode

### ISSUE THREAD

**Issue by nateraw** [gradio-app/gradio#1494] opened 2022-06-08 18:05 UTC
**Is your feature request related to a problem? Please describe.**  

As mentioned in #1490 , the loading indicator gets in the way when you run the following:

```
import gradio as gr

gr.Interface(lambda x: x, gr.Image(source='webcam', streaming=True), "image", live=True).launch()
```

**Describe the solution you'd like**  

Maybe we just show each individual output image as they come in. 

**Additional context**  

Removing this loading indicator could get tricky though, especially if folks use really hefty models. They might be confused as to why its taking so long

**Comment by nateraw** [comment] 2022-06-15 00:49
Hey there @aliabd I just pip installed from source and built the frontend - this issue still exists there. Should we reopen this, or might I have done something wrong?

**Comment by abidlabs** [comment] 2022-06-15 00:53
Same for me, reopening the issue!

<img width="962" alt="image" src="https://user-images.githubusercontent.com/1778297/173713477-a61fefc8-b700-4ca2-bcc2-e7f7bc5f8ff2.png">

**Comment by abidlabs** [comment] 2022-07-19 18:39
Hi @nateraw, this should be fixed now! Thanks for bringing this to our attention, and we'll be releasing 3.1 soon :)

**Comment by nateraw** [comment] 2022-07-19 18:46
Just gave it a go - works for me as well! Looking forward to the release so I can put together a demo with it :)

**Comment by hsonthach** [comment] 2023-07-07 07:28
Hello there! It appears that the issue has resurfaced in the latest version (3.36.0). I recently tested the streaming feature, but unfortunately, I had to revert back to version 3.32.0 in order to resolve i

**Comment by abidlabs** [comment] 2023-07-07 14:03
Thanks @hsonthach I can confirm the issue, reopening

**Comment by abidlabs** [comment] 2023-09-29 17:43
We should fix this, its pretty annoying

**Comment by Yash-Divekar** [comment] 2023-10-01 12:17
Hey @abidlabs , I am new to Open source and I loved this repository. Upon reading some code I have an assumption ( Might be a wrong assumption) that this issue might be occurring due to ' encode_plot_to_base64 ' in ' processing_utils.py ' . I am not really that knowledgeable but I feel saving every frame in a video will create a lag for video. Can we just skip this saving for videos in some way to reduce this lag.

![Screenshot 2023-10-01 173638](https://github.com/gradio-app/gradio/assets/133482969/43e13ada-9669-4dd0-a191-6b73660e8cb9)

**Comment by abidlabs** [comment] 2023-11-17 00:39
Also there's an issue with the upload progress bar showing up again and again, see `stream_frames` demo:

<img width="732" alt="image" src="https://github.com/gradio-app/gradio/assets/1778297/0097475f-3564-4d15-9b9a-dba448413520">

**Closed** 2023-12-13 00:01 UTC
Labels: bug, good first issue, svelte
