### ISSUE TITLE
ImportError: cannot import name 'MultiHostDsn' from 'pydantic.networks' #6578

### ISSUE THREAD

**Issue by KyriakiGeorgiou** [gradio-app/gradio#4912] opened 2023-07-13 08:40 UTC
### Describe the bug

I am using gradio to dispaly my NLP model. On Friday 7/7 it was working perfectly, but after the new release (gradio v3.36.1 and pydantic v2.02 or any other I use) whenever I run any code with the gradio import I get the following error: "[/usr/local/lib/python3.10/dist-packages/fastapi/_compat.py](https://localhost:8080/#) in
295 UndefinedType as UndefinedType, # noqa: F401
296 )
--> 297 from pydantic.networks import ( # type: ignore[no-redef]
298 MultiHostDsn as MultiHostUrl, # noqa: F401
299 )

ImportError: cannot import name 'MultiHostDsn' from 'pydantic.networks' (/usr/local/lib/python3.10/dist-packages/pydantic/networks.cpython-310-x86_64-linux-gnu.so)". Even when I run the code with a simple example like the following and no extra imports I still get the same error.

I have also reported the bug to the pydantic community, but they suggested reporting it here as [Gradio v3.36.1] should have Pydantic V2 supported. 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

import pydantic
import gradio as gr
def sketch_recognition(img):
    pass# Implement your sketch recognition model here...

gr.Interface(fn=sketch_recognition, inputs="sketchpad", outputs="label").launch()

### System Info

```shell
Name: gradio
Version: 3.36.1
Summary: Python library for easily interacting with trained machine learning models
Home-page: 
Author: 
Author-email: Abubakar Abid <team@gradio.app>, Ali Abid <team@gradio.app>, Ali Abdalla <team@gradio.app>, Dawood Khan <team@gradio.app>, Ahsen Khaliq <team@gradio.app>, Pete Allen <team@gradio.app>, Ömer Faruk Özdemir <team@gradio.app>
License: 
Location: /usr/local/lib/python3.10/dist-packages
Requires: aiofiles, aiohttp, altair, fastapi, ffmpy, gradio-client, httpx, huggingface-hub, jinja2, markdown-it-py, markupsafe, matplotlib, mdit-py-plugins, numpy, orjson, pandas, pillow, pydantic, pydub, pygments, python-multipart, pyyaml, requests, semantic-version, uvicorn, websockets
Required-by:
```

### Severity

Blocking usage of gradio

**Comment by KyriakiGeorgiou** [comment] 2023-07-13 14:33
I use exactly the same versions as you in Google Colab. I am still getting this.

<img width="645" alt="Screenshot 2023-07-13 at 5 32 51 PM" src="https://github.com/gradio-app/gradio/assets/81424413/df0bade9-9964-4643-9d0b-d70a4842fce4">

**Comment by freddyaboulton** [comment] 2023-07-13 18:05
I'm sorry @KyriakiGeorgiou but I cannot reproduce on colab: https://colab.research.google.com/drive/1PJXsWO2DHHsx-QdKj8ZcjkGesvkwMGvM?usp=sharing

**Comment by jordan-carson** [comment] 2023-07-14 17:51
I just received this error and google sent me here. For me I was using the latest version of FastAPI 0.100.0, downgrading to a previous version gave me another error. Seems like I was trying to set a APIRouter prefix ending with a "/". Fixing this resolved the issue and was able to run to start the server as normal.


```
poetry run uvicorn app.main:app --host 0.0.0.0 --port 5000 --log-config ./app/log.ini --reload
```

Hope this helps others.

**Comment by freddyaboulton** [comment] 2023-07-14 18:08
What version of pydantic are you using @jordan-carson ?

**Comment by freddyaboulton** [comment] 2023-07-14 18:22
Ok @KyriakiGeorgiou I found the issue - `MultiHostDsn` was introduced in this pydantic PR (https://github.com/pydantic/pydantic/pull/3349/files#diff-193ce4f5c16e16d8094f61f328a9b9d3d73635ee7b4d67e4f140bbbfcc6d553e) and was released in version 1.10.0 (https://docs.pydantic.dev/latest/changelog/#v1100-2022-08-30)

so if you have a version of pydantic before 1.10.0, you will get that error.

I was finally able to reproduce by using a previous version of pydantic (1.9.0). 

```bash
ImportError: cannot import name 'MultiHostDsn' from 'pydantic.networks' (/Users/freddy/miniconda3/envs/gradio/lib/python3.8/site-packages/pydantic/networks.cpython-38-darwin.so)
(gradio)
```

The safest is to `pip install --upgrade pydantic==1.*` or to update gradio to be version 3.36.1 and use pydantic > 2.

I think this is a fastapi bug since they're the ones importing this class, so will close this and file an issue there.

**Closed by freddyaboulton** 2023-07-14 18:22 UTC
Labels: bug, needs repro

**Comment by freddyaboulton** [comment] 2023-07-14 18:36
FastAPI has a PR for this here: https://github.com/tiangolo/fastapi/pull/9852

**Comment by jordan-carson** [comment] 2023-07-14 18:37
> What version of pydantic are you using @jordan-carson ?
> 
> EDIT: Are you launching a gradio demo?

No I am not using gradio, but this error was raised regardless. 
See below from my poetry.toml
```toml
[[package]]
name = "pydantic"
version = "1.7.4"
description = "Data validation and settings management using python 3.6 type hinting"
optional = false
python-versions = ">=3.6"
```

**Comment by jordan-carson** [comment] 2023-07-14 18:38
> FastAPI has a PR for this here: [tiangolo/fastapi#9852](https://github.com/tiangolo/fastapi/pull/9852)

Good find. I will roll over once this has been closed and merged. Thanks @freddyaboulton

**Comment by mrBlackHat777** [comment] 2023-07-17 22:00
I had the same error on a personal project. I had FastAPI and Pydantic in my requirements.txt file. I removed Pydantic from the requirements, and the error disappeared. Now, I am using `pydantic==1.10.11` and `pydantic_core==2.3.0`

**Comment by KyriakiGeorgiou** [comment] 2023-07-18 09:29
This doesn't seem to solve the problem. I tried both gradio 3.36.1 and pydantic 2.0.3 and later pip install --upgrade pydantic==1.* but still the same error appears.
