### ISSUE TITLE
when The computer has no network,gradio does not work properly?

### ISSUE THREAD

**Issue by zhanghongyong123456** [gradio-app/gradio#2708] opened 2022-11-23 02:42 UTC
### Describe the bug

Hi, can gradio be implemented on computers without Internet connection? What should I do if I disconnect the Internet and the message indicating that the link has failed

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

![image](https://user-images.githubusercontent.com/48466610/203459420-9eff4c10-1728-4642-ad2e-7776a5ed14b6.png)
![image](https://user-images.githubusercontent.com/48466610/203459559-092e54f7-aba4-4709-a2a7-e7b90b173938.png)

### Logs

```shell
![image](https://user-images.githubusercontent.com/48466610/203459420-9eff4c10-1728-4642-ad2e-7776a5ed14b6.png)
```

### System Info

```shell
gradio 3.6
```

### Severity

blocking all usage of gradio

**Comment by abidlabs** [comment] 2022-11-23 03:23
Hi @zhanghongyong123456, you're right currently `gradio` doesn't work without an internet connection We're working on hosting all the assets locally so that this won't be a problem in the near future.

Closing this issue as it is a duplicate of #1450.

**Closed by abidlabs** 2022-11-23 03:23 UTC
Labels: bug
