### ISSUE TITLE
Textbox corners not rounded

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#2997] opened 2023-01-17 10:11 UTC
### Describe the bug

If you run any demo, you'll notice that the textbox corners are no longer rounded which looks off

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Run `fake_diffusion` or `english_translator` demo with 3.16.2

### fake_diffusion
<img width="614" alt="image" src="https://user-images.githubusercontent.com/41651716/212870451-843b0f0a-fcf9-4a6b-bc7b-57dfb47e2c11.png">

### generate_english_german
<img width="637" alt="image" src="https://user-images.githubusercontent.com/41651716/212870533-90b9b24d-f3ad-47ff-b0e7-a7bda3bc56e0.png">

### Logs

```shell
-
```

### System Info

```shell
3.16.2
```

### Severity

annoying

**Comment by aliabid94** [comment] 2023-01-17 21:30
Confused - they look rounded in your screenshot? And when I run locally

**Comment by dawoodkhan82** [comment] 2023-01-17 21:31
weird, I can't reproduce this. Can someone else check? @aliabid94 @abidlabs

**Comment by dawoodkhan82** [comment] 2023-01-17 21:32
Well, I see the issue in the screenshot. But not when I run it locally

**Comment by dawoodkhan82** [comment] 2023-01-17 21:32
@aliabid94 see the corner? 
<img width="65" alt="Screenshot 2023-01-17 at 4 32 37 PM" src="https://user-images.githubusercontent.com/12725292/213016770-cea6771f-c8f2-4cf2-9df9-c4bb275fe01b.png">

**Comment by aliabid94** [comment] 2023-01-17 21:33
ohh yeah I see it

**Comment by aliabid94** [comment] 2023-01-17 21:34
looks like its been fixed in main by @pngwn's theme work

**Comment by dawoodkhan82** [comment] 2023-01-17 21:36
@pngwn is squashing bugs even when he's not here

**Closed** 2023-01-17 21:37 UTC
Labels: bug
