### ISSUE TITLE
Issue on inputs.Slider default value is on the wrong place

### ISSUE THREAD

**Issue by apolinario** [gradio-app/gradio#940] opened 2022-04-06 20:56 UTC
### Describe the bug

When I add the following inputs.Slider `gr.inputs.Slider(label="Width", minimum=64, maximum=256, default=256, step=64)`

The default value is on the wrong place

### Reproduction

```
import gradio as gr

def run(number):
    return "Number: "+str(number)

iface = gr.Interface(fn=run, inputs=gr.inputs.Slider(label="Width", minimum=64, maximum=256, default=256, step=64), outputs="text")
iface.launch()

```
### Screenshot
It should be at the end of the slider as it is the last item
![image](https://user-images.githubusercontent.com/788417/162068250-99cd27f3-6ed2-4787-8f4c-27d2c263a9b1.png)

### System Info

```shell
Gradio==2.8.6 
Linux
All browsers
```
Edit: updated to the latest version and issue remains

### Severity

critical

**Comment by apolinario** [comment] 2022-04-06 21:07
Additional information: 
- Removing the steps parameter doesn't solve it
- Removing the minimum parameter doesn't solve it 
- Removing both the minimum and the step parameter doesn't solve it

It seems the issue is boils don't to default value being equal to maximum 
`gr.inputs.Slider(label="Width",  maximum=256, default=256)`

**Comment by FarukOzderim** [comment] 2022-04-08 02:21
Thanks for reporting it @apolinario, @aliabid94 @pngwn @dawoodkhan82 can one of you take it on? it seems like a small ui issue.

**Comment by pngwn** [comment] 2022-04-08 10:40
Pretty sure this is fixed in`dev-blocks`, not sure it is worth fixing in main as `dev-blocks` is close to being merged.

**Comment by FarukOzderim** [comment] 2022-04-08 11:47
@apolinario thanks for reporting, the problem is already solved, it will be in the next release.

**Closed by FarukOzderim** 2022-04-08 11:47 UTC
Labels: bug
