### ISSUE TITLE
Big video files are not supported

### ISSUE THREAD

**Issue by thermelin** [gradio-app/gradio#2297] opened 2022-09-20 06:38 UTC
### Describe the bug

I want to use Gradio for demoing a model that processes videos. The problem is that when I upload videos that pass a certain size (seems to be around 500MB) I get an error without having the function that is specified in the interface even triggered. Error doesn't indicate size issue, but experiments with multiple videos confirms this is the issue.

Additional notes:
* As you can see in the screenshot, an error is thrown, but the program does not stop. I couldn't find a solution for this to return an error for the people who will use this demo. This means that people that will get the public link would just wait without having any feedback that something went wrong.
* It seems that via the public link the size threshold gets worst, and it does not return for files around 200MB (but couldn't confirm it's the same issue, as I don't see any error messages, per point above)
* This also happens when using the gr.FIle component (and not gr.Video), so support of large files in general seems to not be supported.
* This is a great project! Hope this issue will resolve and I can use it!

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

For simplicity, the code below also reproduces the issue. "process_video(video_path)" can do whatever, it's not getting triggered anyway.
Just upload a video that is more than 500MB.

import gradio as gr
import os
from demo_insights import *

test = gr.Interface(fn=process_video, 
                    inputs="video",
                    outputs="file")

test.launch(share=False)

### Screenshot

![image](https://user-images.githubusercontent.com/108273730/191184117-a3e34c0d-25c2-4978-ba13-f03dd3278fd9.png)

### Logs

```shell
Traceback (most recent call last):
  File "C:\Anaconda3\envs\vision\lib\site-packages\gradio\routes.py", line 284, in predict
    fn_index, raw_input, username, session_state
  File "C:\Anaconda3\envs\vision\lib\site-packages\gradio\blocks.py", line 514, in process_api
    processed_input = self.preprocess_data(fn_index, raw_input, state)
  File "C:\Anaconda3\envs\vision\lib\site-packages\gradio\blocks.py", line 419, in preprocess_data
    processed_input.append(block.preprocess(raw_input[i]))
  File "C:\Anaconda3\envs\vision\lib\site-packages\gradio\components.py", line 1667, in preprocess
    file_data, file_path=file_name
  File "C:\Anaconda3\envs\vision\lib\site-packages\gradio\processing_utils.py", line 201, in decode_base64_to_file
    data, extension = decode_base64_to_binary(encoding)
  File "C:\Anaconda3\envs\vision\lib\site-packages\gradio\processing_utils.py", line 195, in decode_base64_to_binary
    extension = get_extension(encoding)
  File "C:\Anaconda3\envs\vision\lib\site-packages\gradio\processing_utils.py", line 49, in get_extension
    extension = mimetypes.guess_extension(type)
  File "C:\Anaconda3\envs\vision\lib\mimetypes.py", line 326, in guess_extension
    return _db.guess_extension(type, strict)
  File "C:\Anaconda3\envs\vision\lib\mimetypes.py", line 192, in guess_extension
    extensions = self.guess_all_extensions(type, strict)
  File "C:\Anaconda3\envs\vision\lib\mimetypes.py", line 171, in guess_all_extensions
    type = type.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
```

### System Info

```shell
'3.0.11', Windows, Edge
```

### Severity

blocking all usage of gradio

**Comment by abidlabs** [comment] 2022-09-22 04:12
Hi @thermelin, I can confirm that the threshold for public links should be around 200 MB and that's set so that the gradio share servers are not overwhelmed. 

Not sure where the size limits for private links is coming from -- will take a look.

**Comment by thermelin** [comment] 2022-09-22 06:01
Thanks! A solution for private links is sufficient.

Additionally (another unrelated issue), it would be great to understand how we can stop the run in case there is a Gradio error (not an error in my code) and present an error message to the user (rather than having it look like it's still running). It seems like the exception is not populating beyond the scope of Gradio.
Thanks again!

**Comment by abidlabs** [comment] 2022-09-22 06:08
> Additionally (another unrelated issue), it would be great to understand how we can stop the run in case there is a Gradio error (not an error in my code) and present an error message to the user (rather than having it look like it's still running). It seems like the exception is not populating beyond the scope of Gradio.

Have you tried the `show_error` parameter in `launch()`?

**Comment by thermelin** [comment] 2022-09-22 08:49
I tried launching like this, and it didn't change the behavior. 
If you prefer that I'll open a separate issue for this, let me know.
Thanks again for a great project! 
![image](https://user-images.githubusercontent.com/108273730/191702016-a5678d42-fdab-4b37-a513-d8d184c586f7.png)

**Comment by abidlabs** [comment] 2022-09-22 08:51
Yes that would be great @thermelin if you can create a separate issue with a full code example that we can use to reproduce

**Comment by thermelin** [comment] 2022-09-28 06:39
Hi,
Updating that upgrading to Gradio 3.4 did not solve the issue.
Thanks!

**Comment by abidlabs** [comment] 2022-12-22 21:32
Duplicate of #2421. Let me close this one and we'll continue the discussion over there

**Closed by abidlabs** 2022-12-22 21:32 UTC
Labels: bug
