### ISSUE TITLE
Video mirroring

### ISSUE THREAD

**Issue by Zengyf-CVer** [gradio-app/gradio#1804] opened 2022-07-16 06:59 UTC
### Describe the bug

Upload a video, and the output video is a mirror image.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```python
import gradio as gr

def video_test(video):
    return video

inputs_video_p5 = gr.Video(format="mp4", source="upload", label="原始视频")  # webcam
outputs_webcam_p5 = gr.Video(format='mp4', label="检测视频")

gyd = gr.Interface(
    fn=video_test,
    inputs=[inputs_video_p5],
    outputs=[outputs_webcam_p5],
)
gyd.launch(
    inbrowser=True,
)
```

### Screenshot

![ksnip_20220716-145557](https://user-images.githubusercontent.com/41098760/179344052-89c2c5be-2256-4ad1-aeef-125d42b1455e.png)

### Logs

```shell
see image above
```

### System Info

```shell
gradio 3.0.25
ubuntu 20.04
chrome
```

### Severity

annoying

**Comment by abidlabs** [comment] 2022-07-16 12:21
Hi @Zengyf-CVer yes this is the default behavior of the webcam component, but can be changed by setting `mirror_webcam=False` in the `Video()`  constructor

**Comment by abidlabs** [comment] 2022-10-06 18:52
Thanks @mistycheney, that seems like reasonable default behavior to me, what do you think @pngwn?

**Comment by pngwn** [comment] 2022-10-07 14:20
Yeah, that really should be the default, i kinda thought it was. Current behaviour feels like a bug.

**Comment by pngwn** [comment] 2022-10-11 12:45
I can't reproduce this on `main` with the example code. I can also confirm that only webcam videos are mirrored nothing else.

https://user-images.githubusercontent.com/12937446/195094030-32702d67-2459-4a7b-bc63-3639c86c201f.mov

We have had multiple reports of this now though, so I'm not sure is happening.

**Comment by abidlabs** [comment] 2022-10-15 03:02
For what its worth, I do get the flipping behavior running on Windows with ffmpeg version 4.4

<img width="961" alt="image" src="https://user-images.githubusercontent.com/1778297/195966062-9dc8e144-2ccb-4ffd-80a9-e14d8010397b.png">

**Comment by pngwn** [comment] 2022-10-17 13:43
If someone who can reproduce this can pick it up, that would be good. I'm not seeing this behaviour. Not sure why.

The problem will be in the backend (in the pre/postprocessor) if it exists.

**Comment by freddyaboulton** [comment] 2022-10-17 15:55
I think I know what's happening. Will put up a PR today and tag you @pngwn !

**Comment by abidlabs** [comment] 2022-10-17 16:59
How do you debug these mysterious issues @freddyaboulton  👀

**Closed** 2022-10-18 15:07 UTC
Labels: bug, pending clarification
