### ISSUE TITLE
gr.Audio()  Doesn't ask for browser audio permissions.

### ISSUE THREAD

**Issue by medram** [gradio-app/gradio#4318] opened 2023-05-22 21:57 UTC
### Describe the bug

gr.Audio() seems to be not working on the Andriod Firefox browser, it can't ask for audio permissions.
but, it's working fine on my PC browser (chrome and Firefox).

Note: My Firefox has the Android microphone permission enabled and the browser set audio to "Ask to Enable"

It could be caused by the incompatibility of the javascript browser API for asking for audio permission.
Please fix this bug.

Thanks.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Here is just the audio field:
```python
audio = gr.Audio(source="microphone", show_label=False, type="filepath", format="mp3").style(container=False) 
```

### Logs

```shell
No logs
```

### System Info

```shell
my device info:
Android version: 12
Browser: Firefox
Note: My Firefox has the Android microphone permission enabled and the browser set audio to "Ask to Enable"
```

### Severity

serious, but I can work around it

**Comment by abidlabs** [comment] 2023-05-23 20:59
Might be related to #2551 

@aliabid94 could you knock both of these out while you're working on the Audio stuff?

**Comment by abidlabs** [comment] 2023-08-09 20:47
Closing for lack of followup -- @medram let us know if you are still facing this issue and how we could reproduce it

**Closed by abidlabs** 2023-08-09 20:47 UTC
Labels: bug, frontend, pending clarification

**Comment by thiswillbeyourgithub** [comment] 2024-08-05 09:20
For anyone else wondering, this might be because chrome, brave, firefox etc, including on android, treat the lack of SSL (HTTPS) as insecure, even if the url is pointing at a local adress. And exceptions can usually only be added to localhost. But for gradio and other services of this kind the usual setup is people run gradio on a computer and try to reach it from their wifi.

Luckily, there's a hidden way to add exceptions to URLs, I documented how to proceed [in this discussion of openwebui](https://github.com/open-webui/open-webui/discussions/4352):

> Hello,
> 
> I've read everywhere in the documentation, discussions, and other GitHub issues that it was impossible to make Voice Recognition, STT, or Speech Recognition work without enabling HTTPS, because modern browsers prevent it. However, Chrome, Brave, Chromium, etc. all allow adding a specific domain to the exceptions, even though this feature is quite hidden and it's widely reported as impossible. It even works on mobile.
> 
> To do this, follow the instructions at this address: https://medium.com/@Carmichaelize/enabling-the-microphone-camera-in-chrome-for-local-unsecure-origins-9c90c3149339
> 
> Basically:
> 
>     1. Open chrome://flags/#unsafely-treat-insecure-origin-as-secure
> 
>     2. Add your local ip there: `192.168.1.39:3000` for example
> 
>     3. Restart the browser
> 
> 
> Of course it's a security tradeoff, but in my case I'm using a VPN to reach this server so it makes sense.
> 
> Ping #1148 #3765 #4020
> 
> I think this should be added in the FAQ, let the user decide the tradeoff it wants!
> 
> Have a great day everyone, goodbye.
