### ISSUE TITLE
get an error when the publish url is generated

### ISSUE THREAD

**Issue by FoolMasque** [gradio-app/gradio#2972] opened 2023-01-12 02:27 UTC
### Describe the bug

I run the simple  code in the online version of jupyter lab,but an error is reported when a public link is generated.
How am I supposed to fix this?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction
```shell
import gradio as gr

def image_classifier(inp):
    return {'cat': 0.3, 'dog': 0.7}

demo = gr.Interface(fn=image_classifier, inputs="image", outputs="label")
demo.launch(share=True)
```

### Logs

```shell
IMPORTANT: You are using gradio version 3.11.0, however version 3.14.0 is available, please upgrade.
--------
Running on local URL:  http://127.0.0.1:7860/
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

*** Failed to connect to ec2.gradio.app:22: [Errno 110] Connection timed out
Traceback (most recent call last):
  File "/home/ma-user/anaconda3/envs/PyTorch-1.8/lib/python3.7/site-packages/gradio/tunneling.py", line 78, in create_tunnel
    pkey=paramiko.RSAKey.from_private_key(StringIO(payload["key"])),
  File "/home/ma-user/anaconda3/envs/PyTorch-1.8/lib/python3.7/site-packages/paramiko/client.py", line 358, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "/home/ma-user/anaconda3/envs/PyTorch-1.8/lib/python3.7/site-packages/paramiko/util.py", line 279, in retry_on_signal
    return function()
  File "/home/ma-user/anaconda3/envs/PyTorch-1.8/lib/python3.7/site-packages/paramiko/client.py", line 358, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ma-user/anaconda3/envs/PyTorch-1.8/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_3550/15547866.py", line 7, in <module>
    demo.launch(share=True)
  File "/home/ma-user/anaconda3/envs/PyTorch-1.8/lib/python3.7/site-packages/gradio/blocks.py", line 1395, in launch
    share_url = networking.setup_tunnel(self.server_port, None)
  File "/home/ma-user/anaconda3/envs/PyTorch-1.8/lib/python3.7/site-packages/gradio/networking.py", line 167, in setup_tunnel
    return create_tunnel(payload, LOCALHOST_NAME, local_server_port)
  File "/home/ma-user/anaconda3/envs/PyTorch-1.8/lib/python3.7/site-packages/gradio/tunneling.py", line 82, in create_tunnel
    sys.exit(1)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ma-user/anaconda3/envs/PyTorch-1.8/lib/python3.7/site-packages/IPython/core/ultratb.py", line 1101, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/home/ma-user/anaconda3/envs/PyTorch-1.8/lib/python3.7/site-packages/IPython/core/ultratb.py", line 248, in wrapped
    return f(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/PyTorch-1.8/lib/python3.7/site-packages/IPython/core/ultratb.py", line 281, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/home/ma-user/anaconda3/envs/PyTorch-1.8/lib/python3.7/inspect.py", line 1502, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
AttributeError: 'tuple' object has no attribute 'tb_frame'
---------------------------------------------------------------------------
TimeoutError                              Traceback (most recent call last)
~/anaconda3/envs/PyTorch-1.8/lib/python3.7/site-packages/gradio/tunneling.py in create_tunnel(payload, local_server, local_server_port)
     77                 username=payload["user"],
---> 78                 pkey=paramiko.RSAKey.from_private_key(StringIO(payload["key"])),
     79             )

~/anaconda3/envs/PyTorch-1.8/lib/python3.7/site-packages/paramiko/client.py in connect(self, hostname, port, username, password, pkey, key_filename, timeout, allow_agent, look_for_keys, compress, sock, gss_auth, gss_kex, gss_deleg_creds, gss_host, banner_timeout, auth_timeout, gss_trust_dns, passphrase, disabled_algorithms, transport_factory)
    357                             pass
--> 358                     retry_on_signal(lambda: sock.connect(addr))
    359                     # Break out of the loop on success

~/anaconda3/envs/PyTorch-1.8/lib/python3.7/site-packages/paramiko/util.py in retry_on_signal(function)
    278         try:
--> 279             return function()
    280         except EnvironmentError as e:

~/anaconda3/envs/PyTorch-1.8/lib/python3.7/site-packages/paramiko/client.py in <lambda>()
    357                             pass
--> 358                     retry_on_signal(lambda: sock.connect(addr))
    359                     # Break out of the loop on success

TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

SystemExit                                Traceback (most recent call last)
    [... skipping hidden 1 frame]

/tmp/ipykernel_3550/15547866.py in <module>
      6 demo = gr.Interface(fn=image_classifier, inputs="image", outputs="label")
----> 7 demo.launch(share=True)

~/anaconda3/envs/PyTorch-1.8/lib/python3.7/site-packages/gradio/blocks.py in launch(self, inline, inbrowser, share, debug, enable_queue, max_threads, auth, auth_message, prevent_thread_lock, show_error, server_name, server_port, show_tips, height, width, encrypt, favicon_path, ssl_keyfile, ssl_certfile, ssl_keyfile_password, quiet, show_api, _frontend)
   1394                 if self.share_url is None:
-> 1395                     share_url = networking.setup_tunnel(self.server_port, None)
   1396                     self.share_url = share_url

~/anaconda3/envs/PyTorch-1.8/lib/python3.7/site-packages/gradio/networking.py in setup_tunnel(local_server_port, endpoint)
    166             payload = response.json()[0]
--> 167             return create_tunnel(payload, LOCALHOST_NAME, local_server_port)
    168         except Exception as e:

~/anaconda3/envs/PyTorch-1.8/lib/python3.7/site-packages/gradio/tunneling.py in create_tunnel(payload, local_server, local_server_port)
     81         print(f'*** Failed to connect to {payload["host"]}:{payload["port"]}: {e}')
---> 82         sys.exit(1)
     83 

SystemExit: 1

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
    [... skipping hidden 1 frame]

~/anaconda3/envs/PyTorch-1.8/lib/python3.7/site-packages/IPython/core/interactiveshell.py in showtraceback(self, exc_tuple, filename, tb_offset, exception_only, running_compiled_code)
   2091                            'the full traceback.\n']
   2092                     stb.extend(self.InteractiveTB.get_exception_only(etype,
-> 2093                                                                      value))
   2094                 else:
   2095                     try:

~/anaconda3/envs/PyTorch-1.8/lib/python3.7/site-packages/IPython/core/ultratb.py in get_exception_only(self, etype, value)
    752         value : exception value
    753         """
--> 754         return ListTB.structured_traceback(self, etype, value)
    755 
    756     def show_exception_only(self, etype, evalue):

~/anaconda3/envs/PyTorch-1.8/lib/python3.7/site-packages/IPython/core/ultratb.py in structured_traceback(self, etype, evalue, etb, tb_offset, context)
    631                     chained_exceptions_tb_offset, context)
    632                 + chained_exception_message
--> 633                 + out_list)
    634 
    635         return out_list

~/anaconda3/envs/PyTorch-1.8/lib/python3.7/site-packages/IPython/core/ultratb.py in structured_traceback(self, etype, value, tb, tb_offset, number_of_lines_of_context)
   1366             self.tb = tb
   1367         return FormattedTB.structured_traceback(
-> 1368             self, etype, value, tb, tb_offset, number_of_lines_of_context)
   1369 
   1370 

~/anaconda3/envs/PyTorch-1.8/lib/python3.7/site-packages/IPython/core/ultratb.py in structured_traceback(self, etype, value, tb, tb_offset, number_of_lines_of_context)
   1266             # Verbose modes need a full traceback
   1267             return VerboseTB.structured_traceback(
-> 1268                 self, etype, value, tb, tb_offset, number_of_lines_of_context
   1269             )
   1270         elif mode == 'Minimal':

~/anaconda3/envs/PyTorch-1.8/lib/python3.7/site-packages/IPython/core/ultratb.py in structured_traceback(self, etype, evalue, etb, tb_offset, number_of_lines_of_context)
   1123 
   1124         formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
-> 1125                                                                tb_offset)
   1126 
   1127         colors = self.Colors  # just a shorthand + quicker name lookup

~/anaconda3/envs/PyTorch-1.8/lib/python3.7/site-packages/IPython/core/ultratb.py in format_exception_as_a_whole(self, etype, evalue, etb, number_of_lines_of_context, tb_offset)
   1080 
   1081 
-> 1082         last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)
   1083 
   1084         frames = self.format_records(records, last_unique, recursion_repeat)

~/anaconda3/envs/PyTorch-1.8/lib/python3.7/site-packages/IPython/core/ultratb.py in find_recursion(etype, value, records)
    380     # first frame (from in to out) that looks different.
    381     if not is_recursion_error(etype, value, records):
--> 382         return len(records), 0
    383 
    384     # Select filename, lineno, func_name to track frames with

TypeError: object of type 'NoneType' has no len()
```

### System Info

```shell
gradio-3.11.0
Ubuntu 18.04.6 LTS, CUDA-10.2
chrome
```

### Severity

serious, but I can work around it

**Comment by freddyaboulton** [comment] 2023-01-13 13:25
Hi @FoolMasque !

I think perhaps our share ec2 server was down when you tried to run this app.

I'm closing as I cannot reproduce!

<img width="1181" alt="image" src="https://user-images.githubusercontent.com/41651716/212330336-50942a03-63be-49db-b05c-a3eb755e03bd.png">

**Closed by freddyaboulton** 2023-01-13 13:25 UTC
Labels: bug
