### ISSUE TITLE
For PDF display Blocking on huggingFace

### ISSUE THREAD

**Issue by jyotiyadav94** [gradio-app/gradio#3062] opened 2023-01-26 11:24 UTC
### Describe the bug

I have used the below code to display examples as input which accepts a PDF in a new space. However displaying examples & processing them doesn't work instead of uploading a new PDF, it processes the image works fine.

![image](https://user-images.githubusercontent.com/72126242/214822226-fae3c432-f3e0-4b6c-a050-984ed7d82b3a.png)

```
iface = gr.Interface(fn=function,
 inputs=gr.File(label="PDF"),
 outputs=[gr.outputs.Image(type="pil", `label="annotated image"),"dataframe"]` ,
 title=title,
 description=description,
  examples=examples,
  css=css,
  #article=article,
  analytics_enabled = True, enable_queue=True)
  iface.launch(inline=False,debug=True)
```

I am facing this issue with PDF example recently however the previous created spaces works fine with the PDF display examples. 
I couldn't find the root cause of it. Would appreciate your help on this. 
I have searched to see if a similar issue already exists but I can't find any solution.- https://github.com/gradio-app/gradio/issues/2031

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
iface = gr.Interface(fn=function,
 inputs=gr.File(label="PDF"),
 outputs=[gr.outputs.Image(type="pil", `label="annotated image"),"dataframe"]` ,
 title=title,
 description=description,
  examples=examples,
  css=css,
  #article=article,
  analytics_enabled = True, enable_queue=True)
  iface.launch(inline=False,debug=True)
```

### Screenshot

![image](https://user-images.githubusercontent.com/72126242/214824047-02a5cfea-7f42-4157-8a38-41c23e811738.png)

### Logs

```shell
There is no logs display for this.
```

### System Info

```shell
gradio==3.16.1
```

### Severity

annoying

**Comment by jyotiyadav94** [comment] 2023-01-27 13:43
Any update on the issue ?

**Comment by freddyaboulton** [comment] 2023-01-30 16:30
Hi @jyotiyadav94 !

I cannot reproduce this error actually. I'm on 3.16.1 and the latest main branch as well.

![image](https://user-images.githubusercontent.com/41651716/215535909-25ddde1d-4414-4e08-9aee-4c8a59e1e2a7.png)

**Comment by jyoti-Wenda** [comment] 2023-01-30 17:58
@freddyaboulton 
Thank you so much for your response. I was facing this issue with previously 2 weeks back when I created the space. But I check today the issue is seems to be resolved when I created the new space But the issue with the previously created space exists.

**Comment by freddyaboulton** [comment] 2023-01-31 20:29
Will close this as the issue seems to be resolved for your on spaces @jyotiyadav94 ! Not sure what happened with your original space, maybe it was a gradio bug that got fixed in a subsequent release.

**Closed by freddyaboulton** 2023-01-31 20:29 UTC
Labels: bug
