### ISSUE TITLE
custom component's error log; Toast.svelte:8 TypeError: ((intermediate value) ||...

### ISSUE THREAD

**Issue by cosmosof** [gradio-app/gradio#7439] opened 2024-02-15 17:29 UTC
### Describe the bug

observing dev console message; 
```
TypeError: ((intermediate value) || (intermediate value)) is not a function
    at load_component (Toast.svelte:8:27)
    at Blocks.svelte:284:15
    at Array.forEach (<anonymous>)
    at prepare_components (Blocks.svelte:228:14)
    at $$self.$$.update (Blocks.svelte:157:25)
    at init (svelte.js:3246:5)
    at new Blocks (Blocks.svelte:707:31)
    at Array.create_if_block_1 (Index.svelte:425:26)
    at Object.p (Index.svelte:373:102)
    at update_slot_base (svelte.js:203:8)
```

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

reproducible on button template component

### Screenshot

<img width="464" alt="Screen Shot 2024-02-15 at 12 26 44 PM" src="https://github.com/gradio-app/gradio/assets/7368238/8f8c1694-1a8d-47dc-b612-663f06d9f5df">

### System Info

```shell
python 3.9
gradio 4.18.0
```

### Severity

I can work around it

**Comment by pngwn** [comment] 2024-02-15 18:00
Thanks fr the report. This is a duplicate of #6909.

**Closed by pngwn** 2024-02-15 18:00 UTC
Labels: bug
