### ISSUE TITLE
An event handler didn't receive enough output values (needed: 3, received: 2)

### ISSUE THREAD

**Issue by yadavj2008** [gradio-app/gradio#6912] opened 2023-12-30 16:47 UTC
### Describe the bug

I'm getting below error while working on capturing audio with change() event feature. Looks like a bug in the way we handle outputs from the function in case of change() method. Though same function works when using submit.button().

I'm sharing a reproducible code block below in case anyone want to test this scenario. I have to rely on change() due to my use case, hence, this is blocking me.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
import base64

def run_audio_prompt(audio, chat_history):
    #print("audio",audio)

    if audio is None:
        return None, chat_history

    with open(audio, "rb") as f:
        encoded_content = base64.b64encode(f.read())

    base64_audio = encoded_content
    audio_player = f'<audio src="data:audio/mpeg;base64,{base64_audio}" controls autoplay></audio>'
    print("Finished run_audio_prompt func")    
    return None, chat_history, audio_player

with gr.Blocks() as demo:
  chatbot = gr.Chatbot()
  html = gr.HTML()
  html.visible = False
  with gr.Row():
    audio = gr.Audio(label="Record Voice", sources="microphone", type="filepath")
    #submit = gr.Button("Submit")
    #submit.click(run_audio_prompt, [audio, chatbot], [audio, chatbot, html])
    audio.change(run_audio_prompt, [audio, chatbot], [audio, chatbot, html])

demo.launch(share=False,debug=True)
```

### Logs

```shell
Finished run_audio_prompt func
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 489, in call_prediction
    output = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1570, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1397, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1371, in validate_outputs
    raise ValueError(
ValueError: An event handler (run_audio_prompt) didn't receive enough output values (needed: 3, received: 2).
Wanted outputs:
    [audio, chatbot, html]
Received outputs:
    [None, []]
```

### System Info

```shell
gradio                           4.12.0
gradio_client                    0.8.0

Notebook: Colab
OS: MacOS
```

### Severity

Blocking usage of gradio

**Comment by yadavj2008** [comment] 2024-01-02 15:39
Hi @AlUlkesh thanks for the comment.

I should have had more clear on my issue reproducible code, in the actual application code i have sections in the code where I'm returning the value of audio variable from the func run_audio_prompt, hence, I can't remove the output variable as you suggested. 

wondering how it is working with submit.click method without any issue?.

**Comment by AlUlkesh** [comment] 2024-01-02 16:09
Hmm, it's kinda difficult to get a picture, without seeing your actual use case.

So just a few pointers:

Currently this happens:

- UI action
- run_audio_prompt is triggered due to .change
- run_audio_prompt returns None, chat_history, audio_player
- so this changes the value of audio to none and triggers another run_audio_prompt
- Now it runs into this code:

```
    if audio is None:
        return None, chat_history
```
And this returns only 2 output values, when 3 are expected.

So, depending on your use case, I think you can either

- remove audio from output
- don't change audio within run_audio_prompt (or set it to the original value before the return)
- make sure all returns have 3 values

**Comment by abidlabs** [comment] 2024-01-02 19:50
Hi @yadavj2008, as @AlUlkesh mentioned, the problem is that you're not returning a 3rd value if `audio` is `None`. This is not an issue with gradio, and @AlUlkesh has kindly provided reasonable workarounds, so I'll go ahead and close this issue.

**Closed by abidlabs** 2024-01-02 19:50 UTC
Labels: bug
