### ISSUE TITLE
microphone source throws RuntimeError for "ffprobe not found"

### ISSUE THREAD

**Issue by KrogFrog** [gradio-app/gradio#3429] opened 2023-03-10 04:26 UTC
### Describe the bug

When the "microphone" source is used with the Interface it throws the following error upon clicking "Submit":

"RuntimeError: Cannot load audio from file: `ffprobe` not found. Please install `ffmpeg` in your system to use non-WAV audio file formats and make sure `ffprobe` is in your PATH."

This seems to be related to an irregularity with the pip install for Gradio, possibly related to ffmpy dependency being installed with the legacy setup.py install.

Work around is to manually download the ffmpeg.exe and ffprobe.exe files into the project.

The above error was encountered on both a Windows 10 and Windows 11 installs.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

na

### Logs

```shell
na
```

### System Info

```shell
Gradio version 3.20.1
Windows 10 and 11
Edge version 111.0.1551.36
```

### Severity

serious, but I can work around it

**Comment by abhishek-mishra-07** [comment] 2023-03-11 14:58
If I want to deploy an app to huggingface using gradio or on streamlit, how do I workaround this issue?

**Comment by abidlabs** [comment] 2023-03-11 15:23
I can't reproduce this issue in a [fresh install on Colab](https://colab.research.google.com/drive/1sJmxbUwarjxhFNgzBc6nugt4k_44fFGV?usp=sharing) or [on Hugging Face Spaces](https://huggingface.co/spaces/abidlabs/test-mic).

@abhishek-mishra-07 this shouldn't be an issue on Hugging Face Spaces.

@KrogFrog it sounds like the issue is what the error message is describing: "please make sure `ffprobe` is in your PATH"

**Comment by abhishek-mishra-07** [comment] 2023-03-11 17:59
Yes, I verified that this does not appear as an issue on hugginface. 
Thanks for your reply :)

**Comment by abidlabs** [comment] 2023-03-14 16:49
Thanks @abhishek-mishra-07 for verifying. Closing for now, @KrogFrog feel free to reopen if this does not solve your issue

**Closed by abidlabs** 2023-03-14 16:49 UTC
Labels: pending clarification

**Comment by sid-fitmatch** [comment] 2023-05-10 17:55
@abhishek-mishra-07 @KrogFrog Would you be able to share how you solved this error? I am currently dealing the same error on MacOS with Microphone input

**Comment by chintan-donda** [comment] 2023-07-11 08:17
Same issue on MacOS.
Any fix?

**Comment by shaojun** [comment] 2024-05-20 14:28
i randomly see this issue in gradio `4.31.3` at recording a audio:
```
c:\Users\music\miniconda3\envs\roboctrl\Lib\site-packages\pydub\utils.py:198: RuntimeWarning: Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work
  warn("Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work", RuntimeWarning)
Traceback (most recent call last):
  File "c:\Users\music\miniconda3\envs\roboctrl\Lib\site-packages\gradio\processing_utils.py", line 544, in audio_from_file
    audio = AudioSegment.from_file(filename)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\music\miniconda3\envs\roboctrl\Lib\site-packages\pydub\audio_segment.py", line 728, in from_file
    info = mediainfo_json(orig_file, read_ahead_limit=read_ahead_limit)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\music\miniconda3\envs\roboctrl\Lib\site-packages\pydub\utils.py", line 274, in mediainfo_json
    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\music\miniconda3\envs\roboctrl\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\Users\music\miniconda3\envs\roboctrl\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\music\.vscode\extensions\ms-python.debugpy-2024.6.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydev_bundle\pydev_monkey.py", line 901, in new_CreateProcess
    return getattr(_subprocess, original_name)(app_name, cmd_line, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\music\miniconda3\envs\roboctrl\Lib\site-packages\gradio\queueing.py", line 528, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\music\miniconda3\envs\roboctrl\Lib\site-packages\gradio\route_utils.py", line 270, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\music\miniconda3\envs\roboctrl\Lib\site-packages\gradio\blocks.py", line 1904, in process_api
    inputs = await self.preprocess_data(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\music\miniconda3\envs\roboctrl\Lib\site-packages\gradio\blocks.py", line 1630, in preprocess_data
    processed_input.append(block.preprocess(inputs_cached))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\music\miniconda3\envs\roboctrl\Lib\site-packages\gradio\components\audio.py", line 218, in preprocess
    sample_rate, data = processing_utils.audio_from_file(temp_file_path)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\music\miniconda3\envs\roboctrl\Lib\site-packages\gradio\processing_utils.py", line 554, in audio_from_file
    raise RuntimeError(msg) from e
RuntimeError: Cannot load audio from file: `ffprobe` not found. Please install `ffmpeg` in your system to use non-WAV audio file formats and make sure `ffprobe` is in your PATH.
```
