### ISSUE TITLE
Be able to display chat messages accordion closed by default for assistant message

### ISSUE THREAD

**Issue by timeki** [gradio-app/gradio#9776] opened 2024-10-21 13:39 UTC
- [x] I have searched to see if a similar issue already exists.
- related to https://github.com/gradio-app/gradio/issues/9081

**Is your feature request related to a problem? Please describe.**  
In gradio chatbot, with type "message", you can add a title in metadata to get a accordion with a title and content inside
By default, this accordion is closed for role user, and open for role assistant

**Describe the solution you'd like**  
It would be nice to be able to have this accordio closed or opened by default with a parameter in the ChatMessage
Something like 
`               ChatMessage(role = "user", content = "user_test", metadata={"title":"title_user"}, accordio = "opened"),
                ChatMessage(role ="assistant", content = "assistant_test", metadata={"title":"title_assistant"}), accordio = "closed"),
`

![image](https://github.com/user-attachments/assets/50fcd6ef-c8c3-461a-9668-acb682ea8dab)

**Comment by abidlabs** [comment] 2024-10-21 14:44
Ah actually it is open only in the last message in the chat history, and closed for all previous message.

**Comment by abidlabs** [comment] 2024-10-21 14:44
But yes we could potentially let users customize this

**Comment by kurisu** [comment] 2024-10-22 18:48
Thank you for adding this, @timeki  

Does anyone know if there is a workaround?  In my use case, I only want the "final answer" to be open by default, and have any tool responses be closed by default.  Unfortunately, the tool responses remain open even after the final answer is added, resulting in a cluttered UX.

**Comment by abidlabs** [comment] 2024-10-22 20:34
@kurisu that should already be the default behavior. If not, can you share a reproducible snippet for us to try?

**Comment by kurisu** [comment] 2024-10-22 22:05
@abidlabs yes.  Every example project has the same problem.  Here's one condensed into a single file: 

```
import gradio as gr
from gradio import ChatMessage
from transformers import load_tool, ReactCodeAgent, HfApiEngine  # type: ignore
from utils import stream_from_transformers_agent

from transformers.agents import DuckDuckGoSearchTool

from gradio import ChatMessage
from transformers.agents import ReactCodeAgent, agent_types
from typing import Generator

def pull_message(step_log: dict):
    if step_log.get("rationale"):
        yield ChatMessage(
            role="assistant", content=step_log["rationale"]
        )
    if step_log.get("tool_call"):
        used_code = step_log["tool_call"]["tool_name"] == "code interpreter"
        content = step_log["tool_call"]["tool_arguments"]
        if used_code:
            content = f"```py\n{content}\n```"
        yield ChatMessage(
            role="assistant",
            metadata={"title": f"🛠️ Used tool {step_log['tool_call']['tool_name']}"},
            content=content,
        )
    if step_log.get("observation"):
        yield ChatMessage(
            role="assistant", content=f"```\n{step_log['observation']}\n```"
        )
    if step_log.get("error"):
        yield ChatMessage(
            role="assistant",
            content=str(step_log["error"]),
            metadata={"title": "💥 Error"},
        )

def stream_from_transformers_agent(
    agent: ReactCodeAgent, prompt: str
) -> Generator[ChatMessage, None, ChatMessage | None]:
    """Runs an agent with the given prompt and streams the messages from the agent as ChatMessages."""

    class Output:
        output: agent_types.AgentType | str = None

    step_log = None
    for step_log in agent.run(prompt, stream=True):
        if isinstance(step_log, dict):
            for message in pull_message(step_log):
                print("message", message)
                yield message

    Output.output = step_log
    if isinstance(Output.output, agent_types.AgentText):
        yield ChatMessage(
            role="assistant", content=f"**Final answer:**\n```\n{Output.output.to_string()}\n```")  # type: ignore
    elif isinstance(Output.output, agent_types.AgentImage):
        yield ChatMessage(
            role="assistant",
            content={"path": Output.output.to_string(), "mime_type": "image/png"},  # type: ignore
        )
    elif isinstance(Output.output, agent_types.AgentAudio):
        yield ChatMessage(
            role="assistant",
            content={"path": Output.output.to_string(), "mime_type": "audio/wav"},  # type: ignore
        )
    else:
        return ChatMessage(role="assistant", content=Output.output)

llm_engine = HfApiEngine("meta-llama/Meta-Llama-3-70B-Instruct")
# Initialize the agent with both tools
agent = ReactCodeAgent(llm_engine=llm_engine, tools=[DuckDuckGoSearchTool()])

def interact_with_agent(prompt, messages):
    messages.append(ChatMessage(role="user", content=prompt))
    yield messages
    for msg in stream_from_transformers_agent(agent, prompt):
        messages.append(msg)
        yield messages
    yield messages

with gr.Blocks() as demo:
    stored_message = gr.State([])
    chatbot = gr.Chatbot(label="Agent",
                         type="messages",
                         avatar_images=(None, "https://em-content.zobj.net/source/twitter/53/robot-face_1f916.png"))
    text_input = gr.Textbox(lines=1, label="Chat Message")
    text_input.submit(lambda s: (s, ""), [text_input], [stored_message, text_input]).then(interact_with_agent, [stored_message, chatbot], [chatbot])

if __name__ == "__main__":
    demo.launch()
```

**Comment by kurisu** [comment] 2024-10-22 22:22
Screenshot for reference.  You can see the final answer, and some of the tool responses above.  If I scroll up, all of the tool responses are still expanded. 

This might be helpful: if I subsequently submit a new user message, all those prior tool responses suddenly collapse.  

However, that doesn't help the user see the conversation while they're typing.  The expanded tool responses break up the flow of conversation.

![image](https://github.com/user-attachments/assets/90d7c213-bf43-4849-bafc-d4f3ffa1e3a1)

**Comment by kurisu** [comment] 2024-10-23 15:52
I couldn't resist looking into it further.  It looks like Line 153 of Message.svelte is where this behavior should be implemented: 

```svelte
expanded={is_last_bot_message(messages, value)}
```

However, in practice, while tool responses are being added via streaming, they are all left expanded. This implies that, at least while streaming, the previously rendered messages do not pass through this part of the code again.  This would also explain why a subsequent user message being separately added (not streaming), the bot messages are re-rendered and only then are collapsed.  

So my theory is that this is a problem with streaming. Now I'm trying to figure out why and how streaming is done differently on the front-end.

**Comment by kurisu** [comment] 2024-10-23 16:52
Well, I think my theory was wrong, BUT I think I found root cause of the problem.  

I see from looking at fetched payloads that the whole list of messages is delivered each time, and I assume the front-end is re-rendering them all each time.  So then I was back to wondering why `is_last_bot_message` could be True for bot messages that are NOT the most recent ones. 

```svelte
export function is_last_bot_message(
	messages: NormalisedMessage[],
	all_messages: NormalisedMessage[]
): boolean {
	const is_bot = messages[messages.length - 1].role === "assistant";
	const last_index = messages[messages.length - 1].index;
	// use JSON.stringify to handle both the number and tuple cases
	// when msg_format is tuples, last_index is an array and when it is messages, it is a number
	const is_last =
		JSON.stringify(last_index) ===
		JSON.stringify(all_messages[all_messages.length - 1].index);
	return is_last && is_bot;
}
```
I'm new to svelte, but from what I can tell, Chatbot.svelte groups messages by role in seqential batches as user and bot go back and forth. (Line 188) Then for each group Chatbot instantiates Message.svelte with messages = the group and value = all messages. (Line 295) 

Then Message loops through each message in its message group, and calls `is_last_bot_message` with `messages` (the whole group) and `value` (all messages).

So.... how can `is_last_bot_message` even tell if the "current" message in the loop is the last message, when that message isn't even passed to the function? It's not.  `is_last_bot_message` is just returning True if the whole `group` of messages is the last `group`, which it is.  

All `is_last_bot_message` can say is True for the whole group.

**Comment by kurisu** [comment] 2024-10-23 16:52
@abidlabs I think I may have found root cause.  See above.

**Comment by abidlabs** [comment] 2024-10-23 17:56
Ah thanks for looking into this, @kurisu. Would you like to open a PR to fix this, we are happy to reivew? Otherwise, we have a few other things we're focused on right now, but I think we should be able to get to this in a month or so

**Comment by kurisu** [comment] 2024-10-23 18:29
@abidlabs Sounds good.  I might be able to take a swing at a PR next week.  I'll check back in this thread before I do.

**Comment by ngaudemet** [comment] 2024-10-26 15:39
I think it was much better before when the agent messages were all closed by default. Agents are so verbose that you don't want to see what they do, except when you want to check how the final answer is grounded. And it is very simple to check it in expanded the message. But it should be closed by default.

**Comment by freddyaboulton** [comment] 2024-10-31 19:12
Yea we'll be restoring that behavior in #9826

**Comment by kurisu** [comment] 2024-10-31 22:45
@freddyaboulton  Thank you for the update.

**Closed** 2024-10-31 22:48 UTC
Labels: enhancement

**Comment by JTGRC-public** [comment] 2025-05-08 00:47
> Ah actually it is open only in the last message in the chat history, and closed for all previous message.

This didn't happen in Gradio 5.18.0, all tool outputs in the chat history are open by default
