### ISSUE TITLE
"Illegal multibyte sequence error" when launching app.py with gradio command on Windows that contains a specific language

### ISSUE THREAD

**Issue by koshian2** [gradio-app/gradio#6063] opened 2023-10-23 08:04 UTC
### Describe the bug

Hello.
In Windows environment, when I try to run app.py containing Japanese Kanji characters in ```gradio app.py demo``` (hot reload enabled mode), it becomes an "illegal multibyte sequence" and does not run properly.

```
D:\test>gradio app.py demo
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\<username>\AppData\Roaming\Python\Python310\Scripts\gradio.exe\__main__.py", line 7, in <module>
  File "C:\Users\<username>\AppData\Roaming\Python\Python310\site-packages\gradio\cli.py", line 21, in cli
    gradio.reload.main()
  File "C:\Users\<username>\AppData\Roaming\Python\Python310\site-packages\gradio\reload.py", line 88, in main
    filename, path, watch_dirs, demo_name = _setup_config()
  File "C:\Users\<username>\AppData\Roaming\Python\Python310\site-packages\gradio\reload.py", line 37, in _setup_config
    app_text = Path(original_path).read_text()
  File "C:\Program Files\Python310\lib\pathlib.py", line 1135, in read_text
    return f.read()
UnicodeDecodeError: 'cp932' codec can't decode byte 0x85 in position 83: illegal multibyte sequence
```

Since this error did not occur when the file did not contain Japanese Kanji or only English, I think the reason is that I did not specify the encoding (e.g. utf-8) when reading the file in gradio/reload.py. Is there any way to deal with this?

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

This code, which is only in English, starts up fine.

```python
import gradio as gr

with gr.Blocks() as demo:
    markdown = gr.Markdown("Hello")

if __name__ == "__main__":
    demo.launch()
```

```
D:\test>gradio app.py demo
Watching: 'C:\Users\<username>\AppData\Roaming\Python\Python310\site-packages\gradio', 'D:\test'

Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
```

Codes that are in Japanese but do not contain Kanji characters also start up correctly

```python
import gradio as gr

with gr.Blocks() as demo:
    markdown = gr.Markdown("こんにちは")

if __name__ == "__main__":
    demo.launch()
```

A multibyte error will occur if certain Kanji characters are included as follows.

```python
# Error case
import gradio as gr

with gr.Blocks() as demo:
    markdown = gr.Markdown("忍者さんこんにちは")

if __name__ == "__main__":
    demo.launch()
```

```
D:\test>gradio app.py demo
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\<username>\AppData\Roaming\Python\Python310\Scripts\gradio.exe\__main__.py", line 7, in <module>
  File "C:\Users\<username>\AppData\Roaming\Python\Python310\site-packages\gradio\cli.py", line 21, in cli
    gradio.reload.main()
  File "C:\Users\<username>\AppData\Roaming\Python\Python310\site-packages\gradio\reload.py", line 88, in main
    filename, path, watch_dirs, demo_name = _setup_config()
  File "C:\Users\<username>\AppData\Roaming\Python\Python310\site-packages\gradio\reload.py", line 37, in _setup_config
    app_text = Path(original_path).read_text()
  File "C:\Program Files\Python310\lib\pathlib.py", line 1135, in read_text
    return f.read()
UnicodeDecodeError: 'cp932' codec can't decode byte 0x85 in position 83: illegal multibyte sequence
```

### Logs

```shell
Couldn't get debug logs because it didn't start.
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Windows
gradio version: 3.50.2
gradio_client version: 0.6.1

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.1.0
altair: 4.2.2
fastapi: 0.99.1
ffmpy: 0.3.0
gradio-client==0.6.1 is not installed.
httpx: 0.23.3
huggingface-hub: 0.15.1
importlib-resources: 6.0.1
jinja2: 3.1.2
markupsafe: 2.1.2
matplotlib: 3.7.1
numpy: 1.23.5
orjson: 3.8.7
packaging: 23.0
pandas: 1.5.3
pillow: 9.3.0
pydantic: 1.10.12
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0
requests: 2.28.1
semantic-version: 2.10.0
typing-extensions: 4.6.3
uvicorn: 0.23.2
websockets: 10.4
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.3.0
httpx: 0.23.3
huggingface-hub: 0.15.1
packaging: 23.0
requests: 2.28.1
typing-extensions: 4.6.3
websockets: 10.4
```

### Severity

Blocking usage of gradio

**Comment by ringwraith** [comment] 2023-11-23 03:37
same error ...

**Comment by freddyaboulton** [comment] 2023-12-04 16:25
This is a duplicate of #6364 which should be fixed soon!

**Closed by freddyaboulton** 2023-12-04 16:25 UTC
Labels: bug
