### ISSUE TITLE
File and PDF Components Allowing Unsupported Files to be Uploaded via 'Click to Upload'

### ISSUE THREAD

**Issue by Jocelyne-Smith** [gradio-app/gradio#9098] opened 2024-08-13 11:17 UTC
### Describe the bug

When using 'click to upload' on a gradio File component, a user is able to select files that are not specified in the file_types=[]. Similarly a user can upload a non-PDF file when using the 'click to upload' for the gradio PDF component. The same 'Invalid file type only x allowed' error should probably be displayed when a user tries to upload an invalid file type.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

submissions_zip_filepath = gr.File(label="Student Solutions (.zip)",
                                               type="filepath", 
                                               file_types=['.zip'], 
                                               interactive=True)

```

### Screenshot

![image](https://github.com/user-attachments/assets/3750512d-5284-499d-9128-f4baa7ea1656)

### System Info

```shell
gradio                    4.41.0
gradio_client             1.3.0
gradio_pdf                0.0.13
```

### Severity

I can work around it

**Comment by freddyaboulton** [comment] 2024-08-13 15:53
I can't repro the issue with the `gr.File` component @Jocelyne-Smith . Anything that's not a `.zip` is not allowed by my file picker. 

<img width="1224" alt="image" src="https://github.com/user-attachments/assets/3d40175c-eb23-4ff2-abe0-efd39643386c">

I will take a look separately at the PDF component.

**Comment by freddyaboulton** [comment] 2024-08-13 15:58
Can't reproduce on the PDF component either!

**Comment by Jocelyne-Smith** [comment] 2024-08-13 17:44
Hi @freddyaboulton.

Thank you for taking a look so quickly!

My apologies, I should have included more information.

I am running on windows.

First open the file explorer by clicking on 'Click to upload'.

![image](https://github.com/user-attachments/assets/9c646150-8842-4929-b62e-516d135d52d1)

Then click on the dropdown as shown in red. Select on 'All Files'.

![image](https://github.com/user-attachments/assets/2bc41d8b-a2d8-4913-97cf-acb9f992420b)

Select any invalid file type. In my example I uploaded a .jpg in the .zip component.

Heres the code of the component:

submissions_zip_filepath = gr.File(label="Student Solutions (.zip)",
                                               type="filepath", 
                                               file_types=['.zip'], 
                                               interactive=True)

I was able to upload a .jpg to the component that only accepts .zip file_types. I did not receive any error or warning.

![image](https://github.com/user-attachments/assets/9e8456b3-a83b-417b-9742-feca73415fe7)

The same issue can be found on the gradio PDF component with the steps as described above.

I did try it on a different PC with the newest gradio and its dependencies.

My apologies I am not sure what the same steps would be on MacOS.

Your help would be really appreciated!

Thank you.

**Comment by abidlabs** [comment] 2024-08-13 19:18
Duplicate of: https://github.com/gradio-app/gradio/issues/8662, I'll actually close https://github.com/gradio-app/gradio/issues/8662 since this has more useful context

**Comment by freddyaboulton** [comment] 2024-08-13 19:27
Gotcha @Jocelyne-Smith - looks like its a windows issue then!

**Comment by abidlabs** [comment] 2024-10-01 17:13
Closed via https://github.com/gradio-app/gradio/pull/9431 in `5.0-dev` branch

**Closed by abidlabs** 2024-10-01 17:13 UTC
Labels: bug
