### ISSUE TITLE
Enable user specified error messages

### ISSUE THREAD

**Issue by apolinario** [gradio-app/gradio#2014] opened 2022-08-15 15:10 UTC
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
I am adding a check if there's enough VRAM available before running a prediction. I can throw an error/exception for that and Gradio will display `ERROR`

**Describe the solution you'd like**  
I would like to specify my own error message if the error is thrown by me - in this case would be "Error: no avaliable GPUs, try again!"

An advanced version of this would allow people to specificy text messages from different potential errors that can happen "internally" on their models

**Comment by freddyaboulton** [comment] 2022-08-16 14:17
I think this is a dupe of https://github.com/gradio-app/gradio/issues/956

**Comment by abidlabs** [comment] 2022-08-18 13:54
Yes, this looks like a duplicate, so closing this issue. @apolinario let us know if #956 doesn't cover your use case.

**Closed by abidlabs** 2022-08-18 13:54 UTC
Labels: enhancement
