### ISSUE TITLE
Gradio-Lite is erroring: No module named 'multipart.multipart'; 'multipart' is not a package

### ISSUE THREAD

**Issue by jsteward2930** [gradio-app/gradio#9774] opened 2024-10-20 20:53 UTC
### Describe the bug

I have been using Gradio in Google Colab for a project that past few weeks. I started getting this error today whenever I try to start my application.  

!pip install --upgrade gradio

import gradio as gr

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-2-1273132a463e>](https://localhost:8080/#) in <cell line: 3>()
      1 import os
      2 import openai
----> 3 import gradio as gr
      4 from openai import OpenAI
      5 import logging

8 frames
[/usr/local/lib/python3.10/dist-packages/gradio/routes.py](https://localhost:8080/#) in <module>
     61 from gradio_client.utils import ServerMessage
     62 from jinja2.exceptions import TemplateNotFound
---> 63 from multipart.multipart import parse_options_header
     64 from starlette.background import BackgroundTask
     65 from starlette.datastructures import UploadFile as StarletteUploadFile

ModuleNotFoundError: No module named 'multipart.multipart'; 'multipart' is not a package

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

```
!pip install --upgrade gradio

import gradio as gr

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-2-1273132a463e>](https://localhost:8080/#) in <cell line: 3>()
      1 import os
      2 import openai
----> 3 import gradio as gr
      4 from openai import OpenAI
      5 import logging

8 frames
[/usr/local/lib/python3.10/dist-packages/gradio/routes.py](https://localhost:8080/#) in <module>
     61 from gradio_client.utils import ServerMessage
     62 from jinja2.exceptions import TemplateNotFound
---> 63 from multipart.multipart import parse_options_header
     64 from starlette.background import BackgroundTask
     65 from starlette.datastructures import UploadFile as StarletteUploadFile

ModuleNotFoundError: No module named 'multipart.multipart'; 'multipart' is not a package

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.

### System Info

```shell
!pip install --upgrade gradio

import gradio as gr

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-2-1273132a463e>](https://localhost:8080/#) in <cell line: 3>()
      1 import os
      2 import openai
----> 3 import gradio as gr
      4 from openai import OpenAI
      5 import logging

8 frames
[/usr/local/lib/python3.10/dist-packages/gradio/routes.py](https://localhost:8080/#) in <module>
     61 from gradio_client.utils import ServerMessage
     62 from jinja2.exceptions import TemplateNotFound
---> 63 from multipart.multipart import parse_options_header
     64 from starlette.background import BackgroundTask
     65 from starlette.datastructures import UploadFile as StarletteUploadFile

ModuleNotFoundError: No module named 'multipart.multipart'; 'multipart' is not a package

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
```

### Severity

Blocking usage of gradio

**Comment by lepolesaLibete** [comment] 2024-10-21 08:19
gradio lite is broken as well with the same error.
![Screenshot 2024-10-21 at 10 17 33](https://github.com/user-attachments/assets/206ff040-ad6a-4a49-bb2c-0a3a39e6697c)
Here is the screen short of the gradio lite documentation

**Comment by abidlabs** [comment] 2024-10-21 14:43
Thanks, it looks like the issue is fixed in Python because `multipart` yanked the latest release, which broke Gradio: https://pypi.org/project/python-multipart/#history, but Gradio-Lite is still not working for me. We're looking into it

cc @aliabd @whitphx

**Comment by jsteward2930** [comment] 2024-10-21 23:05
> multipart renamed as python_multipart in the latest version, you might want to reinstall the 0.0.12 with pip install python-multipart==0.0.12

That worked- thank you!

**Closed** 2024-10-22 14:12 UTC
Labels: bug, gradio-lite
