### ISSUE TITLE
Click "Upload an Image" in ImageEditor to upload an image

### ISSUE THREAD

**Issue by lllyasviel** [gradio-app/gradio#8679] opened 2024-07-02 03:08 UTC
![image](https://github.com/gradio-app/gradio/assets/19834515/dec445e5-3280-4efb-88ea-3910fc1a0884)

If user click here, one should be able to upload an image. otherwise very inconvenient.

**Comment by abidlabs** [comment] 2024-07-02 03:20
Thanks @lllyasviel agreed but duplicate of https://github.com/gradio-app/gradio/issues/6503

**Closed by abidlabs** 2024-07-02 03:20 UTC
