### ISSUE TITLE
DataFrame doesn't show columns anymore when provide pandas dataframe directly

### ISSUE THREAD

**Issue by pseudotensor** [gradio-app/gradio#5237] opened 2023-08-15 17:59 UTC
### Describe the bug

Columns are just numbers.  Really looks awful now, no idea how to work around, except to go back to old gradio.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

df.csv:
```
Collection,Type,Path
UserData,shared,
MyData,personal,
```

```
import gradio as gr
import pandas as pd


def filter_records(records, gender):
    return records[records["gender"] == gender]


df0 = pd.read_csv('df.csv')

demo = gr.Interface(
    filter_records,
    [
        gr.Dataframe(df0,
            interactive=False,
        ),
        gr.Dropdown(["M", "F", "O"]),
    ],
    "dataframe",
    description="Enter gender as 'M', 'F', or 'O' for other.",
)

if __name__ == "__main__":
    demo.launch()

```

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/2249614/26b8e55f-283e-4f1e-b366-ba64646f68c3)

What exact same code looks like in 3.39.0:

![image](https://github.com/gradio-app/gradio/assets/2249614/6c9328b3-121c-4cbf-94a0-77d4a98a4c59)

### System Info

```shell
gradio 3.40.1.  Didn't happen in 3.39.0.
```

### Severity

Blocking usage of gradio

Related: https://github.com/gradio-app/gradio/issues/5236

**Comment by abidlabs** [comment] 2023-08-15 18:00
Ok clearly some regressions happened here -- thanks for flagging @pseudotensor

**Comment by abidlabs** [comment] 2023-08-17 20:09
Unfortunate regression, but can confirm that this is now fixed on `main`: 

<img width="763" alt="image" src="https://github.com/gradio-app/gradio/assets/1778297/836150dc-b14b-4ff8-9d53-c8ebd8a33602">

I'll add some visual tests in a separate PR

**Comment by abidlabs** [comment] 2023-08-17 20:18
Actually it looks like this is fixed as well on `main` now:

Running your code gives me:

<img width="804" alt="image" src="https://github.com/gradio-app/gradio/assets/1778297/1ecff12a-99a7-443e-a572-b2b20e0e9699">

**Closed by abidlabs** 2023-08-17 20:18 UTC
Labels: bug

**Comment by pseudotensor** [comment] 2023-08-17 20:20
cool tx
