### ISSUE TITLE
import gradio gives error

### ISSUE THREAD

**Issue by Kkkassini** [gradio-app/gradio#8877] opened 2024-07-23 15:50 UTC
### Describe the bug

pydantic==2.8.2
gradio==4.39.0

`ImportError: cannot import name 'Schema' from 'pydantic' (/userfs/env/threestudio_env/lib64/python3.9/site-packages/pydantic/__init__.py)`

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
```

### System Info

```shell
.................
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment] 2024-07-23 16:37
Hi @Kkkassini - I can't reproduce with those versions that you shared. Can you try again in a fresh virtual environment?

**Comment by abidlabs** [comment] 2024-07-23 21:40
It might be related to your version of `fastapi`, please see here: https://github.com/Lightning-AI/pytorch-lightning/issues/17106

**Comment by abidlabs** [comment] 2024-07-25 03:33
Going to close this for now since this is not something we can reproduce. Its most likely related to either pydantic or fastapi version that is invalid, please try updating those packages, thanks!

**Closed by abidlabs** 2024-07-25 03:33 UTC
Labels: bug, pending clarification
