### ISSUE TITLE
Chatbot does not render Latex if there is a new line after `$$`

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#7146] opened 2024-01-24 22:19 UTC
### Describe the bug

The chatbot component will not render Latex if there is a newline after `$$`.

The issue is that the `render_markdown` will introduce a line break `<br>` after the `$$` and so katex will not render the latex.

Disabling render_markdown will render the latex correctly in this case.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

def response(msg, history):
    yield history + [[msg, None]]

with gr.Blocks() as iface: 
    chatbot = gr.Chatbot(render_markdown=True)
    msg = gr.Textbox(label="Prompt", lines=7, max_lines=26, placeholder="Enter your question here")
    btn = gr.Button("⏎ Submit", variant="primary") # Submit button

    btn.click(response, inputs=[msg, chatbot], outputs=[chatbot])

iface.queue().launch()

```

And type the following equation into the textbox and press enter

```
$$
\int{-\infty}^{+\infty} e^{-x^2} dx = \sqrt{\pi}
$$
```

<img width="787" alt="image" src="https://github.com/gradio-app/gradio/assets/41651716/7ea337ea-d7eb-401b-86ef-916b1dd3af40">

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Darwin
gradio version: 4.15.0
gradio_client version: 0.8.1

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 4.2.0
fastapi: 0.104.1
ffmpy: 0.3.1
gradio-client==0.8.1 is not installed.
httpx: 0.23.0
huggingface-hub: 0.19.4
importlib-resources: 6.0.1
jinja2: 3.1.2
markupsafe: 2.1.1
matplotlib: 3.7.2
numpy: 1.26.1
orjson: 3.9.4
packaging: 22.0
pandas: 1.5.3
pillow: 9.2.0
pydantic: 2.5.2
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0
ruff: 0.1.7
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.8.0
uvicorn: 0.23.2
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.6.0
httpx: 0.23.0
huggingface-hub: 0.19.4
packaging: 22.0
typing-extensions: 4.8.0
websockets: 11.0.3
```

### Severity

I can work around it

**Comment by abidlabs** [comment] 2024-01-27 00:29
Is this an actual bug? I think this might be behaving correctly according to markdown/latex spec -- you can't have a new line right after the latex delimiter. For example, I see the same behavior here: https://dillinger.io/

**Comment by arian81** [comment] 2024-01-27 00:33
> Is this an actual bug? I think this might be behaving correctly according to markdown/latex spec -- you can't have a new line right after the latex delimiter. For example, I see the same behavior here: https://dillinger.io/

You're right that this is an expected behaviour of latex, however I don't see why we can't add extra logic to handle the case of new line after the delimiter. In my pr as you can see I haven't changed how the latex engine handles latex, but I've removed the newlines from user input using regex. Let me know what you think.

**Comment by abidlabs** [comment] 2024-01-27 01:22
Well, I think we'd also have to look at which latex delimiters a user has enabled for the chatbot using the `latex_delimiters` argument, and we wouldn't want to strip newlines if latex is not enabled.

**Comment by arian81** [comment] 2024-01-27 01:50
> Well, I think we'd also have to look at which latex delimiters a user has enabled for the chatbot using the `latex_delimiters` argument, and we wouldn't want to strip newlines if latex is not enabled.

The delimiters thing is definitely doable i'll make a commit for it. To your second point, based on Chatbox documentation, latex is disabled when `latex_delimeters` is set to empty list, so based on that i will choose to whether run that function or no. I will work on a commit for this if you have decided that you want to have this as a feature.

**Comment by abidlabs** [comment] 2024-01-28 01:16
Personally, I'd prefer leaving the behavior as is because the logic to strip newlines can easily be incorporated into the response function. But I'll let @freddyaboulton chime in if he feels strongly otherwise.

**Comment by freddyaboulton** [comment] 2024-01-28 18:40
This was filed after a discussion on discord - [link](https://discord.com/channels/879548962464493619/1199542566828388413/1199542566828388413). A user noticed that the behavior changed from 3.50 to 4.x. Version 3.50 is able to display the latex correctly. It seemed like a bug to me because the problem is that gradio introduces a `<br>` to the latex that katext won't parse.

I agree this could also be incorporated in the prediction function but if it's possible to do this in the chatbot without breaking anything, it seems like a reasonable improvement.

**Comment by abidlabs** [comment] 2024-01-29 12:27
I see, that makes sense. In that case, let's go ahead with this. I'll go ahead and comment on your PR @arian81

**Comment by abidlabs** [comment] 2024-01-29 12:46
Interesting, I see. I'm still not sure if its worth the added complexity of parsing the generated HTML with regex and removing whitespace immediately after the latex delimiters. There's a simpler solution, setting `line_breaks=False` in `gr.Chatbot`, which I think would work for the original author (if they don't mind the unintended consequences of all single new lines being treated as continuations of the same line)

**Comment by abidlabs** [comment] 2024-02-14 22:21
Do you still feel strongly about this issue @freddyaboulton?

**Comment by abidlabs** [comment] 2024-02-21 02:42
I'll go ahead and close this issue since there's a simpler solution (see above) and I do not think the added complexity is worth it. Open to reconsidering.

**Closed by abidlabs** 2024-02-21 02:42 UTC
Labels: bug, pending clarification
