### ISSUE TITLE
Event listener in `gr.render` produces `AttributeError`

### ISSUE THREAD

**Issue by gsarti** [gradio-app/gradio#8973] opened 2024-08-02 15:07 UTC
### Describe the bug

When I try to dynamically update a field inside a `gr.render` function from the value of other fields, as described in the [Dynamic Apps with the Render Decorator](https://www.gradio.app/guides/dynamic-apps-with-render-decorator) guide, I stumble upon an error stating `AttributeError: Cannot call change outside of a gradio.Blocks context.`. I tried to use various components and event listeners (the above is produced with `gr.Textbox` and `change`), to no avail.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

In this example, the goal would be to render the list of `example_values` while making it editable using textboxes. The `merged` variable would be the concatenation of all answers, and would get dynamically updated when one of the answers is changed.

```python
import gradio as gr

examples = [
    ["A", "B", "C", "D"],
    ["A", "B", "C"],
    ["A", "B", "C", "D", "E"],
]

with gr.Blocks() as demo:
    with gr.Tab("Test tab"):
        with gr.Row():
            with gr.Column():
                example_id = gr.Number(1, label="Ex. ID", minimum=1, maximum=3, step=1, interactive=True)
        
    @gr.render(inputs=[example_id], triggers=[demo.load, example_id.change])
    def show_example(example_number):
        example_values = examples[example_number - 1]
        with gr.Row():
            answers: list[gr.Textbox] = []
            with gr.Column():
                gr.Markdown("Examples:")
                for v in example_values:
                    answer = gr.Textbox(v, show_label=False, placeholder="Insert value...", interactive=True, max_lines=1)
                    answers.append(answer)
            with gr.Column():
                merged = gr.Markdown("MERGED: " + "".join(example_values))
            
            def update_merged(*answers):
                merged = "MERGED: "
                for answer in answers:
                    if answer is not None:
                        merged += answer
                return gr.Markdown(merged)
            
            for answer in answers:
                answer.change(update_merged, [*answers], merged)
        
demo.launch()
```

The error here is produced by the `answer.change` call at the end of the `show_example` function.

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Darwin
gradio version: 4.31.5
gradio_client version: 0.16.4

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.3.0
fastapi: 0.110.1
ffmpy: 0.3.2
gradio-client==0.16.4 is not installed.
httpx: 0.27.0
huggingface-hub: 0.22.2
importlib-resources: 6.4.0
jinja2: 3.1.3
markupsafe: 2.1.5
matplotlib: 3.8.4
numpy: 1.26.4
orjson: 3.10.0
packaging: 24.0
pandas: 2.2.2
pillow: 10.3.0
pydantic: 2.6.4
pydub: 0.25.1
python-multipart: 0.0.9
pyyaml: 6.0.1
ruff: 0.2.2
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.12.2
typing-extensions: 4.11.0
urllib3: 2.2.1
uvicorn: 0.29.0
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2024.2.0
httpx: 0.27.0
huggingface-hub: 0.22.2
packaging: 24.0
typing-extensions: 4.11.0
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by knowsuchagency** [comment] 2024-08-06 04:12
I encountered the same issue. Another reproducible version:

### this is fine

```python

import gradio as gr

with gr.Blocks() as demo:

    subscribed = gr.State(False)

    update_subscription_btn = gr.Button("Update Subscription")

    @update_subscription_btn.click(inputs=subscribed, outputs=subscribed)
    def update_subscription(subscribed):
        return not subscribed

    @gr.render(inputs=subscribed)
    def render_subscription(subscribed):

        if subscribed:
            gr.Textbox("You are subscribed")
            gr.Textbox("You will be billed $10.00 every month")
        else:
            gr.Textbox("You are not subscribed")


demo.launch()
```

### this will fail

```python
import gradio as gr

with gr.Blocks() as demo:
    
    subscribed = gr.State(False)

    @gr.render(inputs=subscribed)
    def render_subscription(subscribed):
      
        update_subscription_btn = gr.Button("Update Subscription")

        @update_subscription_btn.click(inputs=subscribed, outputs=subscribed)
        def update_subscription(subscribed):
            return not subscribed

        if subscribed:
            gr.Textbox("You are subscribed")
            gr.Textbox("You will be billed $10.00 every month")
        else:
            gr.Textbox("You are not subscribed")

demo.launch()
```

```bash
File ".../.venv/lib/python3.12/site-packages/gradio/blocks.py", line 575, in get_config
    "inputs": [block._id for block in self.inputs],
               ^^^^^^^^^
AttributeError: 'bool' object has no attribute '_id'
```

**Comment by knowsuchagency** [comment] 2024-08-06 04:14
The workaround so far has been to avoid event listeners inside the `@render` function

**Comment by freddyaboulton** [comment] 2024-08-12 15:29
I think this is a duplicate of #8670 - will close but will make a not in that issue. Thanks for filing @gsarti @knowsuchagency

**Comment by elismasilva** [comment] 2024-08-28 16:24
see my comment in #8670

**Comment by freddyaboulton** [comment] 2024-09-05 01:30
Can't repro on the latest version of gradio @gsarti ! Are you still facing this issue?

![render_merge_error](https://github.com/user-attachments/assets/f00f59b0-9383-4d9e-b5c0-278c1ee1d51f)

**Comment by gsarti** [comment] 2024-09-05 12:12
4.42 still does not work for me (no changed in the merged string), installing from `main` seems to fix the issue!

**Comment by freddyaboulton** [comment] 2024-09-06 19:13
@gsarti thanks for checking! We released version 4.43.0 yesterday which I confirmed fixes the bug in your repro.

@knowsuchagency - I think the problem is that inside the `@render` event, the input gets unpacked from the "block" into the underlying data. This is the same behavior for all components that are passed to event handler functions. You can use different names for the block and its underlying data, e.g.

```python
import gradio as gr

with gr.Blocks() as demo:
    
    subscribed_state = gr.State(False)

    @gr.render(inputs=subscribed_state)
    def render_subscription(subscribed):
      
        update_subscription_btn = gr.Button("Update Subscription")

        @update_subscription_btn.click(inputs=subscribed_state, outputs=subscribed_state)
        def update_subscription(subscribed):
            return not subscribed

        if subscribed:
            gr.Textbox("You are subscribed")
            gr.Textbox("You will be billed $10.00 every month")
        else:
            gr.Textbox("You are not subscribed")

demo.launch()
```

Or use the other approach you have identified.

Will close for now.

**Closed by freddyaboulton** 2024-09-06 19:13 UTC
Labels: bug

**Comment by elismasilva** [comment] 2024-09-07 01:10
@freddyaboulton i'm having this problem. I have a main button outside the render area for submit. I want it to fire an event that reads the values ​​of the elements that are outside and inside the render. The elements that are being rendered after subscribing to the event become non-interactive. How can I solve this? See an example.

``` python
import gradio as gr

def identity(d1, d2):
    print(d1)
    print(d2)    

render_inputs=[]

with gr.Blocks() as demo:
    show_checkbox = gr.Checkbox(label="Show", value=False)
    
    drop_out = gr.Dropdown(label="Drop out", choices=[1,2,3], value=1)
    @gr.render(inputs=[show_checkbox])
    def render(show: bool) -> None:
        if not show:
            return
               
        drop = gr.Dropdown(label="Drop in", choices=[1,2,3], value=1)
        if drop not in render_inputs:
            render_inputs.append(drop)
    
    submit= gr.Button("Submit", variant="primary")
 
    submit.click(fn=identity, inputs=[drop_out, *render_inputs])  

demo.launch(inbrowser=True)
```

**Comment by elismasilva** [comment] 2024-09-07 01:25
> @freddyaboulton i'm having this problem. I have a main button outside the render area for submit. I want it to fire an event that reads the values ​​of the elements that are outside and inside the render. The elements that are being rendered after subscribing to the event become non-interactive. How can I solve this? See an example.
> 
> ```python
> import gradio as gr
> 
> def identity(d1, d2):
>     print(d1)
>     print(d2)    
> 
> render_inputs=[]
> 
> with gr.Blocks() as demo:
>     show_checkbox = gr.Checkbox(label="Show", value=False)
>     
>     drop_out = gr.Dropdown(label="Drop out", choices=[1,2,3], value=1)
>     @gr.render(inputs=[show_checkbox])
>     def render(show: bool) -> None:
>         if not show:
>             return
>                
>         drop = gr.Dropdown(label="Drop in", choices=[1,2,3], value=1)
>         if drop not in render_inputs:
>             render_inputs.append(drop)
>     
>     submit= gr.Button("Submit", variant="primary")
>  
>     submit.click(fn=identity, inputs=[drop_out, *render_inputs])  
> 
> demo.launch(inbrowser=True)
> ```

In time i think i solved it. I need replace submit.click after render. So i tested with funcion outside and inside with.gr.Blocks() and worked.

``` python
import gradio as gr

def identity(d1, d2):
    print(d1)
    print(d2)    

render_inputs=[]

def render_this(show):
    if not show:
        return
            
    drop = gr.Dropdown(label="Drop in", choices=[1,2,3], value=1)
    if drop not in render_inputs:
        render_inputs.append(drop)
    submit.click(fn=identity, inputs=[drop_out, *render_inputs]) 

with gr.Blocks() as demo:
    show_checkbox = gr.Checkbox(label="Show", value=False)
    
    drop_out = gr.Dropdown(label="Drop out", choices=[1,2,3], value=1)
    @gr.render(inputs=[show_checkbox])
    def render(show: bool) -> None:
        return render_this(show) 
        
    submit= gr.Button("Submit", variant="primary") 
    submit.click(fn=identity, inputs=[drop_out, *render_inputs])  

demo.launch(inbrowser=True)
```
