### ISSUE TITLE
Huge inference time when using gradio interface with GPU

### ISSUE THREAD

**Issue by nhuvan** [gradio-app/gradio#130] opened 2021-03-05 10:27 UTC
Hello,
It seems my model does not run on GPU when calling from the Gradio interface. 
In my server, it runs on GPU and the inference time is only 3s. But when using Gradio interface on the same code, it takes 3 minutes.

**Comment by nhuvan** [comment] 2021-03-05 10:28
Is there any config related to GPU I need set?

**Comment by nhuvan** [comment] 2021-03-09 17:09
What is the problem with Flask? do you have any solution?

**Comment by nhuvan** [comment] 2021-03-09 18:54
Thank you. I solve the issue by making a local rest api for the model.

**Comment by abidlabs** [comment] 2021-04-23 17:26
Closing because the issue is likely based on this link: https://discuss.pytorch.org/t/pytorch-inference-is-slow-inside-flask-api/95476/3:

> Do you run your PyTorch model in Python or have you JITed it to TorchScript? If you run your model through the JIT - even from Python - you avoid the infamous Python GIL for all intermediates, which may give you an edge in multithreaded deployment scenarios.

**Closed by abidlabs** 2021-04-23 17:26 UTC
