### ISSUE TITLE
Gallery's .select(..) event does not trigger when a user deselects an image

### ISSUE THREAD

**Issue by gavinliukaiber** [gradio-app/gradio#7590] opened 2024-03-04 00:37 UTC
### Describe the bug

Hi Gradio team, 

When I click into an image on Gallery, and then click the "X" button to go back the the preview view, no `.select` event is not triggered. 

However, Gallery's doc states this scenario should trigger a .select event --- "Event listener for when the user selects or **deselects** the Gallery. " . My app needs this behavior to enable/disable buttons on the UI when a user deselects a image.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

with gr.Blocks() as demo:
  gallery = gr.Gallery(['r.png', 'd.png'])
  statement = gr.Textbox(label="Statement", lines=2, value="Hello, world!")
  
  def on_select(evt: gr.SelectData):  # SelectData is a subclass of EventData
      return f"You selected {evt.value} at {evt.index} from {evt.target}"
  
  gallery.select(on_select, [], statement)

```

### System Info

```shell
Gradio 4.19.2
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment] 2024-03-05 00:06
This is a dupe of #6697 - will close. But should be straightforward to fix this! Thanks @gavinliukaiber !

**Closed by freddyaboulton** 2024-03-05 00:06 UTC
Labels: bug
