### ISSUE TITLE
Be able to update ChatInterface's additional_inputs from the chat function

### ISSUE THREAD

**Issue by ZhuJD-China** [gradio-app/gradio#6558] opened 2023-11-23 06:41 UTC
### Describe the bug

after run echo() ，i have changed list_collections_name，but i had to  restart  python to change collection_name_select = gr.Dropdown(list_collections_name, label="Select existed Collection")  UI ， please help me to solve it ! 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

collections = client.list_collections()
list_collections_name = []
for collection in collections:
    collection_name = collection.name
    list_collections_name.append(collection_name)

with gr.Blocks(theme=seafoam) as RainbowGPT:
    with gr.Row():
        # 创建一个包含选项的多选框组
        tool_options = ["Google Search", "Local Knowledge Base Search"]
        tool_checkbox_group = gr.CheckboxGroup(tool_options, label="Tools Select Options")

        collection_options = ["None", "Read Existing Collection", "Create New Collection"]
        collection_checkbox_group = gr.Radio(collection_options, label="Local Knowledge Collection Select Options")

        collection_name_select = gr.Dropdown(list_collections_name, label="Select existed Collection")

    # 将最上面的三个 UI 控件并排放置
    with gr.Row():
        new_collection_name = gr.Textbox("", label="Input New Collection Name")
        uploaded_files = gr.File(file_count="multiple", label="Upload Files")
      
    temperature_num = gr.Slider(0, 1, render=False, label="Temperature")
    print_speed_step = gr.Slider(10, 20, render=False, label="Print Speed Step")
    gr.ChatInterface(
        echo, additional_inputs=[collection_name_select, collection_checkbox_group, new_collection_name,
                                 temperature_num, print_speed_step, tool_checkbox_group, uploaded_files],
        title="RainbowGPT-Agent",
        description="How to reach me: zhujiadongvip@163.com",
        css=".gradio-container {background-color: red}",

    )

RainbowGPT.queue().launch(share=True)

after run echo() ，i have changed list_collections_name，but i had to  restart  python to change collection_name_select = gr.Dropdown(list_collections_name, label="Select existed Collection")  UI ， please help me to solve it ! 

### Logs

```shell
none
```

### System Info

```shell
gradio                        3.39.0
gradio_client                 0.7.0
```

### Severity

I can work around it

**Comment by abidlabs** [comment] 2023-11-23 08:13
Hi @ZhuJD-China I'm sorry but I don't understand what this issue is about. The code snippet is also hard to read, please provide a minimal code example that we can use to reproduce the issue, See: https://stackoverflow.com/help/minimal-reproducible-example

Finally, please test on the latest version of `gradio` -- 4.7.1

**Comment by ZhuJD-China** [comment] 2023-11-23 08:51
import datetime
import sys
import threading
import time
import chromadb
from langchain.embeddings import OpenAIEmbeddings, HuggingFaceEmbeddings
from langchain.vectorstores import Chroma
from transformers import GPT2Tokenizer
import logging
import gradio as gr
from typing import Iterable
from gradio.themes.base import Base
from gradio.themes.utils import colors, fonts, sizes
import time

persist_directory = ".chromadb/"
client = chromadb.PersistentClient(path=persist_directory)
print(client.list_collections())

collections = client.list_collections()
list_collections_name = []
for collection in collections:
    collection_name = collection.name
    list_collections_name.append(collection_name)

embeddings = OpenAIEmbeddings()


def echo(message, history, collection_name_select):
    # add a collections to Chroma database, so i can get a new collections by  collections = client.list_collections()
    docsearch_db = Chroma.from_documents(documents="............", embedding=embeddings,
                                         collection_name="NEW_NAME",
                                         persist_directory=persist_directory)

    response = "collections = client.list_collections()  has changed"

    collections = client.list_collections()
    list_collections_name = []
    for collection in collections:
        collection_name = collection.name
        list_collections_name.append(collection_name)
    collection_name_select = gr.Dropdown(list_collections_name, label="Select existed Collection")

    """
        collection_name_select = gr.Dropdown(list_collections_name, label="Select existed Collection")  not changed ???
        
        In the echo function, I added a knowledge base to the Chroma database.
         However, in the UI interface, no matter how I refresh the page, the elements in the drop-down list are not added.
          How do I update the elements in the drop-down list so that I can select the newly added ones in the UI
          
          please!!!
    """

    return response


with gr.Blocks() as RainbowGPT:
    collection_name_select = gr.Dropdown(list_collections_name, label="Select existed Collection")

    gr.ChatInterface(
        echo, additional_inputs=[collection_name_select],
        title="RainbowGPT-Agent",
        description="How to reach me: zhujiadongvip@163.com",
        css=".gradio-container {background-color: red}",
    )

RainbowGPT.queue().launch(share=True)
Q： collection_name_select = gr.Dropdown(list_collections_name, label="Select existed Collection")  not changed ???
        
        In the echo function, I added a knowledge base to the Chroma database.
         However, in the UI interface, no matter how I refresh the page, the elements in the drop-down list are not added.
          How do I update the elements in the drop-down list so that I can select the newly added ones in the UI
          
          please!!!

**Comment by ZhuJD-China** [comment] 2023-11-23 08:52
```python
import datetime
import sys
import threading
import time
import chromadb
from langchain.embeddings import OpenAIEmbeddings, HuggingFaceEmbeddings
from langchain.vectorstores import Chroma
from transformers import GPT2Tokenizer
import logging
import gradio as gr
from typing import Iterable
from gradio.themes.base import Base
from gradio.themes.utils import colors, fonts, sizes
import time

persist_directory = ".chromadb/"
client = chromadb.PersistentClient(path=persist_directory)
print(client.list_collections())

collections = client.list_collections()
list_collections_name = []
for collection in collections:
    collection_name = collection.name
    list_collections_name.append(collection_name)

embeddings = OpenAIEmbeddings()


def echo(message, history, collection_name_select):
    # add a collections to Chroma database, so i can get a new collections by  collections = client.list_collections()
    docsearch_db = Chroma.from_documents(documents="............", embedding=embeddings,
                                         collection_name="NEW_NAME",
                                         persist_directory=persist_directory)

    response = "collections = client.list_collections()  has changed"

    collections = client.list_collections()
    list_collections_name = []
    for collection in collections:
        collection_name = collection.name
        list_collections_name.append(collection_name)
    collection_name_select = gr.Dropdown(list_collections_name, label="Select existed Collection")

    """
        collection_name_select = gr.Dropdown(list_collections_name, label="Select existed Collection")  not changed ???
        
        In the echo function, I added a knowledge base to the Chroma database.
         However, in the UI interface, no matter how I refresh the page, the elements in the drop-down list are not added.
          How do I update the elements in the drop-down list so that I can select the newly added ones in the UI
          
          please!!!
    """

    return response


with gr.Blocks() as RainbowGPT:
    collection_name_select = gr.Dropdown(list_collections_name, label="Select existed Collection")

    gr.ChatInterface(
        echo, additional_inputs=[collection_name_select],
        title="RainbowGPT-Agent",
        description="How to reach me: zhujiadongvip@163.com",
        css=".gradio-container {background-color: red}",
    )

RainbowGPT.queue().launch(share=True)
```
Q:    collection_name_select = gr.Dropdown(list_collections_name, label="Select existed Collection")  not changed ???
        
        In the echo function, I added a knowledge base to the Chroma database.
         However, in the UI interface, no matter how I refresh the page, the elements in the drop-down list are not added.
          How do I update the elements in the drop-down list so that I can select the newly added ones in the UI
          
          please!!!

**Comment by freddyaboulton** [comment] 2023-12-08 18:09
I think it's tricky to do with the ChatInterface as the function must only return a string for the response. If you build the chatbot using `gr.Chatbot`, you can return the updated dropdown component from your function.

If you're unfamiliar with `gr.Chatbot`, you can read the guides here: https://www.gradio.app/guides/creating-a-custom-chatbot-with-blocks

**Comment by freddyaboulton** [comment] 2023-12-08 18:10
Not sure if we'll build this into the chatinterface abstraction since it's meant to be a high level abstraction and this seems like a custom use case.

**Comment by abidlabs** [comment] 2023-12-08 20:09
Agreed with @freddyaboulton -- this is out of scope for `gr.ChatInterface`. For more customizability, I would suggest using the base `gr.Chatbot` component within `gr.Blocks` -- and then you can update components however you'd like! 

https://www.gradio.app/guides/creating-a-custom-chatbot-with-blocks

**Closed by abidlabs** 2023-12-08 20:09 UTC
Labels: enhancement
