### ISSUE TITLE
New image input by drawing rectangle

### ISSUE THREAD

**Issue by anyangml** [gradio-app/gradio#5034] opened 2023-07-28 14:05 UTC
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

I am working on an OCR project, and I would like the user to provide image input by drawing a rectangle directly instead of uploading the image.

**Describe the solution you'd like**  

A new option to gradio.Image(source = "select")

**Additional context**  
No

**Comment by abidlabs** [comment] 2023-11-07 00:05
Hey! We've now made it possible for Gradio users to create their own custom components -- meaning that you can write some Python and JavaScript (Svelte), and publish it as a Gradio component. You can use it in your own Gradio apps, or share it so that anyone can use it in their Gradio apps. Here are some examples of custom Gradio components:

* A "Rich Textbox" that [allows you to write bold/italics/colored text](https://huggingface.co/spaces/abidlabs/gradio_rich_textbox)
* A "Folium Map Viewer" component that [allows you to use interactive maps](https://huggingface.co/spaces/freddyaboulton/gradio_folium)

You can see the source code for those components by clicking the "Files" icon and then clicking "src". The complete source code for the backend and frontend is visible. **In particular, its very fast if you want to build off an existing component**. We've put together a Guide: https://www.gradio.app/guides/five-minute-guide, and we're happy to help. Hopefully this will help address this issue.

**Comment by abidlabs** [comment] 2023-12-05 16:39
Closing as this is actually a duplicate of: #2316

**Closed by abidlabs** 2023-12-05 16:39 UTC
Labels: new component
