### ISSUE TITLE
AttributeError: 'Blocks' object has no attribute 'share' 

### ISSUE THREAD

**Issue by radames** [gradio-app/gradio#1227] opened 2022-05-12 17:29 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Testing beta 3.0b9 Running on a local machine, without mention `share=true` it doesn't run a local webserver, and raises the following error

```
AttributeError: 'Blocks' object has no attribute 'share'

Running on public URL: https://24528.gradio.app
```

### Reproduction

You can run the demo to reproduce the erro

https://github.com/gradio-app/gradio/blob/main/demo/blocks_flashcards/run.py

### System Info

```shell
3.0b0
```

### Severity

critical

**Comment by pngwn** [comment] 2022-05-12 17:34
Duplicate of https://github.com/gradio-app/gradio/issues/1223. Fixed in `main` and will be released soon.

**Comment by radames** [comment] 2022-05-12 17:35
Sorry I've missed that

**Closed by pngwn** 2022-05-12 17:34 UTC
Labels: bug
