### ISSUE TITLE
how to fix this bug when i start this project

### ISSUE THREAD

**Issue by libai-lab** [gradio-app/gradio#2686] opened 2022-11-21 16:07 UTC
### Describe the bug

 when i try to rebuild this project i got this problem

 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @gradio/app@1.0.0 build:local: `vite build --mode production:local --emptyOutDir "--emptyOutDir"`
Exit status 137
 ELIFECYCLE  Command failed with exit code 1.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I just run bash scripts/build_frontend.sh but i got this bug ,how can i fix it

### Screenshot

 .input-slider .dark .value {
       ^
152:     --tw-bg-opacity: 1;
153:     background-color: rgb(75 85 99 / var(--tw-bg-opacity));
transforming (1578) ../../node_modules/.pnpm/d3-color@3.0.1/node_modules/d3-color/src/lab.jsKilled
/workspaces/gradio/ui/packages/app:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @gradio/app@1.0.0 build:local: `vite build --mode production:local --emptyOutDir "--emptyOutDir"`
Exit status 137
 ELIFECYCLE  Command failed with exit code 1.

### Logs

```shell
.input-slider .dark .value {
       ^
152:     --tw-bg-opacity: 1;
153:     background-color: rgb(75 85 99 / var(--tw-bg-opacity));
transforming (1578) ../../node_modules/.pnpm/d3-color@3.0.1/node_modules/d3-color/src/lab.jsKilled
/workspaces/gradio/ui/packages/app:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @gradio/app@1.0.0 build:local: `vite build --mode production:local --emptyOutDir "--emptyOutDir"`
Exit status 137
 ELIFECYCLE  Command failed with exit code 1.
```

### System Info

```shell
node v16.18.0
```

### Severity

annoying

**Comment by abidlabs** [comment] 2022-11-21 16:09
Hi @libai-lab do you have `pnpm` version 7 or above installed?

**Comment by libai-lab** [comment] 2022-11-21 16:20
> yes ,I just follow this step,but last i got this 
Contributing to Gradio
Prequisites:

[Python 3.7+](https://www.python.org/downloads/)
[pnpm version 7.x](https://pnpm.io/7.x/installation) (optional for backend-only changes, but needed for any frontend changes)
More than 80 awesome developers have contributed to the gradio library, and we'd be thrilled if you would like be the next gradio contributor! Start by cloning this repo and installing Gradio locally:

Install Gradio locally from the main branch
Clone this repo
Navigate to the repo folder and run
bash scripts/install_gradio.sh
Build the front end
bash scripts/build_frontend.sh
Install testing requirements

**Comment by libai-lab** [comment] 2022-11-21 16:26
my pnpm version is 7.17.0

**Comment by abidlabs** [comment] 2022-11-21 16:30
It looks like there have been similar issues that have been fixed by upgrading the version of node and pnpm. For example: https://github.com/gradio-app/gradio/issues/2300

Can you confirm that you are running with node 16+?

**Comment by abidlabs** [comment] 2022-11-22 02:29
Hi @libai-lab I'm not sure why it's not working. Is it possible for you to share your codespace (I haven't used codespace so I don't know if it's possible). ccing @pngwn in case you have ideas!

**Comment by libai-lab** [comment] 2022-11-22 02:51
> 嗨@libai实验室我不确定为什么它不起作用。您是否可以共享您的代码空间（我没有使用代码空间，所以我不知道是否可以共享它们）。CCING@pngwn万一你有想法！
I don't know if this can be used, thank you for your kind help!!

[](https://libai-lab-ubiquitous-space-spoon-pjj67wp47jxf696.github.dev/)

**Comment by libai-lab** [comment] 2022-11-22 02:51
> 嗨@libai实验室我不确定为什么它不起作用。您是否可以共享您的代码空间（我没有使用代码空间，所以我不知道是否可以共享它们）。CCING@pngwn万一你有想法！

https://libai-lab-ubiquitous-space-spoon-pjj67wp47jxf696.github.dev/
[https://libai-lab-ubiquitous-space-spoon-pjj67wp47jxf696.github.dev/](url)

**Comment by abidlabs** [comment] 2022-12-10 05:11
Hi @libai-lab those links did not work for me unfortunately. Please let us know if you have some way of reproducing, otherwise we will need to close this issue

**Comment by libai-lab** [comment] 2022-12-10 05:16
> Hi @libai-lab those links did not work for me unfortunately. Please let us know if you have some way of reproducing, otherwise we will need to close this issue

[https://github.com/codespaces](url)
You guys did a really good job, don't need to waste too many events on this issue, thank you so much, I'll try other ways later

**Comment by freddyaboulton** [comment] 2022-12-16 19:57
@libai-lab Can you add the environment variable `NODE_OPTIONS="--max-old-space-size=4096"` like we do i[n our CI](https://github.com/gradio-app/gradio/blob/main/.github/workflows/ui.yml#L16)?

**Comment by abidlabs** [comment] 2022-12-22 11:28
Hi @libai-lab I'll go ahead and close this issue, but please try @freddyaboulton's suggestion and if it doesn't work, let us know

**Closed by abidlabs** 2022-12-22 11:28 UTC
Labels: bug, pending clarification
