### ISSUE TITLE
Gallery - Adding a label under each image

### ISSUE THREAD

**Issue by Pfaeff** [gradio-app/gradio#2327] opened 2022-09-23 12:17 UTC
It would be nice if it were possible to add some additional information to the images in the gallery. 

Being able to return a list of tuples of image and string and having those strings displayed as labels under the images would be a great start.

**Comment by pngwn** [comment] 2022-09-23 12:42
Duplicate of #2091.

Are there any features other than labels you think the gallery should have, or can this be closed?

**Comment by Pfaeff** [comment] 2022-09-23 12:47
Weird that I couldn't find that issue. Yes, this can be closed. Sorry for the inconvenience.

**Comment by abidlabs** [comment] 2022-09-23 14:07
Thanks @Pfaeff! Let us know if we can help in any other way

**Closed by abidlabs** 2022-09-23 14:07 UTC
Labels: pending clarification
